#ifndef READOUT_VERSION_H
#define READOUT_VERSION_H


// Do not edit version_string.  Automatically generated by usagedata
static const char *version_string = "" \
  "Readout 1.82\n" \
  "\n" \
  "Copyright (C) 2005 by the Board of Trustees of Michigan State University.\n" \
  "You may use this software under the terms of the GNU public license\n" \
  "(GPL).  The terms of this license are described at:\n" \
  "http://www.gnu.org/licenses/gpl.txt\n" \
  "\n" \
  "Written by E. Kasten.\n";

#endif
