.TH tcphoist 1 "November 2004" tcphoist-1.0 "USER COMMANDS"

.SH NAME
tcphoist \- hoist data from a non NSCL DAQ system into the NSCL DAQ system.

.SH SYNOPSIS
.B TcpHoist [OPTIONS] ... hostname
.SH  DESCRIPTION
.PP
TcpHoist allows you to import data from a foreign system into the NSCL DAQ
system.  TcpHoist connects to a service in a remote host and expects the server
on the other end of the connection to supply it with raw data buffers.  These
buffers are injected without interpretation into the NSCL DAQ system (via
spectrodaq) where NSCL DAQ clients can analyze them.
.PP
When the partner drops the connection, TcpHoist exists with a message.
.SH OPTIONS
.TP
\-buffersize n
Sets the size of the buffers received to be \fIn\fR. Each read from the remote
system will fill a buffer of size \fIn\fR which is then injecdted into the DAQ
system.  If not supplied, the buffersize defaults to 8192 bytes. 
.TP
\-port 
Sets the TCP port to which the TcpHoist program connects. If this is not
present, this defaults to the \fIdaqhost\fR service in /etc/services.  If that
service is not defined, the default is port number 2049.
.TP
.SH EXAMPLES
.TP
Connect to host foreign.other.domain on the default ports for 8K buffers:

.nf
TcpHoist foreign.other.domain

.fi