#!/bin/bash -xe


rm -rf /tmp/11.0

version=`grep AC_INIT configure.ac | cut -f2 -d" " | sed s/,//`

rm -rf nscldaq-${version}

tar xzf nscldaq-${version}.tar.gz
cd nscldaq-${version}

./configure --prefix=/tmp/11.0
make clean all
make install
chmod u+x nscldaq
./nscldaq start
sleep 10
make check
./nscldaq stop

rm -rf nscldaq-${version}
rm -rf /tmp/11.0
