#!/bin/bash -xe


rm -rf ${WORKSPACE}/11.1

version=`grep AC_INIT configure.ac | cut -f2 -d" " | sed s/,//`

rm -rf nscldaq-${version}

tar xzf nscldaq-${version}.tar.gz
cd nscldaq-${version}

./configure --prefix=${WORKSPACE}/11.1 --enable-usb --enable-sbs=/lib/modules/`uname -r`/build --enable-epics-tools=yes --with-epics-rootdir=/usr/lib/epics --enable-docs
make clean all
make install
chmod u+x nscldaq
./nscldaq start
sleep 10
make check
./nscldaq stop

rm -rf nscldaq-${version}
rm -rf ${WORKSPACE}/11.1
