#!/bin/bash -xe


target=${WORKSPACE}/${GIT_BRANCH}-${BUILD_NUMBER}-fromdist
rm -rf ${target}

acversion=`grep AC_INIT configure.ac | cut -f2 -d"," | sed s/,// | sed s/")"// | sed s/\ //`

rm -rf nscldaq-${acversion} nscldaq-${acversion}

tarball=nscldaq-${acversion}.tar.gz
version=${acversion}



tar xzf ${tarball}

cd `basename ${tarball} .tar.gz`

./configure --prefix=${target} --enable-usb --enable-sbs=/lib/modules/`uname -r`/build --enable-epics-tools=yes --with-epics-rootdir=/usr/lib/epics
make clean all
make install
chmod u+x nscldaq
RINGMASTER_LOGFILE=$PWD/ringmaster_dist.log ./nscldaq start
sleep 10
make check-TESTS
./nscldaq stop

rm -rf `basename ${tarball} .tar.gz`
