#!/bin/bash -xe


target=${WORKSPACE}/${GIT_BRANCH}-${BUILD_NUMBER}-fromdist
rm -rf ${target}

#acversion=`grep AC_INIT configure.ac | cut -f2 -d"," | sed s/,// | sed s/")"// | sed s/\ //`

rm -rf nscldaq-${acversion} nscldaq-${acversion}

tarball=nscldaq-${acversion}.tar.gz
version=${acversion}



tar xzf ${tarball}

cd `basename ${tarball} .tar.gz`

./configure --prefix=${target} --enable-usb --enable-sbs=/lib/modules/`uname -r`/build --enable-epics-tools=yes --with-epics-rootdir=/usr/lib/epics
make -j4 clean all
make install
chmod u+x nscldaq
./nscldaq start 
sleep 10                  # give services a chance to start.
make check-TESTS VERBOSE=1
./nscldaq stop


rm -rf `basename ${tarball} .tar.gz`
