# keeplistDialog_ui.tcl --
#
# UI generated by GUI Builder Build 107673 on 2005-08-02 17:06:20 from:
#    //homedir/home2/fox/My Documents/DAQDocs/2005a/daq/DirectoryStructure/code/keeplistDialog.ui
# THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
# The associated callback file should be modified instead.
#

# Declare the namespace for this dialog
namespace eval keeplistDialog {}

package require BWidget
package require Tk
# keeplistDialog::ui --
#
#   Create the UI for this dialog.
#
# ARGS:
#   root     the parent window for this form
#   args     a catch-all for other args, but none are expected
#
proc keeplistDialog::ui {root args} {
    # this handles '.' as a special case
    set base [expr {($root == ".") ? "" : $root}]
    variable ROOT $root
    variable BASE $base


    # Widget Initialization
    label $base._label_1 \
	    -text {KeepList Manager}
    listbox $base.unkeptruns \
	    -selectmode extended \
	    -width 15 \
	    -xscrollcommand [namespace code [list unkeptruns_xscrollcommand]] \
	    -yscrollcommand [list $base._scrollbar_1 set]
    scrollbar $base._scrollbar_1 \
	    -command [list $base.unkeptruns yview]
    listbox $base.scheduledforkeep \
	    -selectmode extended \
	    -width 15 \
	    -xscrollcommand [namespace code [list scheduledforkeep_xscrollcommand]] \
	    -yscrollcommand [list $base._scrollbar_2 set]
    scrollbar $base._scrollbar_2 \
	    -command [list $base.scheduledforkeep yview]
    ArrowButton $base._ArrowButton_1 \
	    -armcommand [namespace code [list _ArrowButton_1_armcommand]] \
	    -command [namespace code [list _ArrowButton_1_command]] \
	    -dir right \
	    -disarmcommand [namespace code [list _ArrowButton_1_disarmcommand]]
    ArrowButton $base._ArrowButton_2 \
	    -armcommand [namespace code [list _ArrowButton_2_armcommand]] \
	    -command [namespace code [list _ArrowButton_2_command]] \
	    -dir left \
	    -disarmcommand [namespace code [list _ArrowButton_2_disarmcommand]]
    listbox $base.keptruns \
	    -selectmode extended \
	    -width 15 \
	    -xscrollcommand [namespace code [list keptruns_xscrollcommand]] \
	    -yscrollcommand [list $base._scrollbar_3 set]
    scrollbar $base._scrollbar_3 \
	    -command [list $base.keptruns yview]
    button $base.ok \
	    -command [namespace code [list ok_command]] \
	    -text Ok
    button $base.cancel \
	    -command [namespace code [list cancel_command]] \
	    -text Cancel
    label $base._label_2 \
	    -text {Unkept Runs}
    label $base._label_3 \
	    -text {Scheduled fo Keep}
    label $base._label_4 \
	    -text {Kept Runs}


    # Geometry Management

    grid $base._label_1 -in $root -row 1 -column 1 \
	    -columnspan 8 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky n
    grid $base.unkeptruns -in $root -row 3 -column 1 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 2 \
	    -sticky news
    grid $base._scrollbar_1 -in $root -row 3 -column 2 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 2 \
	    -sticky nsw
    grid $base.scheduledforkeep -in $root -row 3 -column 4 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 2 \
	    -sticky news
    grid $base._scrollbar_2 -in $root -row 3 -column 5 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 2 \
	    -sticky nsw
    grid $base._ArrowButton_1 -in $root -row 3 -column 3 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky {}
    grid $base._ArrowButton_2 -in $root -row 4 -column 3 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky {}
    grid $base.keptruns -in $root -row 3 -column 7 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 2 \
	    -sticky news
    grid $base._scrollbar_3 -in $root -row 3 -column 8 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 2 \
	    -sticky nsw
    grid $base.ok -in $root -row 5 -column 3 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky {}
    grid $base.cancel -in $root -row 5 -column 5 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky {}
    grid $base._label_2 -in $root -row 2 -column 1 \
	    -columnspan 1 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky w
    grid $base._label_3 -in $root -row 2 -column 4 \
	    -columnspan 3 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky w
    grid $base._label_4 -in $root -row 2 -column 7 \
	    -columnspan 2 \
	    -ipadx 0 \
	    -ipady 0 \
	    -padx 0 \
	    -pady 0 \
	    -rowspan 1 \
	    -sticky w

    # Resize Behavior
    grid rowconfigure $root 1 -weight 0 -minsize 40 -pad 0
    grid rowconfigure $root 2 -weight 0 -minsize 40 -pad 0
    grid rowconfigure $root 3 -weight 1 -minsize 70 -pad 0
    grid rowconfigure $root 4 -weight 0 -minsize 64 -pad 0
    grid rowconfigure $root 5 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $root 1 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $root 2 -weight 0 -minsize 28 -pad 0
    grid columnconfigure $root 3 -weight 0 -minsize 28 -pad 0
    grid columnconfigure $root 4 -weight 0 -minsize 56 -pad 0
    grid columnconfigure $root 5 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $root 6 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $root 7 -weight 0 -minsize 40 -pad 0
    grid columnconfigure $root 8 -weight 0 -minsize 40 -pad 0
}
