.TH epicsdisplay 1 "May 9, 2005" "NSCL-DAQ" "Commands"
.SH NAME
epicsdisplay \- Display and chart epics channels.
.SH SYNOPSIS
.B epicsdisplay \fIchannelfile\fR
.SH DESCRIPTION
.B epicsdisplay
.PP
Monitors a set of EPICS channels in tabular and, optionally, chart recorder
form.  \fIchannelfile\fR is the name of a file that describes the epics
channels to monitor.  The file consists of two types of text lines; comments
and channel lines.  Comment lines begin with the hash character \#.  Channel
lines begin with a channel name followed by whitespace, followed by an optional
comment.   If the optional comment contains the special word ``chart'',
the channel is added to the chart recorder.
.PP
Channels can also have alarms defined on them.  An alarm is said to fire whenever
the channel value is outside of a 'nominal' window.  Alarms are also defined
using special keywords in the comment field of the channel.  The keyword
\fBnominal\fR indicates that the next word on the line defines the channel's
nominal window.  The nominal window definition can be defined either symmetrically or
asymmetrically about a nominal value.  The nominal window can also be defined in
absolute terms or in terms of a percentage of nominal value.
Describing nominal windows is most easily done via example.
.TP
nominal 35:3
Defines a symmetric nominal window about the nominal value 35.  This nominal
window is the range 32 through 38.
.TP
nominal 35:10%
Defines a nominal interval that is +/- 10% of 35... e.g. the interval 32.5 through 38.5
.TP
nominal 35+3-4
Defines a nominal window between 31 and 38.
Similarly:
.TP
nominal 35+5%-10%
Defines the nominal interval 32.5 through 36.75.
Note that for asymmetric intervals mixes of absolute and percentage tolerances are allowed.
Furthermore, the - and + are interchangeable.
.PP
When a channel transitions to the alarmed state, actions defined on the comment line
for the channel are taken.  Actions are defined by the keyword alarmactions followed
by a comma separated list of actions.  Supported actions are:
.TP
page
The alarm is added to a page that describes all the current alarm.s
.TP
beep
A beep is periodically emitted while the channel is in the alarmed state.
.TP
popup
A popup window is displayed when the alarm is in the alarmed state.
.TP
color=\fIcolorspec\fR
The alarm is displayed with the specified \fIcolorspec\fR colored background.
\fIcolorspec\FR is a color using any color specification that is recognized
by Tcl.  (.e.g. color=red  is the same as color=#ff0000).
.SH "OPERATING INSTRUCTIONS"
.PP
The display is divided into three sections. The top section is the channel
table.  The middle section the chart recorder section and the bottom section
the chart control panel.
.PP
While it appears as if the table section has no controls, in reality it is
possible to resize all of the columns of the table.  Expanding the window width
adds space to the right most, Comment column.  All other columns may be
expanded by dragging their borders with the mouse.
.PP
The chart recorder control panel allows the user to perform a few operations
on the chart.  The Clear button resets the time to 0 and clears the data
accumulated so far.
.PP
The rightmost three controls manage the time scale of the chart widget. Changes
to these widgets do nothing until the Set button is clicked.   The widget
states at that time determine the scale of the chart recorder.  If the ``Auto
Range'' checkbutton is set, the time scale will change dynamically to
accomodate the full time range of values.  If unchecked, the value in the entry
widget labelled ``Range (min):''  determines the width in time of the chart.
The chart is scrolled as needed (by 10% of the range) to keep the most recent
data visible.
