#!/bin/bash
# 
#  DISTDIR must be e.g. /usr/opt/daq/7.4/contrib
#  in your bashrc
#  ConfigDir is whatever directory has your shaper configuration file.
#

# Must be run on a system with a VME crate and VME <--> Caennet interface
#  At the NSCL these are systems with names like spdaqnn

. ~/.bashrc                 # This does not get sourced by kde shortcuts.

cd $ConfigDir
$DISTDIR/N568Panel/shaperapp16.tcl $ConfigDir/shaper.cfg 2>&1

