XMManager Class Reference
#include <XMManagers.h>
Public Methods
XMManager (char *n)
XMManager (Widget w)
XMManager (char *n, WidgetClass cl, XMApplication &parent, ArgList l=NULL, Cardinal num_args=0)
XMManager (char *n, WidgetClass cl, Widget parent, ArgList l=NULL, Cardinal num_args=0)
XMManager (char *n, WidgetClass cl, XMWidget &parent, ArgList l=NULL, Cardinal num_args=0)
Callback_data * AddHelpCallback (void(*callback)(XMWidget *, XtPointer, XtPointer), XtPointer client_data)
void SetNavigationType (XmNavigationType navtype=XmNONE)
void TraversalOn ()
void TraverseOff ()
void SetConstraint (XMWidget &w, String constraint, XtArgVal value)
void SetConstraint (XMWidget &w, String constraint, void *value)
void SetConstraint (Widget w, String constraint, XtArgVal value)
void SetConstraint (Widget w, String constraint, void *value)
Constructor & Destructor Documentation
XMManager::XMManager (char * n) [inline]
Definition at line 318 of file XMManagers.h.
XMManager::XMManager (Widget w) [inline]
Definition at line 319 of file XMManagers.h.
XMManager::XMManager (char * n, WidgetClass cl, XMApplication & parent, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 320 of file XMManagers.h.
XMManager::XMManager (char * n, WidgetClass cl, Widget parent, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 325 of file XMManagers.h.
XMManager::XMManager (char * n, WidgetClass cl, XMWidget & parent, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 329 of file XMManagers.h.
Member Function Documentation
Callback_data* XMManager::AddHelpCallback (void(* callback)(XMWidget *, XtPointer, XtPointer), XtPointer client_data) [inline]
Definition at line 335 of file XMManagers.h.
References XMWidget::AddCallback().
void XMManager::SetConstraint (Widget w, String constraint, void * value) [inline]
Definition at line 365 of file XMManagers.h.
void XMManager::SetConstraint (Widget w, String constraint, XtArgVal value) [inline]
Definition at line 362 of file XMManagers.h.
void XMManager::SetConstraint (XMWidget & w, String constraint, void * value) [inline]
Definition at line 359 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMManager::SetConstraint (XMWidget & w, String constraint, XtArgVal value) [inline]
Definition at line 356 of file XMManagers.h.
References XMWidget::SetAttribute().
Referenced by XMBulletinBoard::SetAbsPosition(), XMForm::SetBottomAttachment(), XMForm::SetBottomOffset(), XMForm::SetBottomPosition(), XMForm::SetBottomWidget(), XMForm::SetLeftAttachment(), XMForm::SetLeftOffset(), XMForm::SetLeftPosition(), XMForm::SetLeftWidget(), XMForm::SetRightAttachment(), XMForm::SetRightOffset(), XMForm::SetRightPosition(), XMForm::SetRightWidget(), XMForm::SetTopAttachment(), XMForm::SetTopOffset(), XMForm::SetTopPosition(), and XMForm::SetTopWidget().
void XMManager::SetNavigationType (XmNavigationType navtype = XmNONE) [inline]
Definition at line 339 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMManager::TraversalOn () [inline]
Definition at line 343 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMManager::TraverseOff () [inline]
Definition at line 346 of file XMManagers.h.
References XMWidget::SetAttribute().
The documentation for this class was generated from the following file:
XMManagers.h