CFileEventReactor Class Reference
Public Methods
CFileEventReactor (const string &rName, CFileEvent &rOwner)
~CFileEventReactor ()
virtual void OnReadable (CFdMonitor &rMonitor, int fd)
virtual void OnWritable (CFdMonitor &rMonitor, int fd)
virtual void OnException (CFdMonitor &rMonitor, int fd)
virtual void OnTimeout (CEventMonitor &rMonitor)
Private Attributes
CFileEvent & m_rOwner
Owner of us.
Detailed Description
This is an internal class which is automatically used as the Reactor for File events. About the only thing it does is call back to the file event.
Definition at line 342 of file CFileEvent.h.
Constructor & Destructor Documentation
CFileEventReactor::CFileEventReactor (const string & rName, CFileEvent & rOwner)
Constructor for CFileEventReactor (p.): Constructs the reactor by
Calling the base class constructor (CReactor() (p.)).
Initializing m_rOwner to the event which is instantiating us.
Calling AppendClassInfo() (p.) so that our place in the class hierarchy is well defined.
Parameters:
rName - Reference to the name given to this reactor.
rOwner - Reference to the owning event.
Definition at line 324 of file CFileEvent.cpp.
References CNamedObject::AppendClassInfo().
CFileEventReactor::~CFileEventReactor () [inline]
Definition at line 347 of file CFileEvent.h.
Member Function Documentation
void CFileEventReactor::OnException (CFdMonitor & rMonitor, int fd) [virtual]
Called when an exceptional condition is encountered on a file. We create an iostream and bounce the call back to m_rOwner's OnException. This creates the look and feel of a monolithic Event class.
Reimplemented from CFdReactor (p.).
Definition at line 371 of file CFileEvent.cpp.
References CFileEventReactor::m_rOwner, and CFileEvent::OnException().
void CFileEventReactor::OnReadable (CFdMonitor & rMonitor, int fd) [virtual]
Called whenever the file becomes readable. We create an istream for the file, and call back to m_rOwner's OnReadable member. This all makes the Event seem like a monolithic unit to the user.... They just subclass it, open a file in an appropriate way and poof.
arm rMonitor - Refers to the monitor on the file (unused).
Parameters:
fd - File descriptor open on the file.
Reimplemented from CFdReactor (p.).
Definition at line 342 of file CFileEvent.cpp.
References CFileEventReactor::m_rOwner, and CFileEvent::OnReadable().
void CFileEventReactor::OnTimeout (CEventMonitor & rMonitor) [virtual]
Called when a wait on the file event times out.
Parameters:
rMonitor -referens to the event monitor.
Reimplemented from CReactor (p.).
Definition at line 383 of file CFileEvent.cpp.
References CFileEvent::getFd(), CFileEventReactor::m_rOwner, and CFileEvent::OnTimeout().
void CFileEventReactor::OnWritable (CFdMonitor & rMonitor, int fd) [virtual]
Called when a file descriptor becomes writable. We just create a stream and bounce the call back to the CFileEvent (p.)'s OnWritable member. This presents a monolithic look and feel to the end user of this library.
Parameters:
rMonitor - The file monitor which declared the event.(unused)
fd - The file id which is now writable (constructs the ostream)
Reimplemented from CFdReactor (p.).
Definition at line 360 of file CFileEvent.cpp.
References CFileEventReactor::m_rOwner, and CFileEvent::OnWritable().
Member Data Documentation
CFileEvent& CFileEventReactor::m_rOwner [private]
Owner of us.
Definition at line 344 of file CFileEvent.h.
Referenced by CFileEventReactor::OnException(), CFileEventReactor::OnReadable(), CFileEventReactor::OnTimeout(), and CFileEventReactor::OnWritable().
The documentation for this class was generated from the following files:
CFileEvent.cpp
CFileEvent.h