CBufferEvent< T > Class Template Reference
\class: CBufferEvent \file: CBufferEvent.h.
#include <CBufferEvent.h>
Public Methods
CBufferEvent ()
Anonymous buffer event.
CBufferEvent (const char *pName)
Named event with char* name.
CBufferEvent (const string &rName)
Named event with string name.
~CBufferEvent ()
Destroy the event.
list< AddLinkRequest > getPendingAddQueue () const
list< AddLinkRequest > getPendingDeleteQueue () const
CBufferMonitor< T > & getMonitor ()
Allow manipulation of the event monitor:.
CBufferReactor< T > & getReactor ()
Allow manipulation of the event reactor:.
void AddLink (const string &url, unsigned int tag, unsigned int mask=ALLBITS_MASK, int reliability=COS_RELIABLE)
void DeleteLink (const string &url, unsigned int tag, unsigned int mask=ALLBITS_MASK, int reliability=COS_RELIABLE)
virtual void OnBuffer (Pointer< DAQBuffer< T >, T > &pBuffer)
virtual void OnTimeout ()
virtual void setBufferTag (int tag)
virtual void setBufferMask (int mask)
virtual string DescribeSelf ()
Protected Methods
virtual void ProcessQueues ()
void ProcessAddQueue ()
void ProcessDelQueue ()
string QueueEntryToString (AddLinkRequest &rEntry)
Private Methods
CBufferEvent (const CBufferEvent &rhs)
CBufferEvent & operator= (const CBufferEvent &rhs)
int operator== (const CBufferEvent &rhs)
Private Attributes
list< AddLinkRequest > m_AddQueue
Requests to add links go here.
list< AddLinkRequest > m_DelQueue
Requests to delete links go here.
CBufferMonitor< T > & m_rMonitor
Monitors the input links.
CGenericBufferReactor< T > & m_rReactor
Reacts to the input links.
Detailed Description
template<class T> class CBufferEvent< T >
\class: CBufferEvent \file: CBufferEvent.h.
Provides an ABC for building application level objects to react to SpectroDaq Buffers. This is an abstract, templated class which is templated by the type of buffer whch can be received. Note that depending on how this is constructed,, The object can handle alarm events instead of data buffers.
Definition at line 342 of file CBufferEvent.h.
Constructor & Destructor Documentation
template<class T> CBufferEvent< T >::CBufferEvent ()
Anonymous buffer event.
Construct an anonymous event. The monitor is a standard buffer monitor, the event readctor is a CGenericBufferReactor (p.).
Definition at line 359 of file CBufferEvent.cpp.
References CBufferEvent< T >::getMonitor(), CBufferEvent< T >::getReactor(), CBufferEvent< T >::m_rMonitor, and CBufferEvent< T >::m_rReactor.
template<class T> CBufferEvent< T >::CBufferEvent (const char * pName)
Named event with char* name.
Called to create a named buffer event when the name is a char* string:
Definition at line 371 of file CBufferEvent.cpp.
template<class T> CBufferEvent< T >::CBufferEvent (const string & rName)
Named event with string name.
Called to create a named buffer event when the name is an stl string.
Definition at line 383 of file CBufferEvent.cpp.
template<class T> CBufferEvent< T >::~CBufferEvent ()
Destroy the event.
Destroy the buffer event:
Definition at line 395 of file CBufferEvent.cpp.
References CBufferEvent< T >::m_rMonitor, and CBufferEvent< T >::m_rReactor.
template<class T> CBufferEvent< T >::CBufferEvent (const CBufferEvent< T > & rhs) [private]
Member Function Documentation
template<class T> void CBufferEvent< T >::AddLink (const string & url, unsigned int tag, unsigned int mask = ALLBITS_MASK, int reliability = COS_RELIABLE)
Called to add a link. The link must be added in the context of the event's thread or else buffers will not be received. The link addition requests, are therefore queued to the list of pending link add requests m_AddQueue. This must be done in a globally synchronized way.
Parameters:
url - The url of the host to link data from.
tag - The match tag (after mask has been applied).
mask - Receive mask to be anded with the buffer type.
reliability - Can be:
COS_RELIABLE - Indicates the link should recieve all buffers.
COS_UNRELIABLE - Indicates the link need not receive all buffers.
Definition at line 415 of file CBufferEvent.cpp.
References CApplicationSerializer::getInstance(), CThreadRecursiveMutex::Lock(), CBufferEvent< T >::m_AddQueue, and CThreadRecursiveMutex::UnLock().
template<class T> void CBufferEvent< T >::DeleteLink (const string & url, unsigned int tag, unsigned int mask = ALLBITS_MASK, int reliability = COS_RELIABLE)
Queues a link deletion. Links are deleted by matching URL, mask and reliabilities. The deletion must be done in the context of the thread receiving buffers. Therefore, this member just synchronizes with the application global mutex, and adds the link description to the pending deletion queue. Next time the buffer receiving thread executes (either because a buffer arrives or because the wait times out), new links will be made and old links deleted.
Parameters:
url - The URL describing the server which we will be getting buffers from.
tag - The buffer tag.
mask - Mask to be applied to the inbound buffer.
reliability - Can be any of:
COS_RELIABLE - All matching buffers are delivered.
COS_UNRELIABLE - Matching buffers are only deliverd if receive has no 'active' buffers.
Definition at line 451 of file CBufferEvent.cpp.
References CApplicationSerializer::getInstance(), CThreadRecursiveMutex::Lock(), CBufferEvent< T >::m_DelQueue, CBufferEvent< T >::AddLinkRequest::s_mask, CBufferEvent< T >::AddLinkRequest::s_tag, CBufferEvent< T >::AddLinkRequest::s_url, and CThreadRecursiveMutex::UnLock().
template<class T> string CBufferEvent< T >::DescribeSelf () [virtual]
Called to get a description of this type of event.
Reimplemented from CEvent (p.).
Definition at line 556 of file CBufferEvent.cpp.
References CEvent::DescribeSelf(), CBufferEvent< T >::m_AddQueue, CBufferEvent< T >::m_DelQueue, and CBufferEvent< T >::QueueEntryToString().
template<class T> CBufferMonitor<T>& CBufferEvent< T >::getMonitor () [inline]
Allow manipulation of the event monitor:.
Reimplemented from CEvent (p.).
Definition at line 412 of file CBufferEvent.h.
Referenced by CBufferEvent< T >::CBufferEvent().
template<class T> list<AddLinkRequest> CBufferEvent< T >::getPendingAddQueue () const [inline]
Definition at line 400 of file CBufferEvent.h.
template<class T> list<AddLinkRequest> CBufferEvent< T >::getPendingDeleteQueue () const [inline]
Definition at line 406 of file CBufferEvent.h.
template<class T> CBufferReactor<T>& CBufferEvent< T >::getReactor () [inline]
Allow manipulation of the event reactor:.
Reimplemented from CEvent (p.).
Definition at line 415 of file CBufferEvent.h.
Referenced by CBufferEvent< T >::CBufferEvent().
template<class T> void CBufferEvent< T >::OnBuffer (Pointer< DAQBuffer< T >, T > & pBuffer) [virtual]
This member function is the default (no-op) action when a buffer has been received on the link.
Parameters:
pBuffer - A `pointer' into the DAQBuffer<T>
Definition at line 477 of file CBufferEvent.cpp.
template<class T> void CBufferEvent< T >::OnTimeout () [virtual]
This member function is the default (no-op) action when waiting for buffers has timed out and timeout delivery is enabled.
Definition at line 487 of file CBufferEvent.cpp.
template<class T> CBufferEvent& CBufferEvent< T >::operator= (const CBufferEvent< T > & rhs) [private]
template<class T> int CBufferEvent< T >::operator== (const CBufferEvent< T > & rhs) [private]
template<class T> void CBufferEvent< T >::ProcessAddQueue () [protected]
This utility function is called to take all of the elements in the Add queue and create links corresponding to them. It should be called only in the context of the executing event thread.
Definition at line 515 of file CBufferEvent.cpp.
References CApplicationSerializer::getInstance(), CThreadRecursiveMutex::Lock(), CBufferEvent< T >::m_AddQueue, CBufferEvent< T >::m_rMonitor, CBufferEvent< T >::AddLinkRequest::s_linktype, CBufferEvent< T >::AddLinkRequest::s_mask, CBufferEvent< T >::AddLinkRequest::s_tag, CBufferEvent< T >::AddLinkRequest::s_url, and CThreadRecursiveMutex::UnLock().
Referenced by CBufferEvent< T >::ProcessQueues().
template<class T> void CBufferEvent< T >::ProcessDelQueue () [protected]
This utility function is called periodically in the context of the event thread. It dequeues each element from the delete link request queue and deletes the corresponding link.
Definition at line 535 of file CBufferEvent.cpp.
References CApplicationSerializer::getInstance(), LinkIterator, CThreadRecursiveMutex::Lock(), CBufferEvent< T >::m_DelQueue, CBufferEvent< T >::m_rMonitor, CBufferEvent< T >::AddLinkRequest::s_mask, CBufferEvent< T >::AddLinkRequest::s_tag, CBufferEvent< T >::AddLinkRequest::s_url, and CThreadRecursiveMutex::UnLock().
Referenced by CBufferEvent< T >::ProcessQueues().
template<class T> void CBufferEvent< T >::ProcessQueues () [protected, virtual]
Called periodically at event thread context to process any ITC's (inter thread communication) primitives which are required by the event. In this case, we need to process the two link request queues:
m_AddQueue - queue of links to add.
m_DelQueue - queue of links to delete.
since context switches are in theory unpredictable, it's possible to queue a deletion on an add request which has not yet been processed. Therefore, the add queue is processed first and then the delete queue.
Reimplemented from CEvent (p.).
Definition at line 503 of file CBufferEvent.cpp.
References CBufferEvent< T >::ProcessAddQueue(), and CBufferEvent< T >::ProcessDelQueue().
template<class T> string CBufferEvent< T >::QueueEntryToString (CBufferEvent< T >::AddLinkRequest & rEntry) [protected]
Represent the contents of a Link request entry (CBufferEvent<T>::AddLinkRequest&) as a string. This is intended to be used by DescribSelf() when dumping the queues.
Definition at line 592 of file CBufferEvent.cpp.
Referenced by CBufferEvent< T >::DescribeSelf().
template<class T> virtual void CBufferEvent< T >::setBufferMask (int mask) [inline, virtual]
Definition at line 434 of file CBufferEvent.h.
template<class T> virtual void CBufferEvent< T >::setBufferTag (int tag) [inline, virtual]
Definition at line 431 of file CBufferEvent.h.
Member Data Documentation
template<class T> list<AddLinkRequest> CBufferEvent< T >::m_AddQueue [private]
Requests to add links go here.
Definition at line 375 of file CBufferEvent.h.
Referenced by CBufferEvent< T >::AddLink(), CBufferEvent< T >::DescribeSelf(), CBufferEvent< U >::getPendingAddQueue(), and CBufferEvent< T >::ProcessAddQueue().
template<class T> list<AddLinkRequest> CBufferEvent< T >::m_DelQueue [private]
Requests to delete links go here.
Definition at line 376 of file CBufferEvent.h.
Referenced by CBufferEvent< T >::DeleteLink(), CBufferEvent< T >::DescribeSelf(), CBufferEvent< U >::getPendingDeleteQueue(), and CBufferEvent< T >::ProcessDelQueue().
template<class T> CBufferMonitor<T>& CBufferEvent< T >::m_rMonitor [private]
Monitors the input links.
Reimplemented from CEvent (p.).
Definition at line 378 of file CBufferEvent.h.
Referenced by CBufferEvent< T >::CBufferEvent(), CBufferEvent< T >::ProcessAddQueue(), CBufferEvent< T >::ProcessDelQueue(), and CBufferEvent< T >::~CBufferEvent().
template<class T> CGenericBufferReactor<T>& CBufferEvent< T >::m_rReactor [private]
Reacts to the input links.
Reimplemented from CEvent (p.).
Definition at line 379 of file CBufferEvent.h.
Referenced by CBufferEvent< T >::CBufferEvent(), CBufferEvent< U >::getReactor(), and CBufferEvent< T >::~CBufferEvent().
The documentation for this class was generated from the following files:
CBufferEvent.h
CBufferEvent.cpp