CTCLProcessor Class Reference
#include <TCLProcessor.h>
Public Methods
CTCLProcessor (const std::string &sCommand, CTCLInterpreter *pInterp)
CTCLProcessor (const char *pCommand, CTCLInterpreter *pInterp)
virtual ~CTCLProcessor ()
int operator== (const CTCLProcessor &aCTCLProcessor) const
std::string getCommandName () const
TCLInterpreterIterator begin ()
TCLInterpreterIterator end ()
virtual int operator() (CTCLInterpreter &rInterpreter, CTCLResult &rResult, int nArguments, char *pArguments[])=0
virtual void OnDelete ()
int ParseInt (const char *pString, int *pInteger)
int ParseInt (const std::string &rString, int *pInteger)
int ParseDouble (const char *pString, double *pDouble)
int ParseDouble (const std::string &rString, double *pDouble)
int ParseBoolean (const char *pString, Bool_t *pBoolean)
int ParseBoolean (const std::string &rString, Bool_t *pBoolean)
virtual void Register ()
int Unregister ()
void UnregisterAll ()
Static Public Methods
std::string ConcatenateParameters (int nArguments, char *pArguments[])
int EvalRelay (ClientData pData, Tcl_Interp *pInterp, int Argc, char *Argv[])
void DeleteRelay (ClientData pObject)
int MatchKeyword (vector< string > &MatchTable, const string &rValue, int NoMatch=-1)
Protected Methods
void setCommandName (const std::string &am_sCommandName)
void setRegisteredOn (const std::vector< CTCLInterpreter * > &am_vRegisteredOn)
void AddRegisteredOnCurrent ()
Private Methods
CTCLProcessor (const CTCLProcessor &aCTCLProcessor)
CTCLProcessor & operator= (const CTCLProcessor &aCTCLProcessor)
Private Attributes
std::string m_sCommandName
TCLInterpreterList m_vRegisteredOn
Constructor & Destructor Documentation
CTCLProcessor::CTCLProcessor (const std::string & sCommand, CTCLInterpreter * pInterp)
Definition at line 323 of file TCLProcessor.cpp.
References m_sCommandName.
CTCLProcessor::CTCLProcessor (const char * pCommand, CTCLInterpreter * pInterp)
Definition at line 330 of file TCLProcessor.cpp.
References m_sCommandName.
virtual CTCLProcessor::~CTCLProcessor () [inline, virtual]
Definition at line 334 of file TCLProcessor.h.
References UnregisterAll().
CTCLProcessor::CTCLProcessor (const CTCLProcessor & aCTCLProcessor) [private]
Member Function Documentation
void CTCLProcessor::AddRegisteredOnCurrent () [inline, protected]
Definition at line 380 of file TCLProcessor.h.
References CTCLInterpreterObject::AssertIfNotBound(), and m_vRegisteredOn.
Referenced by CDAQTCLProcessor::Register().
TCLInterpreterIterator CTCLProcessor::begin () [inline]
Definition at line 364 of file TCLProcessor.h.
References m_vRegisteredOn, and TCLInterpreterIterator.
Referenced by DeleteRelay(), and EvalRelay().
std::string CTCLProcessor::ConcatenateParameters (int nArguments, char * pArguments[]) [static]
Definition at line 346 of file TCLProcessor.cpp.
void CTCLProcessor::DeleteRelay (ClientData pObject) [static]
Reimplemented in CDAQTCLProcessor (p.).
Definition at line 489 of file TCLProcessor.cpp.
References begin(), CTCLInterpreterObject::Bind(), end(), CTCLInterpreter::getInterpreter(), CTCLInterpreterObject::getInterpreter(), m_vRegisteredOn, OnDelete(), and TCLInterpreterIterator.
Referenced by CDAQTCLProcessor::DeleteRelay(), and Register().
TCLInterpreterIterator CTCLProcessor::end () [inline]
Definition at line 367 of file TCLProcessor.h.
References m_vRegisteredOn, and TCLInterpreterIterator.
Referenced by DeleteRelay(), and EvalRelay().
int CTCLProcessor::EvalRelay (ClientData pData, Tcl_Interp * pInterp, int Argc, char * Argv[]) [static]
Definition at line 387 of file TCLProcessor.cpp.
References begin(), CTCLInterpreterObject::Bind(), end(), CTCLInterpreter::getInterpreter(), CTCLInterpreterObject::getInterpreter(), and TCLInterpreterIterator.
Referenced by CDAQTCLProcessor::EvalRelay(), and Register().
std::string CTCLProcessor::getCommandName () const [inline]
Definition at line 360 of file TCLProcessor.h.
References m_sCommandName.
Referenced by CDAQTCLProcessor::Register().
int CTCLProcessor::MatchKeyword (vector< string > & MatchTable, const string & rValue, int NoMatch = -1) [static]
Definition at line 706 of file TCLProcessor.cpp.
void CTCLProcessor::OnDelete () [virtual]
Definition at line 460 of file TCLProcessor.cpp.
Referenced by DeleteRelay().
virtual int CTCLProcessor::operator() (CTCLInterpreter & rInterpreter, CTCLResult & rResult, int nArguments, char * pArguments[]) [pure virtual]
Implemented in CTCLSynchronizeCommand (p.).
CTCLProcessor& CTCLProcessor::operator= (const CTCLProcessor & aCTCLProcessor) [private]
int CTCLProcessor::operator== (const CTCLProcessor & aCTCLProcessor) const [inline]
Definition at line 350 of file TCLProcessor.h.
References m_sCommandName, m_vRegisteredOn, and CTCLInterpreterObject::operator==().
Referenced by CTCLPackagedCommand::operator==(), CTCLSynchronizeCommand::operator==(), and CDAQTCLProcessor::operator==().
int CTCLProcessor::ParseBoolean (const std::string & rString, Bool_t * pBoolean) [inline]
Definition at line 411 of file TCLProcessor.h.
References Bool_t, and ParseBoolean().
int CTCLProcessor::ParseBoolean (const char * pString, Bool_t * pBoolean)
Definition at line 604 of file TCLProcessor.cpp.
References Bool_t, CTCLInterpreter::getInterpreter(), and CTCLInterpreterObject::getInterpreter().
Referenced by ParseBoolean().
int CTCLProcessor::ParseDouble (const std::string & rString, double * pDouble) [inline]
Definition at line 406 of file TCLProcessor.h.
References ParseDouble().
int CTCLProcessor::ParseDouble (const char * pString, double * pDouble)
Definition at line 572 of file TCLProcessor.cpp.
References CTCLInterpreter::getInterpreter(), and CTCLInterpreterObject::getInterpreter().
Referenced by ParseDouble().
int CTCLProcessor::ParseInt (const std::string & rString, int * pInteger) [inline]
Definition at line 401 of file TCLProcessor.h.
References ParseInt().
int CTCLProcessor::ParseInt (const char * pString, int * pInteger)
Definition at line 533 of file TCLProcessor.cpp.
References CTCLInterpreter::getInterpreter(), and CTCLInterpreterObject::getInterpreter().
Referenced by ParseInt().
void CTCLProcessor::Register () [virtual]
Reimplemented in CDAQTCLProcessor (p.).
Definition at line 642 of file TCLProcessor.cpp.
References CTCLInterpreter::AddCommand(), CTCLInterpreterObject::AssertIfNotBound(), DeleteRelay(), EvalRelay(), m_sCommandName, and m_vRegisteredOn.
void CTCLProcessor::setCommandName (const std::string & am_sCommandName) [inline, protected]
Definition at line 374 of file TCLProcessor.h.
References m_sCommandName.
void CTCLProcessor::setRegisteredOn (const std::vector< CTCLInterpreter * > & am_vRegisteredOn) [inline, protected]
Definition at line 377 of file TCLProcessor.h.
References m_vRegisteredOn.
int CTCLProcessor::Unregister ()
Definition at line 663 of file TCLProcessor.cpp.
References CTCLInterpreterObject::AssertIfNotBound(), m_sCommandName, and CTCLInterpreter::UnregisterCommand().
Referenced by UnregisterAll().
void CTCLProcessor::UnregisterAll ()
Definition at line 684 of file TCLProcessor.cpp.
References CTCLInterpreterObject::Bind(), CTCLInterpreterObject::getInterpreter(), m_vRegisteredOn, and Unregister().
Referenced by ~CTCLProcessor().
Member Data Documentation
std::string CTCLProcessor::m_sCommandName [private]
Definition at line 324 of file TCLProcessor.h.
Referenced by CTCLProcessor(), getCommandName(), operator==(), Register(), setCommandName(), and Unregister().
TCLInterpreterList CTCLProcessor::m_vRegisteredOn [private]
Definition at line 325 of file TCLProcessor.h.
Referenced by AddRegisteredOnCurrent(), begin(), DeleteRelay(), end(), operator==(), Register(), setRegisteredOn(), and UnregisterAll().
The documentation for this class was generated from the following files:
TCLProcessor.h
TCLProcessor.cpp