CFdMonitor Class Reference
#include <CFdMonitor.h>
Public Types
enum FdConditions { FD_READABLE = 0,
FD_WRITABLE = 1,
FD_EXCEPTION = 2
 }
Public Methods
CFdMonitor (int am_nFd, bool am_fTimedWait=true)
CFdMonitor (const string &rName, int am_nFd, bool am_fTimedWait=true)
CFdMonitor (const char *pName, int am_nFd, bool am_fTimedWait=true)
int operator== (const CFdMonitor &aCFdMonitor) const
virtual ~CFdMonitor ()
int getFd () const
unsigned int getConditionMask () const
int getLastEventMask () const
void MonitorReadable (bool fReadable=true)
void MonitorWritable (bool fWritable=true)
void MonitorExceptions (bool fException=true)
virtual CEventMonitor::result operator() ()
virtual string DescribeSelf ()
Protected Methods
void setFd (const int am_nFd)
void setConditionMask (const unsigned int am_nConditionMask)
void setLastEventMask (const int am_fLastEventMask)
Private Methods
CFdMonitor (const CRegisteredObject &aCRegisteredObject)
CFdMonitor operator= (const CRegisteredObject &aCRegisteredObject)
Assignment is forbidden for now.
Private Attributes
int m_nFd
unsigned int m_nConditionMask
int m_fLastEventMask
Detailed Description
\class: CFdMonitor.h
This file defines the CFdMonitor class. Monitors activity on a file descriptor. A file descriptior can be monitored for the logical or of any of the following conditions: Readable Writable Exception
Monitoring is done via the select(2) system service. Note that this can yield some unexpected results. For example, in some operating systems, tape drives are never considered readable without blocking.
Author: Jason Venema NSCL Michigan State University East Lansing, MI 48824-1321 mailto:venemaja@msu.edu
Definition at line 319 of file CFdMonitor.h.
Member Enumeration Documentation
enum CFdMonitor::FdConditions
Mask of the last set of bits to be detected
Enumeration values:
FD_READABLE
FD_WRITABLE
FD_EXCEPTION
Definition at line 329 of file CFdMonitor.h.
Referenced by CFdReactor::OnEvent().
Constructor & Destructor Documentation
CFdMonitor::CFdMonitor (int am_nFd, bool am_fTimedWait = true) [inline]
Definition at line 338 of file CFdMonitor.h.
References CNamedObject::AppendClassInfo(), m_fLastEventMask, m_nConditionMask, and m_nFd.
CFdMonitor::CFdMonitor (const string & rName, int am_nFd, bool am_fTimedWait = true) [inline]
Definition at line 345 of file CFdMonitor.h.
References CNamedObject::AppendClassInfo(), m_fLastEventMask, m_nConditionMask, and m_nFd.
CFdMonitor::CFdMonitor (const char * pName, int am_nFd, bool am_fTimedWait = true) [inline]
Definition at line 352 of file CFdMonitor.h.
References CNamedObject::AppendClassInfo(), m_fLastEventMask, m_nConditionMask, and m_nFd.
virtual CFdMonitor::~CFdMonitor () [inline, virtual]
Definition at line 369 of file CFdMonitor.h.
CFdMonitor::CFdMonitor (const CRegisteredObject & aCRegisteredObject) [private]
Member Function Documentation
string CFdMonitor::DescribeSelf () [virtual]
Operation Type: Interface Implementation
Purpose: Uses the m_sClassPath member to describe its class path, and returns a string containing this and its data member values.
Reimplemented from CNamedObject (p.).
Reimplemented in CServerMonitor (p.).
Definition at line 420 of file CFdMonitor.cpp.
References CNamedObject::DescribeSelf(), CEventMonitor::getTimedWait(), CEventMonitor::getTimeout(), and m_nFd.
Referenced by main().
unsigned int CFdMonitor::getConditionMask () const [inline]
Definition at line 386 of file CFdMonitor.h.
References m_nConditionMask.
Referenced by main().
int CFdMonitor::getFd () const [inline]
Definition at line 381 of file CFdMonitor.h.
References m_nFd.
Referenced by CFdReactor::OnEvent().
int CFdMonitor::getLastEventMask () const [inline]
Definition at line 391 of file CFdMonitor.h.
References m_fLastEventMask.
Referenced by CFdReactor::OnEvent().
void CFdMonitor::MonitorExceptions (bool fException = true)
Operation Type: Mutator
Purpose: Sets or clears the FD_EXCEPTION bit in m_nConditionMask.
Definition at line 344 of file CFdMonitor.cpp.
References FD_EXCEPTION, and m_nConditionMask.
Referenced by main().
void CFdMonitor::MonitorReadable (bool fReadable = true)
Operation Type: Mutator
Purpose: Sets or clears the FD_READABLE bit in m_nConditionMask.
Definition at line 314 of file CFdMonitor.cpp.
References FD_READABLE, and m_nConditionMask.
Referenced by main().
void CFdMonitor::MonitorWritable (bool fWritable = true)
Operation Type: Mutator
Purpose: Sets or clears the FD_WRITABLE bit in the m_nConditionMask attribute.
Definition at line 329 of file CFdMonitor.cpp.
References FD_WRITABLE, and m_nConditionMask.
Referenced by main().
CEventMonitor::result CFdMonitor::operator() () [virtual]
Operation Type: Interface Implementation
Purpose:
Implements a wait for a single file descriptor event as described in the mask. Returns one of: Occured - one of the masked conditions occured. TimedOut - Timeout was enabled and none of the conditions occured within the timeout. Error - An error condition ocurred.
Implements CEventMonitor (p.).
Reimplemented in CServerMonitor (p.).
Definition at line 367 of file CFdMonitor.cpp.
References CEventMonitor::Error, FD_EXCEPTION, FD_READABLE, FD_WRITABLE, CEventMonitor::getTimedWait(), CEventMonitor::getTimeout(), m_fLastEventMask, m_nConditionMask, m_nFd, CEventMonitor::Occurred, and CEventMonitor::TimedOut.
CFdMonitor CFdMonitor::operator= (const CRegisteredObject & aCRegisteredObject) [private]
Assignment is forbidden for now.
Reimplemented from CEventMonitor (p.).
Referenced by CServerMonitor::operator=().
int CFdMonitor::operator== (const CFdMonitor & aCFdMonitor) const [inline]
Definition at line 360 of file CFdMonitor.h.
References m_fLastEventMask, m_nConditionMask, m_nFd, and CEventMonitor::operator==().
Referenced by CServerMonitor::operator==().
void CFdMonitor::setConditionMask (const unsigned int am_nConditionMask) [inline, protected]
Definition at line 404 of file CFdMonitor.h.
References m_nConditionMask.
void CFdMonitor::setFd (const int am_nFd) [inline, protected]
Definition at line 399 of file CFdMonitor.h.
References m_nFd.
void CFdMonitor::setLastEventMask (const int am_fLastEventMask) [inline, protected]
Definition at line 409 of file CFdMonitor.h.
References m_fLastEventMask.
Member Data Documentation
int CFdMonitor::m_fLastEventMask [private]
Conditions which will be monitored by the monitor for the file descriptor.
Definition at line 324 of file CFdMonitor.h.
Referenced by CFdMonitor(), getLastEventMask(), operator()(), operator==(), and setLastEventMask().
unsigned int CFdMonitor::m_nConditionMask [private]
File descriptor which will be monitored by the monitor
Definition at line 322 of file CFdMonitor.h.
Referenced by CFdMonitor(), getConditionMask(), MonitorExceptions(), MonitorReadable(), MonitorWritable(), operator()(), operator==(), and setConditionMask().
int CFdMonitor::m_nFd [private]
Definition at line 321 of file CFdMonitor.h.
Referenced by CFdMonitor(), DescribeSelf(), getFd(), operator()(), operator==(), and setFd().
The documentation for this class was generated from the following files:
CFdMonitor.h
CFdMonitor.cpp