XMToggleButton Class Reference
#include <XMPushbutton.h>
Public Methods
XMToggleButton (char *n, Widget parent, void(*cb)(XMWidget *, XtPointer, XtPointer)=NULL, XtPointer cd=NULL)
XMToggleButton (char *n, XMWidget &parent, void(*cb)(XMWidget *, XtPointer, XtPointer)=NULL, XtPointer cd=NULL)
XMToggleButton (Widget w)
Callback_data * AddCallback (void(*cb)(XMWidget *, XtPointer, XtPointer)=NULL, XtPointer cd=NULL)
void ShowIndicator ()
void HideIndicator ()
void Diamond ()
void Box ()
void SetState (Boolean state)
void Set ()
void UnSet ()
Boolean GetState ()
Constructor & Destructor Documentation
XMToggleButton::XMToggleButton (char * n, Widget parent, void(* cb)(XMWidget *, XtPointer, XtPointer) = NULL, XtPointer cd = NULL) [inline]
Definition at line 471 of file XMPushbutton.h.
References XMWidget::AddCallback(), and XMButton::Enable().
XMToggleButton::XMToggleButton (char * n, XMWidget & parent, void(* cb)(XMWidget *, XtPointer, XtPointer) = NULL, XtPointer cd = NULL) [inline]
Definition at line 481 of file XMPushbutton.h.
References XMWidget::AddCallback(), and XMButton::Enable().
XMToggleButton::XMToggleButton (Widget w) [inline]
Definition at line 490 of file XMPushbutton.h.
Member Function Documentation
Callback_data* XMToggleButton::AddCallback (void(* cb)(XMWidget *, XtPointer, XtPointer) = NULL, XtPointer cd = NULL) [inline]
Definition at line 497 of file XMPushbutton.h.
References XMWidget::AddCallback().
void XMToggleButton::Box () [inline]
Definition at line 511 of file XMPushbutton.h.
References XMWidget::SetAttribute().
void XMToggleButton::Diamond () [inline]
Definition at line 508 of file XMPushbutton.h.
References XMWidget::SetAttribute().
Boolean XMToggleButton::GetState () [inline]
Definition at line 521 of file XMPushbutton.h.
References XMWidget::GetAttribute().
void XMToggleButton::HideIndicator () [inline]
Definition at line 506 of file XMPushbutton.h.
References XMWidget::SetAttribute().
void XMToggleButton::Set () [inline]
Definition at line 517 of file XMPushbutton.h.
References XMWidget::SetAttribute().
void XMToggleButton::SetState (Boolean state) [inline]
Definition at line 515 of file XMPushbutton.h.
References XMWidget::SetAttribute().
void XMToggleButton::ShowIndicator () [inline]
Definition at line 504 of file XMPushbutton.h.
References XMWidget::SetAttribute().
void XMToggleButton::UnSet () [inline]
Definition at line 519 of file XMPushbutton.h.
References XMWidget::SetAttribute().
The documentation for this class was generated from the following file:
XMPushbutton.h