CErrnoException Class Reference
#include <CErrnoException.h>
Public Methods
CErrnoException (const char *pszAction)
CErrnoException (const std::string &rsAction)
~CErrnoException ()
CErrnoException (const CErrnoException &aCErrnoException)
CErrnoException & operator= (const CErrnoException &aCErrnoException)
int operator== (const CErrnoException &aCErrnoException)
Int_t getErrno () const
virtual const char * ReasonText () const
virtual Int_t ReasonCode () const
Protected Methods
void setErrno (Int_t am_nErrno)
Private Attributes
Int_t m_nErrno
Constructor & Destructor Documentation
CErrnoException::CErrnoException (const char * pszAction) [inline]
Definition at line 325 of file CErrnoException.h.
References m_nErrno.
CErrnoException::CErrnoException (const std::string & rsAction) [inline]
Definition at line 328 of file CErrnoException.h.
References m_nErrno.
CErrnoException::~CErrnoException () [inline]
Definition at line 331 of file CErrnoException.h.
CErrnoException::CErrnoException (const CErrnoException & aCErrnoException) [inline]
Definition at line 335 of file CErrnoException.h.
References m_nErrno.
Member Function Documentation
Int_t CErrnoException::getErrno () const [inline]
Definition at line 361 of file CErrnoException.h.
References Int_t, and m_nErrno.
CErrnoException& CErrnoException::operator= (const CErrnoException & aCErrnoException) [inline]
Definition at line 342 of file CErrnoException.h.
References m_nErrno, and CException::operator=().
Referenced by CTCPNoSuchService::operator=(), CTCPConnectionLost::operator=(), and CTCPConnectionFailed::operator=().
int CErrnoException::operator== (const CErrnoException & aCErrnoException) [inline]
Definition at line 352 of file CErrnoException.h.
References m_nErrno, and CException::operator==().
Referenced by CTCPNoSuchService::operator==(), CTCPConnectionLost::operator==(), and CTCPConnectionFailed::operator==().
Int_t CErrnoException::ReasonCode () const [virtual]
Return an integer valued code which indicates the reason for the exception. This value is exception type dependent. for CErrnoException, the value is the value of errno at the time the exception was instantiated.
Reimplemented from CException (p.).
Definition at line 342 of file CErrnoException.cpp.
References m_nErrno.
const char * CErrnoException::ReasonText () const [virtual]
Return the textual reason for the error. This is done by asking for the strerror of m_nErrno. Note therefore that the reason text returned relates to the value of errno at the time the exception was thrown, not the current time.
Reimplemented from CException (p.).
Reimplemented in CTCPConnectionFailed (p.), CTCPConnectionLost (p.), and CTCPNoSuchService (p.).
Definition at line 323 of file CErrnoException.cpp.
References m_nErrno.
Referenced by CTCPNoSuchService::ReasonText(), CTCPConnectionLost::ReasonText(), and CTCPConnectionFailed::ReasonText().
void CErrnoException::setErrno (Int_t am_nErrno) [inline, protected]
Definition at line 367 of file CErrnoException.h.
References Int_t, and m_nErrno.
Member Data Documentation
Int_t CErrnoException::m_nErrno [private]
Definition at line 319 of file CErrnoException.h.
Referenced by CErrnoException(), getErrno(), operator=(), operator==(), ReasonCode(), ReasonText(), and setErrno().
The documentation for this class was generated from the following files:
CErrnoException.h
CErrnoException.cpp