XMLabel Class Reference
#include <XMLabel.h>
Public Methods
XMLabel (char *n, XMWidget &parent, char *text, ArgList args=NULL, Cardinal arg_count=0)
XMLabel (char *n, Widget parent, char *text, ArgList args=NULL, Cardinal arg_count=0)
XMLabel (char *n)
XMLabel (Widget w)
void SetLabel (char *text)
void SetLabel (XmString lbl)
Constructor & Destructor Documentation
XMLabel::XMLabel (char * n, XMWidget & parent, char * text, ArgList args = NULL, Cardinal arg_count = 0) [inline]
Definition at line 303 of file XMLabel.h.
References SetLabel().
XMLabel::XMLabel (char * n, Widget parent, char * text, ArgList args = NULL, Cardinal arg_count = 0) [inline]
Definition at line 309 of file XMLabel.h.
References SetLabel().
XMLabel::XMLabel (char * n) [inline]
Definition at line 315 of file XMLabel.h.
XMLabel::XMLabel (Widget w) [inline]
Definition at line 317 of file XMLabel.h.
Member Function Documentation
void XMLabel::SetLabel (XmString lbl) [inline]
Definition at line 324 of file XMLabel.h.
References XMWidget::SetAttribute().
void XMLabel::SetLabel (char * text) [inline]
Definition at line 319 of file XMLabel.h.
References XMWidget::SetAttribute().
Referenced by XMLabel().
The documentation for this class was generated from the following file:
XMLabel.h