CPointerPredicate< T > Class Template Reference
#include <CPointerPredicate.h>
Public Methods
CPointerPredicate ()
CPointerPredicate (const string &rName)
CPointerPredicate (const char *pName)
~CPointerPredicate ()
int operator== (const CPointerPredicate< T > &aCPointerPredicate) const
virtual bool operator() (T nValue)=0
virtual string DescribeSelf ()=0
Static Protected Methods
string GetAutoName (const string &rBaseName)
Private Methods
CPointerPredicate (const CPointerPredicate< T > &aCPointerPredicate)
CPointerPredicate< T > operator= (const CPointerPredicate< T > &aCPointerPredicate)
Static Private Attributes
unsigned int m_nAutoIndex = 0
Used to name autonamed objects.
template<typename T> class CPointerPredicate< T >
Constructor & Destructor Documentation
template<typename T> CPointerPredicate< T >::CPointerPredicate () [inline]
Used to name predicate objects
template<typename T> CPointerPredicate< T >::CPointerPredicate (const string & rName) [inline]
template<typename T> CPointerPredicate< T >::CPointerPredicate (const char * pName) [inline]
template<typename T> CPointerPredicate< T >::~CPointerPredicate () [inline]
template<typename T> CPointerPredicate< T >::CPointerPredicate (const CPointerPredicate< T > & aCPointerPredicate) [private]
Member Function Documentation
template<typename T> virtual string CPointerPredicate< T >::DescribeSelf () [pure virtual]
Describes the named object. The information given is the object type given by m_sClassPath, and the object name.
Reimplemented from CNamedObject (p.).
Implemented in CChangedPredicate< T > (p.), and CMaskedValuePredicate< T > (p.).
template<typename T> string CPointerPredicate< T >::GetAutoName (const string & rBaseName) [static, protected]
\function string CPointerPredicate::GetAutoName(const string& rBaseName) (p.) Automatically names an object given its base class(es)
Parameters:
const string& rBaseName The base name of the object being named
Reimplemented from CNamedObject (p.).
Definition at line 296 of file CPointerPredicate.cpp.
References CPointerPredicate< T >::m_nAutoIndex.
template<typename T> virtual bool CPointerPredicate< T >::operator() (T nValue) [pure virtual]
Implemented in CChangedPredicate< T > (p.), and CMaskedValuePredicate< T > (p.).
template<typename T> CPointerPredicate<T> CPointerPredicate< T >::operator= (const CPointerPredicate< T > & aCPointerPredicate) [private]
template<typename T> int CPointerPredicate< T >::operator== (const CPointerPredicate< T > & aCPointerPredicate) const [inline]
Definition at line 335 of file CPointerPredicate.h.
References CRegisteredObject::operator==().
Referenced by CMaskedValuePredicate< T >::operator==(), and CChangedPredicate< T >::operator==().
Member Data Documentation
template<typename T> unsigned int CPointerPredicate< T >::m_nAutoIndex = 0 [static, private]
Used to name autonamed objects.
NamedObject.cpp Base class for all objects in the event management system.
Author: Jason Venema NSCL Michigan State University East Lansing, MI 48824-1321 mailto:venemaja@msu.edu
Reimplemented from CNamedObject (p.).
Definition at line 283 of file CPointerPredicate.cpp.
Referenced by CPointerPredicate< T >::GetAutoName().
The documentation for this class was generated from the following files:
CPointerPredicate.h
CPointerPredicate.cpp