CRangeError Class Reference
#include <CRangeError.h>
Public Types
enum { knTooLow,
knTooHigh
 }
Public Methods
CRangeError (Int_t nLow, Int_t nHigh, Int_t nRequested, const char *pDoing)
CRangeError (Int_t nLow, Int_t nHigh, Int_t nRequested, const string &rDoing)
virtual ~CRangeError ()
CRangeError (const CRangeError &aCRangeError)
CRangeError operator= (const CRangeError &aCRangeError)
int operator== (const CRangeError &aCRangeError)
Int_t getLow () const
Int_t getHigh () const
Int_t getRequested () const
virtual const char * ReasonText () const
virtual Int_t ReasonCode () const
Protected Methods
void setLow (Int_t am_nLow)
void setHigh (Int_t am_nHigh)
void setRequested (Int_t am_nRequested)
void UpdateReason ()
Private Attributes
Int_t m_nLow
Int_t m_nHigh
Int_t m_nRequested
string m_ReasonText
Member Enumeration Documentation
anonymous enum
Enumeration values:
knTooLow
knTooHigh
Definition at line 315 of file CRangeError.h.
Constructor & Destructor Documentation
CRangeError::CRangeError (Int_t nLow, Int_t nHigh, Int_t nRequested, const char * pDoing) [inline]
Definition at line 321 of file CRangeError.h.
References Int_t, m_nHigh, m_nLow, m_nRequested, and UpdateReason().
CRangeError::CRangeError (Int_t nLow, Int_t nHigh, Int_t nRequested, const string & rDoing) [inline]
Definition at line 328 of file CRangeError.h.
References Int_t, m_nHigh, m_nLow, m_nRequested, and UpdateReason().
virtual CRangeError::~CRangeError () [inline, virtual]
Definition at line 335 of file CRangeError.h.
CRangeError::CRangeError (const CRangeError & aCRangeError) [inline]
Definition at line 339 of file CRangeError.h.
References m_nHigh, m_nLow, m_nRequested, and UpdateReason().
Member Function Documentation
Int_t CRangeError::getHigh () const [inline]
Definition at line 384 of file CRangeError.h.
References Int_t, and m_nHigh.
Int_t CRangeError::getLow () const [inline]
Definition at line 380 of file CRangeError.h.
References Int_t, and m_nLow.
Int_t CRangeError::getRequested () const [inline]
Definition at line 388 of file CRangeError.h.
References Int_t, and m_nRequested.
CRangeError CRangeError::operator= (const CRangeError & aCRangeError) [inline]
Definition at line 350 of file CRangeError.h.
References m_nHigh, m_nLow, m_nRequested, CException::operator=(), and UpdateReason().
int CRangeError::operator== (const CRangeError & aCRangeError) [inline]
Definition at line 365 of file CRangeError.h.
References m_nHigh, m_nLow, m_nRequested, and CException::operator==().
Int_t CRangeError::ReasonCode () const [virtual]
Returns a code which describes the reason for the exception . This is exception type specific and may be used to do detailed exception analysis and recovery. For example in the CErrnoException (p.) class, the errno at the time of instantiation of the object is returned. The default returns -1
Reimplemented from CException (p.).
Definition at line 334 of file CRangeError.cpp.
References knTooHigh, knTooLow, m_nHigh, m_nLow, and m_nRequested.
const char * CRangeError::ReasonText () const [virtual]
Returns a const pointer to text which describes the reason the exception was thrown. This is exception type specific. The default action returns a pointer to the constant string: `Unspecified Exception`
Reimplemented from CException (p.).
Definition at line 316 of file CRangeError.cpp.
References m_ReasonText.
void CRangeError::setHigh (Int_t am_nHigh) [inline, protected]
Definition at line 400 of file CRangeError.h.
References Int_t, m_nHigh, and UpdateReason().
void CRangeError::setLow (Int_t am_nLow) [inline, protected]
Definition at line 395 of file CRangeError.h.
References Int_t, m_nLow, and UpdateReason().
void CRangeError::setRequested (Int_t am_nRequested) [inline, protected]
Definition at line 405 of file CRangeError.h.
References Int_t, m_nRequested, and UpdateReason().
void CRangeError::UpdateReason () [protected]
Definition at line 363 of file CRangeError.cpp.
References m_nHigh, m_nLow, m_nRequested, and m_ReasonText.
Referenced by CRangeError(), operator=(), setHigh(), setLow(), and setRequested().
Member Data Documentation
Int_t CRangeError::m_nHigh [private]
Definition at line 307 of file CRangeError.h.
Referenced by CRangeError(), getHigh(), operator=(), operator==(), ReasonCode(), setHigh(), and UpdateReason().
Int_t CRangeError::m_nLow [private]
Definition at line 306 of file CRangeError.h.
Referenced by CRangeError(), getLow(), operator=(), operator==(), ReasonCode(), setLow(), and UpdateReason().
Int_t CRangeError::m_nRequested [private]
Definition at line 308 of file CRangeError.h.
Referenced by CRangeError(), getRequested(), operator=(), operator==(), ReasonCode(), setRequested(), and UpdateReason().
string CRangeError::m_ReasonText [private]
Definition at line 310 of file CRangeError.h.
Referenced by ReasonText(), and UpdateReason().
The documentation for this class was generated from the following files:
CRangeError.h
CRangeError.cpp