CTCPConnectionLost Class Reference
#include <CTCPConnectionLost.h>
Public Methods
CTCPConnectionLost (CSocket *pSocket, const char *pDoing)
CTCPConnectionLost (const CTCPConnectionLost &rhs)
virtual ~CTCPConnectionLost ()
CTCPConnectionLost & operator= (const CTCPConnectionLost &rhs)
int operator== (const CTCPConnectionLost &rhs)
string getHost () const
string getPort () const
virtual const char * ReasonText () const
Protected Methods
void setHost (const string &rHost)
void setPort (const string &rPort)
void Host (CSocket *pSocket)
void Port (CSocket *pSocket)
Private Attributes
string m_Host
string m_Port
string m_ReasonText
Detailed Description
Encapsulate the connection lost exception. This exception is thrown when a read is attempted on a busted socket.
Definition at line 306 of file CTCPConnectionLost.h.
Constructor & Destructor Documentation
CTCPConnectionLost::CTCPConnectionLost (CSocket * pSocket, const char * pDoing)
'Normal constructor' This is called prior to throwing a connection lost exception. The host and port information are gotten from the socket. The reason the connection was lost is currently in errno.
Parameters:
pSocket - the socket which just lost connection.
Definition at line 308 of file CTCPConnectionLost.cpp.
References Host(), and Port().
CTCPConnectionLost::CTCPConnectionLost (const CTCPConnectionLost & rhs)
Copy constructor.. used by the compiler to generate termporary variables and of course, by throw to create a scope-safe copy of the exception being thrown.
Parameters:
rhs - the reference object being copied.
Definition at line 319 of file CTCPConnectionLost.cpp.
virtual CTCPConnectionLost::~CTCPConnectionLost () [inline, virtual]
Definition at line 320 of file CTCPConnectionLost.h.
Member Function Documentation
string CTCPConnectionLost::getHost () const [inline]
Definition at line 329 of file CTCPConnectionLost.h.
References m_Host.
string CTCPConnectionLost::getPort () const [inline]
Definition at line 331 of file CTCPConnectionLost.h.
References m_Port.
void CTCPConnectionLost::Host (CSocket * pSocket) [protected]
Extract the peer's hostname from the socket. This is done as follows:
The fd of the socket is gotten.
getpeername(2) is called to get the peer address.
gethostbyaddr(3) is called to translate this (if possible) to a hostname.
If gethostbyaddr(3) failed to return a useful hostname, inet_addr(3) is used to translate the peer address into a dotted ip string.
Parameters:
pSocket - Pointer to the socket for which this information is to be retrieved.
NOTE: We assume gethostbyaddr(3) and inet_addr(3) are not thread-safe.
Definition at line 397 of file CTCPConnectionLost.cpp.
References CApplicationSerializer::getInstance(), CSocket::getSocketFd(), CThreadRecursiveMutex::Lock(), m_Host, and CThreadRecursiveMutex::UnLock().
Referenced by CTCPConnectionLost().
CTCPConnectionLost & CTCPConnectionLost::operator= (const CTCPConnectionLost & rhs)
Assignment operator. Only slightly different than copy construction:
Protect against self assign.
Return *this.
this is already fully constructed.
Parameters:
rhs - Reference to rhs of assignment operation.
Definition at line 334 of file CTCPConnectionLost.cpp.
References m_Host, m_Port, and CErrnoException::operator=().
int CTCPConnectionLost::operator== (const CTCPConnectionLost & rhs)
Equality comparison.
Parameters:
rhs The right hand side of the ==.
Definition at line 349 of file CTCPConnectionLost.cpp.
References m_Host, m_Port, and CErrnoException::operator==().
void CTCPConnectionLost::Port (CSocket * pSocket) [protected]
For a given CSocket (p.)* fills in m_Port. This is done by:
Retreiving the socket fd.
Asking getpeername(2) who is attached to the socket.
Asking getservbyport(3) to return the service name from the port.
If getservbyport(3) failed, the numeric service name is encoded.
If getpeername(2) failed, the port -unavailable- is returned.
Parameters:
pSocket - Pointer to the soket about which we're asking.
NOTE: We assume that getservbyport(3) is not thread safe.
Definition at line 437 of file CTCPConnectionLost.cpp.
References CApplicationSerializer::getInstance(), CSocket::getSocketFd(), CThreadRecursiveMutex::Lock(), m_Port, and CThreadRecursiveMutex::UnLock().
Referenced by CTCPConnectionLost().
const char * CTCPConnectionLost::ReasonText () const [virtual]
Return the reason for the exception as a textual string of the form:
Connection with host m_Host at m_Port was lost: CErrnoException::ReasonText() (p.)
Reimplemented from CErrnoException (p.).
Definition at line 367 of file CTCPConnectionLost.cpp.
References m_Host, m_Port, m_ReasonText, and CErrnoException::ReasonText().
void CTCPConnectionLost::setHost (const string & rHost) [inline, protected]
Definition at line 337 of file CTCPConnectionLost.h.
References m_Host.
void CTCPConnectionLost::setPort (const string & rPort) [inline, protected]
Definition at line 340 of file CTCPConnectionLost.h.
References m_Port.
Member Data Documentation
string CTCPConnectionLost::m_Host [private]
Definition at line 310 of file CTCPConnectionLost.h.
Referenced by getHost(), Host(), operator=(), operator==(), ReasonText(), and setHost().
string CTCPConnectionLost::m_Port [private]
Definition at line 311 of file CTCPConnectionLost.h.
Referenced by getPort(), operator=(), operator==(), Port(), ReasonText(), and setPort().
string CTCPConnectionLost::m_ReasonText [private]
Definition at line 313 of file CTCPConnectionLost.h.
Referenced by ReasonText().
The documentation for this class was generated from the following files:
CTCPConnectionLost.h
CTCPConnectionLost.cpp