CTCLResult Class Reference
#include <TCLResult.h>
Public Methods
CTCLResult ()
~CTCLResult ()
CTCLResult (CTCLInterpreter *pInterp)
CTCLResult (const CTCLResult &aCTCLResult)
CTCLResult & operator= (const CTCLResult &aCTCLResult)
int operator== (const CTCLResult &aCTCLResult)
CTCLResult & operator= (const char *pString)
CTCLResult & operator= (const std::string &rString)
CTCLResult & operator+= (const char *pString)
CTCLResult & operator+= (const std::string &rString)
CTCLResult & operator+ (const char *pString)
CTCLResult & operator+ (const std::string &rString)
void Clear ()
void AppendElement (const char *pString)
void AppendElement (const std::string &rString)
operator const char * ()
operator std::string ()
operator CTCLString ()
Constructor & Destructor Documentation
CTCLResult::CTCLResult () [inline]
Definition at line 315 of file TCLResult.h.
CTCLResult::~CTCLResult () [inline]
Definition at line 316 of file TCLResult.h.
CTCLResult::CTCLResult (CTCLInterpreter * pInterp) [inline]
Definition at line 320 of file TCLResult.h.
CTCLResult::CTCLResult (const CTCLResult & aCTCLResult) [inline]
Definition at line 326 of file TCLResult.h.
Member Function Documentation
void CTCLResult::AppendElement (const std::string & rString) [inline]
Definition at line 373 of file TCLResult.h.
References AppendElement().
void CTCLResult::AppendElement (const char * pString)
Definition at line 394 of file TCLResult.cpp.
References CTCLInterpreterObject::AssertIfNotBound(), and CTCLInterpreter::getInterpreter().
Referenced by AppendElement().
void CTCLResult::Clear ()
Definition at line 377 of file TCLResult.cpp.
References CTCLInterpreterObject::AssertIfNotBound(), and CTCLInterpreter::getInterpreter().
CTCLResult::operator const char * ()
Definition at line 417 of file TCLResult.cpp.
References CTCLInterpreterObject::AssertIfNotBound(), and CTCLInterpreter::getInterpreter().
CTCLResult::operator CTCLString ()
Definition at line 450 of file TCLResult.cpp.
CTCLResult::operator std::string ()
Definition at line 434 of file TCLResult.cpp.
CTCLResult& CTCLResult::operator+ (const std::string & rString) [inline]
Definition at line 366 of file TCLResult.h.
References operator+=().
CTCLResult& CTCLResult::operator+ (const char * pString) [inline]
Definition at line 363 of file TCLResult.h.
References operator+=().
CTCLResult& CTCLResult::operator+= (const std::string & rString) [inline]
Definition at line 360 of file TCLResult.h.
References operator+=().
CTCLResult & CTCLResult::operator+= (const char * pString)
Definition at line 350 of file TCLResult.cpp.
References CTCLInterpreterObject::AssertIfNotBound(), and CTCLInterpreter::getInterpreter().
Referenced by operator+(), and operator+=().
CTCLResult& CTCLResult::operator= (const std::string & rString) [inline]
Definition at line 355 of file TCLResult.h.
References operator=().
CTCLResult & CTCLResult::operator= (const char * pString)
Definition at line 321 of file TCLResult.cpp.
References CTCLInterpreterObject::AssertIfNotBound(), and CTCLInterpreter::getInterpreter().
CTCLResult& CTCLResult::operator= (const CTCLResult & aCTCLResult) [inline]
Definition at line 334 of file TCLResult.h.
References CTCLInterpreterObject::operator=().
Referenced by operator=().
int CTCLResult::operator== (const CTCLResult & aCTCLResult) [inline]
Definition at line 344 of file TCLResult.h.
References CTCLInterpreterObject::operator==().
The documentation for this class was generated from the following files:
TCLResult.h
TCLResult.cpp