XMList Class Reference
#include <XMList.h>
Public Methods
XMList (char *n, XMWidget &parent, int rows=10, ArgList args=NULL, Cardinal arg_count=0)
XMList (char *n, Widget parent, int rows=10, ArgList args=NULL, Cardinal arg_count=0)
XMList (char *n)
XMList (Widget w)
Constructor & Destructor Documentation
XMList::XMList (char * n, XMWidget & parent, int rows = 10, ArgList args = NULL, Cardinal arg_count = 0) [inline]
Definition at line 447 of file XMList.h.
References XMWidget::Manage(), and XMListBaseClass::SetRows().
XMList::XMList (char * n, Widget parent, int rows = 10, ArgList args = NULL, Cardinal arg_count = 0) [inline]
Definition at line 453 of file XMList.h.
References XMWidget::Manage(), and XMListBaseClass::SetRows().
XMList::XMList (char * n) [inline]
Definition at line 459 of file XMList.h.
References XMWidget::Manage().
XMList::XMList (Widget w) [inline]
Definition at line 460 of file XMList.h.
References XMWidget::Manage().
The documentation for this class was generated from the following file:
XMList.h