CDAQTCLProcessor Class Reference
#include <CDAQTCLProcessor.h>
Public Methods
CDAQTCLProcessor (const string &rCommand, CTCLInterpreter *pInterp)
CDAQTCLProcessor (const char *pCommand, CTCLInterpreter *pInter)
~CDAQTCLProcessor ()
int operator== (const CDAQTCLProcessor &aCDAQTCLProcessor) const
Operator== Equality Operator.
virtual void Register ()
Private Methods
CDAQTCLProcessor (const CDAQTCLProcessor &aCDAQTCLProcessor)
Copy Constructor illegal and therefore unimplemented.
CDAQTCLProcessor & operator= (const CDAQTCLProcessor &aCDAQTCLProcessor)
Operator= Assignment Operator illegal and therefore unimplemented.
Static Private Methods
int EvalRelay (ClientData pData, Tcl_Interp *pInterp, int Argc, char **Argv)
void DeleteRelay (ClientData pData)
Detailed Description
Provides a synchronized TCL command. Inheriting from this class allows you to produce a TCL command which is synchronized to the application through the application mutex. This member essentially just replaces the TCLProcessor's registration procedures and static callback relay. The static callback relay will now lock the application mutex prior to calling operator() and unlock on return (exception or normal).
Definition at line 318 of file CDAQTCLProcessor.h.
Constructor & Destructor Documentation
CDAQTCLProcessor::CDAQTCLProcessor (const string & rCommand, CTCLInterpreter * pInterp)
Constructor. Builds a new command which will execute synchronized with all other threads in the application.
Definition at line 309 of file CDAQTCLProcessor.cpp.
CDAQTCLProcessor::CDAQTCLProcessor (const char * pCommand, CTCLInterpreter * pInterp)
Constructor, Builds a new command which will execute synchronized with all the other threads in the application.
Definition at line 319 of file CDAQTCLProcessor.cpp.
CDAQTCLProcessor::~CDAQTCLProcessor ()
Destructor: The base class will take care of everything we need. The fact that register registered our DeleteRelay will take care of ensuring that OnDelete is executed with application synchronization.
Definition at line 301 of file CDAQTCLProcessor.cpp.
CDAQTCLProcessor::CDAQTCLProcessor (const CDAQTCLProcessor & aCDAQTCLProcessor) [private]
Copy Constructor illegal and therefore unimplemented.
Member Function Documentation
void CDAQTCLProcessor::DeleteRelay (ClientData pData) [static, private]
Locks the application mutex, call's the object's OnDelete member function (the object is pointed to by the client data parameter), and unlocks the mutex.
Reimplemented from CTCLProcessor (p.).
Definition at line 374 of file CDAQTCLProcessor.cpp.
References CTCLProcessor::DeleteRelay(), CApplicationSerializer::getInstance(), CThreadRecursiveMutex::Lock(), and CThreadRecursiveMutex::UnLock().
Referenced by Register().
int CDAQTCLProcessor::EvalRelay (ClientData pData, Tcl_Interp * pInterp, int Argc, char ** Argv) [static, private]
Locks the application mutex, calls operator() and the unlocks the resource.
Definition at line 351 of file CDAQTCLProcessor.cpp.
References CTCLProcessor::EvalRelay(), CApplicationSerializer::getInstance(), CThreadRecursiveMutex::Lock(), and CThreadRecursiveMutex::UnLock().
Referenced by Register().
CDAQTCLProcessor& CDAQTCLProcessor::operator= (const CDAQTCLProcessor & aCDAQTCLProcessor) [private]
Operator= Assignment Operator illegal and therefore unimplemented.
int CDAQTCLProcessor::operator== (const CDAQTCLProcessor & aCDAQTCLProcessor) const [inline]
Operator== Equality Operator.
Definition at line 335 of file CDAQTCLProcessor.h.
References CTCLProcessor::operator==().
void CDAQTCLProcessor::Register () [virtual]
Registers the processor on the current interpreter. This reimplements code from the base class because I need to specify my own Eval and Delete relay functions (there's naturally no way for static functions to be virtual).
Reimplemented from CTCLProcessor (p.).
Definition at line 334 of file CDAQTCLProcessor.cpp.
References CTCLInterpreter::AddCommand(), CTCLProcessor::AddRegisteredOnCurrent(), CTCLInterpreterObject::AssertIfNotBound(), DeleteRelay(), EvalRelay(), and CTCLProcessor::getCommandName().
Referenced by CInterpreterStartup::RegisterExtensions().
The documentation for this class was generated from the following files:
CDAQTCLProcessor.h
CDAQTCLProcessor.cpp