CObjectRegistry Class Reference
#include <CObjectRegistry.h>
Public Methods
CObjectRegistry (string am_sName)
virtual ~CObjectRegistry ()
map< string, CNamedObject * > getObjects () const
void Add (CNamedObject &rObject)
void Remove (const string &rName)
void Remove (const CNamedObject &rObject)
const ObjectIterator Find (const string &rObjectName) const
ObjectIterator begin ()
ObjectIterator end ()
virtual string DescribeSelf ()
Protected Methods
void setObjects (map< string, CNamedObject * > am_Objects)
Private Attributes
map< string, CNamedObject * > m_Objects
Detailed Description
Implements a registry of named objects. Registries allow you to determine which instances of particular types of objects exist. Typically a programmer wanting to allow this level of introspection will subclass a class hierarchy from CRegisteredObject (p.) such that the constructor of each class will register that class. One can then programmatically search for named instances of a class as well as iterate through the registry to determine which instances exist.
Definition at line 321 of file CObjectRegistry.h.
Constructor & Destructor Documentation
CObjectRegistry::CObjectRegistry (string am_sName) [inline]
Map containing the name key and a pointer to the object.
Definition at line 329 of file CObjectRegistry.h.
References CNamedObject::AppendClassInfo().
virtual CObjectRegistry::~CObjectRegistry () [inline, virtual]
Definition at line 334 of file CObjectRegistry.h.
Member Function Documentation
void CObjectRegistry::Add (CNamedObject & rObject)
Adds an object to the object registry. The name of the object is gotten from the object itself.
Parameters:
rObject The object to add to the registry.
Definition at line 310 of file CObjectRegistry.cpp.
References CNamedObject::getName(), and m_Objects.
ObjectIterator CObjectRegistry::begin ()
Returns an iterator which 'points' to the beginning of the registry of objects. Traversing the registry through this iterator will visit all objects in name alphabetical order.
Definition at line 386 of file CObjectRegistry.cpp.
References m_Objects.
string CObjectRegistry::DescribeSelf () [virtual]
Returns a string which describes the registry The description includes the name and class path of the registry, and the name and class path of all objects contained in the registry.
Reimplemented from CNamedObject (p.).
Definition at line 409 of file CObjectRegistry.cpp.
References CNamedObject::DescribeSelf(), m_Objects, and ObjectIterator.
ObjectIterator CObjectRegistry::end ()
Returns an iterator which 'points' off the end of the registry of objects. Provided to allow clients to know when to terminate iteration through the registry.
Definition at line 397 of file CObjectRegistry.cpp.
References m_Objects.
const ObjectIterator CObjectRegistry::Find (const string & rObjectName) const
Searches the registry for an object name. If the object exists in the registry, an ObjectIterator pointing to the object is returned. If it does not exist, a CNoSuchObjectException (p.) is thrown.
Parameters:
rObjectName The name of the object to find.
Definition at line 368 of file CObjectRegistry.cpp.
References m_Objects, and ObjectIterator.
map<string, CNamedObject*> CObjectRegistry::getObjects () const [inline]
Definition at line 339 of file CObjectRegistry.h.
References m_Objects.
void CObjectRegistry::Remove (const CNamedObject & rObject)
Removes an object from the object registry. The name of the object is obtained from the object itself. If the name does not exist in the registry, a CNoSuchObjectException (p.) is thrown.
Parameters:
rObject The object to be removed from the registry.
Definition at line 350 of file CObjectRegistry.cpp.
References CNamedObject::getName(), and m_Objects.
void CObjectRegistry::Remove (const string & rName)
Removes an object from the object registry. The name of the object is inserted into the registry. If the name does not exists, a CNoSuchObjectException (p.) is thrown.
Parameters:
rName The name of the object to remove from the registry.
Definition at line 332 of file CObjectRegistry.cpp.
References m_Objects.
void CObjectRegistry::setObjects (map< string, CNamedObject * > am_Objects) [inline, protected]
Definition at line 347 of file CObjectRegistry.h.
References m_Objects.
Member Data Documentation
map<string, CNamedObject*> CObjectRegistry::m_Objects [private]
Definition at line 323 of file CObjectRegistry.h.
Referenced by Add(), begin(), DescribeSelf(), end(), Find(), getObjects(), Remove(), and setObjects().
The documentation for this class was generated from the following files:
CObjectRegistry.h
CObjectRegistry.cpp