CDuplicateSingleton Class Reference
#include <CDuplicateSingleton.h>
Public Methods
CDuplicateSingleton (const char *pDoing, const char *pName)
CDuplicateSingleton (const char *pDoing, const string &rName)
CDuplicateSingleton (const string &rDoing, const char *pName)
CDuplicateSingleton (const string &rDoing, const string &rName)
virtual ~CDuplicateSingleton ()
CDuplicateSingleton (const CDuplicateSingleton &aCDuplicateSingleton)
CDuplicateSingleton operator= (const CDuplicateSingleton &aCDuplicateSingleton)
int operator== (const CDuplicateSingleton &aCDuplicateSingleton)
string getName () const
void setName (string am_sName)
virtual const char * ReasonText () const
Protected Methods
void UpdateReasonText ()
Private Attributes
string m_sName
string m_sReasonText
Constructor & Destructor Documentation
CDuplicateSingleton::CDuplicateSingleton (const char * pDoing, const char * pName) [inline]
Definition at line 299 of file CDuplicateSingleton.h.
References m_sName, and UpdateReasonText().
CDuplicateSingleton::CDuplicateSingleton (const char * pDoing, const string & rName) [inline]
Definition at line 304 of file CDuplicateSingleton.h.
References m_sName, and UpdateReasonText().
CDuplicateSingleton::CDuplicateSingleton (const string & rDoing, const char * pName) [inline]
Definition at line 309 of file CDuplicateSingleton.h.
References m_sName, and UpdateReasonText().
CDuplicateSingleton::CDuplicateSingleton (const string & rDoing, const string & rName) [inline]
Definition at line 314 of file CDuplicateSingleton.h.
References m_sName, and UpdateReasonText().
virtual CDuplicateSingleton::~CDuplicateSingleton () [inline, virtual]
Definition at line 319 of file CDuplicateSingleton.h.
CDuplicateSingleton::CDuplicateSingleton (const CDuplicateSingleton & aCDuplicateSingleton) [inline]
Definition at line 323 of file CDuplicateSingleton.h.
References m_sName, and UpdateReasonText().
Member Function Documentation
string CDuplicateSingleton::getName () const [inline]
Definition at line 353 of file CDuplicateSingleton.h.
References m_sName.
CDuplicateSingleton CDuplicateSingleton::operator= (const CDuplicateSingleton & aCDuplicateSingleton) [inline]
Definition at line 333 of file CDuplicateSingleton.h.
References m_sName, CException::operator=(), and UpdateReasonText().
int CDuplicateSingleton::operator== (const CDuplicateSingleton & aCDuplicateSingleton) [inline]
Definition at line 344 of file CDuplicateSingleton.h.
References m_sName, and CException::operator==().
const char * CDuplicateSingleton::ReasonText () const [virtual]
Returns a const pointer to text which describes the reason the exception was thrown. This is exception type specific. The default action returns a pointer to the constant string: `Unspecified Exception`
Reimplemented from CException (p.).
Definition at line 283 of file CDuplicateSingleton.cpp.
References m_sReasonText.
void CDuplicateSingleton::setName (string am_sName) [inline]
Definition at line 359 of file CDuplicateSingleton.h.
References m_sName.
void CDuplicateSingleton::UpdateReasonText () [protected]
Definition at line 289 of file CDuplicateSingleton.cpp.
References m_sName, and m_sReasonText.
Referenced by CDuplicateSingleton(), and operator=().
Member Data Documentation
string CDuplicateSingleton::m_sName [private]
Definition at line 295 of file CDuplicateSingleton.h.
Referenced by CDuplicateSingleton(), getName(), operator=(), operator==(), setName(), and UpdateReasonText().
string CDuplicateSingleton::m_sReasonText [private]
Definition at line 296 of file CDuplicateSingleton.h.
Referenced by ReasonText(), and UpdateReasonText().
The documentation for this class was generated from the following files:
CDuplicateSingleton.h
CDuplicateSingleton.cpp