XMPulldown Class Reference
#include <XMMenus.h>
Public Methods
XMPulldown (char *n, Widget &parent, Cardinal max_items, ArgList l=NULL, Cardinal num_args=0)
XMPulldown (char *n, XMWidget &parent, Cardinal max_items, ArgList l=NULL, Cardinal num_args=0)
~XMPulldown ()
void Label (char *label)
void RadioMenu ()
void RadioForceOne ()
void NoRadioMenu ()
void RadioNoForceOne ()
XMPushButton * AddMenuButton (char *n, void(*callback)(XMWidget *, XtPointer, XtPointer)=NULL, XtPointer client_data=NULL, ArgList l=NULL, Cardinal num_args=0)
XMToggleButton * AddMenuToggleButton (char *n, void(*callback)(XMWidget *, XtPointer, XtPointer)=NULL, XtPointer client_data=NULL, ArgList l=NULL, Cardinal num_args=0)
XMWidget * AddSeparator ()
XMPulldown * AddSubmenu (char *n, int max_items, ArgList l=NULL, Cardinal num_args=0)
int MenuSize ()
int MaxMenuSize ()
XMMenuItem * GetMenuItem (Cardinal index)
XMMenuItem * FindMenuItem (char *n)
XMWidget * GetCascadeButton ()
XMMenuItem * GetNextMenuItem ()
XMMenuItem * GetFirstMenuItem ()
Protected Methods
void BuildMenu (Cardinal max_items, Widget parent, ArgList l, Cardinal num_args)
Protected Attributes
XMCascadeButton * pd_button
XMMenuItem * menu_items
Cardinal menu_count
Cardinal max_menu_items
Cardinal menu_cursor
Constructor & Destructor Documentation
XMPulldown::XMPulldown (char * n, Widget & parent, Cardinal max_items, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 329 of file XMMenus.h.
References BuildMenu().
Referenced by AddSubmenu().
XMPulldown::XMPulldown (char * n, XMWidget & parent, Cardinal max_items, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 335 of file XMMenus.h.
References BuildMenu(), and XMWidget::getid().
XMPulldown::~XMPulldown ()
Definition at line 379 of file XMMenus.cpp.
References Button, XMMenuItem::item, menu_count, menu_items, pd_button, Separator, Submenu, ToggleButton, XMMenuItem::type, and Unused.
Member Function Documentation
XMPushButton * XMPulldown::AddMenuButton (char * n, void(* callback)(XMWidget *, XtPointer, XtPointer) = NULL, XtPointer client_data = NULL, ArgList l = NULL, Cardinal num_args = 0)
Definition at line 442 of file XMMenus.cpp.
References Button, exit(), max_menu_items, menu_count, menu_items, XMWidget::name, and XMWidget::SetAttribute().
XMToggleButton * XMPulldown::AddMenuToggleButton (char * n, void(* callback)(XMWidget *, XtPointer, XtPointer) = NULL, XtPointer client_data = NULL, ArgList l = NULL, Cardinal num_args = 0)
Definition at line 500 of file XMMenus.cpp.
References exit(), max_menu_items, menu_count, menu_items, XMWidget::name, XMWidget::SetAttribute(), and ToggleButton.
XMWidget * XMPulldown::AddSeparator ()
Definition at line 548 of file XMMenus.cpp.
References exit(), max_menu_items, menu_count, menu_items, Separator, and XMManagedWidget::XMManagedWidget().
XMPulldown * XMPulldown::AddSubmenu (char * n, int max_items, ArgList l = NULL, Cardinal num_args = 0)
Definition at line 600 of file XMMenus.cpp.
References exit(), max_menu_items, menu_count, menu_items, Submenu, and XMPulldown().
void XMPulldown::BuildMenu (Cardinal max_items, Widget parent, ArgList l, Cardinal num_args) [protected]
Definition at line 332 of file XMMenus.cpp.
References exit(), XMWidget::id, XMMenuItem::item, XMButton::Label(), max_menu_items, menu_count, menu_items, XMWidget::name, pd_button, XMCascadeButton::SetAssociatedMenu(), XMButton::SetMnemonic(), XMMenuItem::type, and Unused.
Referenced by XMPulldown().
XMMenuItem * XMPulldown::FindMenuItem (char * n)
Definition at line 641 of file XMMenus.cpp.
References Button, exit(), XMWidget::getname(), XMMenuItem::item, menu_count, menu_items, Separator, Submenu, ToggleButton, XMMenuItem::type, and Unused.
Referenced by XMMenuBar::GetMenuItem().
XMWidget* XMPulldown::GetCascadeButton () [inline]
Definition at line 394 of file XMMenus.h.
Referenced by XMMenuBar::AddHelpPulldown().
XMMenuItem* XMPulldown::GetFirstMenuItem () [inline]
Definition at line 400 of file XMMenus.h.
References GetNextMenuItem(), and menu_cursor.
XMMenuItem* XMPulldown::GetMenuItem (Cardinal index) [inline]
Definition at line 390 of file XMMenus.h.
References menu_count.
XMMenuItem * XMPulldown::GetNextMenuItem ()
Definition at line 680 of file XMMenus.cpp.
References menu_count, menu_cursor, and menu_items.
Referenced by GetFirstMenuItem().
void XMPulldown::Label (char * label) [inline]
Definition at line 345 of file XMMenus.h.
References XMButton::Label().
int XMPulldown::MaxMenuSize () [inline]
Definition at line 389 of file XMMenus.h.
References max_menu_items.
int XMPulldown::MenuSize () [inline]
Definition at line 388 of file XMMenus.h.
References menu_count.
void XMPulldown::NoRadioMenu () [inline]
Definition at line 355 of file XMMenus.h.
References XMWidget::SetAttribute().
void XMPulldown::RadioForceOne () [inline]
Definition at line 351 of file XMMenus.h.
References XMWidget::SetAttribute().
void XMPulldown::RadioMenu () [inline]
Definition at line 349 of file XMMenus.h.
References XMWidget::SetAttribute().
void XMPulldown::RadioNoForceOne () [inline]
Definition at line 357 of file XMMenus.h.
References XMWidget::SetAttribute().
Member Data Documentation
Cardinal XMPulldown::max_menu_items [protected]
Definition at line 322 of file XMMenus.h.
Referenced by AddMenuButton(), AddMenuToggleButton(), AddSeparator(), AddSubmenu(), BuildMenu(), and MaxMenuSize().
Cardinal XMPulldown::menu_count [protected]
Definition at line 321 of file XMMenus.h.
Referenced by AddMenuButton(), AddMenuToggleButton(), AddSeparator(), AddSubmenu(), BuildMenu(), FindMenuItem(), GetMenuItem(), GetNextMenuItem(), MenuSize(), and ~XMPulldown().
Cardinal XMPulldown::menu_cursor [protected]
Definition at line 323 of file XMMenus.h.
Referenced by GetFirstMenuItem(), and GetNextMenuItem().
XMMenuItem* XMPulldown::menu_items [protected]
Definition at line 320 of file XMMenus.h.
Referenced by AddMenuButton(), AddMenuToggleButton(), AddSeparator(), AddSubmenu(), BuildMenu(), FindMenuItem(), GetNextMenuItem(), and ~XMPulldown().
XMCascadeButton* XMPulldown::pd_button [protected]
Definition at line 319 of file XMMenus.h.
Referenced by BuildMenu(), and ~XMPulldown().
The documentation for this class was generated from the following files:
XMMenus.h
XMMenus.cpp