CConfigurationManager Class Reference
#include <CConfigurationManager.h>
Public Methods
CConfigurationManager ()
Default construtor.
CConfigurationManager (list< CTypeFreeBinding * > &rBindings)
Prestocked configuration.
~CConfigurationManager ()
Destruction requires nothing special.
CConfigurationManager (const CConfigurationManager &rhs)
Copy constructor.
CConfigurationManager & operator= (const CConfigurationManager &rhs)
Assignment operator.
int operator== (const CConfigurationManager &rhs)
int operator!= (const CConfigurationManager &rhs)
list< CTypeFreeBinding * > getBindings () const
void setBindings (list< CTypeFreeBinding * > newBindings)
Replace all bindings.
void AddBinding (CTypeFreeBinding &rBinding)
void AddBinding (list< CTypeFreeBinding * > addlist)
void ReadConfigFile (const char *pName)
void ReadConfigFile (const string &rName)
void ReadConfigFile (int fd)
void Read1stConfigFile (const vector< string > &Names)
void Read1stConfigFile (const vector< string > &Paths, const char *pName)
void Read1stConfigFile (const vector< string > &Paths, const string &rName)
void ReadAllConfigFiles (const vector< string > &Name)
void ReadAllConfigFiles (const vector< string > &Paths, const char *pName)
void ReadAllConfigFiles (const vector< string > &Paths, const string &rName)
void WriteConfigFile (const char *pName)
void WriteConfigFile (const string &rName)
void WriteConfigFile (int fd)
Protected Methods
void InternalReadConfigFile (CTCLInterpreter &rInterp, int fd)
Private Attributes
list< CTypeFreeBinding * > m_lBindings
List of configuration bindings.
Detailed Description
ConfigurationManager provides a flexible scheme for configuring various application parameters. The idea is that a script or set of scripts will hold configuration information (variable sets e.g.). These configuration scripts are linked to application variables via instances of subclasses of CBinding (p.). The configuration manager is asked to read a set of configuration files, it instantiates a TCLInterpreter with which to interpret the files. Folowing this, the application has its configuration variable set as a result of this script exeuction and the set of defined bindings between TCL variables and application variables.
The following bindings are supported:
CVariableBinding (p.) - Binds a single C/C++ variable location to a TCL variable. After the configuration completes, this variable will contain the value which was set in the corresponding TCL variable, or a default value if the variable was not set during configuration.
CArrayBinding (p.) - Binds a slice of a C/C++ array to a TCL array which is assumed to be indexed by numerically encoded indices. After configuration completes, the slice contains the corresponding values from the TCL array or an optional default value if element(s) were not set.
CAssocArrayBinding (p.) - Encapsulates an associative array (STL map<string,T>). and binds it to a corresponding TCL array which is assumed to have arbitrary indices. After the configuration is done, TCL array elements are copied to corresponding Map entries, creating new entries as needed.
All of the bindings types are templated types. However due to TCL restrictions, only some type parameterizations are allowed:
int - corresponds to TCL_LINK_INT in Tcl_LinkVar e.g.
double - Corresponds to TCL_LINK_DOUBLE in Tcl_LinkVar e.g.
bool - Corresponds to TCL_LINK_BOOLEAN in Tcl_LinkVar e.g.
char* - Corresponds to TCL_LINK_STRING in Tcl_LinkVar e.g.
All of these type parameterizations are straightforward with the exception of char* char* variables are filled in with pointers to malloc'd copies of the contents of the variable after configuration is done. In practice this is only an issue if multiple configurations reads members are performed (e.g. reconfiguration after complete configuration).
The major member functions supported by this class are:
ReadConfigFile - Reads in a single configuration file.
Read1stConfigFile - Reads in a single config file searched from path.
ReadConfigFiles - Reads in a set of configuration files.
WriteConfigFile - Writes a file which can recover the current configuration.
Definition at line 357 of file CConfigurationManager.h.
Constructor & Destructor Documentation
CConfigurationManager::CConfigurationManager () [inline]
Default construtor.
Definition at line 365 of file CConfigurationManager.h.
CConfigurationManager::CConfigurationManager (list< CTypeFreeBinding * > & rBindings) [inline]
Prestocked configuration.
Definition at line 366 of file CConfigurationManager.h.
References m_lBindings.
CConfigurationManager::~CConfigurationManager () [inline]
Destruction requires nothing special.
Definition at line 368 of file CConfigurationManager.h.
CConfigurationManager::CConfigurationManager (const CConfigurationManager & rhs) [inline]
Copy constructor.
Definition at line 374 of file CConfigurationManager.h.
References m_lBindings.
Member Function Documentation
void CConfigurationManager::AddBinding (list< CTypeFreeBinding * > addlist) [inline]
Parameters:
addlist Append list of bindings
Definition at line 401 of file CConfigurationManager.h.
References m_lBindings.
void CConfigurationManager::AddBinding (CTypeFreeBinding & rBinding) [inline]
Definition at line 398 of file CConfigurationManager.h.
References m_lBindings.
list<CTypeFreeBinding*> CConfigurationManager::getBindings () const [inline]
Definition at line 388 of file CConfigurationManager.h.
References m_lBindings.
void CConfigurationManager::InternalReadConfigFile (CTCLInterpreter & rInterp, int fd) [protected]
Internal function to read a configuration file and execute it. since the lowest common denominator is a file descriptor and Tcl/Tk doesn't have a function to process a script given an fd, we'll read the entire file into a buffer and process the file from that string. In practice, configuration files will not be too large so this will not be a serious problem.
Parameters:
rInterp - Tcl Interpreter which will interpret the file.
fd - File descriptor already open on the file.
Exceptions:
CTCLException (p.) - if the script does not parse properly etc.
CErrnoException (p.) - if unable to determine file size.
Note:
It is the caller's responsibility to close the file.
Definition at line 678 of file CConfigurationManager.cpp.
References CTCLInterpreter::GlobalEval().
Referenced by ReadAllConfigFiles(), and ReadConfigFile().
int CConfigurationManager::operator!= (const CConfigurationManager & rhs) [inline]
Definition at line 382 of file CConfigurationManager.h.
References operator==().
CConfigurationManager& CConfigurationManager::operator= (const CConfigurationManager & rhs) [inline]
Assignment operator.
Definition at line 376 of file CConfigurationManager.h.
References m_lBindings.
int CConfigurationManager::operator== (const CConfigurationManager & rhs) [inline]
Definition at line 379 of file CConfigurationManager.h.
References m_lBindings.
Referenced by operator!=().
void CConfigurationManager::Read1stConfigFile (const vector< string > & Paths, const string & rName)
Reads the first configuration file which can be opened from a vector of path strings and a string filename. We just call the previous member fucnction passing the c_str() of the filename.
Parameters:
Paths - STL String vector of paths.
rName - STL string filename.
Definition at line 490 of file CConfigurationManager.cpp.
References Read1stConfigFile().
void CConfigurationManager::Read1stConfigFile (const vector< string > & Paths, const char * pName)
Given a set of directory paths, and a filename which is appended to the path, this member locates the first filename path / filename which can be opened for read and runs it as a configuration file.
What really happens is that the path vector and filename are used to create a vector of filenames to try and then the previous member function is called to do the rest.
Parameters:
Paths - Set of paths within which to search for the filename.
pName - Cstring pointer to the filename.
Definition at line 465 of file CConfigurationManager.cpp.
References PathSep, and Read1stConfigFile().
void CConfigurationManager::Read1stConfigFile (const vector< string > & rNames)
Executes the first configuration file which can be successfully opened from a list of configuration files. Note that if none of the configuration files can be located or opened, this function is a silent no-op.
Parameters:
Names - An STL vector of filenames to search. Names are searched for in vector order.
Exceptions:
CTCLException (p.) - if there was an error executing the script.
Definition at line 434 of file CConfigurationManager.cpp.
References ReadConfigFile().
Referenced by Read1stConfigFile().
void CConfigurationManager::ReadAllConfigFiles (const vector< string > & rPaths, const string & rFilename)
Reads all of the configuration files which can be found that are built by concatenating path names with a path separator and a filename. This is done by simply building a vector of the resulting filenames and passing it to the previous member
Parameters:
rPaths - STL Vector of STL strings which represent filesystem paths in which the file could live.
rFilename - STL String which is the filename to execute.
Definition at line 550 of file CConfigurationManager.cpp.
References PathSep, and ReadAllConfigFiles().
void CConfigurationManager::ReadAllConfigFiles (const vector< string > & rPaths, const char * pFilename)
Reads in all files which can be found from the filenames constructed by contcatenating a filename with set of paths. The only difference from the previous member is that the filename is represented as a C null terminated string. We'll generate an STL string from it and delegate to the previous overload.
Parameters:
rPaths - STL vector of STL strings which give the list of paths to search.
pFilename - Pointer to a null terminated string of characters which will be appended to each path in turn to generate the names of the script files which will be executed.
Definition at line 579 of file CConfigurationManager.cpp.
References ReadAllConfigFiles().
void CConfigurationManager::ReadAllConfigFiles (const vector< string > & Names)
Reads all configuration files which can be found from a set of filenames. If any filename cannot be found it is silently ignored. Files are executed in vector order.
Note that all configuration files are taken as a single configuration. An error in a single configuration script results in an exception which terminates the search.
Parameters:
Names - STL vector of STL strings which contains the set of filenames to try to open.
Exceptions:
CTCLException (p.) - If there is an error executing a script (e.g. syntax).
Definition at line 511 of file CConfigurationManager.cpp.
References InternalReadConfigFile(), and m_lBindings.
Referenced by ReadAllConfigFiles().
void CConfigurationManager::ReadConfigFile (int fd)
Reads a configuration file given that it is open on a file descriptor. The file is interpreted from its current location until end of file.
Parameters:
fd - File descriptor open on the file.
Exceptions:
CTCLException (p.) - if there was a problem interpreting the script e.g.
Definition at line 399 of file CConfigurationManager.cpp.
References InternalReadConfigFile(), and m_lBindings.
void CConfigurationManager::ReadConfigFile (const string & rName)
Reads a single configuration file specified by an stl string. Just calls the previous function with the name passed by cstring. See the documentation of the above function for more information.
Parameters:
rName - stl string containing the filename of the configuration script.
Definition at line 387 of file CConfigurationManager.cpp.
References ReadConfigFile().
void CConfigurationManager::ReadConfigFile (const char * pName)
Reads a single configuration file. This involves:
Ensuring the file exists.
Creating a CTCLInterpreter (p.) on which to interpret the config file.
Initializing all bindings on the interpreter.
Interpreting the script file.
Committing all bindings on the interpreter.
Shutting down all bindings on the interpreter.
Destroying the CTCLIntpereter.
Parameters:
pName - Pointer to the name of the file to read. This must be fully specified (absolute or relative path).
Exceptions:
CErrnoException (p.) - if e.g. file cannot be opened for read.
CTCLException (p.) - if there was a problem (e.g. syntax error) interpreting the configuration script.
Definition at line 364 of file CConfigurationManager.cpp.
Referenced by Read1stConfigFile(), and ReadConfigFile().
void CConfigurationManager::setBindings (list< CTypeFreeBinding * > newBindings) [inline]
Replace all bindings.
Definition at line 395 of file CConfigurationManager.h.
References m_lBindings.
void CConfigurationManager::WriteConfigFile (int fd)
Writes a configuration file which can be re-read to duplicate the current state of the configuration variables. The configuration file will contain a comment which will give the following information:
Identifying information to indicate that this is a configuration file written by the configuration subsystem. - When written
Name of user executing this program.
Parameters:
fd - File descriptor of file open on the output configuration file.
Exceptions:
CErrnoException (p.) - If there are problems writing to the file.
Note:
It is the caller's responsibilility to close the file.
Definition at line 601 of file CConfigurationManager.cpp.
References m_lBindings.
void CConfigurationManager::WriteConfigFile (const string & rName)
Writes a configuration file which can be re-read to duplicate the current configuration. The file is specified by an STL string object. This file simply calls the prior overload of this function specifying the .c_str() return value of the filename.
Parameters:
rName - STL const string& name of the file to write to.
Definition at line 657 of file CConfigurationManager.cpp.
References WriteConfigFile().
void CConfigurationManager::WriteConfigFile (const char * pName)
Writes a configuraiton file which can be re-read to duplicate the current configuration. The file is specified by a null terminated array of characters (C-string). This function attempts to open the specified file for write and on success delegates the actual write operation to the previous overload of this function.
Parameters:
pName - Pointer to the filename as a C-string.
Definition at line 641 of file CConfigurationManager.cpp.
Referenced by WriteConfigFile().
Member Data Documentation
list<CTypeFreeBinding*> CConfigurationManager::m_lBindings [private]
List of configuration bindings.
Definition at line 361 of file CConfigurationManager.h.
Referenced by AddBinding(), CConfigurationManager(), getBindings(), operator=(), operator==(), ReadAllConfigFiles(), ReadConfigFile(), setBindings(), and WriteConfigFile().
The documentation for this class was generated from the following files:
CConfigurationManager.h
CConfigurationManager.cpp