XMScrolledText Class Reference
#include <XMText.h>
Public Methods
XMScrolledText (char *n, XMWidget &parent, int rows=20, int columns=40, ArgList args=NULL, Cardinal arg_count=0)
XMScrolledText (char *n, Widget parent, int rows=20, int columns=40, ArgList args=NULL, Cardinal arg_count=0)
void SetMaxLength (int maxlen)
void ClearText ()
void AddText (char *string)
Widget Scroller ()
Protected Attributes
int text_length
int max_text_length
Widget scroller
Constructor & Destructor Documentation
XMScrolledText::XMScrolledText (char * n, XMWidget & parent, int rows = 20, int columns = 40, ArgList args = NULL, Cardinal arg_count = 0) [inline]
Definition at line 404 of file XMText.h.
References XMWidget::getid(), XMWidget::id, max_text_length, scroller, XMText::SetColumns(), XMText::SetRows(), and text_length.
XMScrolledText::XMScrolledText (char * n, Widget parent, int rows = 20, int columns = 40, ArgList args = NULL, Cardinal arg_count = 0) [inline]
Definition at line 415 of file XMText.h.
References XMWidget::id, max_text_length, scroller, XMText::SetColumns(), XMText::SetRows(), and text_length.
Member Function Documentation
void XMScrolledText::AddText (char * string) [inline]
Definition at line 434 of file XMText.h.
References XMWidget::id, max_text_length, and text_length.
void XMScrolledText::ClearText () [inline]
Definition at line 430 of file XMText.h.
References XMWidget::id, and text_length.
Widget XMScrolledText::Scroller () [inline]
Definition at line 447 of file XMText.h.
References scroller.
void XMScrolledText::SetMaxLength (int maxlen) [inline]
Reimplemented from XMText (p.).
Definition at line 429 of file XMText.h.
References max_text_length.
Member Data Documentation
int XMScrolledText::max_text_length [protected]
Definition at line 398 of file XMText.h.
Referenced by AddText(), SetMaxLength(), and XMScrolledText().
Widget XMScrolledText::scroller [protected]
Definition at line 399 of file XMText.h.
Referenced by Scroller(), and XMScrolledText().
int XMScrolledText::text_length [protected]
Definition at line 397 of file XMText.h.
Referenced by AddText(), ClearText(), and XMScrolledText().
The documentation for this class was generated from the following file:
XMText.h