CIncompatibleMonitor Class Reference
#include <CIncompatibleMonitor.h>
Public Methods
CIncompatibleMonitor (CEventMonitor &rMonitor, const char *pDoing)
CIncompatibleMonitor (const CIncompatibleMonitor &rhs)
virtual ~CIncompatibleMonitor ()
CIncompatibleMonitor & operator= (const CIncompatibleMonitor &rhs)
int operator== (const CIncompatibleMonitor &rhs)
string getMonitorDescription () const
void setMonitorDescription (const string &rnew)
virtual const char * ReasonText () const
Private Attributes
string m_MonitorDescription
string m_Reason
Detailed Description
Encapsulates exceptions thrown when a reactor sense that it has been attached to an incompatible event monitor. The exception is capable of returning textual string information about the type of the monitor received and what the reactor was doing when it threw the exception.
Definition at line 307 of file CIncompatibleMonitor.h.
Constructor & Destructor Documentation
CIncompatibleMonitor::CIncompatibleMonitor (CEventMonitor & rMonitor, const char * pDoing)
`Normal` Constructor. Constructs an incompatible exception object just prior to throwing it. Information from the monitor is stored as is information about what was happening in the system at the time the exception was constructed:
Parameters:
rMonitor - The monitor which was not compatible with the Reactor that detected the problem.
pDoing - Text string describing what the program was attempting to do when the incompatibility was detected.
Definition at line 306 of file CIncompatibleMonitor.cpp.
CIncompatibleMonitor::CIncompatibleMonitor (const CIncompatibleMonitor & rhs)
Copy constructor. Used by the compiler construct temporary objects or alternatively, and more usually for this class to build a 'scope safe' copy of the exception which can be saved and passed to catch handlers.
Parameters:
rhs - the reference object being copy constructed.
Definition at line 320 of file CIncompatibleMonitor.cpp.
virtual CIncompatibleMonitor::~CIncompatibleMonitor () [inline, virtual]
Definition at line 318 of file CIncompatibleMonitor.h.
Member Function Documentation
string CIncompatibleMonitor::getMonitorDescription () const [inline]
Definition at line 325 of file CIncompatibleMonitor.h.
References m_MonitorDescription.
CIncompatibleMonitor & CIncompatibleMonitor::operator= (const CIncompatibleMonitor & rhs)
Assignment operator. .much like copy construction except:
We gaurd against self assignment problems.
We are already a fully constructed object in our own right.
We return a refereince to *this.
Parameters:
rhs - the object being assigned to us.
Definition at line 335 of file CIncompatibleMonitor.cpp.
References m_MonitorDescription, and CException::operator=().
int CIncompatibleMonitor::operator== (const CIncompatibleMonitor & rhs)
Equality comparison. We do base class comparison and compare the monitor description. The m_Reason string is not relevant.
Parameters:
rhs - Reference to object we compare ourselves to.
Definition at line 351 of file CIncompatibleMonitor.cpp.
References m_MonitorDescription, and CException::operator==().
const char * CIncompatibleMonitor::ReasonText () const [virtual]
Returns a description of why the exception is being thrown. This is of the form: Incompatible Event monitor found: `monitor description`, while: Doing`
Reimplemented from CException (p.).
Definition at line 363 of file CIncompatibleMonitor.cpp.
References m_MonitorDescription, m_Reason, and CException::WasDoing().
void CIncompatibleMonitor::setMonitorDescription (const string & rnew) [inline]
Definition at line 331 of file CIncompatibleMonitor.h.
References m_MonitorDescription.
Member Data Documentation
string CIncompatibleMonitor::m_MonitorDescription [private]
Definition at line 311 of file CIncompatibleMonitor.h.
Referenced by getMonitorDescription(), operator=(), operator==(), ReasonText(), and setMonitorDescription().
string CIncompatibleMonitor::m_Reason [private]
Definition at line 312 of file CIncompatibleMonitor.h.
Referenced by ReasonText().
The documentation for this class was generated from the following files:
CIncompatibleMonitor.h
CIncompatibleMonitor.cpp