CTCLObject Class Reference
#include <TCLObject.h>
Public Methods
CTCLObject ()
virtual ~CTCLObject ()
CTCLObject (Tcl_Obj *am_pObject)
CTCLObject (const CTCLObject &aCTCLObject)
CTCLObject & operator= (const CTCLObject &aCTCLObject)
int operator== (const CTCLObject &aCTCLObject) const
Tcl_Obj * getObject ()
CTCLObject & operator= (const string &rSource)
CTCLObject & operator= (const char *pSource)
CTCLObject & operator= (int nSource)
CTCLObject & operator= (const CTCLList &rList)
CTCLObject & operator= (double dSource)
operator string ()
operator int ()
operator CTCLList ()
operator double ()
CTCLObject & operator+= (const CTCLObject &rObject)
CTCLObject & operator+= (int nItem)
CTCLObject & operator+= (const string &rItem)
CTCLObject & operator+= (const char *pItem)
CTCLObject & operator+= (double Item)
CTCLObject clone ()
CTCLObject operator() ()
Protected Methods
void setObject (Tcl_Obj *am_pObject)
void DupIfMust ()
Private Attributes
Tcl_Obj * m_pObject
Constructor & Destructor Documentation
CTCLObject::CTCLObject () [inline]
Definition at line 332 of file TCLObject.h.
References m_pObject.
Referenced by clone(), and operator()().
virtual CTCLObject::~CTCLObject () [inline, virtual]
Definition at line 339 of file TCLObject.h.
References m_pObject.
CTCLObject::CTCLObject (Tcl_Obj * am_pObject) [inline]
Definition at line 345 of file TCLObject.h.
References m_pObject.
CTCLObject::CTCLObject (const CTCLObject & aCTCLObject) [inline]
Definition at line 357 of file TCLObject.h.
References m_pObject.
Member Function Documentation
CTCLObject CTCLObject::clone ()
Definition at line 596 of file TCLObject.cpp.
References CTCLObject(), and m_pObject.
void CTCLObject::DupIfMust () [inline, protected]
Definition at line 429 of file TCLObject.h.
References m_pObject.
Referenced by operator+=(), and operator=().
Tcl_Obj* CTCLObject::getObject () [inline]
Definition at line 376 of file TCLObject.h.
References m_pObject.
CTCLObject::operator CTCLList ()
Definition at line 465 of file TCLObject.cpp.
References m_pObject.
CTCLObject::operator double ()
Definition at line 481 of file TCLObject.cpp.
References CTCLInterpreterObject::AssertIfNotBound(), CTCLInterpreter::getInterpreter(), and m_pObject.
CTCLObject::operator int ()
Definition at line 445 of file TCLObject.cpp.
References CTCLInterpreterObject::AssertIfNotBound(), CTCLInterpreter::getInterpreter(), and m_pObject.
CTCLObject::operator string ()
Definition at line 432 of file TCLObject.cpp.
References m_pObject.
CTCLObject CTCLObject::operator() ()
Definition at line 609 of file TCLObject.cpp.
References CTCLInterpreterObject::AssertIfNotBound(), CTCLObject(), CTCLInterpreter::getInterpreter(), and m_pObject.
CTCLObject & CTCLObject::operator+= (double Item)
Definition at line 577 of file TCLObject.cpp.
References CTCLInterpreterObject::AssertIfNotBound(), DupIfMust(), CTCLInterpreter::getInterpreter(), and m_pObject.
CTCLObject & CTCLObject::operator+= (const char * pItem)
Definition at line 558 of file TCLObject.cpp.
References CTCLInterpreterObject::AssertIfNotBound(), DupIfMust(), CTCLInterpreter::getInterpreter(), and m_pObject.
CTCLObject & CTCLObject::operator+= (const string & rItem)
Definition at line 540 of file TCLObject.cpp.
References CTCLInterpreterObject::AssertIfNotBound(), DupIfMust(), CTCLInterpreter::getInterpreter(), and m_pObject.
CTCLObject & CTCLObject::operator+= (int nItem)
Definition at line 518 of file TCLObject.cpp.
References CTCLInterpreterObject::AssertIfNotBound(), DupIfMust(), CTCLInterpreter::getInterpreter(), and m_pObject.
CTCLObject & CTCLObject::operator+= (const CTCLObject & rObject)
Definition at line 502 of file TCLObject.cpp.
References CTCLInterpreterObject::AssertIfNotBound(), DupIfMust(), CTCLInterpreter::getInterpreter(), and m_pObject.
CTCLObject & CTCLObject::operator= (double dSource)
Definition at line 418 of file TCLObject.cpp.
References DupIfMust(), and m_pObject.
CTCLObject & CTCLObject::operator= (const CTCLList & rList)
Definition at line 399 of file TCLObject.cpp.
References DupIfMust(), CTCLList::getList(), and m_pObject.
CTCLObject & CTCLObject::operator= (int nSource)
Definition at line 382 of file TCLObject.cpp.
References DupIfMust(), and m_pObject.
CTCLObject & CTCLObject::operator= (const char * pSource)
Definition at line 364 of file TCLObject.cpp.
References m_pObject.
CTCLObject & CTCLObject::operator= (const string & rSource)
Definition at line 347 of file TCLObject.cpp.
References DupIfMust(), and m_pObject.
CTCLObject & CTCLObject::operator= (const CTCLObject & aCTCLObject)
Definition at line 326 of file TCLObject.cpp.
References m_pObject, and CTCLInterpreterObject::operator=().
int CTCLObject::operator== (const CTCLObject & aCTCLObject) const
Definition at line 309 of file TCLObject.cpp.
References m_pObject.
void CTCLObject::setObject (Tcl_Obj * am_pObject) [inline, protected]
Definition at line 385 of file TCLObject.h.
References m_pObject.
Member Data Documentation
Tcl_Obj* CTCLObject::m_pObject [private]
Definition at line 325 of file TCLObject.h.
Referenced by clone(), CTCLObject(), DupIfMust(), getObject(), operator CTCLList(), operator double(), operator int(), operator string(), operator()(), operator+=(), operator=(), operator==(), setObject(), and ~CTCLObject().
The documentation for this class was generated from the following files:
TCLObject.h
TCLObject.cpp