XMTextField Class Reference
#include <XMText.h>
Public Methods
XMTextField (char *n, XMWidget &parent, int columns=30, ArgList args=NULL, Cardinal arg_count=0)
XMTextField (char *n, Widget parent, int columns=30, ArgList args=NULL, Cardinal arg_count=0)
XMTextField (char *n)
XMTextField (Widget w)
void SetColumns (int columns)
void SetMaxLength (int len)
void EnableWordWrap ()
char * GetText ()
void SetText (char *txt)
Callback_data * AddActivateCallback (void(*callback)(XMWidget *, XtPointer, XtPointer), XtPointer user_data=NULL)
Constructor & Destructor Documentation
XMTextField::XMTextField (char * n, XMWidget & parent, int columns = 30, ArgList args = NULL, Cardinal arg_count = 0) [inline]
Definition at line 356 of file XMText.h.
References SetColumns().
XMTextField::XMTextField (char * n, Widget parent, int columns = 30, ArgList args = NULL, Cardinal arg_count = 0) [inline]
Definition at line 363 of file XMText.h.
References SetColumns().
XMTextField::XMTextField (char * n) [inline]
Definition at line 369 of file XMText.h.
XMTextField::XMTextField (Widget w) [inline]
Definition at line 370 of file XMText.h.
Member Function Documentation
Callback_data* XMTextField::AddActivateCallback (void(* callback)(XMWidget *, XtPointer, XtPointer), XtPointer user_data = NULL) [inline]
Definition at line 388 of file XMText.h.
References XMWidget::AddCallback().
void XMTextField::EnableWordWrap () [inline]
Definition at line 380 of file XMText.h.
References XMWidget::SetAttribute().
char* XMTextField::GetText () [inline]
Definition at line 383 of file XMText.h.
References XMWidget::id.
void XMTextField::SetColumns (int columns) [inline]
Definition at line 374 of file XMText.h.
References XMWidget::SetAttribute().
Referenced by XMTextField().
void XMTextField::SetMaxLength (int len) [inline]
Definition at line 377 of file XMText.h.
References XMWidget::SetAttribute().
void XMTextField::SetText (char * txt) [inline]
Definition at line 385 of file XMText.h.
References XMWidget::id.
The documentation for this class was generated from the following file:
XMText.h