CTCLIdleProcess Class Reference
#include <TCLIdleProcess.h>
Public Methods
CTCLIdleProcess (CTCLInterpreterObject *pInterp)
CTCLIdleProcess (CTCLInterpreter *pInterp)
virtual ~CTCLIdleProcess ()
int operator== (const CTCLIdleProcess &rRhs)
void Set ()
void Clear ()
virtual void operator() ()=0
Private Methods
CTCLIdleProcess (const CTCLIdleProcess &rRhs)
CTCLIdleProcess & operator= (const CTCLIdleProcess &rRhs)
Constructor & Destructor Documentation
CTCLIdleProcess::CTCLIdleProcess (CTCLInterpreterObject * pInterp) [inline]
Definition at line 327 of file TCLIdleProcess.h.
References CTCLInterpreterObject::getInterpreter().
CTCLIdleProcess::CTCLIdleProcess (CTCLInterpreter * pInterp) [inline]
Definition at line 330 of file TCLIdleProcess.h.
virtual CTCLIdleProcess::~CTCLIdleProcess () [inline, virtual]
Definition at line 333 of file TCLIdleProcess.h.
CTCLIdleProcess::CTCLIdleProcess (const CTCLIdleProcess & rRhs) [private]
Member Function Documentation
void CTCLIdleProcess::Clear () [inline]
Reimplemented from CTCLTimer (p.).
Definition at line 358 of file TCLIdleProcess.h.
References CTCLTimer::Clear().
virtual void CTCLIdleProcess::operator() () [pure virtual]
Implements CTCLTimer (p.).
CTCLIdleProcess& CTCLIdleProcess::operator= (const CTCLIdleProcess & rRhs) [private]
int CTCLIdleProcess::operator== (const CTCLIdleProcess & rRhs) [inline]
Definition at line 349 of file TCLIdleProcess.h.
References CTCLInterpreterObject::operator==().
void CTCLIdleProcess::Set () [inline]
Reimplemented from CTCLTimer (p.).
Definition at line 355 of file TCLIdleProcess.h.
References CTCLTimer::Set().
The documentation for this class was generated from the following file:
TCLIdleProcess.h