CServerConnectionEvent Class Reference
\class: CServerConnectionEvent \file: CServerConnectionEvent.h.
#include <CServerConnectionEvent.h>
Public Methods
CServerConnectionEvent (CSocket &sock)
CServerConnectionEvent (const char *pName, CSocket &sock)
CServerConnectionEvent (const string &rName, CSocket &sock)
CServerConnectionEvent (const string &rServiceName)
CServerConnectionEvent (const char *pName, const string &rServiceName)
CServerConnectionEvent (const string &rName, const string &rServiceName)
CServerConnectionEvent (int nFd)
CServerConnectionEvent (const char *pName, int nFd)
CServerConnectionEvent (const string &rName, int nFd)
~CServerConnectionEvent ()
CSocket * getSocket ()
bool isDynamicSocket () const
virtual void OnConnection (CSocket *pPeer)
virtual void OnReadable (istream &rStream)
virtual string DescribeSelf ()
Protected Methods
void setSocket (CSocket *pSocket)
void setDynamic (bool fDyn)
void ConfigureSocket (const string &rSvcName)
void ConfigureSocket (int nPort)
int Protocol ()
Private Methods
CServerConnectionEvent (const CServerConnectionEvent &rhs)
CServerConnectionEvent & operator= (const CServerConnectionEvent &rhs)
int operator== (const CServerConnectionEvent &rhs)
Private Attributes
CSocket * m_pService
Server listener socket.
bool m_fDeleteSocket
true if destructor delete socket.
Detailed Description
\class: CServerConnectionEvent \file: CServerConnectionEvent.h.
This class encapsulates the process of listening for and accepting client connections to a Tcp/Ip service. The event is policy free in the sense that all it does is set up an encapsulated CSocket (p.) to listen on a specified port and listen for connections on the socket within a thread. When a connection request is received... it is accepted and the resulting socket is passed to OnConnection() (p.)
The user of this class in general will subclass the server and override the default (no-op) implementation of OnConnection() (p.)
Definition at line 322 of file CServerConnectionEvent.h.
Constructor & Destructor Documentation
CServerConnectionEvent::CServerConnectionEvent (CSocket & rSocket)
Construct an anonymous connection listener from an existing socket object. In this case, it will not be necessary for the destructor to eliminate the socket.
Parameters:
sock - An existing socket, bound, listening and ready to accept when the fd becomes readable.
Definition at line 305 of file CServerConnectionEvent.cpp.
CServerConnectionEvent::CServerConnectionEvent (const char * pname, CSocket & rSocket)
Construct a named connection listener from and existing socket object.
Parameters:
pName - char* pointer to the name of the event.
rSocket - Reference to existing socket.
Definition at line 317 of file CServerConnectionEvent.cpp.
CServerConnectionEvent::CServerConnectionEvent (const string & rName, CSocket & rSocket)
Construct a named connnection listener from an existing socket object.
Parameters:
rName - Reference to the object name desired.
rSocket- Socket to create the listener around. The socket must be in the listening state, by the time the event is enabled/scheduled.
Definition at line 331 of file CServerConnectionEvent.cpp.
CServerConnectionEvent::CServerConnectionEvent (const string & rServiceName)
Construct an anonymous connection listener from a service name. Since we need to construct the file event with an fd, that will be done by an explicit socket(2) call. The m_pService will be dynamically allocated and configured from the fd, and the service information in the constructor body.
Parameters:
rServiceName - Name of the service to connect to. The CSocket (p.) type accepts either a name which translates via getservbyname, or a stringified service number.
Definition at line 349 of file CServerConnectionEvent.cpp.
References ConfigureSocket().
CServerConnectionEvent::CServerConnectionEvent (const char * pName, const string & rServiceName)
Construct a named connection listener from a service name. See above for more information.
Parameters:
pName - char* name to be given to the connection listener.
rServiceName - Name of the service to connect to. The CSocket (p.) type accepts either a name which translates via getservbyname, or a stringified service number.
Definition at line 365 of file CServerConnectionEvent.cpp.
References ConfigureSocket().
CServerConnectionEvent::CServerConnectionEvent (const string & rName, const string & rServiceName)
Definition at line 373 of file CServerConnectionEvent.cpp.
References ConfigureSocket().
CServerConnectionEvent::CServerConnectionEvent (int nFd)
Construct an anonymous Connection listener given a file id which represents a bound and listening socket.
Parameters:
nFd - A file descriptor which is a bound and listening socket.
Definition at line 388 of file CServerConnectionEvent.cpp.
CServerConnectionEvent::CServerConnectionEvent (const char * pName, int nFd)
Construct a named connection listener given a file id which represents a bound and listening socket.
Parameters:
pName - char* name to be given to the socket.
nFd - File descriptor representing a bound and listening sock.
Definition at line 401 of file CServerConnectionEvent.cpp.
CServerConnectionEvent::CServerConnectionEvent (const string & rName, int nFd)
Construct a named connection listener given a file id which represents a bound and listening socket.
Parameters:
rName - string& name to be given to the socket.
nFd - File descriptor representing a bound and listening socket.
Definition at line 414 of file CServerConnectionEvent.cpp.
CServerConnectionEvent::~CServerConnectionEvent ()
Destructor... if m_fDelete socket is true, then the socket is deleted. otherwise just closed.
Definition at line 425 of file CServerConnectionEvent.cpp.
References m_pService, and CSocket::Shutdown().
CServerConnectionEvent::CServerConnectionEvent (const CServerConnectionEvent & rhs) [private]
Member Function Documentation
void CServerConnectionEvent::ConfigureSocket (int nPort) [protected]
Utility function to configure a socket. The port id is used to bind the socket and set it into listen mode.
Note:
It's possible that a socket can come into this function in the wrong mode if there are program errors. In that case, the CSocket (p.) calls made may throw an exception. We catch all exceptions, if necessary delete the socket object and rethrow to the caller.
Parameters:
nPort - The number of the port to bind the socket to.
Note:
On non exceptional exit from this function, m_pService is bound to the selected service and the socket is in the listen state.
Definition at line 513 of file CServerConnectionEvent.cpp.
References ConfigureSocket().
void CServerConnectionEvent::ConfigureSocket (const string & rSvcName) [protected]
Utility function to configure a socket. The service name is used to bind the socket and set it into listen mode.
Note:
It's possible that a socket can come into this function in the wrong mode if there are program errors. In that case, the CSocket (p.) calls made may throw an exception. We catch all exceptions, if necessary delete the socket object and rethrow to the caller.
Parameters:
rSvcName - A service name which can either be an entry in the local system's service data base, or alternatively a numerically encoded port id.
Note:
On non exceptional exit from this function, m_pService is bound to the selected service and the socket is in the listen state.
Definition at line 485 of file CServerConnectionEvent.cpp.
References CSocket::Bind(), CSocket::Listen(), m_fDeleteSocket, and m_pService.
Referenced by ConfigureSocket(), and CServerConnectionEvent().
string CServerConnectionEvent::DescribeSelf () [virtual]
Returns a string which describes this object.
Reimplemented from CFileEvent (p.).
Definition at line 552 of file CServerConnectionEvent.cpp.
References CEvent::DescribeSelf(), CSocket::getSocketFd(), CSocket::getState(), m_fDeleteSocket, m_pService, and CSocket::StateName().
CSocket* CServerConnectionEvent::getSocket () [inline]
Definition at line 363 of file CServerConnectionEvent.h.
bool CServerConnectionEvent::isDynamicSocket () const [inline]
Definition at line 367 of file CServerConnectionEvent.h.
References m_fDeleteSocket.
void CServerConnectionEvent::OnConnection (CSocket * pPeer) [virtual]
This member function is called whenever a connection is available. The default implementation rejects the connection and destroys the connection object. It's assumed that the user of this class will subclass it and override this member with code to generate an object to manage the connection. How this is done depends on the needs of the application. One typical way to do this would be to create a CServerInstance (p.) derived object and enable it. This would start up a server instance in a separate thread, to handle requests in a application synchronized manner.
Parameters:
pPeer - pointer to dynamically created socket representing the connection peer.
Definition at line 445 of file CServerConnectionEvent.cpp.
References CSocket::Shutdown().
Referenced by OnReadable().
void CServerConnectionEvent::OnReadable (istream & rStream) [virtual]
Called when the service socket becomes readable. This indicates that a connection request is available. The request is serviced by an accept on the service socket and OnConnection is called to handle the actual service.
Note:
OnReadable is called while holding the application serialization mutex.
OnReadable in general need not be overridden in subclasses.
Parameters:
rStream - istream on the socket... ignored.
Reimplemented from CFileEvent (p.).
Definition at line 462 of file CServerConnectionEvent.cpp.
References CSocket::Accept(), m_pService, and OnConnection().
CServerConnectionEvent& CServerConnectionEvent::operator= (const CServerConnectionEvent & rhs) [private]
int CServerConnectionEvent::operator== (const CServerConnectionEvent & rhs) [private]
int CServerConnectionEvent::Protocol () [protected]
Determine the correct protocol id for a socket(2) call. We only support tcp as the protocol. This function encapsulates the call to getprotobyname(3), and the decode of the arguments. getprotobyname(3) is assumed to be non-reentrant/non-recursive and therefore the call to it is serialized to the application.
Failures are not considered possible, so are asserted against, since the only acceptable protocol is `TCP`.
Return values:
int - a protocol id suitable for the last parameter of the socket(2) call.
Definition at line 535 of file CServerConnectionEvent.cpp.
References CApplicationSerializer::getInstance(), CThreadRecursiveMutex::Lock(), and CThreadRecursiveMutex::UnLock().
void CServerConnectionEvent::setDynamic (bool fDyn) [inline, protected]
Definition at line 376 of file CServerConnectionEvent.h.
References m_fDeleteSocket.
void CServerConnectionEvent::setSocket (CSocket * pSocket) [inline, protected]
Definition at line 373 of file CServerConnectionEvent.h.
Member Data Documentation
bool CServerConnectionEvent::m_fDeleteSocket [private]
true if destructor delete socket.
Definition at line 327 of file CServerConnectionEvent.h.
Referenced by ConfigureSocket(), DescribeSelf(), isDynamicSocket(), and setDynamic().
CSocket* CServerConnectionEvent::m_pService [private]
Server listener socket.
Definition at line 326 of file CServerConnectionEvent.h.
Referenced by ConfigureSocket(), DescribeSelf(), OnReadable(), and ~CServerConnectionEvent().
The documentation for this class was generated from the following files:
CServerConnectionEvent.h
CServerConnectionEvent.cpp