CRefcountedPtr< T > Class Template Reference
#include <CRefptr.h>
Public Methods
CRefcountedPtr ()
CRefcountedPtr (T *p)
~CRefcountedPtr ()
template<class U> CRefcountedPtr (const CRefcountedPtr< U > &rhs)
CRefcountedPtr & operator= (const CRefcountedPtr &rhs)
int refcount () const
template<class U> int operator== (const CRefcountedPtr< U > &rhs)
T & operator * ()
T * operator $\rightarrow$ ()
Private Attributes
CReferenceCounted< T > * m_Object
template<class T> class CRefcountedPtr< T >
Constructor & Destructor Documentation
template<class T> CRefcountedPtr< T >::CRefcountedPtr () [inline]
Definition at line 326 of file CRefptr.h.
template<class T> CRefcountedPtr< T >::CRefcountedPtr (T * p) [inline]
Definition at line 327 of file CRefptr.h.
template<class T> CRefcountedPtr< T >::~CRefcountedPtr () [inline]
Definition at line 329 of file CRefptr.h.
References CReferenceCounted< T >::dereference(), and CReferenceCounted< T >::norefs().
template<class T> template<class U> CRefcountedPtr< T >::CRefcountedPtr (const CRefcountedPtr< U > & rhs) [inline]
Definition at line 336 of file CRefptr.h.
References CRefcountedPtr< T >::m_Object, and CReferenceCounted< T >::reference().
Member Function Documentation
template<class T> T& CRefcountedPtr< T >::operator * () [inline]
Definition at line 372 of file CRefptr.h.
template<class T> T* CRefcountedPtr< T >::operator $\rightarrow$ () [inline]
Definition at line 373 of file CRefptr.h.
References CReferenceCounted< T >::get().
template<class T> CRefcountedPtr& CRefcountedPtr< T >::operator= (const CRefcountedPtr< T > & rhs) [inline]
Definition at line 343 of file CRefptr.h.
References CReferenceCounted< T >::dereference(), CRefcountedPtr< T >::m_Object, CReferenceCounted< T >::norefs(), and CReferenceCounted< T >::reference().
template<class T> template<class U> int CRefcountedPtr< T >::operator== (const CRefcountedPtr< U > & rhs) [inline]
Definition at line 369 of file CRefptr.h.
References CRefcountedPtr< T >::m_Object.
template<class T> int CRefcountedPtr< T >::refcount () const [inline]
Definition at line 358 of file CRefptr.h.
References CReferenceCounted< T >::refcount().
Member Data Documentation
template<class T> CReferenceCounted<T>* CRefcountedPtr< T >::m_Object [private]
Definition at line 324 of file CRefptr.h.
Referenced by CRefcountedPtr< T >::CRefcountedPtr(), CRefcountedPtr< T >::operator=(), and CRefcountedPtr< T >::operator==().
The documentation for this class was generated from the following file:
CRefptr.h