CEventMonitor Class Reference
#include <CEventMonitor.h>
Public Types
enum result { Occurred = 0,
TimedOut = 1,
Error = 2
 }
Public Methods
CEventMonitor (bool am_fTimedWait=true)
CEventMonitor (const string &rName, bool am_fTimedWait=true)
CEventMonitor (const char *pName, bool am_fTimedWait=true)
int operator== (const CEventMonitor &aCEventMonitor) const
virtual ~CEventMonitor ()
timeval getTimeout () const
bool getTimedWait () const
virtual CEventMonitor::result operator() ()=0
virtual void setTimeout (int nTimeout=FOREVER)
Protected Methods
void setTimeout (const timeval am_tvTimeout)
void setTimedWait (const bool am_fTimedWait)
Static Protected Methods
string GetAutoName (const string &rBaseName)
Assign default name.
Private Methods
CEventMonitor (const CEventMonitor &aCEventMonitor)
Copy construction is forbidden for now.
CEventMonitor operator= (const CRegisteredObject &aCEventMonitor)
Assignment is forbidden for now.
Private Attributes
timeval m_tvTimeout
bool m_fTimedWait
Static Private Attributes
unsigned int m_nAutoIndex
Detailed Description
\class: CEventMonitor
This file defines the CEventMonitor class. CEventMonitor is the ABC for all Event Monitors. An event monitor provides event specific logic for waiting for external program events. operator() is expected to wait for an event to occur and return to indicate if the event in fact did occur.
Definition at line 326 of file CEventMonitor.h.
Member Enumeration Documentation
enum CEventMonitor::result
Used to name autonamed objects
Enumeration values:
Occurred
TimedOut
Error
Definition at line 335 of file CEventMonitor.h.
Referenced by CEvent::OnEvent(), and CReactor::operator()().
Constructor & Destructor Documentation
CEventMonitor::CEventMonitor (bool am_fTimedWait = true)
Default constructor. An EventMonitor with name of the form Monitor_nnn is created. The monitor is entered in to the `Monitors` registry of the classified object registry returned from getCClassifiedObjectRegistry(). The name used is gaurenteed unique and can be queried via: getName() (p.).
Definition at line 312 of file CEventMonitor.cpp.
References CNamedObject::AppendClassInfo(), m_fTimedWait, m_tvTimeout, and RegistryName.
CEventMonitor::CEventMonitor (const string & rName, bool am_fTimedWait = true)
Constructs an EventMonitor given a name as an STL string, and a value of m_fTimedWait :
Parameters:
rName - The desired name of the event monitor.
am_fTimedWait - indicates whether or not the monitor is timed
Throws:
CDuplicateNameException (p.) (indirectly) if a Reactor of this name already exists.
Definition at line 333 of file CEventMonitor.cpp.
References CNamedObject::AppendClassInfo(), m_fTimedWait, m_tvTimeout, and RegistryName.
CEventMonitor::CEventMonitor (const char * pName, bool am_fTimedWait = true)
Constructs an event monitor given its name as an ASCII string and an (optional) value for m_fTimedWait :
Parameters:
pName - char* pointer to the desired object name.
am_fTimedWait - bool indicates whether the monitor is timed
Throws: -CDuplicateNameException (p.) (indirectly) if an event monitor of this name already exists.
Definition at line 354 of file CEventMonitor.cpp.
References CNamedObject::AppendClassInfo(), m_fTimedWait, m_tvTimeout, and RegistryName.
CEventMonitor::CEventMonitor (const CEventMonitor & aCEventMonitor) [private]
Copy construction is forbidden for now.
CEventMonitor::~CEventMonitor () [virtual]
Destructor: Just ensure that we are removed from the Reactors registry before being destroyed.
Definition at line 368 of file CEventMonitor.cpp.
References CRegisteredObject::getRegistry(), RegistryName, and CClassifiedObjectRegistry::Remove().
Member Function Documentation
string CEventMonitor::GetAutoName (const string & rBaseName) [static, protected]
Assign default name.
Allocate a name for an object given some generic base name. The final name is of the form: BaseName(m_nAutoIndex).
Reimplemented from CNamedObject (p.).
Definition at line 397 of file CEventMonitor.cpp.
References m_nAutoIndex.
bool CEventMonitor::getTimedWait () const [inline]
Definition at line 375 of file CEventMonitor.h.
References m_fTimedWait.
Referenced by CFdMonitor::DescribeSelf(), CFdMonitor::operator()(), and CBufferMonitor< T >::operator()().
timeval CEventMonitor::getTimeout () const [inline]
Definition at line 370 of file CEventMonitor.h.
References m_tvTimeout.
Referenced by CFdMonitor::DescribeSelf(), CTimerMonitor::operator()(), CLocationMonitor< T >::operator()(), CFdMonitor::operator()(), and CBufferMonitor< T >::operator()().
virtual CEventMonitor::result CEventMonitor::operator() () [pure virtual]
Implemented in CBufferMonitor< T > (p.), CFdMonitor (p.), CLocationMonitor< T > (p.), CServerMonitor (p.), CTimerMonitor (p.), and CBufferMonitor< U > (p.).
CEventMonitor CEventMonitor::operator= (const CRegisteredObject & aCEventMonitor) [private]
Assignment is forbidden for now.
Reimplemented from CRegisteredObject (p.).
Reimplemented in CFdMonitor (p.).
int CEventMonitor::operator== (const CEventMonitor & aCEventMonitor) const [inline]
Definition at line 348 of file CEventMonitor.h.
References m_fTimedWait, m_tvTimeout, and CRegisteredObject::operator==().
Referenced by CTimerMonitor::operator==(), CLocationMonitor< T >::operator==(), and CFdMonitor::operator==().
void CEventMonitor::setTimedWait (const bool am_fTimedWait) [inline, protected]
Definition at line 388 of file CEventMonitor.h.
References m_fTimedWait.
void CEventMonitor::setTimeout (int nTimeout = FOREVER) [virtual]
void CEventMonitor::setTimeout (p.)(int nTimeout=FOREVER) Operation Type: mutator
Purpose: Sets the timeout. The length of the timeout is determined by the parameter in ms.. Special values: 0 - Poll (return instantly). FOREVER - Block until event.
Reimplemented in CTimerMonitor (p.).
Definition at line 389 of file CEventMonitor.cpp.
References m_fTimedWait, and m_tvTimeout.
void CEventMonitor::setTimeout (const timeval am_tvTimeout) [inline, protected]
Definition at line 383 of file CEventMonitor.h.
References m_tvTimeout.
Referenced by main(), CEvent::operator()(), and CTimerMonitor::setTimeout().
Member Data Documentation
bool CEventMonitor::m_fTimedWait [private]
Timeout length
Definition at line 329 of file CEventMonitor.h.
Referenced by CEventMonitor(), getTimedWait(), operator==(), setTimedWait(), and setTimeout().
unsigned int CEventMonitor::m_nAutoIndex [static, private]
Timed wait?
Reimplemented from CNamedObject (p.).
Referenced by GetAutoName().
timeval CEventMonitor::m_tvTimeout [private]
Definition at line 328 of file CEventMonitor.h.
Referenced by CEventMonitor(), getTimeout(), operator==(), and setTimeout().
The documentation for this class was generated from the following files:
CEventMonitor.h
CEventMonitor.cpp