CNoSuchLinkException Class Reference
#include <CNoSuchLinkException.h>
Public Methods
CNoSuchLinkException (const char *pDoing, const char *pName)
CNoSuchLinkException (const char *pDoing, const string &rName)
CNoSuchLinkException (const string &rDoing, const char *pName)
CNoSuchLinkException (const string &rDoing, const string &rName)
CNoSuchLinkException (const string &rDoing, int nId)
CNoSuchLinkException (const char *pDoing, int nId)
virtual ~CNoSuchLinkException ()
CNoSuchLinkException (const CNoSuchLinkException &aCNoSuchLinkException)
CNoSuchLinkException operator= (const CNoSuchLinkException &aCNoSuchLinkException)
int operator== (const CNoSuchLinkException &aCNoSuchLinkException)
string getName () const
void setName (string am_sName)
virtual const char * ReasonText () const
Protected Methods
void UpdateReasonText ()
Private Attributes
string m_sName
int m_nId
bool m_fName
string m_sReasonText
Constructor & Destructor Documentation
CNoSuchLinkException::CNoSuchLinkException (const char * pDoing, const char * pName) [inline]
Definition at line 301 of file CNoSuchLinkException.h.
References m_sName, and UpdateReasonText().
CNoSuchLinkException::CNoSuchLinkException (const char * pDoing, const string & rName) [inline]
Definition at line 306 of file CNoSuchLinkException.h.
References m_sName, and UpdateReasonText().
CNoSuchLinkException::CNoSuchLinkException (const string & rDoing, const char * pName) [inline]
Definition at line 311 of file CNoSuchLinkException.h.
References m_sName, and UpdateReasonText().
CNoSuchLinkException::CNoSuchLinkException (const string & rDoing, const string & rName) [inline]
Definition at line 316 of file CNoSuchLinkException.h.
References m_sName, and UpdateReasonText().
CNoSuchLinkException::CNoSuchLinkException (const string & rDoing, int nId) [inline]
Definition at line 321 of file CNoSuchLinkException.h.
References m_fName, m_nId, and UpdateReasonText().
CNoSuchLinkException::CNoSuchLinkException (const char * pDoing, int nId) [inline]
Definition at line 327 of file CNoSuchLinkException.h.
References m_fName, m_nId, and UpdateReasonText().
virtual CNoSuchLinkException::~CNoSuchLinkException () [inline, virtual]
Definition at line 333 of file CNoSuchLinkException.h.
CNoSuchLinkException::CNoSuchLinkException (const CNoSuchLinkException & aCNoSuchLinkException) [inline]
Definition at line 337 of file CNoSuchLinkException.h.
References m_sName, and UpdateReasonText().
Member Function Documentation
string CNoSuchLinkException::getName () const [inline]
Definition at line 367 of file CNoSuchLinkException.h.
References m_sName.
CNoSuchLinkException CNoSuchLinkException::operator= (const CNoSuchLinkException & aCNoSuchLinkException) [inline]
Definition at line 347 of file CNoSuchLinkException.h.
References m_sName, CException::operator=(), and UpdateReasonText().
int CNoSuchLinkException::operator== (const CNoSuchLinkException & aCNoSuchLinkException) [inline]
Definition at line 358 of file CNoSuchLinkException.h.
References m_sName, and CException::operator==().
const char * CNoSuchLinkException::ReasonText () const [virtual]
Returns a const pointer to text which describes the reason the exception was thrown. This is exception type specific. The default action returns a pointer to the constant string: `Unspecified Exception`
Reimplemented from CException (p.).
Definition at line 285 of file CNoSuchLinkException.cpp.
References m_sReasonText.
void CNoSuchLinkException::setName (string am_sName) [inline]
Definition at line 373 of file CNoSuchLinkException.h.
References m_sName.
void CNoSuchLinkException::UpdateReasonText () [protected]
Definition at line 291 of file CNoSuchLinkException.cpp.
References m_nId, m_sName, and m_sReasonText.
Referenced by CNoSuchLinkException(), and operator=().
Member Data Documentation
bool CNoSuchLinkException::m_fName [private]
Definition at line 297 of file CNoSuchLinkException.h.
Referenced by CNoSuchLinkException().
int CNoSuchLinkException::m_nId [private]
Definition at line 296 of file CNoSuchLinkException.h.
Referenced by CNoSuchLinkException(), and UpdateReasonText().
string CNoSuchLinkException::m_sName [private]
Definition at line 295 of file CNoSuchLinkException.h.
Referenced by CNoSuchLinkException(), getName(), operator=(), operator==(), setName(), and UpdateReasonText().
string CNoSuchLinkException::m_sReasonText [private]
Definition at line 298 of file CNoSuchLinkException.h.
Referenced by ReasonText(), and UpdateReasonText().
The documentation for this class was generated from the following files:
CNoSuchLinkException.h
CNoSuchLinkException.cpp