CBinding< T > Class Template Reference
#include <CBinding.h>
Public Methods
virtual void InitBindings (CTCLInterpreter &rInterp)=0
virtual void Commit (CTCLInterpreter &rInterp)=0
virtual void Dump (int fd)=0
int VariableType (T item)
string ItemToString (T Item)
Detailed Description
template<class T> class CBinding< T >
This is an abstract base class for the Tcl configuration manager's bindings subsystem. interfaces for the functions required of all bindings objects are defined as pure virtual member functions.
Definition at line 322 of file CBinding.h.
Member Function Documentation
template<class T> virtual void CBinding< T >::Commit (CTCLInterpreter & rInterp) [pure virtual]
This function is called just after a configuration script or set of configuration scripts have been read to perform any actions required to commit the read in Tcl values to the variables. For example, an associative array bindings might need to fetch the individual values from Tcl array elements.
Parameters:
rInterp - The interpreter in which the config script was read.
Implements CTypeFreeBinding (p.).
Implemented in CArrayBinding< T > (p.), CAssocArrayBinding< T > (p.), and CVariableBinding< T > (p.).
template<class T> virtual void CBinding< T >::Dump (int fd) [pure virtual]
This function is called just prior to deleting the interpreter. Any cleanup actions required by the binding should be done at this point. For example, if Init mapped a C variable to a TCL variable, that mapping should be broken.
Parameters:
rInterp - The interpreter about to be deleted. virtual void ShutdownBindings(CTCLInterpreter& rInterp) (p.)= 0; /*! This function is called to write the set of Tcl commands required to duplicate the current state. Note that this may not be identical to the set of commands which produced the configuration.
Implements CTypeFreeBinding (p.).
Implemented in CArrayBinding< T > (p.), CAssocArrayBinding< T > (p.), and CVariableBinding< T > (p.).
template<class T> virtual void CBinding< T >::InitBindings (CTCLInterpreter & rInterp) [pure virtual]
This function will be called just prior to reading in a configuration file. The Tcl Interpreter has been set up and initialized. The Init function can do any preparation required by the binding prior to readin (e.g. a simple binding >might< bind the contained variable to a Tcl variable
Parameters:
rInterp - The interpreter on which the config script will be read.
Implements CTypeFreeBinding (p.).
Implemented in CArrayBinding< T > (p.), CAssocArrayBinding< T > (p.), and CVariableBinding< T > (p.).
template<class T> string CBinding< T >::ItemToString (T Item) [inline]
Item to string conversion: Converts an item of type T to its string representation.
Parameters:
item - item to convert.
Exceptions:
CRangeError (p.) - no type match
Bug:
 Should invent a bad type exception and throw it.
Definition at line 390 of file CBinding.h.
Referenced by CVariableBinding< T >::Dump(), CAssocArrayBinding< T >::Dump(), and CArrayBinding< T >::Dump().
template<class T> int CBinding< T >::VariableType (T item) [inline]
Returns the TCL code for the type of variable being bound to: This can be one of:
TCL_LINK_INT - Variable is an integer.
TCL_LINK_DOUBLE - Variable is a double precision.
TCL_LINK_BOOLEAN - Variable is a boolean.
TCL_LINK_STRING - Variable is a char*.
Parameters:
item - A variable of type T.
Exceptions:
CRangeError (p.) - no neat match.
Bug:
Really should invent a bad type exception and throw it instead
Definition at line 372 of file CBinding.h.
Referenced by CAssocArrayBinding< T >::CAssocArrayBinding().
The documentation for this class was generated from the following file:
CBinding.h