CTCLInterpreter Class Reference
#include <TCLInterpreter.h>
Public Methods
CTCLInterpreter ()
virtual ~CTCLInterpreter ()
CTCLInterpreter (Tcl_Interp *am_pInterpreter)
int operator== (const CTCLInterpreter &aCTCLInterpreter)
Tcl_Interp * getInterpreter ()
std::string Eval (const char *pScript)
std::string Eval (const CTCLString &rScript)
std::string Eval (const std::string &rScript)
std::string EvalFile (const char *pFilename)
std::string EvalFile (const CTCLString &rFilename)
std::string EvalFile (const std::string &rFilename)
std::string GlobalEval (const char *pScript)
std::string GlobalEval (const CTCLString &rScript)
std::string GlobalEval (const std::string &rScript)
std::string RecordAndEval (const char *pScript, Bool_t fEval=kfFALSE)
std::string RecordAndEval (const CTCLString &rScript, Bool_t fEval=kfFALSE)
std::string RecordAndEval (const std::string &rScript, Bool_t fEval=kfFALSE)
std::string ExprString (const char *pExpression)
std::string ExprString (const CTCLString &rExpr)
std::string ExprString (const std::string &rExpr)
Long_t ExprLong (const char *pExpression)
Long_t ExprLong (std::string &rExpression)
Long_t ExprLong (const CTCLString &rExpr)
DFloat_t ExprDouble (const char *pExpression)
DFloat_t ExprDouble (const CTCLString &rExpression)
DFloat_t ExprDouble (const std::string &rExpression)
Bool_t ExprBoolean (const char *pExpression)
Bool_t ExprBoolean (const CTCLString &rExpression)
Bool_t ExprBoolean (const std::string &rExpression)
std::string TildeSubst (const char *pFilename) const
std::string TildeSubst (const CTCLString &rName) const
std::string TildeSubst (const std::string &rName)
std::string PosixError () const
void DetachProcess (const std::vector< UInt_t > &rPids) const
void DetachProcess (UInt_t nPids, Int_t *pPids) const
void ReapDetachedProcesses () const
void AddCommand (const char *pCommandName, Tcl_CmdProc *pCommandProcessor, ClientData pData, Tcl_CmdDeleteProc *pDeleteProcessor=(Tcl_CmdDeleteProc *) kpNULL) const
void AddCommand (const std::string &rCommandName, Tcl_CmdProc *pCommandProcessor, ClientData pData, Tcl_CmdDeleteProc *pDeleteProcessor=(Tcl_CmdDeleteProc *) kpNULL) const
void AddCommand (const CTCLString &rCommandName, Tcl_CmdProc *pCommandProcessor, ClientData pData, Tcl_CmdDeleteProc *pDeleteProcessor=(Tcl_CmdDeleteProc *) kpNULL) const
void UnregisterCommand (const char *pCommandName) const
void UnregisterCommand (const std::string &rCommandName) const
void UnregisterCommand (const CTCLString &rCommandName) const
std::string GetResultString () const
Tcl_Interp * operator $\rightarrow$ ()
operator Tcl_Interp * ()
Static Public Methods
std::string ErrnoId ()
std::string SignalId (UInt_t nSignal)
std::string SignalMsg (UInt_t nSignal)
Protected Methods
void setInterpreter (Tcl_Interp *am_pInterpreter)
Private Methods
CTCLInterpreter (const CTCLInterpreter &aCTCLInterpreter)
CTCLInterpreter operator= (const CTCLInterpreter &aCTCLInterpreter)
Private Attributes
Tcl_Interp * m_pInterpreter
Constructor & Destructor Documentation
CTCLInterpreter::CTCLInterpreter () [inline]
Definition at line 332 of file TCLInterpreter.h.
References m_pInterpreter.
virtual CTCLInterpreter::~CTCLInterpreter () [inline, virtual]
Definition at line 336 of file TCLInterpreter.h.
References m_pInterpreter.
CTCLInterpreter::CTCLInterpreter (Tcl_Interp * am_pInterpreter) [inline]
Definition at line 341 of file TCLInterpreter.h.
References m_pInterpreter.
CTCLInterpreter::CTCLInterpreter (const CTCLInterpreter & aCTCLInterpreter) [private]
Member Function Documentation
void CTCLInterpreter::AddCommand (const CTCLString & rCommandName, Tcl_CmdProc * pCommandProcessor, ClientData pData, Tcl_CmdDeleteProc * pDeleteProcessor = (Tcl_CmdDeleteProc*)kpNULL) const [inline]
Definition at line 490 of file TCLInterpreter.h.
References AddCommand().
void CTCLInterpreter::AddCommand (const std::string & rCommandName, Tcl_CmdProc * pCommandProcessor, ClientData pData, Tcl_CmdDeleteProc * pDeleteProcessor = (Tcl_CmdDeleteProc*)kpNULL) const [inline]
Definition at line 482 of file TCLInterpreter.h.
References AddCommand().
void CTCLInterpreter::AddCommand (const char * pCommandName, Tcl_CmdProc * pCommandProcessor, ClientData pData, Tcl_CmdDeleteProc * pDeleteProcessor = (Tcl_CmdDeleteProc *) kpNULL) const
Definition at line 723 of file TCLInterpreter.cpp.
References m_pInterpreter.
Referenced by AddCommand(), CTCLProcessor::Register(), and CDAQTCLProcessor::Register().
void CTCLInterpreter::DetachProcess (UInt_t nPids, Int_t * pPids) const [inline]
Definition at line 471 of file TCLInterpreter.h.
References Int_t, and UInt_t.
void CTCLInterpreter::DetachProcess (const std::vector< UInt_t > & rPids) const
Definition at line 687 of file TCLInterpreter.cpp.
References Int_t, and UInt_t.
std::string CTCLInterpreter::ErrnoId () [static]
Definition at line 631 of file TCLInterpreter.cpp.
std::string CTCLInterpreter::Eval (const std::string & rScript) [inline]
Definition at line 385 of file TCLInterpreter.h.
References Eval().
std::string CTCLInterpreter::Eval (const CTCLString & rScript) [inline]
Definition at line 382 of file TCLInterpreter.h.
References Eval().
std::string CTCLInterpreter::Eval (const char * pScript)
Definition at line 321 of file TCLInterpreter.cpp.
References m_pInterpreter.
Referenced by Eval(), and CTCLSynchronizeCommand::operator()().
std::string CTCLInterpreter::EvalFile (const std::string & rFilename) [inline]
Definition at line 395 of file TCLInterpreter.h.
References EvalFile().
std::string CTCLInterpreter::EvalFile (const CTCLString & rFilename) [inline]
Definition at line 392 of file TCLInterpreter.h.
References EvalFile().
std::string CTCLInterpreter::EvalFile (const char * pFilename)
Definition at line 356 of file TCLInterpreter.cpp.
References m_pInterpreter.
Referenced by EvalFile().
Bool_t CTCLInterpreter::ExprBoolean (const std::string & rExpression) [inline]
Definition at line 453 of file TCLInterpreter.h.
References Bool_t, and ExprBoolean().
Bool_t CTCLInterpreter::ExprBoolean (const CTCLString & rExpression) [inline]
Definition at line 450 of file TCLInterpreter.h.
References Bool_t, and ExprBoolean().
Bool_t CTCLInterpreter::ExprBoolean (const char * pExpression)
Definition at line 551 of file TCLInterpreter.cpp.
References Int_t, and m_pInterpreter.
Referenced by CAssocArrayBinding< T >::Commit(), CArrayBinding< T >::Commit(), and ExprBoolean().
DFloat_t CTCLInterpreter::ExprDouble (const std::string & rExpression) [inline]
Definition at line 444 of file TCLInterpreter.h.
References DFloat_t, and ExprDouble().
DFloat_t CTCLInterpreter::ExprDouble (const CTCLString & rExpression) [inline]
Definition at line 441 of file TCLInterpreter.h.
References DFloat_t, and ExprDouble().
DFloat_t CTCLInterpreter::ExprDouble (const char * pExpression)
Definition at line 515 of file TCLInterpreter.cpp.
References DFloat_t, Int_t, and m_pInterpreter.
Referenced by CAssocArrayBinding< T >::Commit(), CArrayBinding< T >::Commit(), and ExprDouble().
Long_t CTCLInterpreter::ExprLong (const CTCLString & rExpr) [inline]
Definition at line 435 of file TCLInterpreter.h.
References ExprLong(), and Long_t.
Long_t CTCLInterpreter::ExprLong (std::string & rExpression) [inline]
Definition at line 432 of file TCLInterpreter.h.
References ExprLong(), and Long_t.
Long_t CTCLInterpreter::ExprLong (const char * pExpression)
Definition at line 479 of file TCLInterpreter.cpp.
References Long_t, and m_pInterpreter.
Referenced by CAssocArrayBinding< T >::Commit(), CArrayBinding< T >::Commit(), and ExprLong().
std::string CTCLInterpreter::ExprString (const std::string & rExpr) [inline]
Definition at line 426 of file TCLInterpreter.h.
References ExprString().
std::string CTCLInterpreter::ExprString (const CTCLString & rExpr) [inline]
Definition at line 423 of file TCLInterpreter.h.
References ExprString().
std::string CTCLInterpreter::ExprString (const char * pExpression)
Definition at line 449 of file TCLInterpreter.cpp.
References m_pInterpreter.
Referenced by ExprString().
Tcl_Interp* CTCLInterpreter::getInterpreter () [inline]
Definition at line 365 of file TCLInterpreter.h.
References m_pInterpreter.
Referenced by CTCLException::AddErrorInfo(), CTCLResult::AppendElement(), CTCLResult::Clear(), CAssocArrayBinding< T >::Commit(), CTCLProcessor::DeleteRelay(), CTCLProcessor::EvalRelay(), CTCLVariable::Get(), CVariableBinding< T >::InitBindings(), CTCLVariable::Link(), CTCLResult::operator const char *(), CTCLObject::operator double(), CTCLObject::operator int(), CTCLObject::operator()(), CTCLResult::operator+=(), CTCLObject::operator+=(), CTCLResult::operator=(), CTCLProcessor::ParseBoolean(), CTCLProcessor::ParseDouble(), CTCLProcessor::ParseInt(), CTCLVariable::Set(), CTCLException::SetErrorCode(), CVariableBinding< T >::ShutdownBindings(), CTCLList::Split(), CTCLVariable::Trace(), CTCLVariable::TraceRelay(), CTCLVariable::Unlink(), CTCLVariable::UnTrace(), and CTCLVariable::Update().
std::string CTCLInterpreter::GetResultString () const
Definition at line 794 of file TCLInterpreter.cpp.
References m_pInterpreter.
std::string CTCLInterpreter::GlobalEval (const std::string & rScript) [inline]
Definition at line 404 of file TCLInterpreter.h.
References GlobalEval().
std::string CTCLInterpreter::GlobalEval (const CTCLString & rScript) [inline]
Definition at line 401 of file TCLInterpreter.h.
References GlobalEval().
std::string CTCLInterpreter::GlobalEval (const char * pScript)
Definition at line 391 of file TCLInterpreter.cpp.
References m_pInterpreter.
Referenced by CAssocArrayBinding< T >::Commit(), GlobalEval(), and CConfigurationManager::InternalReadConfigFile().
CTCLInterpreter::operator Tcl_Interp * () [inline]
Definition at line 514 of file TCLInterpreter.h.
References m_pInterpreter.
Tcl_Interp* CTCLInterpreter::operator $\rightarrow$ () [inline]
Definition at line 509 of file TCLInterpreter.h.
References m_pInterpreter.
CTCLInterpreter CTCLInterpreter::operator= (const CTCLInterpreter & aCTCLInterpreter) [private]
int CTCLInterpreter::operator== (const CTCLInterpreter & aCTCLInterpreter) [inline]
Definition at line 355 of file TCLInterpreter.h.
References m_pInterpreter.
std::string CTCLInterpreter::PosixError () const
Definition at line 613 of file TCLInterpreter.cpp.
References m_pInterpreter.
void CTCLInterpreter::ReapDetachedProcesses () const [inline]
Definition at line 474 of file TCLInterpreter.h.
std::string CTCLInterpreter::RecordAndEval (const std::string & rScript, Bool_t fEval = kfFALSE) [inline]
Definition at line 415 of file TCLInterpreter.h.
References Bool_t, and RecordAndEval().
std::string CTCLInterpreter::RecordAndEval (const CTCLString & rScript, Bool_t fEval = kfFALSE) [inline]
Definition at line 411 of file TCLInterpreter.h.
References Bool_t, and RecordAndEval().
std::string CTCLInterpreter::RecordAndEval (const char * pScript, Bool_t fEval = kfFALSE)
Definition at line 415 of file TCLInterpreter.cpp.
References Bool_t, and m_pInterpreter.
Referenced by RecordAndEval().
void CTCLInterpreter::setInterpreter (Tcl_Interp * am_pInterpreter) [inline, protected]
Definition at line 371 of file TCLInterpreter.h.
References m_pInterpreter.
std::string CTCLInterpreter::SignalId (UInt_t nSignal) [static]
Definition at line 647 of file TCLInterpreter.cpp.
References Int_t, and UInt_t.
std::string CTCLInterpreter::SignalMsg (UInt_t nSignal) [static]
Definition at line 667 of file TCLInterpreter.cpp.
References UInt_t.
std::string CTCLInterpreter::TildeSubst (const std::string & rName) [inline]
Definition at line 462 of file TCLInterpreter.h.
References TildeSubst().
std::string CTCLInterpreter::TildeSubst (const CTCLString & rName) const [inline]
Definition at line 459 of file TCLInterpreter.h.
References TildeSubst().
std::string CTCLInterpreter::TildeSubst (const char * pFilename) const
Definition at line 583 of file TCLInterpreter.cpp.
References m_pInterpreter.
Referenced by TildeSubst().
void CTCLInterpreter::UnregisterCommand (const CTCLString & rCommandName) const [inline]
Definition at line 502 of file TCLInterpreter.h.
References UnregisterCommand().
void CTCLInterpreter::UnregisterCommand (const std::string & rCommandName) const [inline]
Definition at line 499 of file TCLInterpreter.h.
References UnregisterCommand().
void CTCLInterpreter::UnregisterCommand (const char * pCommandName) const
Definition at line 766 of file TCLInterpreter.cpp.
References m_pInterpreter.
Referenced by CTCLProcessor::Unregister(), and UnregisterCommand().
Member Data Documentation
Tcl_Interp* CTCLInterpreter::m_pInterpreter [private]
Definition at line 327 of file TCLInterpreter.h.
Referenced by AddCommand(), CTCLInterpreter(), Eval(), EvalFile(), ExprBoolean(), ExprDouble(), ExprLong(), ExprString(), getInterpreter(), GetResultString(), GlobalEval(), operator Tcl_Interp *(), operator $\rightarrow$ (), CTCLInterpreterObject::operator=(), operator==(), PosixError(), RecordAndEval(), setInterpreter(), TildeSubst(), UnregisterCommand(), and ~CTCLInterpreter().
The documentation for this class was generated from the following files:
TCLInterpreter.h
TCLInterpreter.cpp