CReferenceCounted< T > Class Template Reference
#include <CRefptr.h>
Public Methods
CReferenceCounted (T *p)
~CReferenceCounted ()
T & operator * ()
T * get ()
void reference ()
void dereference ()
int norefs ()
int refcount ()
Private Methods
template<class U> CReferenceCounted< T > & operator= (const CReferenceCounted< U > &rhs)
template<class U> CReferenceCounted (const CReferenceCounted< U > &rhs)
Private Attributes
unsigned m_ReferenceCount
T * m_Pointer
template<class T> class CReferenceCounted< T >
Constructor & Destructor Documentation
template<class T> template<class U> CReferenceCounted< T >::CReferenceCounted (const CReferenceCounted< U > & rhs) [private]
template<class T> CReferenceCounted< T >::CReferenceCounted (T * p) [inline]
Definition at line 307 of file CRefptr.h.
References CReferenceCounted< T >::m_Pointer, and CReferenceCounted< T >::m_ReferenceCount.
template<class T> CReferenceCounted< T >::~CReferenceCounted () [inline]
Definition at line 310 of file CRefptr.h.
References CReferenceCounted< T >::m_Pointer.
Member Function Documentation
template<class T> void CReferenceCounted< T >::dereference () [inline]
Definition at line 314 of file CRefptr.h.
References CReferenceCounted< T >::m_ReferenceCount.
Referenced by CRefcountedPtr< T >::operator=(), and CRefcountedPtr< T >::~CRefcountedPtr().
template<class T> T* CReferenceCounted< T >::get () [inline]
Definition at line 312 of file CRefptr.h.
References CReferenceCounted< T >::m_Pointer.
Referenced by CRefcountedPtr< T >::operator $\rightarrow$ ().
template<class T> int CReferenceCounted< T >::norefs () [inline]
Definition at line 315 of file CRefptr.h.
References CReferenceCounted< T >::m_ReferenceCount.
Referenced by CRefcountedPtr< T >::operator=(), and CRefcountedPtr< T >::~CRefcountedPtr().
template<class T> T& CReferenceCounted< T >::operator * () [inline]
Definition at line 311 of file CRefptr.h.
References CReferenceCounted< T >::m_Pointer.
template<class T> template<class U> CReferenceCounted<T>& CReferenceCounted< T >::operator= (const CReferenceCounted< U > & rhs) [private]
template<class T> int CReferenceCounted< T >::refcount () [inline]
Definition at line 316 of file CRefptr.h.
References CReferenceCounted< T >::m_ReferenceCount.
Referenced by CRefcountedPtr< T >::refcount().
template<class T> void CReferenceCounted< T >::reference () [inline]
Definition at line 313 of file CRefptr.h.
References CReferenceCounted< T >::m_ReferenceCount.
Referenced by CRefcountedPtr< T >::CRefcountedPtr(), and CRefcountedPtr< T >::operator=().
Member Data Documentation
template<class T> T* CReferenceCounted< T >::m_Pointer [private]
Definition at line 298 of file CRefptr.h.
Referenced by CReferenceCounted< T >::CReferenceCounted(), CReferenceCounted< T >::get(), CReferenceCounted< T >::operator *(), and CReferenceCounted< T >::~CReferenceCounted().
template<class T> unsigned CReferenceCounted< T >::m_ReferenceCount [private]
Definition at line 297 of file CRefptr.h.
Referenced by CReferenceCounted< T >::CReferenceCounted(), CReferenceCounted< T >::dereference(), CReferenceCounted< T >::norefs(), CReferenceCounted< T >::refcount(), and CReferenceCounted< T >::reference().
The documentation for this class was generated from the following file:
CRefptr.h