CTCLString Class Reference
#include <TCLString.h>
Public Methods
CTCLString ()
~CTCLString ()
CTCLString (const char *pString)
CTCLString (const std::string &rString)
CTCLString (const Tcl_DString &rString)
CTCLString (const CTCLString &aCTCLString)
CTCLString & operator= (const CTCLString &aCTCLString)
int operator== (const CTCLString &aCTCLString)
int operator!= (const CTCLString &aCTCLString)
int operator> (const CTCLString &aCTCLString)
int operator< (const CTCLString &aCTCLString)
int operator>= (const CTCLString &aCTCLString)
int operator<= (const CTCLString &aCTCLString)
Tcl_DString & getString ()
void setString (const Tcl_DString &am_String)
CTCLString & Append (const std::string &rString, Int_t nLength=-1)
CTCLString & Append (const CTCLString &rString, Int_t nLength=-1)
CTCLString & Append (Tcl_DString &pString, Int_t nLength=-1)
CTCLString & Append (const char *pString, Int_t nLength=-1)
CTCLString & AppendElement (const Tcl_DString *pRhs)
CTCLString & AppendElement (const CTCLString &rRhs)
CTCLString & AppendElement (const std::string &rRhs)
CTCLString & AppendElement (const char *pRhs)
CTCLString & StartSublist ()
CTCLString & EndSublist ()
UInt_t Length () const
CTCLString & Truncate (UInt_t nNewLength)
Bool_t isCommand () const
Bool_t Match (const char *pPattern) const
Bool_t Match (std::string &rPattern) const
Bool_t Match (const CTCLString &rPattern) const
operator const char * () const
operator std::string () const
operator Tcl_DString * ()
CTCLString & operator+= (const CTCLString &rRhs)
CTCLString operator+ (const CTCLString &rRhs)
Protected Methods
void DoAssign (const CTCLString &rRhs)
Private Attributes
Tcl_DString m_String
Constructor & Destructor Documentation
CTCLString::CTCLString () [inline]
Definition at line 321 of file TCLString.h.
References m_String.
CTCLString::~CTCLString () [inline]
Definition at line 324 of file TCLString.h.
References m_String.
CTCLString::CTCLString (const char * pString) [inline]
Definition at line 330 of file TCLString.h.
References m_String.
CTCLString::CTCLString (const std::string & rString) [inline]
Definition at line 335 of file TCLString.h.
References m_String.
CTCLString::CTCLString (const Tcl_DString & rString) [inline]
Definition at line 339 of file TCLString.h.
References m_String.
CTCLString::CTCLString (const CTCLString & aCTCLString) [inline]
Definition at line 346 of file TCLString.h.
References DoAssign(), and m_String.
Member Function Documentation
CTCLString & CTCLString::Append (const char * pString, Int_t nLength = -1)
Definition at line 317 of file TCLString.cpp.
References Int_t, and m_String.
CTCLString& CTCLString::Append (Tcl_DString & pString, Int_t nLength = -1) [inline]
Definition at line 413 of file TCLString.h.
References Append(), and Int_t.
CTCLString& CTCLString::Append (const CTCLString & rString, Int_t nLength = -1) [inline]
Definition at line 410 of file TCLString.h.
References Append(), Int_t, and m_String.
CTCLString& CTCLString::Append (const std::string & rString, Int_t nLength = -1) [inline]
Definition at line 407 of file TCLString.h.
References Int_t.
Referenced by Append().
CTCLString & CTCLString::AppendElement (const char * pRhs)
Definition at line 349 of file TCLString.cpp.
References m_String.
CTCLString& CTCLString::AppendElement (const std::string & rRhs) [inline]
Definition at line 426 of file TCLString.h.
References AppendElement().
CTCLString& CTCLString::AppendElement (const CTCLString & rRhs) [inline]
Definition at line 423 of file TCLString.h.
References AppendElement(), and m_String.
CTCLString& CTCLString::AppendElement (const Tcl_DString * pRhs) [inline]
Definition at line 420 of file TCLString.h.
Referenced by AppendElement(), CVariableBinding< T >::Dump(), and CArrayBinding< T >::Dump().
void CTCLString::DoAssign (const CTCLString & rRhs) [protected]
Definition at line 530 of file TCLString.cpp.
References m_String.
Referenced by CTCLString(), and operator=().
CTCLString & CTCLString::EndSublist ()
Definition at line 398 of file TCLString.cpp.
References m_String.
Tcl_DString& CTCLString::getString () [inline]
Definition at line 391 of file TCLString.h.
References m_String.
Bool_t CTCLString::isCommand () const
Definition at line 456 of file TCLString.cpp.
References Int_t, and m_String.
UInt_t CTCLString::Length () const
Definition at line 417 of file TCLString.cpp.
References m_String.
Bool_t CTCLString::Match (const CTCLString & rPattern) const [inline]
Definition at line 445 of file TCLString.h.
References Bool_t, m_String, and Match().
Bool_t CTCLString::Match (std::string & rPattern) const [inline]
Definition at line 442 of file TCLString.h.
References Bool_t, and Match().
Bool_t CTCLString::Match (const char * pPattern) const
Definition at line 471 of file TCLString.cpp.
References Int_t, and m_String.
Referenced by Match().
CTCLString::operator const char * () const [inline]
Definition at line 449 of file TCLString.h.
References m_String.
CTCLString::operator std::string () const [inline]
Definition at line 452 of file TCLString.h.
References m_String.
CTCLString::operator Tcl_DString * () [inline]
Definition at line 455 of file TCLString.h.
int CTCLString::operator!= (const CTCLString & aCTCLString) [inline]
Definition at line 369 of file TCLString.h.
References operator==().
CTCLString CTCLString::operator+ (const CTCLString & rRhs)
Definition at line 504 of file TCLString.cpp.
CTCLString& CTCLString::operator+= (const CTCLString & rRhs) [inline]
Definition at line 458 of file TCLString.h.
int CTCLString::operator< (const CTCLString & aCTCLString) [inline]
Definition at line 377 of file TCLString.h.
References m_String.
Referenced by operator<=().
int CTCLString::operator<= (const CTCLString & aCTCLString) [inline]
Definition at line 385 of file TCLString.h.
References operator<(), and operator==().
CTCLString& CTCLString::operator= (const CTCLString & aCTCLString) [inline]
Definition at line 354 of file TCLString.h.
References DoAssign().
Referenced by setString().
int CTCLString::operator== (const CTCLString & aCTCLString) [inline]
Definition at line 364 of file TCLString.h.
References m_String.
Referenced by operator!=(), operator<=(), and operator>=().
int CTCLString::operator> (const CTCLString & aCTCLString) [inline]
Definition at line 372 of file TCLString.h.
References m_String.
Referenced by operator>=().
int CTCLString::operator>= (const CTCLString & aCTCLString) [inline]
Definition at line 382 of file TCLString.h.
References operator==(), and operator>().
void CTCLString::setString (const Tcl_DString & am_String) [inline]
Definition at line 398 of file TCLString.h.
References operator=().
CTCLString & CTCLString::StartSublist ()
Definition at line 378 of file TCLString.cpp.
References m_String.
CTCLString & CTCLString::Truncate (UInt_t nNewLength)
Definition at line 432 of file TCLString.cpp.
References m_String, and UInt_t.
Member Data Documentation
Tcl_DString CTCLString::m_String [private]
Definition at line 316 of file TCLString.h.
Referenced by Append(), AppendElement(), CTCLString(), DoAssign(), EndSublist(), getString(), isCommand(), Length(), Match(), operator const char *(), operator std::string(), operator<(), operator==(), operator>(), StartSublist(), Truncate(), and ~CTCLString().
The documentation for this class was generated from the following files:
TCLString.h
TCLString.cpp