XMSeparator Class Reference
#include <XMSeparators.h>
Public Methods
XMSeparator (char *n)
XMSeparator (char *n, Widget parent, ArgList l=NULL, Cardinal num_args=0)
XMSeparator (char *n, XMWidget &parent, ArgList l=NULL, Cardinal num_args=0)
XMSeparator (Widget w)
void SetShadowType (unsigned char newtype)
void SetOrientation (unsigned char orientation)
Constructor & Destructor Documentation
XMSeparator::XMSeparator (char * n) [inline]
Definition at line 305 of file XMSeparators.h.
XMSeparator::XMSeparator (char * n, Widget parent, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 306 of file XMSeparators.h.
XMSeparator::XMSeparator (char * n, XMWidget & parent, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 310 of file XMSeparators.h.
XMSeparator::XMSeparator (Widget w) [inline]
Definition at line 314 of file XMSeparators.h.
Member Function Documentation
void XMSeparator::SetOrientation (unsigned char orientation) [inline]
Definition at line 321 of file XMSeparators.h.
References XMWidget::SetAttribute().
Referenced by XMHorizontalSeparator::XMHorizontalSeparator(), and XMVerticalSeparator::XMVerticalSeparator().
void XMSeparator::SetShadowType (unsigned char newtype) [inline]
Definition at line 318 of file XMSeparators.h.
References XMWidget::SetAttribute().
The documentation for this class was generated from the following file:
XMSeparators.h