XMForm Class Reference
#include <XMManagers.h>
Public Methods
XMForm (char *name)
XMForm (Widget id)
XMForm (char *n, XMApplication &parent, ArgList l=NULL, Cardinal num_args=0)
XMForm (char *n, Widget parent, ArgList l=NULL, Cardinal num_args=0)
XMForm (char *n, XMWidget &parent, ArgList l=NULL, Cardinal num_args=0)
void SetFractionBase (int n)
void SetHorizontalSpacing (Dimension n)
void SetRubberPositioning (Boolean on)
void SetVerticalSpacing (Dimension n)
void SetBottomAttachment (XMWidget &wid, unsigned char method)
void SetBottomAttachment (Widget wid, unsigned char method)
void SetBottomOffset (XMWidget &wid, int off)
void SetBottomPosition (XMWidget &wid, int position)
void SetBottomWidget (XMWidget &wid, XMWidget &bound)
void SetBottomWidget (XMWidget &wid, Widget bound)
void SetLeftAttachment (XMWidget &wid, unsigned char method)
void SetLeftAttachment (Widget wid, unsigned char method)
void SetLeftOffset (XMWidget &wid, int offset)
void SetLeftPosition (XMWidget &wid, int position)
void SetLeftWidget (XMWidget &wid, XMWidget &bound)
void SetLeftWidget (XMWidget &wid, Widget bound)
void SetRightAttachment (XMWidget &wid, unsigned char method)
void SetRightAttachment (Widget wid, unsigned char method)
void SetRightOffset (XMWidget &wid, int offset)
void SetRightPosition (XMWidget &wid, int position)
void SetRightWidget (XMWidget &wid, XMWidget &bound)
void SetRightWidget (XMWidget &wid, Widget bound)
void SetTopAttachment (XMWidget &wid, unsigned char method)
void SetTopAttachment (Widget wid, unsigned char method)
void SetTopOffset (XMWidget &wid, int offset)
void SetTopPosition (XMWidget &wid, int position)
void SetTopWidget (XMWidget &wid, XMWidget &bound)
void SetTopWidget (XMWidget &wid, Widget bound)
void SetTopWidget (Widget wid, Widget bound)
void SetTopWidget (Widget wid, XMWidget &bound)
Constructor & Destructor Documentation
XMForm::XMForm (char * name) [inline]
Definition at line 456 of file XMManagers.h.
References XMWidget::name.
XMForm::XMForm (Widget id) [inline]
Definition at line 457 of file XMManagers.h.
References XMWidget::id.
XMForm::XMForm (char * n, XMApplication & parent, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 458 of file XMManagers.h.
References XMWidget::getid().
XMForm::XMForm (char * n, Widget parent, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 462 of file XMManagers.h.
XMForm::XMForm (char * n, XMWidget & parent, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 466 of file XMManagers.h.
References XMWidget::getid().
Member Function Documentation
void XMForm::SetBottomAttachment (Widget wid, unsigned char method) [inline]
Definition at line 491 of file XMManagers.h.
References XMManager::SetConstraint().
void XMForm::SetBottomAttachment (XMWidget & wid, unsigned char method) [inline]
Definition at line 488 of file XMManagers.h.
References XMManager::SetConstraint().
void XMForm::SetBottomOffset (XMWidget & wid, int off) [inline]
Definition at line 495 of file XMManagers.h.
References XMManager::SetConstraint().
void XMForm::SetBottomPosition (XMWidget & wid, int position) [inline]
Definition at line 498 of file XMManagers.h.
References XMManager::SetConstraint().
void XMForm::SetBottomWidget (XMWidget & wid, Widget bound) [inline]
Definition at line 504 of file XMManagers.h.
References XMManager::SetConstraint().
void XMForm::SetBottomWidget (XMWidget & wid, XMWidget & bound) [inline]
Definition at line 501 of file XMManagers.h.
References XMWidget::getid(), and XMManager::SetConstraint().
void XMForm::SetFractionBase (int n) [inline]
Definition at line 473 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMForm::SetHorizontalSpacing (Dimension n) [inline]
Definition at line 476 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMForm::SetLeftAttachment (Widget wid, unsigned char method) [inline]
Definition at line 512 of file XMManagers.h.
References XMManager::SetConstraint().
void XMForm::SetLeftAttachment (XMWidget & wid, unsigned char method) [inline]
Definition at line 509 of file XMManagers.h.
References XMManager::SetConstraint().
void XMForm::SetLeftOffset (XMWidget & wid, int offset) [inline]
Definition at line 515 of file XMManagers.h.
References XMManager::SetConstraint().
void XMForm::SetLeftPosition (XMWidget & wid, int position) [inline]
Definition at line 518 of file XMManagers.h.
References XMManager::SetConstraint().
void XMForm::SetLeftWidget (XMWidget & wid, Widget bound) [inline]
Definition at line 524 of file XMManagers.h.
References XMManager::SetConstraint().
void XMForm::SetLeftWidget (XMWidget & wid, XMWidget & bound) [inline]
Definition at line 521 of file XMManagers.h.
References XMWidget::getid(), and XMManager::SetConstraint().
void XMForm::SetRightAttachment (Widget wid, unsigned char method) [inline]
Definition at line 532 of file XMManagers.h.
References XMManager::SetConstraint().
void XMForm::SetRightAttachment (XMWidget & wid, unsigned char method) [inline]
Definition at line 529 of file XMManagers.h.
References XMManager::SetConstraint().
void XMForm::SetRightOffset (XMWidget & wid, int offset) [inline]
Definition at line 535 of file XMManagers.h.
References XMManager::SetConstraint().
void XMForm::SetRightPosition (XMWidget & wid, int position) [inline]
Definition at line 538 of file XMManagers.h.
References XMManager::SetConstraint().
void XMForm::SetRightWidget (XMWidget & wid, Widget bound) [inline]
Definition at line 544 of file XMManagers.h.
References XMManager::SetConstraint().
void XMForm::SetRightWidget (XMWidget & wid, XMWidget & bound) [inline]
Definition at line 541 of file XMManagers.h.
References XMWidget::getid(), and XMManager::SetConstraint().
void XMForm::SetRubberPositioning (Boolean on) [inline]
Definition at line 479 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMForm::SetTopAttachment (Widget wid, unsigned char method) [inline]
Definition at line 551 of file XMManagers.h.
References XMManager::SetConstraint().
void XMForm::SetTopAttachment (XMWidget & wid, unsigned char method) [inline]
Definition at line 548 of file XMManagers.h.
References XMManager::SetConstraint().
void XMForm::SetTopOffset (XMWidget & wid, int offset) [inline]
Definition at line 554 of file XMManagers.h.
References XMManager::SetConstraint().
void XMForm::SetTopPosition (XMWidget & wid, int position) [inline]
Definition at line 557 of file XMManagers.h.
References XMManager::SetConstraint().
void XMForm::SetTopWidget (Widget wid, XMWidget & bound) [inline]
Definition at line 569 of file XMManagers.h.
References XMWidget::getid(), and XMManager::SetConstraint().
void XMForm::SetTopWidget (Widget wid, Widget bound) [inline]
Definition at line 566 of file XMManagers.h.
References XMManager::SetConstraint().
void XMForm::SetTopWidget (XMWidget & wid, Widget bound) [inline]
Definition at line 563 of file XMManagers.h.
References XMManager::SetConstraint().
void XMForm::SetTopWidget (XMWidget & wid, XMWidget & bound) [inline]
Definition at line 560 of file XMManagers.h.
References XMWidget::getid(), and XMManager::SetConstraint().
void XMForm::SetVerticalSpacing (Dimension n) [inline]
Definition at line 482 of file XMManagers.h.
References XMWidget::SetAttribute().
The documentation for this class was generated from the following file:
XMManagers.h