XMWidgetList Class Reference
#include <XMWlist.h>
Public Methods
XMWidgetList (int num=LIST_DEFAULT_SIZE)
void SetAttribute (String attribute, XtArgVal value)
void SetAttribute (String attribute, void *value)
Constructor & Destructor Documentation
XMWidgetList::XMWidgetList (int num = LIST_DEFAULT_SIZE) [inline]
Definition at line 374 of file XMWlist.h.
References LIST_DEFAULT_SIZE.
Member Function Documentation
void XMWidgetList::SetAttribute (String attribute, void * value)
Definition at line 322 of file XMWlist.cpp.
References Generic_List< XMWidget >::Exists(), Generic_List< XMWidget >::InitIteration(), Generic_List< XMWidget >::Next(), and XMWidget::SetAttribute().
void XMWidgetList::SetAttribute (String attribute, XtArgVal value)
Definition at line 312 of file XMWlist.cpp.
References Generic_List< XMWidget >::Exists(), Generic_List< XMWidget >::InitIteration(), Generic_List< XMWidget >::Next(), and XMWidget::SetAttribute().
Referenced by XMButtonList::Disable(), and XMButtonList::Enable().
The documentation for this class was generated from the following files:
XMWlist.h
XMWlist.cpp