CAssocArrayBinding< T > Class Template Reference
#include <CAssocArrayBinding.h>
Public Methods
CAssocArrayBinding (const string &rName)
CAssocArrayBinding (const char *pName)
~CAssocArrayBinding ()
map< string, T > getArray () const
< Get entire map.
map< string, T >::iterator begin ()
map< string, T >::iterator end ()
T & operator[] (const char *pName)
T & operator[] (const string &rName)
map< string, T >::iterator find (const char *pName)
map< string, T >::iterator find (const string &rName)
string getName () const
int getType () const
virtual void InitBindings (CTCLInterpreter &rInterp)
virtual void Commit (CTCLInterpreter &rInterp)
virtual void ShutdownBindings (CTCLInterpreter &rInterp)
virtual void Dump (int fd)
Private Methods
CAssocArrayBinding (const CAssocArrayBinding &rhs)
CAssocArrayBinding & operator= (const CAssocArrayBinding &rhs)
int operator== (const CAssocArrayBinding &rhs)
Private Attributes
map< string, T > m_Array
Data stored in this map.
string m_sName
TCL Name of array.
int m_TCLVariableType
Type of data in the array.
Detailed Description
template<class T> class CAssocArrayBinding< T >
Encapsulates the configuration of an associative array. Associative arrays are arrays whose indices are strings rather than numbers. One use of associative arrays is to provide meaningful subscripts to configuration items. For example, suppose I want to store the thresholds for all of my 'detector' adc's. I might have an associative array named thresholds with subscripts which indicate detector segment and subtype e.g. `seg1,de` could be an index. Some key properties of associative arrays:
One can iterate through the elements which have been given a value
One can index by subscript, however if the element does not yet exist, it will be generated and the value will be that provided by the default constructor. Note that this is a null pointer for characters.
There is no way to provide default values to elements in this clas.
Definition at line 326 of file CAssocArrayBinding.h.
Constructor & Destructor Documentation
template<class T> CAssocArrayBinding< T >::CAssocArrayBinding (const string & rName)
Constructs an associative array configured from a TCL array. The TCL array name is specified by a const string&
Parameters:
rName - Name of the configuration array.
Definition at line 309 of file CAssocArrayBinding.cpp.
References CAssocArrayBinding< T >::m_TCLVariableType, and CBinding< T >::VariableType().
template<class T> CAssocArrayBinding< T >::CAssocArrayBinding (const char * pName)
Constructs an associative array configured from a TCL array. The TCL array name is speicified by a const char*
Parameters:
pName - Name of the configuration array.
Definition at line 322 of file CAssocArrayBinding.cpp.
References CAssocArrayBinding< T >::m_TCLVariableType, and CBinding< T >::VariableType().
template<class T> CAssocArrayBinding< T >::~CAssocArrayBinding ()
The destructor will need to delete storage associated with character entries in the map.
Definition at line 334 of file CAssocArrayBinding.cpp.
References CAssocArrayBinding< T >::m_Array, and CAssocArrayBinding< T >::m_TCLVariableType.
template<class T> CAssocArrayBinding< T >::CAssocArrayBinding (const CAssocArrayBinding< T > & rhs) [private]
Member Function Documentation
template<class T> map<string,T>::iterator CAssocArrayBinding< T >::begin () [inline]
Definition at line 350 of file CAssocArrayBinding.h.
References CAssocArrayBinding< T >::m_Array.
template<class T> void CAssocArrayBinding< T >::Commit (CTCLInterpreter & rInterp) [virtual]
Commits the bindings to the array. In this case we will determine the set of indices the variable has (by running a string script of the form `array names m_sName`, and fetching the results from the result string. For each item in the TCL array an item is created in the m_Array. Note that if the type is TCL_BIND_STRING, dynamic memory is allocated to hold the result string.
Parameters:
rInterp - the interpreter which read in the config file. Used to fetch variable strings etc.
Implements CBinding< T > (p.).
Definition at line 371 of file CAssocArrayBinding.cpp.
References CTCLInterpreter::ExprBoolean(), CTCLInterpreter::ExprDouble(), CTCLInterpreter::ExprLong(), CTCLInterpreter::getInterpreter(), CTCLInterpreter::GlobalEval(), CAssocArrayBinding< T >::m_Array, CAssocArrayBinding< T >::m_sName, CTCLList::Split(), and StringArray.
template<class T> void CAssocArrayBinding< T >::Dump (int fd) [virtual]
Dumps the contents of the array out in a form which allows the array to be recovered by reading the file.
Parameters:
fd - A file descriptor on which to write this data.
Implements CBinding< T > (p.).
Definition at line 469 of file CAssocArrayBinding.cpp.
References CBinding< T >::ItemToString(), CAssocArrayBinding< T >::m_Array, and CAssocArrayBinding< T >::m_sName.
template<class T> map<string,T>::iterator CAssocArrayBinding< T >::end () [inline]
Definition at line 353 of file CAssocArrayBinding.h.
References CAssocArrayBinding< T >::m_Array.
template<class T> map<string,T>::iterator CAssocArrayBinding< T >::find (const string & rName) [inline]
Definition at line 366 of file CAssocArrayBinding.h.
References CAssocArrayBinding< T >::m_Array.
template<class T> map<string,T>::iterator CAssocArrayBinding< T >::find (const char * pName) [inline]
Definition at line 363 of file CAssocArrayBinding.h.
References CAssocArrayBinding< T >::m_Array.
template<class T> map<string,T> CAssocArrayBinding< T >::getArray () const [inline]
< Get entire map.
Definition at line 346 of file CAssocArrayBinding.h.
References CAssocArrayBinding< T >::m_Array.
template<class T> string CAssocArrayBinding< T >::getName () const [inline]
Definition at line 370 of file CAssocArrayBinding.h.
References CAssocArrayBinding< T >::m_sName.
template<class T> int CAssocArrayBinding< T >::getType () const [inline]
Definition at line 374 of file CAssocArrayBinding.h.
References CAssocArrayBinding< T >::m_TCLVariableType.
template<class T> void CAssocArrayBinding< T >::InitBindings (CTCLInterpreter & rInterp) [virtual]
Initialize the bindings prior to reading in the configuration file. for this class the actual binding operation is done in the commit phase so this is a no-op.
Parameters:
rInterp - Referencers the TCL interpreter which will be used to read in the configuration file.
Implements CBinding< T > (p.).
Definition at line 354 of file CAssocArrayBinding.cpp.
template<class T> CAssocArrayBinding& CAssocArrayBinding< T >::operator= (const CAssocArrayBinding< T > & rhs) [private]
template<class T> int CAssocArrayBinding< T >::operator== (const CAssocArrayBinding< T > & rhs) [private]
template<class T> T& CAssocArrayBinding< T >::operator[] (const string & rName) [inline]
Definition at line 360 of file CAssocArrayBinding.h.
References CAssocArrayBinding< T >::m_Array.
template<class T> T& CAssocArrayBinding< T >::operator[] (const char * pName) [inline]
Definition at line 356 of file CAssocArrayBinding.h.
References CAssocArrayBinding< T >::m_Array.
template<class T> void CAssocArrayBinding< T >::ShutdownBindings (CTCLInterpreter & rInterp) [virtual]
Closes out whatever needs closing prior to deleting the interpreter which was used to read the configuration file. In this case, no action is taken as the 'binding' is done at commit time and no real connection is made between the interpreter and the array.
Parameters:
rInterp - Interpreter which read the config file.
Implements CTypeFreeBinding (p.).
Definition at line 459 of file CAssocArrayBinding.cpp.
Member Data Documentation
template<class T> map<string,T> CAssocArrayBinding< T >::m_Array [private]
Data stored in this map.
Definition at line 330 of file CAssocArrayBinding.h.
Referenced by CAssocArrayBinding< T >::begin(), CAssocArrayBinding< T >::Commit(), CAssocArrayBinding< T >::Dump(), CAssocArrayBinding< T >::end(), CAssocArrayBinding< T >::find(), CAssocArrayBinding< T >::getArray(), CAssocArrayBinding< T >::operator[](), and CAssocArrayBinding< T >::~CAssocArrayBinding().
template<class T> string CAssocArrayBinding< T >::m_sName [private]
TCL Name of array.
Definition at line 331 of file CAssocArrayBinding.h.
Referenced by CAssocArrayBinding< T >::Commit(), CAssocArrayBinding< T >::Dump(), and CAssocArrayBinding< T >::getName().
template<class T> int CAssocArrayBinding< T >::m_TCLVariableType [private]
Type of data in the array.
Definition at line 332 of file CAssocArrayBinding.h.
Referenced by CAssocArrayBinding< T >::CAssocArrayBinding(), CAssocArrayBinding< T >::getType(), and CAssocArrayBinding< T >::~CAssocArrayBinding().
The documentation for this class was generated from the following files:
CAssocArrayBinding.h
CAssocArrayBinding.cpp