XMMainWindow Class Reference
#include <XMManagers.h>
Public Methods
XMMainWindow (char *name)
XMMainWindow (Widget id)
XMMainWindow (char *name, XMApplication &parent, ArgList l=NULL, Cardinal arg_count=0)
XMMainWindow (char *name, XMWidget &parent, ArgList l=NULL, Cardinal arg_count=0)
XMMainWindow (char *name, Widget &parent, ArgList l=NULL, Cardinal arg_count=0)
void SetAreas (XMWidget *menubar=NULL, XMWidget *commandwindow=NULL, XMWidget *horizontalscroller=NULL, XMWidget *verticalscroller=NULL, XMWidget *workregion=NULL, XMWidget *messagewidget=NULL)
void ShowSeparator (Boolean show)
void CommandWindowLocation (unsigned char where)
Constructor & Destructor Documentation
XMMainWindow::XMMainWindow (char * name) [inline]
Definition at line 702 of file XMManagers.h.
References XMWidget::name.
XMMainWindow::XMMainWindow (Widget id) [inline]
Definition at line 703 of file XMManagers.h.
References XMWidget::id.
XMMainWindow::XMMainWindow (char * name, XMApplication & parent, ArgList l = NULL, Cardinal arg_count = 0) [inline]
Definition at line 704 of file XMManagers.h.
References XMWidget::name.
XMMainWindow::XMMainWindow (char * name, XMWidget & parent, ArgList l = NULL, Cardinal arg_count = 0) [inline]
Definition at line 708 of file XMManagers.h.
References XMWidget::name.
XMMainWindow::XMMainWindow (char * name, Widget & parent, ArgList l = NULL, Cardinal arg_count = 0) [inline]
Definition at line 712 of file XMManagers.h.
References XMWidget::name.
Member Function Documentation
void XMMainWindow::CommandWindowLocation (unsigned char where) [inline]
Definition at line 727 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMMainWindow::SetAreas (XMWidget * menubar = NULL, XMWidget * commandwindow = NULL, XMWidget * horizontalscroller = NULL, XMWidget * verticalscroller = NULL, XMWidget * workregion = NULL, XMWidget * messagewidget = NULL)
Definition at line 322 of file XMManagers.cpp.
References XMWidget::getid(), and XMWidget::SetAttribute().
void XMMainWindow::ShowSeparator (Boolean show) [inline]
Definition at line 724 of file XMManagers.h.
References XMWidget::SetAttribute().
The documentation for this class was generated from the following files:
XMManagers.h
XMManagers.cpp