CClassifiedObjectRegistry Class Reference
#include <CClassifiedObjectRegistry.h>
Public Methods
CClassifiedObjectRegistry (string am_sName)
virtual ~CClassifiedObjectRegistry ()
map< string, CObjectRegistry > getRegistries () const
void CreateRegistry (const string &RegistryName)
void DeleteRegistry (const string &RegistryName)
void Add (const string &RegistryName, CNamedObject &rObject)
void Remove (const string &RegistryName, CNamedObject &Object)
ObjectIterator Find (const string &RegistryName, const string &ObjectName)
CRefcountedPtr< ObjectList > Find (const string &ObjectName)
RegistryIterator beginregistry ()
RegistryIterator endregistry ()
virtual string DescribeSelf ()
Protected Methods
void setRegistries (map< string, CObjectRegistry > am_Registries)
Private Attributes
map< string, CObjectRegistry > m_Registries
Constructor & Destructor Documentation
CClassifiedObjectRegistry::CClassifiedObjectRegistry (string am_sName) [inline]
map containing the type key and object registry
Definition at line 332 of file CClassifiedObjectRegistry.h.
References CNamedObject::AppendClassInfo().
virtual CClassifiedObjectRegistry::~CClassifiedObjectRegistry () [inline, virtual]
Definition at line 337 of file CClassifiedObjectRegistry.h.
Member Function Documentation
void CClassifiedObjectRegistry::Add (const string & RegistryName, CNamedObject & rObject)
Adds an object to a registry. If the item already exists in that registry, a CDuplicateNameException (p.) is thrown. If the registry does not exist, a CNoSuchObjectException (p.) is thrown.
Parameters:
RegistryName The name of the registry to add the item to.
rObject A reference to the object to add to the registry.
Definition at line 353 of file CClassifiedObjectRegistry.cpp.
References endregistry(), m_Registries, and RegistryIterator.
Referenced by CRegisteredObject::RegisterSelf().
RegistryIterator CClassifiedObjectRegistry::beginregistry ()
Returns an iterator into the registries which are contained by this object. Note that iterating returns registries, not objects.
Definition at line 469 of file CClassifiedObjectRegistry.cpp.
References m_Registries.
Referenced by DescribeSelf(), and Find().
void CClassifiedObjectRegistry::CreateRegistry (const string & RegistryName)
Creates a new registry. It is not an error to create a registry which already exists. If this is attempted, the function is a no-op.
Parameters:
RegistryName The name of the registry being created.
Definition at line 314 of file CClassifiedObjectRegistry.cpp.
References m_Registries.
Referenced by CRegisteredObject::RegisterSelf().
void CClassifiedObjectRegistry::DeleteRegistry (const string & RegistryName)
Deletes an existing registry. Any registry entries are destroyed, however the objects they point to are not. If the registry does not exist, a CNoSuchObjectException (p.) is thrown.
Parameters:
RegistryName The name of the registry being destroyed.
Definition at line 334 of file CClassifiedObjectRegistry.cpp.
References m_Registries.
string CClassifiedObjectRegistry::DescribeSelf () [virtual]
Produces a string containing the class path and name of the CClassifiedObjectRegistry, the class path and name of all of the CObjectRegistry (p.)'s contained therein, and the class path and name of all of the CNamedObject (p.)'s contained within the registries.
Reimplemented from CNamedObject (p.).
Definition at line 492 of file CClassifiedObjectRegistry.cpp.
References beginregistry(), CNamedObject::DescribeSelf(), endregistry(), and RegistryIterator.
RegistryIterator CClassifiedObjectRegistry::endregistry ()
Returns a registry iterator suitable for determining when iteration has been completed.
Definition at line 479 of file CClassifiedObjectRegistry.cpp.
References m_Registries.
Referenced by Add(), DescribeSelf(), and Find().
CRefcountedPtr< ObjectList > CClassifiedObjectRegistry::Find (const string & ObjectName)
Returns a reference counted pointer to a dynamically allocated list of Objects which match the name requested. The list is drawn from all of the registries. If no registries contain the requested name, an empty list is returned. Note: A reference counted pointer is returned so that the client does not have to remember to delete the list when they are done with it.
Parameters:
ObjectName The name of the object to search for.
Definition at line 449 of file CClassifiedObjectRegistry.cpp.
References beginregistry(), endregistry(), ObjectIterator, ObjectList, and RegistryIterator.
ObjectIterator CClassifiedObjectRegistry::Find (const string & RegistryName, const string & ObjectName)
Locates an object in a specific registry. If the registry or object do not exist, a CNoSuchObjectException (p.) is thrown. The name embedded in the exception differentiates between these two cases.
Parameters:
RegistryName The name of the registry to search for the object in.
ObjectName The name of the object to search for.
Definition at line 415 of file CClassifiedObjectRegistry.cpp.
References m_Registries, ObjectIterator, and RegistryIterator.
map<string, CObjectRegistry> CClassifiedObjectRegistry::getRegistries () const [inline]
Definition at line 342 of file CClassifiedObjectRegistry.h.
References m_Registries.
void CClassifiedObjectRegistry::Remove (const string & RegistryName, CNamedObject & Object)
Removes an object from a registry. The named object is removed from the designated registry. If the object does not exist, or the registry does not exist, a CNoSuchObjectException (p.) is thrown. The name embedded in the exception differentiates between these two cases.
Parameters:
RegistryName The name of the registry containing the object to remove.
Object A reference to the object being removed.
Definition at line 384 of file CClassifiedObjectRegistry.cpp.
References CNamedObject::getName(), m_Registries, and RegistryIterator.
Referenced by CEventMonitor::~CEventMonitor(), and CReactor::~CReactor().
void CClassifiedObjectRegistry::setRegistries (map< string, CObjectRegistry > am_Registries) [inline, protected]
Definition at line 350 of file CClassifiedObjectRegistry.h.
References m_Registries.
Member Data Documentation
map<string, CObjectRegistry> CClassifiedObjectRegistry::m_Registries [private]
Definition at line 326 of file CClassifiedObjectRegistry.h.
Referenced by Add(), beginregistry(), CreateRegistry(), DeleteRegistry(), endregistry(), Find(), getRegistries(), Remove(), and setRegistries().
The documentation for this class was generated from the following files:
CClassifiedObjectRegistry.h
CClassifiedObjectRegistry.cpp