CTCLInterpreterStartup Class Reference
#include <CTCLInterpreterStartup.h>
Public Methods
CTCLInterpreterStartup ()
virtual ~CTCLInterpreterStartup ()
Static Protected Methods
int Tcl_Init (Tcl_Interp *pInterp)
Private Methods
virtual int operator() (int argc, char **argv)
CTCLInterpreterStartup (const CTCLInterpreterStartup &aCTCLInterpreterStartup)
Copy Constructor Illegal private and unimplemented.
CTCLInterpreterStartup & operator= (const CTCLInterpreterStartup &aCTCLInterpreterStartup)
Operator= Assignment Operator Illegal private and unimplemented.
int operator== (const CTCLInterpreterStartup &aCTCLInterpreterStartup) const
Operator== Equality Operator Illegal private and unimplemented.
Detailed Description
Starts up a TCL interpreter. This is suitable for applications which do not require or cannot use a GUI.
Definition at line 309 of file CTCLInterpreterStartup.h.
Constructor & Destructor Documentation
CTCLInterpreterStartup::CTCLInterpreterStartup () [inline]
Definition at line 316 of file CTCLInterpreterStartup.h.
virtual CTCLInterpreterStartup::~CTCLInterpreterStartup () [inline, virtual]
Definition at line 317 of file CTCLInterpreterStartup.h.
CTCLInterpreterStartup::CTCLInterpreterStartup (const CTCLInterpreterStartup & aCTCLInterpreterStartup) [private]
Copy Constructor Illegal private and unimplemented.
Member Function Documentation
int CTCLInterpreterStartup::operator() (int argc, char ** argv) [private, virtual]
Operation Type: Override.
Purpose:
Calls OnInitialize.
Sets up the Tcl interpreter.
Within the Tcl initialization function (CTCLInterpreterStartup::Tcl_Init (p.)) call RegisterExtensions.
Note that the instance of the interpreter is gotten via a call to CEventLoop::getInstance() (p.) since this is a singleton class.
Parameters:
argc - Number of `command line` parameters in
argv - `command line` argument strings.
Implements CInterpreterStartup (p.).
Definition at line 329 of file CTCLInterpreterStartup.cpp.
References NULL, CInterpreterStartup::OnInitialize(), and Tcl_Init().
CTCLInterpreterStartup& CTCLInterpreterStartup::operator= (const CTCLInterpreterStartup & aCTCLInterpreterStartup) [private]
Operator= Assignment Operator Illegal private and unimplemented.
int CTCLInterpreterStartup::operator== (const CTCLInterpreterStartup & aCTCLInterpreterStartup) const [private]
Operator== Equality Operator Illegal private and unimplemented.
int CTCLInterpreterStartup::Tcl_Init (Tcl_Interp * pInterp) [static, protected]
Operation Type: Initialization.
Purpose:
Called from the Tcl_Main() function. This static member:
Obtains the object by calling CEventLoop::getInstance() (p.)
Initializes the interpreter.
Invokes the Object's RegisterExtensions function to load packages, register modules and add application specific commands.
Returns to allow Tcl to start it's main loop.
Parameters:
Tcl_Interp * pInterp The interpreter created to run Tcl.
Definition at line 366 of file CTCLInterpreterStartup.cpp.
References CEventLoop::getInstance(), NULL, CInterpreterStartup::RegisterExtensions(), and CInterpreterStartup::setInterpreter().
Referenced by operator()().
The documentation for this class was generated from the following files:
CTCLInterpreterStartup.h
CTCLInterpreterStartup.cpp