CEvent Class Reference
#include <CEvent.h>
Public Methods
CEvent (CEventMonitor &rMonitor, CReactor &rReactor, bool InformTimeouts=false, int nTimeoutMs=500)
CEvent (const char *pName, CEventMonitor &rMonitor, CReactor &rReactor, bool InformTimeouts=false, int nTimeoutMs=500)
CEvent (const string &rName, CEventMonitor &rMonitor, CReactor &rReactor, bool InformTimeouts=false, int nTimeoutMs=500)
virtual ~CEvent ()
bool isEnabled () const
Return TRUE if the thread is enabled if not thread halt is pending.
bool isActive () const
Return TRUE if the thread is running (active) (small timing hole).
bool getInformTimeout () const
Return TRUE if Reactor also catches timeouts.
int getMsReactivity () const
Return the reactivity of the event to programmatic stimulus.
CEventMonitor & getMonitor ()
Allow manipulation of the event monitor:.
CReactor & getReactor ()
Allow manipulation of the event reactor:.
DAQThreadId getThreadId () const
Allow external manipulation of the thread:.
void Enable ()
void Disable ()
void setReactivity (int nMs)
void setEnable (bool fEnable)
void ReactToTimeouts (bool fReact=true)
virtual string DescribeSelf ()
Protected Methods
void setActive (bool fActive)
Set state of active flag.. implies thread is running.
void setTid (const DAQThreadId Tid)
Set Thread ID: implies you know a lot about the system.
virtual void OnEvent (CEventMonitor::result why)
void Schedule ()
virtual int operator() (int nargs, char **ppArgs)
virtual void ProcessQueues ()
DAQStatus JoinThis ()
Private Methods
CEvent (const CEvent &aCEvent)
Copy Constructor - not allowed.
CEvent & operator= (const CEvent &aCEvent)
Operator= Assignment Operator - not allowed.
int operator== (const CEvent &aCEvent) const
Operator== Equality Operator no point.
Private Attributes
bool m_fEnabled
Event enabled flag.
bool m_fActive
True if thread is active.
bool m_InformTimeouts
Pass timeouts on to reactor.
int m_nMsReactivity
Reactivity to external events.
CEventMonitor & m_rMonitor
Monitor which polls for event.
CReactor & m_rReactor
Reactor to the event when it fires.
DAQThreadId m_Tid
spectrodaq thread identifier.
Detailed Description
Encapsulates event handling. Events consist of an event monitor which is responsible for determining when an event fires and a reactor which provides application specific handling of the event. When enabled, the event will schedule a thread m_EventThread to process the event. The event thread contains code to repeatedly calll the monitor's operator(), lock the global mutex and call the reactor's operator(). The reactors provided with classes derived from this are generally standardized to invoke Subclass virtual function which are specific to the event being managed..
Definition at line 331 of file CEvent.h.
Constructor & Destructor Documentation
CEvent::CEvent (CEventMonitor & rMonitor, CReactor & rReactor, bool InformTimeouts = false, int nTimeoutMs = 500)
Construct an `anonymous` event object. Anonymous event objects have names like EventThread(unique_index). All Event objects will be registered in the `Event` registry of the application's global object classified registry.
Parameters:
rMonitor - The monitor which notices events.
rReactor - The reactor which does stuff when an event fires.
InformTimeouts [false] - Optional parameter which, if true, allows the Reactor to be called when the monitor times out.
Enabled [true] - Optional parameter which when true indicates that the constructor should begin execution of the Event monitoring thread. If false, a call to the Enable member is required to start execution.
nTimeoutMs - The timeout in ms for the Event monitor. Timeouts are an essential part of the event thread. The thread can only react to externally generated attempts to Disable it after the Monitor returns. The timeout in ms therefore is a measure of the reactiveness of the event to programmatic stimulus from other threads. For 'permanent' events, use a timeout of -1 which will cause the monitor to be configured to run without a timeout. NOTE:
The Event runs as a separate thread in the process. Destruction implies an attempt to kill the thread and join with it and may therefore be a time consuming process if the thread is active with a long or nonexistent timeout.
All calls to the reactor are synchronized with the application global mutex.
Definition at line 358 of file CEvent.cpp.
References CNamedObject::AppendClassInfo(), and RegistryName.
CEvent::CEvent (const char * pName, CEventMonitor & rMonitor, CReactor & rReactor, bool InformTimeouts = false, int nTimeoutMs = 500)
Construct a named event object. See the previous overload of CEvent::CEvent (p.) for most of the descriptive information. However:
Parameters:
pName - the name of the event object.
Throws:
CDuplicateNameException (p.) if there is already an Event derived object with this name.
Definition at line 384 of file CEvent.cpp.
References CNamedObject::AppendClassInfo(), and RegistryName.
CEvent::CEvent (const string & rName, CEventMonitor & rMonitor, CReactor & rReactor, bool InformTimeouts = false, int nTimeoutMs = 500)
Construct a named event object. See the previous overloads of CEvent::CEvent (p.), however:
Parameters:
rName - STL String name of event.
Throws:
CDuplicateNameException (p.) if there is already an Event derived object with this name.
Definition at line 410 of file CEvent.cpp.
References CNamedObject::AppendClassInfo(), and RegistryName.
CEvent::~CEvent () [virtual]
Destroys an instance of ourselves. This implies that our thread will exit. In general the destructor will not be called from this thread.
Definition at line 431 of file CEvent.cpp.
References Disable().
CEvent::CEvent (const CEvent & aCEvent) [private]
Copy Constructor - not allowed.
Member Function Documentation
string CEvent::DescribeSelf () [virtual]
Produce a string describing this :
Reimplemented from CNamedObject (p.).
Reimplemented in CBufferEvent< T > (p.), CFileEvent (p.), CLocationEvent< T > (p.), CServerConnectionEvent (p.), CServerInstance (p.), CTimerEvent (p.), and CBufferEvent< U > (p.).
Definition at line 534 of file CEvent.cpp.
References CNamedObject::DescribeSelf(), m_fActive, m_fEnabled, m_nMsReactivity, m_rMonitor, and m_rReactor.
Referenced by CTimerEvent::DescribeSelf(), CServerInstance::DescribeSelf(), CServerConnectionEvent::DescribeSelf(), CLocationEvent< T >::DescribeSelf(), CFileEvent::DescribeSelf(), and CBufferEvent< T >::DescribeSelf().
void CEvent::Disable ()
Disable execution of the event. A join is done with the event to ensure that it actually exits. There are two cases:
m_fActive == true - The thread is active m_fEnabled is set false, after some time, the thread will actually exit. We join with it to ensure that by the time Disable is exited, the thread has exited too.
m_fActive == false - The thread is not active, we can just return.
Note:
If the calling thread owns the global serialization mutex, it will be temporarily released. If this were not done, the Join could deadlock the initiating thread and the thread being killed:
The initiating thread will wait on the event thread to die, while holding the serialization mutex.
The Event thread will wait on the serialization mutex before it can notice that it has been asked to exit.
Definition at line 479 of file CEvent.cpp.
References CApplicationSerializer::getInstance(), CThreadRecursiveMutex::getLockLevel(), CThreadRecursiveMutex::getOwningThread(), CThreadRecursiveMutex::Lock(), m_fEnabled, m_Tid, and CThreadRecursiveMutex::UnLockCompletely().
Referenced by ~CEvent().
void CEvent::Enable ()
Enable execution of the event. This is intended to be called from outside the Event thread. This allows us to directly schedule the object as a thread, rather than going through the rigmarole required by CEvent::Schedule (p.)
Enabling an active thread is a no-op.
The enable state is a flag, not a counter, so only a single disable is required to kill the thread regardless of the number of Enable calls.
Reimplemented in CTimerEvent (p.).
Definition at line 449 of file CEvent.cpp.
References CApplicationSerializer::getInstance(), CThreadRecursiveMutex::Lock(), m_fEnabled, m_Tid, and CThreadRecursiveMutex::UnLock().
Referenced by CTimerEvent::Enable().
bool CEvent::getInformTimeout () const [inline]
Return TRUE if Reactor also catches timeouts.
Definition at line 390 of file CEvent.h.
References m_InformTimeouts.
CEventMonitor& CEvent::getMonitor () [inline]
Allow manipulation of the event monitor:.
Reimplemented in CBufferEvent< T > (p.), CLocationEvent< T > (p.), CTimerEvent (p.), and CBufferEvent< U > (p.).
Definition at line 398 of file CEvent.h.
Referenced by CFileEvent::MonitorExceptions(), CFileEvent::MonitorReadable(), CFileEvent::MonitorWritable(), and CFileEvent::~CFileEvent().
int CEvent::getMsReactivity () const [inline]
Return the reactivity of the event to programmatic stimulus.
Definition at line 394 of file CEvent.h.
References m_nMsReactivity.
CReactor& CEvent::getReactor () [inline]
Allow manipulation of the event reactor:.
Reimplemented in CBufferEvent< T > (p.), CLocationEvent< T > (p.), CTimerEvent (p.), and CBufferEvent< U > (p.).
Definition at line 402 of file CEvent.h.
Referenced by CFileEvent::~CFileEvent().
DAQThreadId CEvent::getThreadId () const [inline]
Allow external manipulation of the thread:.
Definition at line 406 of file CEvent.h.
References m_Tid.
bool CEvent::isActive () const [inline]
Return TRUE if the thread is running (active) (small timing hole).
Definition at line 386 of file CEvent.h.
References m_fActive.
bool CEvent::isEnabled () const [inline]
Return TRUE if the thread is enabled if not thread halt is pending.
Definition at line 382 of file CEvent.h.
References m_fEnabled.
DAQStatus CEvent::JoinThis () [protected]
Does a join on the current object. The assumption is that at some time this object exists as a thread and will exit to be joined before restarting.
Definition at line 638 of file CEvent.cpp.
References m_Tid.
void CEvent::OnEvent (CEventMonitor::result why) [protected, virtual]
Called when the event monitor indicates that an event has occured. The default action (overridable) is to: 1. Lock the global serialization mutex. 2. Call the Event reactor's operator() member function. 3. Unlock the global serialization mutex.
Parameters:
why - Indicates what condition the monitor signalled.
Definition at line 565 of file CEvent.cpp.
References CApplicationSerializer::getInstance(), CThreadRecursiveMutex::Lock(), m_InformTimeouts, m_rMonitor, m_rReactor, ProcessQueues(), CEventMonitor::result, CEventMonitor::TimedOut, and CThreadRecursiveMutex::UnLock().
Referenced by operator()().
int CEvent::operator() (int nargs, char ** ppArgs) [protected, virtual]
This is the Event thread's entry point when scheduled.
Reap the scheduler thread.
Delete the scheduler object which started us.
Enter the main event loop of polling the monitor and dipatching to the reactor.
Parameters:
nargs - Number of parameters.
ppargs - Pointer to the arguments. In this case it's just a pointer to the dispatching thread's object.
Reimplemented in CLocationEvent< T > (p.).
Definition at line 616 of file CEvent.cpp.
References m_fActive, m_nMsReactivity, m_rMonitor, m_Tid, OnEvent(), and CEventMonitor::setTimeout().
Referenced by CLocationEvent< T >::operator()().
CEvent& CEvent::operator= (const CEvent & aCEvent) [private]
Operator= Assignment Operator - not allowed.
int CEvent::operator== (const CEvent & aCEvent) const [private]
Operator== Equality Operator no point.
void CEvent::ProcessQueues () [protected, virtual]
Called periodically in event thread context to process any inter thread communication primitives which may require action at event context.
Reimplemented in CBufferEvent< T > (p.), and CBufferEvent< U > (p.).
Definition at line 650 of file CEvent.cpp.
Referenced by OnEvent().
void CEvent::ReactToTimeouts (bool fReact = true)
Determines whether or not Monitor timeouts will cause a reactor to be fired. Timeouts are used regardless in order to sense the dropping of the m_fEnabled flag. However if a timeout occurs and m_fInformTimeouts is false, the Reactor will not be called.
Parameters:
fReact [true] - true if reactivity is desired...
Definition at line 526 of file CEvent.cpp.
References m_InformTimeouts.
void CEvent::Schedule () [protected]
Called to schedule this process. Eric feels that it is not safe to just start this process off directly, e.g. from the constructor, because execution may start while the constructor is still executing either at this or a lower level of the class hierarchy if this is a class derived from CEvent. Therefore we do the following tricky startup:
Create a new thread (EventStartupThread).
Schedule that thread this is a parameter.
The thread will wait for some period of ms. which hopefully will ensure that the constructors have all exited.
The thread will start this object as a thread, passing itself to our operator()
Our operator() will do a Join on the thread which started us up to reap it.
Our operator() will enter the main event loop.
Definition at line 595 of file CEvent.cpp.
References m_fEnabled.
void CEvent::setActive (bool fActive) [inline, protected]
Set state of active flag.. implies thread is running.
Definition at line 414 of file CEvent.h.
References m_fActive.
void CEvent::setEnable (bool fEnable) [inline]
Definition at line 427 of file CEvent.h.
References m_fEnabled.
Referenced by CTimerEvent::InternalOnTimer(), and CServerInstance::Shutdown().
void CEvent::setReactivity (int nMs)
Changes the Monitor timeout. This will take effect after the next exit from the monitor.. which may require as much as the current value of timeout.
Parameters:
nMs - Number of milliseconds in the new timeout. -1 disables timeouts which in turn makes the time required to kill the thread unbounded.
Definition at line 512 of file CEvent.cpp.
References m_nMsReactivity.
Referenced by CTimerEvent::CTimerEvent(), CTimerEvent::Enable(), and CTimerEvent::SetTimeout().
void CEvent::setTid (const DAQThreadId Tid) [inline, protected]
Set Thread ID: implies you know a lot about the system.
Definition at line 418 of file CEvent.h.
References m_Tid.
Member Data Documentation
bool CEvent::m_fActive [private]
True if thread is active.
Definition at line 338 of file CEvent.h.
Referenced by DescribeSelf(), isActive(), operator()(), and setActive().
bool CEvent::m_fEnabled [private]
Event enabled flag.
Definition at line 337 of file CEvent.h.
Referenced by DescribeSelf(), Disable(), Enable(), isEnabled(), Schedule(), and setEnable().
bool CEvent::m_InformTimeouts [private]
Pass timeouts on to reactor.
Definition at line 339 of file CEvent.h.
Referenced by getInformTimeout(), OnEvent(), and ReactToTimeouts().
int CEvent::m_nMsReactivity [private]
Reactivity to external events.
Definition at line 340 of file CEvent.h.
Referenced by DescribeSelf(), getMsReactivity(), operator()(), and setReactivity().
CEventMonitor& CEvent::m_rMonitor [private]
Monitor which polls for event.
Reimplemented in CBufferEvent< T > (p.), CLocationEvent< T > (p.), CTimerEvent (p.), and CBufferEvent< U > (p.).
Definition at line 341 of file CEvent.h.
Referenced by DescribeSelf(), OnEvent(), and operator()().
CReactor& CEvent::m_rReactor [private]
Reactor to the event when it fires.
Reimplemented in CBufferEvent< T > (p.), CLocationEvent< T > (p.), CTimerEvent (p.), and CBufferEvent< U > (p.).
Definition at line 342 of file CEvent.h.
Referenced by DescribeSelf(), and OnEvent().
DAQThreadId CEvent::m_Tid [private]
spectrodaq thread identifier.
Definition at line 343 of file CEvent.h.
Referenced by Disable(), Enable(), getThreadId(), JoinThis(), operator()(), and setTid().
The documentation for this class was generated from the following files:
CEvent.h
CEvent.cpp