CNamedObject Class Reference
#include <CNamedObject.h>
Public Methods
CNamedObject ()
CNamedObject (string am_sName)
virtual ~CNamedObject ()
CNamedObject & operator= (const CNamedObject &rhs)
int operator== (const CNamedObject &rhs) const
string getClassPath () const
const string getName () const
unsigned int getAutoIndex () const
< Return value of auto naming index.
virtual string DescribeSelf ()
Protected Methods
void setClassPath (const string am_sClassPath)
void setAutoIndex (unsigned nNew)
virtual void AppendClassInfo ()
Static Protected Methods
string GetAutoName (const string &rBase)
Assign default name.
Private Attributes
string m_sName
string m_sClassPath
Static Private Attributes
unsigned int m_nAutoIndex
Used to name autonamed objects.
Detailed Description
Definition of a named object. Named objects are objects with a name and class path. The class path describes what type the object derived from CNamedObject actually is. That type is determined by AppendClass() which uses RTTI and is called each time CNamedObject (or anything derived from it) is instantiated.
Definition at line 314 of file CNamedObject.h.
Constructor & Destructor Documentation
CNamedObject::CNamedObject () [inline]
Definition at line 323 of file CNamedObject.h.
References AppendClassInfo(), GetAutoName(), and m_sName.
CNamedObject::CNamedObject (string am_sName) [inline]
Definition at line 328 of file CNamedObject.h.
References AppendClassInfo(), and m_sName.
virtual CNamedObject::~CNamedObject () [inline, virtual]
Definition at line 333 of file CNamedObject.h.
Member Function Documentation
void CNamedObject::AppendClassInfo () [protected, virtual]
Appends class information to m_sClassPath. The information consists of the class hierarchy of the object being created.
Definition at line 304 of file CNamedObject.cpp.
References m_sClassPath.
Referenced by CBufferReactor< T >::CBufferReactor(), CClassifiedObjectRegistry::CClassifiedObjectRegistry(), CEvent::CEvent(), CEventMonitor::CEventMonitor(), CFdMonitor::CFdMonitor(), CFdReactor::CFdReactor(), CFileEvent::CFileEvent(), CFileEventReactor::CFileEventReactor(), CLocationReactor< T >::CLocationReactor(), CNamedObject(), CObjectRegistry::CObjectRegistry(), CReactor::CReactor(), CRegisteredObject::CRegisteredObject(), and CTimerMonitor::CTimerMonitor().
string CNamedObject::DescribeSelf () [virtual]
Describes the named object. The information given is the object type given by m_sClassPath, and the object name.
Reimplemented in CBufferEvent< T > (p.), CBufferMonitor< T > (p.), CChangedPredicate< T > (p.), CClassifiedObjectRegistry (p.), CEvent (p.), CFdMonitor (p.), CFileEvent (p.), CLocationEvent< T > (p.), CLocationMonitor< T > (p.), CMaskedValuePredicate< T > (p.), CObjectRegistry (p.), CPointerPredicate< T > (p.), CServerConnectionEvent (p.), CServerInstance (p.), CServerMonitor (p.), CTimerEvent (p.), CTimerMonitor (p.), CBufferEvent< U > (p.), and CBufferMonitor< U > (p.).
Definition at line 316 of file CNamedObject.cpp.
References m_sClassPath, and m_sName.
Referenced by CTimerMonitor::DescribeSelf(), CObjectRegistry::DescribeSelf(), CLocationMonitor< T >::DescribeSelf(), CFdMonitor::DescribeSelf(), CEvent::DescribeSelf(), CClassifiedObjectRegistry::DescribeSelf(), and CBufferMonitor< T >::DescribeSelf().
unsigned int CNamedObject::getAutoIndex () const [inline]
< Return value of auto naming index.
Definition at line 364 of file CNamedObject.h.
References m_nAutoIndex.
string CNamedObject::GetAutoName (const string & rBase) [static, protected]
Assign default name.
Allocate a name for an object given some generic base name. The final name is of the form: BaseName(m_nAutoIndex).
Reimplemented in CEventMonitor (p.), and CPointerPredicate< T > (p.).
Definition at line 330 of file CNamedObject.cpp.
References m_nAutoIndex.
Referenced by CFileEvent::CFileEvent(), and CNamedObject().
string CNamedObject::getClassPath () const [inline]
Definition at line 354 of file CNamedObject.h.
References m_sClassPath.
const string CNamedObject::getName () const [inline]
Definition at line 360 of file CNamedObject.h.
References m_sName.
Referenced by CObjectRegistry::Add(), CObjectRegistry::Remove(), and CClassifiedObjectRegistry::Remove().
CNamedObject& CNamedObject::operator= (const CNamedObject & rhs) [inline]
Definition at line 337 of file CNamedObject.h.
References m_sClassPath, and m_sName.
int CNamedObject::operator== (const CNamedObject & rhs) const [inline]
Definition at line 345 of file CNamedObject.h.
References m_sClassPath, and m_sName.
Referenced by CRegisteredObject::operator==().
void CNamedObject::setAutoIndex (unsigned nNew) [inline, protected]
Definition at line 378 of file CNamedObject.h.
References m_nAutoIndex.
void CNamedObject::setClassPath (const string am_sClassPath) [inline, protected]
Definition at line 374 of file CNamedObject.h.
References m_sClassPath.
Member Data Documentation
unsigned int CNamedObject::m_nAutoIndex [static, private]
Used to name autonamed objects.
NamedObject.cpp Base class for all objects in the event management system.
Author: Jason Venema NSCL Michigan State University East Lansing, MI 48824-1321 mailto:venemaja@msu.edu
Reimplemented in CEventMonitor (p.), and CPointerPredicate< T > (p.).
Referenced by getAutoIndex(), GetAutoName(), and setAutoIndex().
string CNamedObject::m_sClassPath [private]
The class path of the object
Definition at line 317 of file CNamedObject.h.
Referenced by AppendClassInfo(), DescribeSelf(), getClassPath(), operator=(), operator==(), and setClassPath().
string CNamedObject::m_sName [private]
The name of the object
Definition at line 316 of file CNamedObject.h.
Referenced by CNamedObject(), DescribeSelf(), getName(), operator=(), and operator==().
The documentation for this class was generated from the following files:
CNamedObject.h
CNamedObject.cpp