CTKInterpreterStartup Class Reference
#include <CTKInterpreterStartup.h>
Public Methods
CTKInterpreterStartup ()
virtual ~CTKInterpreterStartup ()
Static Protected Methods
int Tk_Init (Tcl_Interp *pInterp)
Private Methods
CTKInterpreterStartup (const CTKInterpreterStartup &aCTKInterpreterStartup)
Copy Constructor illegal, private, unimplemented.
CTKInterpreterStartup & operator= (const CTKInterpreterStartup &aCTKInterpreterStartup)
Operator= Assignment Operator illegal, private, unimplemented.
int operator== (const CTKInterpreterStartup &aCTKInterpreterStartup) const
Operator== Equality Operator illegal, private, unimplemented.
virtual int operator() (int argc, char **argv)
Detailed Description
Encapsulates the startup of a Tk/wish interpreter. An application must subclass this, Implement RegisterExtensions.
Definition at line 311 of file CTKInterpreterStartup.h.
Constructor & Destructor Documentation
CTKInterpreterStartup::CTKInterpreterStartup () [inline]
Definition at line 314 of file CTKInterpreterStartup.h.
virtual CTKInterpreterStartup::~CTKInterpreterStartup () [inline, virtual]
Definition at line 315 of file CTKInterpreterStartup.h.
CTKInterpreterStartup::CTKInterpreterStartup (const CTKInterpreterStartup & aCTKInterpreterStartup) [private]
Copy Constructor illegal, private, unimplemented.
Member Function Documentation
int CTKInterpreterStartup::operator() (int argc, char ** argv) [private, virtual]
Starts up the Tk interpreter.
Calls OnInitialize to allow users to do early initialization.
Starts the Tk interpreter by callling Tk_Main.
The static member Tk_Init is passed as the application initialization function.
Parameters:
argc The number of `command line` parameters
argv Vector of pointers to the `command line` parameter strings.
Implements CInterpreterStartup (p.).
Definition at line 307 of file CTKInterpreterStartup.cpp.
References CInterpreterStartup::OnInitialize(), and Tk_Init().
CTKInterpreterStartup& CTKInterpreterStartup::operator= (const CTKInterpreterStartup & aCTKInterpreterStartup) [private]
Operator= Assignment Operator illegal, private, unimplemented.
int CTKInterpreterStartup::operator== (const CTKInterpreterStartup & aCTKInterpreterStartup) const [private]
Operator== Equality Operator illegal, private, unimplemented.
int CTKInterpreterStartup::Tk_Init (Tcl_Interp * pInterp) [static, protected]
Called by Tk_Main to do application specific initialization.
Establishes object context by invoking CEventLoop::getInstance() (p.)
Invokes RegisterExtensions so that applicaiton packages and commands can be registered on the interpreter.
Finally returns to the Tk event loop..
Parameters:
pInterp Pointer to the Tcl interpreter created by Tk_Main.
Definition at line 342 of file CTKInterpreterStartup.cpp.
References CEventLoop::getInstance(), CInterpreterStartup::RegisterExtensions(), CInterpreterStartup::setInterpreter(), and Tk_Init().
Referenced by operator()(), and Tk_Init().
The documentation for this class was generated from the following files:
CTKInterpreterStartup.h
CTKInterpreterStartup.cpp