XMPushButton Class Reference
#include <XMPushbutton.h>
Public Methods
XMPushButton (char *n, Widget parent, void(*cb)(XMWidget *, XtPointer, XtPointer)=NULL, XtPointer cd=NULL)
XMPushButton (char *n, XMWidget &parent, void(*cb)(XMWidget *, XtPointer, XtPointer)=NULL, XtPointer cd=NULL)
XMPushButton (Widget w)
Callback_data * AddCallback (void(*cb)(XMWidget *, XtPointer, XtPointer)=NULL, XtPointer cd=NULL)
Constructor & Destructor Documentation
XMPushButton::XMPushButton (char * n, Widget parent, void(* cb)(XMWidget *, XtPointer, XtPointer) = NULL, XtPointer cd = NULL) [inline]
Definition at line 377 of file XMPushbutton.h.
References XMWidget::AddCallback(), and XMButton::Enable().
XMPushButton::XMPushButton (char * n, XMWidget & parent, void(* cb)(XMWidget *, XtPointer, XtPointer) = NULL, XtPointer cd = NULL) [inline]
Definition at line 387 of file XMPushbutton.h.
References XMWidget::AddCallback(), and XMButton::Enable().
XMPushButton::XMPushButton (Widget w) [inline]
Definition at line 397 of file XMPushbutton.h.
Member Function Documentation
Callback_data* XMPushButton::AddCallback (void(* cb)(XMWidget *, XtPointer, XtPointer) = NULL, XtPointer cd = NULL) [inline]
Definition at line 400 of file XMPushbutton.h.
References XMWidget::AddCallback().
The documentation for this class was generated from the following file:
XMPushbutton.h