CException Class Reference
#include <CException.h>
Public Methods
virtual ~CException ()
CException (const char *pszAction)
CException (const std::string &rsAction)
CException (const CException &aCException)
CException & operator= (const CException &aCException)
int operator== (const CException &aCException)
int operator!= (const CException &rException)
const char * getAction () const
virtual const char * ReasonText () const
virtual Int_t ReasonCode () const
const char * WasDoing () const
Protected Methods
void setAction (const char *pszAction)
void setAction (const std::string &rsAction)
virtual void DoAssign (const CException &rhs)
Private Attributes
char m_szAction [kACTIONSIZE]
Detailed Description
Base class for exceptions thrown by the histogrammign subsystem. (could be used for any other subsystem for that matter).
Definition at line 308 of file CException.h.
Constructor & Destructor Documentation
virtual CException::~CException () [inline, virtual]
Definition at line 318 of file CException.h.
CException::CException (const char * pszAction)
Definition at line 319 of file CException.cpp.
References setAction().
CException::CException (const std::string & rsAction)
Definition at line 323 of file CException.cpp.
References setAction().
CException::CException (const CException & aCException)
Definition at line 335 of file CException.cpp.
References DoAssign().
Member Function Documentation
void CException::DoAssign (const CException & rException) [protected, virtual]
This is virtual to allow derived classes to override and chain calls to.
Definition at line 465 of file CException.cpp.
References m_szAction, and setAction().
Referenced by CException(), and operator=().
const char* CException::getAction () const [inline]
Definition at line 343 of file CException.h.
References m_szAction.
Referenced by WasDoing().
int CException::operator!= (const CException & rException) [inline]
Definition at line 335 of file CException.h.
References operator==().
CException & CException::operator= (const CException & aCException)
Definition at line 347 of file CException.cpp.
References DoAssign().
Referenced by CTCLException::operator=(), CTCPBadSocketState::operator=(), CRangeError::operator=(), CNoSuchObjectException::operator=(), CNoSuchLinkException::operator=(), CLinkFailedException::operator=(), CIncompatibleMonitor::operator=(), CErrnoException::operator=(), CDuplicateSingleton::operator=(), and CDuplicateNameException::operator=().
int CException::operator== (const CException & aCException)
Definition at line 363 of file CException.cpp.
References m_szAction.
Referenced by operator!=(), CTCLException::operator==(), CTCPNoSuchHost::operator==(), CTCPBadSocketState::operator==(), CStreamIOError::operator==(), CRangeError::operator==(), CNoSuchObjectException::operator==(), CNoSuchLinkException::operator==(), CLinkFailedException::operator==(), CIncompatibleMonitor::operator==(), CErrnoException::operator==(), CDuplicateSingleton::operator==(), and CDuplicateNameException::operator==().
Int_t CException::ReasonCode () const [virtual]
Returns a code which describes the reason for the exception . This is exception type specific and may be used to do detailed exception analysis and recovery. For example in the CErrnoException (p.) class, the errno at the time of instantiation of the object is returned. The default returns -1
Reimplemented in CTCPNoSuchHost (p.), CErrnoException (p.), CRangeError (p.), CStreamIOError (p.), and CTCLException (p.).
Definition at line 407 of file CException.cpp.
const char * CException::ReasonText () const [virtual]
Returns a const pointer to text which describes the reason the exception was thrown. This is exception type specific. The default action returns a pointer to the constant string: `Unspecified Exception`
Reimplemented in CDuplicateNameException (p.), CDuplicateSingleton (p.), CIncompatibleMonitor (p.), CLinkFailedException (p.), CNoSuchLinkException (p.), CNoSuchObjectException (p.), CTCPBadSocketState (p.), CTCPConnectionFailed (p.), CTCPConnectionLost (p.), CTCPNoSuchHost (p.), CTCPNoSuchService (p.), CErrnoException (p.), CRangeError (p.), CStreamIOError (p.), and CTCLException (p.).
Definition at line 385 of file CException.cpp.
void CException::setAction (const std::string & rsAction) [protected]
Definition at line 448 of file CException.cpp.
References setAction().
void CException::setAction (const char * pszAction) [protected]
Definition at line 443 of file CException.cpp.
References m_szAction.
Referenced by CException(), DoAssign(), and setAction().
const char * CException::WasDoing () const
Returns a const pointer to m_szAction. This is intended to describe the action which was occuring when the exception was thrown.
Definition at line 427 of file CException.cpp.
References getAction().
Referenced by CTCPNoSuchHost::ReasonText(), CTCPBadSocketState::ReasonText(), and CIncompatibleMonitor::ReasonText().
Member Data Documentation
char CException::m_szAction[kACTIONSIZE] [private]
Definition at line 312 of file CException.h.
Referenced by DoAssign(), getAction(), operator==(), and setAction().
The documentation for this class was generated from the following files:
CException.cpp
CException.h