CFdReactor Class Reference
#include <CFdReactor.h>
Public Methods
CFdReactor ()
CFdReactor (const char *pName)
CFdReactor (const string &rName)
virtual ~CFdReactor ()
int operator== (const CFdReactor &aCFdReactor) const
Operator== Equality Operator.
virtual void OnEvent (CEventMonitor &rMonitor)
virtual void OnReadable (CFdMonitor &rMonitor, int fd)
virtual void OnWritable (CFdMonitor &rMonitor, int fd)
virtual void OnException (CFdMonitor &rMonitor, int fd)
Private Methods
CFdReactor (const CFdReactor &aCFdReactor)
Copy construction is prohibited.
CFdReactor & operator= (const CFdReactor &aCFdReactor)
Operator= Assignment Operator - Prohibited.
Detailed Description
Base class for file descriptor reactors: Fd reactors react to events on a file descriptor. This abstract base class must be subclassed by the programmer to provide application specific behavior.
Definition at line 317 of file CFdReactor.h.
Constructor & Destructor Documentation
CFdReactor::CFdReactor ()
Default constructor: Creates a file descriptor reactor which autonamed. Such fd reactors in general are not named in a memorable way.
Definition at line 300 of file CFdReactor.cpp.
References CNamedObject::AppendClassInfo().
CFdReactor::CFdReactor (const char * pName)
Constructor for a named reactor. Creates a file descriptor reactor which is given a memorable name by the object's client.
Parameters:
pName -Pointer to object name in ASCIZ form.
Definition at line 310 of file CFdReactor.cpp.
References CNamedObject::AppendClassInfo().
CFdReactor::CFdReactor (const string & rName)
Constructor for a named reactor. Creates a file descriptor reactor which is given a memorable name by the object's client.
Parameters:
rName - reference to an STL String which has the object's name.
Definition at line 321 of file CFdReactor.cpp.
References CNamedObject::AppendClassInfo().
CFdReactor::CFdReactor (const CFdReactor & aCFdReactor) [private]
Copy construction is prohibited.
CFdReactor::~CFdReactor () [virtual]
Definition at line 327 of file CFdReactor.cpp.
Member Function Documentation
void CFdReactor::OnEvent (CEventMonitor & rMonitor) [virtual]
EDispatches an incomming event from an FdMonitor to one or more of the following member functions:
OnReadble - The file is readable.
OnWritable - The file is writable.
OnException - The file has an exceptional condition.
NOTE: We can only dispatch to conditions the monitor is looking for.
Throws:
CIncompatibleMonitorException - If the monitor cannot be cast to a CFdMonitor (p.) object.
Parameters:
rMonitor - Reference to the monitor which caused us to be invoked. This should be an object which lives in the CFdMonitor (p.) branch of the CMonitor class hierarchy.
Reimplemented from CReactor (p.).
Definition at line 357 of file CFdReactor.cpp.
References CFdMonitor::FD_EXCEPTION, CFdMonitor::FD_READABLE, CFdMonitor::FD_WRITABLE, CFdMonitor::FdConditions, CFdMonitor::getFd(), CFdMonitor::getLastEventMask(), OnException(), OnReadable(), and OnWritable().
void CFdReactor::OnException (CFdMonitor & rMonitor, int fd) [virtual]
Called when the file associated with the event monitor has an `exceptional condition`.. Actual use of this Reactor involves subclassing the monitor and overriding OnException if you care about processing exceptional conditions.
Reimplemented in CFileEventReactor (p.).
Definition at line 409 of file CFdReactor.cpp.
Referenced by OnEvent().
void CFdReactor::OnReadable (CFdMonitor & rMonitor, int fd) [virtual]
Called when the file associated with the event monitor becomes readable. Actual use of this Reactor involves subclassing the monitor and overriding OnReadable if you care about reading the file.
Reimplemented in CFileEventReactor (p.).
Definition at line 389 of file CFdReactor.cpp.
Referenced by OnEvent().
void CFdReactor::OnWritable (CFdMonitor & rMonitor, int fd) [virtual]
Called when the file associated with the event monitor becomes writable. Actual use of this Reactor involves subclassing the monitor and overriding OnWritable if you care about writing the file.
Reimplemented in CFileEventReactor (p.).
Definition at line 399 of file CFdReactor.cpp.
Referenced by OnEvent().
CFdReactor& CFdReactor::operator= (const CFdReactor & aCFdReactor) [private]
Operator= Assignment Operator - Prohibited.
int CFdReactor::operator== (const CFdReactor & aCFdReactor) const
Operator== Equality Operator.
Definition at line 332 of file CFdReactor.cpp.
References CReactor::operator==().
The documentation for this class was generated from the following files:
CFdReactor.h
CFdReactor.cpp