XMText Class Reference
#include <XMText.h>
Public Methods
XMText (char *n, XMWidget &parent, int rows=1, int columns=30, ArgList args=NULL, Cardinal arg_count=0)
XMText (char *n, Widget parent, int rows=1, int columns=30, ArgList args=NULL, Cardinal arg_count=0)
XMText (char *n)
XMText (Widget w)
void SetColumns (int columns)
void SetRows (int rows)
void SetMaxLength (int len)
void EnableWordWrap ()
void DisableWordWrap ()
char * GetText ()
void SetText (char *txt)
void SetEditing (Boolean enable)
Constructor & Destructor Documentation
XMText::XMText (char * n, XMWidget & parent, int rows = 1, int columns = 30, ArgList args = NULL, Cardinal arg_count = 0) [inline]
Definition at line 305 of file XMText.h.
References SetColumns(), and SetRows().
XMText::XMText (char * n, Widget parent, int rows = 1, int columns = 30, ArgList args = NULL, Cardinal arg_count = 0) [inline]
Definition at line 312 of file XMText.h.
References SetColumns(), and SetRows().
XMText::XMText (char * n) [inline]
Definition at line 319 of file XMText.h.
XMText::XMText (Widget w) [inline]
Definition at line 320 of file XMText.h.
Member Function Documentation
void XMText::DisableWordWrap () [inline]
Definition at line 336 of file XMText.h.
References XMWidget::SetAttribute().
void XMText::EnableWordWrap () [inline]
Definition at line 333 of file XMText.h.
References XMWidget::SetAttribute().
char* XMText::GetText () [inline]
Definition at line 339 of file XMText.h.
References XMWidget::id.
void XMText::SetColumns (int columns) [inline]
Definition at line 324 of file XMText.h.
References XMWidget::SetAttribute().
Referenced by XMScrolledText::XMScrolledText(), and XMText().
void XMText::SetEditing (Boolean enable) [inline]
Definition at line 344 of file XMText.h.
References XMWidget::SetAttribute().
void XMText::SetMaxLength (int len) [inline]
Reimplemented in XMScrolledText (p.).
Definition at line 330 of file XMText.h.
References XMWidget::SetAttribute().
void XMText::SetRows (int rows) [inline]
Definition at line 327 of file XMText.h.
References XMWidget::SetAttribute().
Referenced by XMScrolledText::XMScrolledText(), and XMText().
void XMText::SetText (char * txt) [inline]
Definition at line 341 of file XMText.h.
References XMWidget::id.
The documentation for this class was generated from the following file:
XMText.h