XMListBaseClass Class Reference
#include <XMList.h>
Public Methods
XMListBaseClass (char *n, WidgetClass cl, XMWidget &parent, ArgList l=NULL, Cardinal num_args=0)
XMListBaseClass (char *n, WidgetClass cl, Widget parent, ArgList l=NULL, Cardinal num_args=0)
XMListBaseClass (char *n)
XMListBaseClass (Widget w)
void AutoSelect (Boolean enable=True)
void SetDoubleClickTime (int ms=100)
void SetRows (int rows)
void SetScrollPolicy (int policy=XmAS_NEEDED)
void SetSelectionPolicy (int policy=XmSINGLE_SELECT)
int GetListCount ()
XmStringTable GetListValues ()
int GetSelectedListCount ()
XmStringTable GetSelectedItems ()
Callback_data * AddbrowseSelectionCallback (void(*callback)(XMWidget *, XtPointer, XtPointer), XtPointer user_data=NULL)
Callback_data * AddDefaultActionCallback (void(*callback)(XMWidget *, XtPointer, XtPointer), XtPointer user_data=NULL)
Callback_data * AddExtendedSelectionCallback (void(*callback)(XMWidget *, XtPointer, XtPointer), XtPointer user_data=NULL)
Callback_data * AddMultipleSelectionCallback (void(*callback)(XMWidget *, XtPointer, XtPointer), XtPointer user_data=NULL)
Callback_data * AddSingleSelectionCallback (void(*callback)(XMWidget *, XtPointer, XtPointer), XtPointer user_data=NULL)
void AddItem (char *item, int position=0)
void ClearItems ()
void DeleteItem (char *item)
void DeleteItem (int loc=0)
void DeleteItems (int loc, int count=1)
void DeselectAll ()
void DeselectItem (char *item)
void DeselectItem (int pos=0)
void SetBottomItem (int position=0)
void SelectItem (int pos=0)
Constructor & Destructor Documentation
XMListBaseClass::XMListBaseClass (char * n, WidgetClass cl, XMWidget & parent, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 311 of file XMList.h.
XMListBaseClass::XMListBaseClass (char * n, WidgetClass cl, Widget parent, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 314 of file XMList.h.
XMListBaseClass::XMListBaseClass (char * n) [inline]
Definition at line 318 of file XMList.h.
XMListBaseClass::XMListBaseClass (Widget w) [inline]
Definition at line 319 of file XMList.h.
Member Function Documentation
Callback_data* XMListBaseClass::AddbrowseSelectionCallback (void(* callback)(XMWidget *, XtPointer, XtPointer), XtPointer user_data = NULL) [inline]
Definition at line 364 of file XMList.h.
References XMWidget::AddCallback().
Callback_data* XMListBaseClass::AddDefaultActionCallback (void(* callback)(XMWidget *, XtPointer, XtPointer), XtPointer user_data = NULL) [inline]
Definition at line 370 of file XMList.h.
References XMWidget::AddCallback().
Callback_data* XMListBaseClass::AddExtendedSelectionCallback (void(* callback)(XMWidget *, XtPointer, XtPointer), XtPointer user_data = NULL) [inline]
Definition at line 377 of file XMList.h.
References XMWidget::AddCallback().
void XMListBaseClass::AddItem (char * item, int position = 0) [inline]
Definition at line 401 of file XMList.h.
References XMWidget::id.
Callback_data* XMListBaseClass::AddMultipleSelectionCallback (void(* callback)(XMWidget *, XtPointer, XtPointer), XtPointer user_data = NULL) [inline]
Definition at line 384 of file XMList.h.
References XMWidget::AddCallback().
Callback_data* XMListBaseClass::AddSingleSelectionCallback (void(* callback)(XMWidget *, XtPointer, XtPointer), XtPointer user_data = NULL) [inline]
Definition at line 391 of file XMList.h.
References XMWidget::AddCallback().
void XMListBaseClass::AutoSelect (Boolean enable = True) [inline]
Definition at line 323 of file XMList.h.
References XMWidget::SetAttribute().
void XMListBaseClass::ClearItems () [inline]
Definition at line 406 of file XMList.h.
References XMWidget::id.
void XMListBaseClass::DeleteItem (int loc = 0) [inline]
Definition at line 412 of file XMList.h.
References XMWidget::id.
void XMListBaseClass::DeleteItem (char * item) [inline]
Definition at line 407 of file XMList.h.
References XMWidget::id.
void XMListBaseClass::DeleteItems (int loc, int count = 1) [inline]
Definition at line 415 of file XMList.h.
References XMWidget::id.
void XMListBaseClass::DeselectAll () [inline]
Definition at line 418 of file XMList.h.
References XMWidget::id.
void XMListBaseClass::DeselectItem (int pos = 0) [inline]
Definition at line 427 of file XMList.h.
References XMWidget::id.
void XMListBaseClass::DeselectItem (char * item) [inline]
Definition at line 421 of file XMList.h.
References XMWidget::id.
int XMListBaseClass::GetListCount () [inline]
Definition at line 340 of file XMList.h.
References XMWidget::GetAttribute().
XmStringTable XMListBaseClass::GetListValues () [inline]
Definition at line 345 of file XMList.h.
References XMWidget::GetAttribute().
XmStringTable XMListBaseClass::GetSelectedItems () [inline]
Definition at line 357 of file XMList.h.
References XMWidget::GetAttribute().
int XMListBaseClass::GetSelectedListCount () [inline]
Definition at line 351 of file XMList.h.
References XMWidget::GetAttribute().
void XMListBaseClass::SelectItem (int pos = 0) [inline]
Definition at line 434 of file XMList.h.
References XMWidget::id.
void XMListBaseClass::SetBottomItem (int position = 0) [inline]
Definition at line 430 of file XMList.h.
References XMWidget::id.
void XMListBaseClass::SetDoubleClickTime (int ms = 100) [inline]
Definition at line 326 of file XMList.h.
References XMWidget::SetAttribute().
void XMListBaseClass::SetRows (int rows) [inline]
Definition at line 330 of file XMList.h.
References XMWidget::SetAttribute().
Referenced by XMList::XMList(), and XMScrolledList::XMScrolledList().
void XMListBaseClass::SetScrollPolicy (int policy = XmAS_NEEDED) [inline]
Definition at line 333 of file XMList.h.
References XMWidget::SetAttribute().
void XMListBaseClass::SetSelectionPolicy (int policy = XmSINGLE_SELECT) [inline]
Definition at line 336 of file XMList.h.
References XMWidget::SetAttribute().
The documentation for this class was generated from the following file:
XMList.h