CFileEvent Class Reference
#include <CFileEvent.h>
Public Methods
CFileEvent (int fd, int access=readable)
CFileEvent (const char *pName, int flags=O_RDONLY, int access=readable)
CFileEvent (const string &rName, int flags=O_RDONLY, int access=readable)
CFileEvent (int fd, const char *pObjName, int access=readable)
CFileEvent (const char *pObjName, const char *pName, int flags=O_RDONLY, int access=readable)
CFileEvent (const char *pObjName, const string &rName, int flags=O_RDONLY, int access=readable)
CFileEvent (int fd, const string &rObjName, int access=readable)
CFileEvent (const string &rObjName, const char *pname, int flags=O_RDONLY, int access=readable)
CFileEvent (const string &rObjName, const string &rName, int flags=O_RDONLY, int access=readable)
~CFileEvent ()
int getFd () const
int getCloseOnDestory () const
void MonitorReadable (bool fReadable=true)
void MonitorWritable (bool fWritable=true)
void MonitorExceptions (bool fExcept=true)
virtual void OnReadable (istream &rStream)
virtual void OnWritable (ostream &rStream)
virtual void OnException (iostream &fd)
virtual void OnTimeout (iostream &str)
virtual string DescribeSelf ()
Static Public Attributes
int readable = 1
Bitmask for readable monitoring.
int writeable = 2
Bitmask for writable monitoring.
int exceptions = 4
Bitmask for exception monitoring.
Protected Methods
void Exit (int status)
void SetupMonitor (int AccessMask)
CFdMonitor * CreateMonitor (const char *pFilename, const char *pMonitor, int flags)
Private Methods
CFileEvent (const CFileEvent &rEvent)
CFileEvent & operator= (const CFileEvent &rhs)
int operator== (const CFileEvent &rEvent)
Private Attributes
int m_nFd
File descriptor.
bool m_fCloseOnDestroy
true if we opened the file.
Detailed Description
C lass providing functionality for file descriptor events. Must be derived and operator() implemented to provide application functionality.
Definition at line 333 of file CFileEvent.h.
Constructor & Destructor Documentation
CFileEvent::CFileEvent (int fd, int access = readable)
Construct an anonymous file event from a file descriptor, The file monitor is a CFdMonitor (p.) directly constructed from the fd via new.
Parameters:
fd - File descriptor to open on the file.
access - Bitwise or of access required to file.
Definition at line 404 of file CFileEvent.cpp.
References CNamedObject::AppendClassInfo(), CNamedObject::GetAutoName(), m_fCloseOnDestroy, m_nFd, and SetupMonitor().
CFileEvent::CFileEvent (const char * pName, int flags = O_RDONLY, int access = readable)
Construct an anonymous file event from a filename as a const char* A file is opened and created with CreateMonitor.
Parameters:
pName - Name of file to open/create.
flags - open(2) flags.
access - Bitwise access requirements for the file.
Definition at line 421 of file CFileEvent.cpp.
References CNamedObject::AppendClassInfo(), and SetupMonitor().
CFileEvent::CFileEvent (const string & rName, int flags = O_RDONLY, int access = readable)
Construct an anonymous file event from a filename as a const string& A file is opened and created with CreateMonitor() (p.)
Parameters:
rName - Nameof the file to open/create
flags - open(2) flags..
access - Bitwise access requirements for the file.
Definition at line 436 of file CFileEvent.cpp.
References CNamedObject::AppendClassInfo(), and SetupMonitor().
CFileEvent::CFileEvent (int fd, const char * pObjName, int access = readable)
Construct a named file event from a char* object name, and a file descriptor. The CFdMonitor (p.) is directly new'd into existence in the operation.
Parameters:
pObjName - Pointer to object name.
fd - File descriptor on already open file to monitor.
access - Bitwise or of the desired access to the file.
Throws:
CDuplicateNameException (p.) - if this object or any subobject already have this name.
Definition at line 463 of file CFileEvent.cpp.
References CNamedObject::AppendClassInfo(), and SetupMonitor().
CFileEvent::CFileEvent (const char * pObjName, const char * pFilename, int flags = O_RDONLY, int access = readable)
Construct a named file event from a char* object name and a char* filename. The CFdMonitor (p.) is created by CreateMonitor.
Parameters:
pObjName - Name to give to all the objects.
pFilename - Name of the file to access.
flags - open(2) flags.
access - Bitwise or of the access rights desired to the file.
Throws:
CDuplicateNameException (p.) - if this object or any subobject already have this name.
Definition at line 489 of file CFileEvent.cpp.
References CNamedObject::AppendClassInfo(), and SetupMonitor().
CFileEvent::CFileEvent (const char * pObjName, const string & rFilename, int flags = O_RDONLY, int access = readable)
Constructs a named file event given a char* object name and a string& filename. The monitor is created via CreateMonitor.
Parameters:
pObjName - Pointer to the name of the object
rFilename - Reference to the name of the file
flags - open(2) flags..
access - Bitmask specifying access desired.
Throws:
CDuplicateNameException (p.) - if this object or any subobject already have this name.
Definition at line 513 of file CFileEvent.cpp.
References CNamedObject::AppendClassInfo(), and SetupMonitor().
CFileEvent::CFileEvent (int fd, const string & rObjName, int access = readable)
Construct a file event from a string& object name and an fd. The Monitor can be created directly via new
Parameters:
rObjName - Reference to the name of the object.
fd - File descriptor to monitor.
access - Desired access to the file.
Throws:
CDuplicateNameException (p.) - if this object or any subobject already have this name.
Definition at line 539 of file CFileEvent.cpp.
References CNamedObject::AppendClassInfo(), and SetupMonitor().
CFileEvent::CFileEvent (const string & rObjName, const char * pFilename, int flags = O_RDONLY, int access = readable)
Construct a file event from a string& object name and a char* filename. The monitor is created via CreateMonitor.
Parameters:
rObjName - Reference to the name of the object.
pFilename - Pointer to the filename.
flags - open(2) flags.
access - Bitmask specifying the desired file access.
Throws:
CDuplicateNameException (p.) - if this object or any subobject already have this name.
Definition at line 562 of file CFileEvent.cpp.
References CNamedObject::AppendClassInfo(), and SetupMonitor().
CFileEvent::CFileEvent (const string & rObjName, const string & rFilename, int flags = O_RDONLY, int access = readable)
Construct a file event from a string& object name, and a string& filename. The monitor is created via CreateMonitor:
Parameters:
rObjName - The name of the object being created.
rFilename - The name of the file being accessed.
flags - open(2) flags.
access - bitmask of requested access.
Throws:
CDuplicateNameException (p.) - if this object or any subobject already have this name.
Definition at line 584 of file CFileEvent.cpp.
References CNamedObject::AppendClassInfo(), and SetupMonitor().
CFileEvent::~CFileEvent ()
Destructor: In all of the construction methods, the monitor and reactor are dynamically instantiated via new (that's what CreateMonitor will do). We need to get the Monitor and the Reactor and delete them.
Definition at line 600 of file CFileEvent.cpp.
References CEvent::getMonitor(), CEvent::getReactor(), and m_nFd.
CFileEvent::CFileEvent (const CFileEvent & rEvent) [private]
Member Function Documentation
CFdMonitor * CFileEvent::CreateMonitor (const char * pFilename, const char * pMonitor, int flags) [protected]
Creates a new monitor given a filename. The file is created/opened for read/write and the fd resulting is used to create a new CFdMonitor (p.) (via new).
Parameters:
pFilename - Name of the file to create/open.
pMonitor - Name to give to the monitor.
flags - open(2) flags.
Exceptions:
CErrnoException (p.) - If the file cannot be created/opened.
CDuplicateNameException (p.) - If the a monitor with that name already exists.
Definition at line 728 of file CFileEvent.cpp.
References m_nFd.
string CFileEvent::DescribeSelf () [virtual]
Called to get a description of the object. Tells the world we're a file handling event, dumps the CEvent (p.) Description, and gives the values of m_nFd, m_fCloseOnDestroy:
Reimplemented from CEvent (p.).
Reimplemented in CServerConnectionEvent (p.), and CServerInstance (p.).
Definition at line 785 of file CFileEvent.cpp.
References CEvent::DescribeSelf(), m_fCloseOnDestroy, and m_nFd.
void CFileEvent::Exit (int status) [protected]
Exits the thread now (the object must still be destroyed at some point). The global mutex is released unconditionally, a DAQStatus object is created with the given status value and DAQThread::Exit is called.
Parameters:
status - An integer status value (often chosen from errno.h).
Definition at line 706 of file CFileEvent.cpp.
References CApplicationSerializer::getInstance(), and CThreadRecursiveMutex::UnLockCompletely().
int CFileEvent::getCloseOnDestory () const [inline]
Definition at line 405 of file CFileEvent.h.
References m_fCloseOnDestroy.
int CFileEvent::getFd () const [inline]
Definition at line 404 of file CFileEvent.h.
References m_nFd.
Referenced by CFileEventReactor::OnTimeout().
void CFileEvent::MonitorExceptions (bool fExcept = true)
Select if the monitor should watch exceptions on the fd. This is delegated to the monitor's MonitorExceptions member function.
Parameters:
fExcept - true to watch for exceptions, false to disable.
Definition at line 636 of file CFileEvent.cpp.
References CEvent::getMonitor().
Referenced by SetupMonitor().
void CFileEvent::MonitorReadable (bool fReadable = true)
Select if the monitor should watch readability. This is delegated to the monitor's MonitorReadable member function.
Parameters:
fReadable - true to watch readability false to disable that.
Definition at line 616 of file CFileEvent.cpp.
References CEvent::getMonitor().
Referenced by SetupMonitor(), and CServerInstance::Shutdown().
void CFileEvent::MonitorWritable (bool fWritable = true)
Select if the monitor should watch writability. This is delegated to the Monitor's MonitorWritable member function.
Parameters:
fWritable - true to watch writability false to disable
Definition at line 626 of file CFileEvent.cpp.
References CEvent::getMonitor().
Referenced by SetupMonitor().
void CFileEvent::OnException (iostream & rStream) [virtual]
Called when the file descriptor has some exception condition. Normally, if an application is interested in this, the programmer will create a subclass of a CFileEvent which implements this member function in a non null way. Default action is an implemented no-op. This requires the programmer to only provide implementations for the members s/he needs. The alternative (pure virtual member), requires a programmer to implement (even if only as a no-op), all members.
Parameters:
rStream - Stream open on the file.
Definition at line 683 of file CFileEvent.cpp.
Referenced by CFileEventReactor::OnException().
void CFileEvent::OnReadable (istream & str) [virtual]
Called when a file descriptor becomes readable. Normally, if an application is interested in this, the programmer will create a subclass of CFileEvent which implements this member function in a non-null way. Default action is an implemented No-op. By implementing (rather than making this a pure virtual member), the programmer needs only to provide the members s/he's interested in.
Parameters:
rStream - Stream open on the file.
Reimplemented in CServerConnectionEvent (p.), and CServerInstance (p.).
Definition at line 654 of file CFileEvent.cpp.
Referenced by CFileEventReactor::OnReadable().
void CFileEvent::OnTimeout (iostream & rStream) [virtual]
Calle dwhen a wait times out, and the caller has idicated that they want to pay attention to timeouts.
ams str - reference to stream open on file.
Definition at line 692 of file CFileEvent.cpp.
Referenced by CFileEventReactor::OnTimeout().
void CFileEvent::OnWritable (ostream & rStream) [virtual]
Called when the file descriptor becomes writable. Normally, if an application is interested in this, the programmer will create a subclass of a CFileEvent which implements this member function in a non null way. Default action is an implemented no-op. This requires the programmer to only provide implementations for the members s/he needs. The alternative (pure virtual member), requires a programmer to implement (even if only as a no-op), all members.
Parameters:
rStream - Stream open on the file.
Definition at line 668 of file CFileEvent.cpp.
Referenced by CFileEventReactor::OnWritable().
CFileEvent& CFileEvent::operator= (const CFileEvent & rhs) [private]
int CFileEvent::operator== (const CFileEvent & rEvent) [private]
void CFileEvent::SetupMonitor (int AccessMask) [protected]
Set up the acessibility of the monitor. This means that the access mask is translated into an initial set of calls to MonitorReadable, MonitorWritable.
Parameters:
AccessMask - Bitwise or of the access requested.
Legitimate bits in AccessMask are:
CFileEvent::readable (p.) - Monitor readability.
CFileEvent::writable - Monitor writability.
CFileEvent::exceptions (p.) - Monitor for exceptions.
Definition at line 762 of file CFileEvent.cpp.
References exceptions, MonitorExceptions(), MonitorReadable(), MonitorWritable(), readable, and writeable.
Referenced by CFileEvent().
Member Data Documentation
int CFileEvent::exceptions = 4 [static]
Bitmask for exception monitoring.
Definition at line 304 of file CFileEvent.cpp.
Referenced by SetupMonitor().
bool CFileEvent::m_fCloseOnDestroy [private]
true if we opened the file.
Definition at line 358 of file CFileEvent.h.
Referenced by CFileEvent(), DescribeSelf(), and getCloseOnDestory().
int CFileEvent::m_nFd [private]
File descriptor.
Definition at line 357 of file CFileEvent.h.
Referenced by CFileEvent(), CreateMonitor(), DescribeSelf(), getFd(), and ~CFileEvent().
int CFileEvent::readable = 1 [static]
Bitmask for readable monitoring.
Definition at line 302 of file CFileEvent.cpp.
Referenced by SetupMonitor().
int CFileEvent::writeable = 2 [static]
Bitmask for writable monitoring.
Definition at line 303 of file CFileEvent.cpp.
Referenced by SetupMonitor().
The documentation for this class was generated from the following files:
CFileEvent.h
CFileEvent.cpp