XMVerticalSeparator Class Reference
#include <XMSeparators.h>
Public Methods
XMVerticalSeparator (char *n)
XMVerticalSeparator (char *n, Widget parent, ArgList l=NULL, Cardinal num_args=0)
XMVerticalSeparator (char *n, XMWidget &parent, ArgList l=NULL, Cardinal num_args=0)
Constructor & Destructor Documentation
XMVerticalSeparator::XMVerticalSeparator (char * n) [inline]
Definition at line 353 of file XMSeparators.h.
References XMWidget::Manage().
XMVerticalSeparator::XMVerticalSeparator (char * n, Widget parent, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 354 of file XMSeparators.h.
References XMWidget::Manage(), and XMSeparator::SetOrientation().
XMVerticalSeparator::XMVerticalSeparator (char * n, XMWidget & parent, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 359 of file XMSeparators.h.
References XMWidget::Manage(), and XMSeparator::SetOrientation().
The documentation for this class was generated from the following file:
XMSeparators.h