CTypeFreeBinding Class Reference
#include <CTypeFreeBinding.h>
Public Methods
virtual void InitBindings (CTCLInterpreter &rInterp)=0
virtual void Commit (CTCLInterpreter &rInterp)=0
virtual void ShutdownBindings (CTCLInterpreter &rInterp)=0
virtual void Dump (int fd)=0
Detailed Description
Provides a non-templated ABC for configuration variable bindings. this is required to allow the CConfigurationManager (p.) class to hold a list of bindings. For information about the member functions, see CBinding (p.)
Definition at line 299 of file CTypeFreeBinding.h.
Member Function Documentation
virtual void CTypeFreeBinding::Commit (CTCLInterpreter & rInterp) [pure virtual]
Implemented in CArrayBinding< T > (p.), CAssocArrayBinding< T > (p.), CBinding< T > (p.), and CVariableBinding< T > (p.).
Referenced by CCommit::operator()().
virtual void CTypeFreeBinding::Dump (int fd) [pure virtual]
Implemented in CArrayBinding< T > (p.), CAssocArrayBinding< T > (p.), CBinding< T > (p.), and CVariableBinding< T > (p.).
Referenced by CDumpBinding::operator()().
virtual void CTypeFreeBinding::InitBindings (CTCLInterpreter & rInterp) [pure virtual]
Implemented in CArrayBinding< T > (p.), CAssocArrayBinding< T > (p.), CBinding< T > (p.), and CVariableBinding< T > (p.).
Referenced by CInitBinding::operator()().
virtual void CTypeFreeBinding::ShutdownBindings (CTCLInterpreter & rInterp) [pure virtual]
Implemented in CArrayBinding< T > (p.), CAssocArrayBinding< T > (p.), and CVariableBinding< T > (p.).
Referenced by CShutdownBinding::operator()().
The documentation for this class was generated from the following file:
CTypeFreeBinding.h