CLinkFailedException Class Reference
#include <CLinkFailedException.h>
Public Methods
CLinkFailedException (const char *pDoing, const char *pName)
CLinkFailedException (const char *pDoing, const string &rName)
CLinkFailedException (const string &rDoing, const char *pName)
CLinkFailedException (const string &rDoing, const string &rName)
CLinkFailedException (const string &rDoing, int nId)
CLinkFailedException (const char *pDoing, int nId)
virtual ~CLinkFailedException ()
CLinkFailedException (const CLinkFailedException &aCLinkFailedException)
CLinkFailedException operator= (const CLinkFailedException &aCLinkFailedException)
int operator== (const CLinkFailedException &aCLinkFailedException)
string getName () const
void setName (string am_sName)
virtual const char * ReasonText () const
Protected Methods
void UpdateReasonText ()
Private Attributes
string m_sName
int m_nId
bool m_fName
string m_sReasonText
Constructor & Destructor Documentation
CLinkFailedException::CLinkFailedException (const char * pDoing, const char * pName) [inline]
Definition at line 301 of file CLinkFailedException.h.
References m_fName, m_sName, and UpdateReasonText().
CLinkFailedException::CLinkFailedException (const char * pDoing, const string & rName) [inline]
Definition at line 307 of file CLinkFailedException.h.
References m_fName, m_sName, and UpdateReasonText().
CLinkFailedException::CLinkFailedException (const string & rDoing, const char * pName) [inline]
Definition at line 313 of file CLinkFailedException.h.
References m_fName, m_sName, and UpdateReasonText().
CLinkFailedException::CLinkFailedException (const string & rDoing, const string & rName) [inline]
Definition at line 319 of file CLinkFailedException.h.
References m_fName, m_sName, and UpdateReasonText().
CLinkFailedException::CLinkFailedException (const string & rDoing, int nId) [inline]
Definition at line 325 of file CLinkFailedException.h.
References m_fName, m_nId, and UpdateReasonText().
CLinkFailedException::CLinkFailedException (const char * pDoing, int nId) [inline]
Definition at line 331 of file CLinkFailedException.h.
References m_fName, m_nId, and UpdateReasonText().
virtual CLinkFailedException::~CLinkFailedException () [inline, virtual]
Definition at line 337 of file CLinkFailedException.h.
CLinkFailedException::CLinkFailedException (const CLinkFailedException & aCLinkFailedException) [inline]
Definition at line 341 of file CLinkFailedException.h.
References m_sName, and UpdateReasonText().
Member Function Documentation
string CLinkFailedException::getName () const [inline]
Definition at line 371 of file CLinkFailedException.h.
References m_sName.
CLinkFailedException CLinkFailedException::operator= (const CLinkFailedException & aCLinkFailedException) [inline]
Definition at line 351 of file CLinkFailedException.h.
References m_sName, CException::operator=(), and UpdateReasonText().
int CLinkFailedException::operator== (const CLinkFailedException & aCLinkFailedException) [inline]
Definition at line 362 of file CLinkFailedException.h.
References m_sName, and CException::operator==().
const char * CLinkFailedException::ReasonText () const [virtual]
Returns a const pointer to text which describes the reason the exception was thrown. This is exception type specific. The default action returns a pointer to the constant string: `Unspecified Exception`
Reimplemented from CException (p.).
Definition at line 285 of file CLinkFailedException.cpp.
References m_sReasonText.
void CLinkFailedException::setName (string am_sName) [inline]
Definition at line 377 of file CLinkFailedException.h.
References m_sName.
void CLinkFailedException::UpdateReasonText () [protected]
Definition at line 291 of file CLinkFailedException.cpp.
References m_nId, m_sName, and m_sReasonText.
Referenced by CLinkFailedException(), and operator=().
Member Data Documentation
bool CLinkFailedException::m_fName [private]
Definition at line 297 of file CLinkFailedException.h.
Referenced by CLinkFailedException().
int CLinkFailedException::m_nId [private]
Definition at line 296 of file CLinkFailedException.h.
Referenced by CLinkFailedException(), and UpdateReasonText().
string CLinkFailedException::m_sName [private]
Definition at line 295 of file CLinkFailedException.h.
Referenced by CLinkFailedException(), getName(), operator=(), operator==(), setName(), and UpdateReasonText().
string CLinkFailedException::m_sReasonText [private]
Definition at line 298 of file CLinkFailedException.h.
Referenced by ReasonText(), and UpdateReasonText().
The documentation for this class was generated from the following files:
CLinkFailedException.h
CLinkFailedException.cpp