XMCascadeButton Class Reference
#include <XMPushbutton.h>
Public Methods
void SetAssociatedMenu (XMWidget &w)
void SetAssociatedMenu (Widget w)
XMCascadeButton (char *n, Widget parent, void(*cb)(XMWidget *, XtPointer, XtPointer)=NULL, XtPointer cd=NULL)
XMCascadeButton (char *n, XMWidget &parent, void(*cb)(XMWidget *, XtPointer, XtPointer)=NULL, XtPointer cd=NULL)
XMCascadeButton (Widget w)
Callback_data * AddCallback (void(*cb)(XMWidget *, XtPointer, XtPointer)=NULL, XtPointer cd=NULL)
Constructor & Destructor Documentation
XMCascadeButton::XMCascadeButton (char * n, Widget parent, void(* cb)(XMWidget *, XtPointer, XtPointer) = NULL, XtPointer cd = NULL) [inline]
Definition at line 431 of file XMPushbutton.h.
References XMWidget::AddCallback(), and XMButton::Enable().
XMCascadeButton::XMCascadeButton (char * n, XMWidget & parent, void(* cb)(XMWidget *, XtPointer, XtPointer) = NULL, XtPointer cd = NULL) [inline]
Definition at line 441 of file XMPushbutton.h.
References XMWidget::AddCallback(), and XMButton::Enable().
XMCascadeButton::XMCascadeButton (Widget w) [inline]
Definition at line 451 of file XMPushbutton.h.
Member Function Documentation
Callback_data* XMCascadeButton::AddCallback (void(* cb)(XMWidget *, XtPointer, XtPointer) = NULL, XtPointer cd = NULL) [inline]
Definition at line 455 of file XMPushbutton.h.
References XMWidget::AddCallback().
void XMCascadeButton::SetAssociatedMenu (Widget w) [inline]
Definition at line 421 of file XMPushbutton.h.
References XMWidget::SetAttribute().
void XMCascadeButton::SetAssociatedMenu (XMWidget & w) [inline]
Definition at line 417 of file XMPushbutton.h.
References XMWidget::getid(), and XMWidget::SetAttribute().
Referenced by XMPulldown::BuildMenu().
The documentation for this class was generated from the following file:
XMPushbutton.h