XMWidget Class Reference
#include <XMWidget.h>
Public Methods
XMWidget (char *n)
XMWidget (Widget w)
XMWidget (char *n, WidgetClass cl, XMApplication &parent, ArgList l=NULL, Cardinal num_args=0)
XMWidget (char *n, WidgetClass cl, Widget parent, ArgList l=NULL, Cardinal num_args=0)
XMWidget (char *n, WidgetClass cl, XMWidget &parent, ArgList l=NULL, Cardinal num_args=0)
virtual ~XMWidget ()
Widget getid ()
Widget getparent ()
char * getname ()
void SetAttribute (String attribute, XtArgVal value)
void SetAttribute (String attribute, void *value)
void GetAttribute (String attribute, void *value)
void GetAttribute (String attribute, XtArgVal value)
Callback_data * AddCallback (String reason, void(*proc)(XMWidget *, XtPointer, XtPointer), XtPointer data=NULL)
void Map ()
void UnMap ()
void Manage ()
void UnManage ()
void Realize ()
void UnRealize ()
Protected Methods
void Create (char *n, WidgetClass cl, Widget parent, ArgList l, Cardinal num_args)
Protected Attributes
Widget id
XMWidgetName name
Constructor & Destructor Documentation
XMWidget::XMWidget (char * n) [inline]
Definition at line 375 of file XMWidget.h.
References name.
XMWidget::XMWidget (Widget w) [inline]
Definition at line 380 of file XMWidget.h.
References id, and name.
XMWidget::XMWidget (char * n, WidgetClass cl, XMApplication & parent, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 385 of file XMWidget.h.
References Create(), and XMApplication::getid().
XMWidget::XMWidget (char * n, WidgetClass cl, Widget parent, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 390 of file XMWidget.h.
References Create().
XMWidget::XMWidget (char * n, WidgetClass cl, XMWidget & parent, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 395 of file XMWidget.h.
References Create(), and getid().
virtual XMWidget::~XMWidget () [inline, virtual]
Definition at line 400 of file XMWidget.h.
References id.
Member Function Documentation
Callback_data* XMWidget::AddCallback (String reason, void(* proc)(XMWidget *, XtPointer, XtPointer), XtPointer data = NULL) [inline]
Definition at line 419 of file XMWidget.h.
References XMAddCallback().
Referenced by XMTextField::AddActivateCallback(), XMListBaseClass::AddbrowseSelectionCallback(), XMArrowButton::AddCallback(), XMToggleButton::AddCallback(), XMCascadeButton::AddCallback(), XMPushButton::AddCallback(), XMScale::AddChangedCallback(), XMListBaseClass::AddDefaultActionCallback(), XMScale::AddDragCallback(), XMRowColumn::AddEntryCallback(), XMListBaseClass::AddExtendedSelectionCallback(), XMManager::AddHelpCallback(), XMListBaseClass::AddMultipleSelectionCallback(), XMListBaseClass::AddSingleSelectionCallback(), XMArrowButton::XMArrowButton(), XMCascadeButton::XMCascadeButton(), XMPushButton::XMPushButton(), and XMToggleButton::XMToggleButton().
void XMWidget::Create (char * n, WidgetClass cl, Widget parent, ArgList l, Cardinal num_args) [inline, protected]
Definition at line 366 of file XMWidget.h.
References id, and name.
Referenced by XMWidget().
void XMWidget::GetAttribute (String attribute, XtArgVal value) [inline]
Definition at line 416 of file XMWidget.h.
References id.
void XMWidget::GetAttribute (String attribute, void * value) [inline]
Definition at line 414 of file XMWidget.h.
References id.
Referenced by XMArrowButton::Direction(), Shell::GetGeometry(), TopLevelShell::GetIconic(), TopLevelShell::GetIconName(), XMListBaseClass::GetListCount(), XMListBaseClass::GetListValues(), Shell::GetSaveUnder(), XMListBaseClass::GetSelectedItems(), XMListBaseClass::GetSelectedListCount(), XMToggleButton::GetState(), and Shell::IsResizeAllowed().
Widget XMWidget::getid () [inline]
Definition at line 404 of file XMWidget.h.
References id.
Referenced by XMMenuBar::AddHelpPulldown(), XMCallback< Shell >::Register(), XMMainWindow::SetAreas(), XMCascadeButton::SetAssociatedMenu(), XMForm::SetBottomWidget(), XMForm::SetLeftWidget(), XMForm::SetRightWidget(), XMForm::SetTopWidget(), Shell::Shell(), XMCallback< Shell >::UnRegister(), XM_help(), XMAddCallback(), XMForm::XMForm(), XMMenuBar::XMMenuBar(), XMPulldown::XMPulldown(), XMRemoveCallback(), XMScrolledList::XMScrolledList(), XMScrolledText::XMScrolledText(), and XMWidget().
char* XMWidget::getname () [inline]
Definition at line 406 of file XMWidget.h.
References name.
Referenced by XMPulldown::FindMenuItem(), and XMMenuBar::GetPulldown().
Widget XMWidget::getparent () [inline]
Definition at line 405 of file XMWidget.h.
References id.
void XMWidget::Manage () [inline]
Reimplemented in XMScrolledList (p.), and Shell (p.).
Definition at line 433 of file XMWidget.h.
References id.
Referenced by XMHorizontalSeparator::XMHorizontalSeparator(), XMList::XMList(), XMManagedWidget::XMManagedWidget(), and XMVerticalSeparator::XMVerticalSeparator().
void XMWidget::Map () [inline]
Definition at line 431 of file XMWidget.h.
References id.
void XMWidget::Realize () [inline]
Reimplemented in Shell (p.).
Definition at line 435 of file XMWidget.h.
References id.
void XMWidget::SetAttribute (String attribute, void * value) [inline]
Definition at line 411 of file XMWidget.h.
References id.
void XMWidget::SetAttribute (String attribute, XtArgVal value) [inline]
Definition at line 409 of file XMWidget.h.
References id.
Referenced by XMMenuBar::AddHelpPulldown(), XMPulldown::AddMenuButton(), XMPulldown::AddMenuToggleButton(), XMRowColumn::Align(), XMBulletinBoard::AllowOverlap(), Shell::AllowResize(), XMPanedWindow::AllowResize(), XMListBaseClass::AutoSelect(), XMToggleButton::Box(), XMMainWindow::CommandWindowLocation(), XMToggleButton::Diamond(), XMButton::Disable(), XMText::DisableWordWrap(), XMButton::Enable(), XMTextField::EnableWordWrap(), XMText::EnableWordWrap(), XMToggleButton::HideIndicator(), XMButton::Label(), XMPanedWindow::Margins(), XMRowColumn::Margins(), XMFrame::Margins(), XMBulletinBoard::Margins(), XMPanedWindow::MaxPaneSize(), XMPanedWindow::MinPaneSize(), XMPulldown::NoRadioMenu(), XMRowColumn::NoRadioMenu(), XMArrowButton::PointDown(), XMArrowButton::PointLeft(), XMArrowButton::PointRight(), XMArrowButton::PointUp(), XMPulldown::RadioForceOne(), XMRowColumn::RadioForceOne(), XMPulldown::RadioMenu(), XMRowColumn::RadioMenu(), XMPulldown::RadioNoForceOne(), XMRowColumn::RadioNoForceOne(), TopLevelShell::RealizeIconic(), XMToggleButton::Set(), XMRowColumn::SetAlignment(), XMMainWindow::SetAreas(), XMCascadeButton::SetAssociatedMenu(), XMWidgetList::SetAttribute(), XMTextField::SetColumns(), XMText::SetColumns(), XMManager::SetConstraint(), XMListBaseClass::SetDoubleClickTime(), XMText::SetEditing(), XMRowColumn::SetEntryClass(), XMForm::SetFractionBase(), Shell::SetGeometry(), XMRowColumn::SetHomogenous(), XMForm::SetHorizontalSpacing(), TopLevelShell::SetIconName(), XMLabel::SetLabel(), XMTextField::SetMaxLength(), XMText::SetMaxLength(), XMButton::SetMnemonic(), XMManager::SetNavigationType(), XMSeparator::SetOrientation(), XMRowColumn::SetOrientation(), XMRowColumn::SetPacking(), XMPanedWindow::SetPaneSpacing(), XMRowColumn::SetRowColumns(), XMText::SetRows(), XMListBaseClass::SetRows(), XMForm::SetRubberPositioning(), XMPanedWindow::SetSashHeight(), XMPanedWindow::SetSashIndent(), Shell::SetSaveUnder(), XMListBaseClass::SetScrollPolicy(), XMListBaseClass::SetSelectionPolicy(), XMPanedWindow::SetSeparator(), XMSeparator::SetShadowType(), XMFrame::SetShadowType(), XMBulletinBoard::SetShadowType(), XMRowColumn::SetSpacing(), XMToggleButton::SetState(), XMForm::SetVerticalSpacing(), XMToggleButton::ShowIndicator(), XMMainWindow::ShowSeparator(), XMPanedWindow::SkipAdjust(), XMManager::TraversalOn(), XMManager::TraverseOff(), and XMToggleButton::UnSet().
void XMWidget::UnManage () [inline]
Reimplemented in XMScrolledList (p.), and Shell (p.).
Definition at line 434 of file XMWidget.h.
References id.
Referenced by XMUnmanageChild().
void XMWidget::UnMap () [inline]
Definition at line 432 of file XMWidget.h.
References id.
void XMWidget::UnRealize () [inline]
Definition at line 436 of file XMWidget.h.
References id.
Member Data Documentation
Widget XMWidget::id [protected]
Definition at line 364 of file XMWidget.h.
Referenced by XMListBaseClass::AddItem(), XMScrolledText::AddText(), XMPulldown::BuildMenu(), XMListBaseClass::ClearItems(), XMScrolledText::ClearText(), Create(), XMListBaseClass::DeleteItem(), XMListBaseClass::DeleteItems(), XMListBaseClass::DeselectAll(), XMListBaseClass::DeselectItem(), GetAttribute(), getid(), getparent(), XMTextField::GetText(), XMText::GetText(), Manage(), Shell::Manage(), XMScrolledList::Manage(), Map(), XMMenuBar::mbCreate(), Realize(), Shell::Realize(), XMListBaseClass::SelectItem(), XMButton::SetAccelerator(), SetAttribute(), XMListBaseClass::SetBottomItem(), XMScale::SetRange(), XMTextField::SetText(), XMText::SetText(), Shell::Shell(), UnManage(), Shell::UnManage(), XMScrolledList::UnManage(), UnMap(), UnRealize(), XMScale::Value(), XMForm::XMForm(), XMFrame::XMFrame(), XMMainWindow::XMMainWindow(), XMPanedWindow::XMPanedWindow(), XMRowColumn::XMRowColumn(), XMScrolledList::XMScrolledList(), XMScrolledText::XMScrolledText(), XMWidget(), and ~XMWidget().
XMWidgetName XMWidget::name [protected]
Definition at line 365 of file XMWidget.h.
Referenced by XMPulldown::AddMenuButton(), XMPulldown::AddMenuToggleButton(), XMPulldown::BuildMenu(), Create(), TopLevelShell::GetIconName(), getname(), XMMenuBar::mbCreate(), TopLevelShell::SetIconName(), XMForm::XMForm(), XMFrame::XMFrame(), XMMainWindow::XMMainWindow(), XMPanedWindow::XMPanedWindow(), XMRowColumn::XMRowColumn(), and XMWidget().
The documentation for this class was generated from the following file:
XMWidget.h