XMManagedWidget Class Reference
#include <XMWidget.h>
Public Methods
XMManagedWidget (char *n)
XMManagedWidget (char *n, WidgetClass cl, Widget parent, ArgList l=NULL, Cardinal num_args=0)
XMManagedWidget (char *n, WidgetClass cl, XMWidget &parent, ArgList l=NULL, Cardinal num_args=0)
XMManagedWidget (Widget w)
Constructor & Destructor Documentation
XMManagedWidget::XMManagedWidget (char * n) [inline]
Definition at line 442 of file XMWidget.h.
Referenced by XMPulldown::AddSeparator().
XMManagedWidget::XMManagedWidget (char * n, WidgetClass cl, Widget parent, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 447 of file XMWidget.h.
References XMWidget::Manage().
XMManagedWidget::XMManagedWidget (char * n, WidgetClass cl, XMWidget & parent, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 451 of file XMWidget.h.
References XMWidget::Manage().
XMManagedWidget::XMManagedWidget (Widget w) [inline]
Definition at line 455 of file XMWidget.h.
The documentation for this class was generated from the following file:
XMWidget.h