CBufferReactor< T > Class Template Reference
#include <CBufferReactor.h>
Public Methods
CBufferReactor ()
CBufferReactor (const string &rName)
CBufferReactor (const char *pName)
~CBufferReactor ()
template<class U> int operator== (const CBufferReactor< U > &aCBufferReactor) const
Operator== Equality comparison:.
virtual void OnEvent (CEventMonitor &rMonitor)
virtual void OnBuffer (CBufferMonitor< T > &rMonitor, Pointer< DAQBuffer< T >, T > pBuffer)
Private Methods
CBufferReactor (const CBufferReactor &aCBufferReactor)
Copy Constructor disallowed.
CBufferReactor & operator= (const CBufferReactor &aCBufferReactor)
Operator= Assignment Operator disallowed.
Detailed Description
template<class T> class CBufferReactor< T >
Base class for SpectroDaq buffer receipt. This object must be subclassed to provide application specific processing.
Definition at line 327 of file CBufferReactor.h.
Constructor & Destructor Documentation
template<class T> CBufferReactor< T >::CBufferReactor ()
Construct a buffer reactor with a default name. Note that buffer reactors are templated by the type of data contained in the buffer.
Definition at line 310 of file CBufferReactor.cpp.
References CNamedObject::AppendClassInfo().
template<class T> CBufferReactor< T >::CBufferReactor (const string & rName)
Construct a named buffer reactor using an STL string parameter for the object name.
Parameters:
rName - the name of the reactor.
Definition at line 322 of file CBufferReactor.cpp.
References CNamedObject::AppendClassInfo().
template<class T> CBufferReactor< T >::CBufferReactor (const char * pName)
Construct a named buffer reactor using a ASCIZ (C) string parameter for the object name.
Parameters:
pName - Pointer to an ASCIZ string naming the buffer.
Definition at line 334 of file CBufferReactor.cpp.
References CNamedObject::AppendClassInfo().
template<class T> CBufferReactor< T >::~CBufferReactor ()
Definition at line 340 of file CBufferReactor.cpp.
template<class T> CBufferReactor< T >::CBufferReactor (const CBufferReactor< T > & aCBufferReactor) [private]
Copy Constructor disallowed.
Member Function Documentation
template<class T> void CBufferReactor< T >::OnBuffer (CBufferMonitor< T > & rMonitor, Pointer< DAQBuffer< T >, T > pBuffer) [virtual]
Called when a buffer has been received by a buffer monitor. In normal use, the user will subclass CBufferReactor and override this no-op member.
Parameters:
rMonitor - The buffer monitor which received the buffer.
pBuffer - A DAQBufferPtr of the appropriate type into the buffer received.
Reimplemented in CBufferEvent< T >::CGenericBufferReactor< T > (p.).
Definition at line 389 of file CBufferReactor.cpp.
Referenced by CBufferReactor< T >::OnEvent().
template<class T> void CBufferReactor< T >::OnEvent (CEventMonitor & rMonitor) [virtual]
Called when the event monitor declares an event. The event monitor must be descended from CBufferMonitor (p.) or this function will throw a CIncompatibleMonitor (p.) exception. The OnBuffer virtual member is called with a pointer to the buffer.
Parameters:
rMonitor - Reference to the monitor which declared the event.
Reimplemented from CReactor (p.).
Definition at line 365 of file CBufferReactor.cpp.
References CBufferMonitor< T >::getBufferPointer(), and CBufferReactor< T >::OnBuffer().
template<class T> CBufferReactor& CBufferReactor< T >::operator= (const CBufferReactor< T > & aCBufferReactor) [private]
Operator= Assignment Operator disallowed.
template<class T> template<class U> int CBufferReactor< T >::operator== (const CBufferReactor< U > & aCBufferReactor) const
Operator== Equality comparison:.
Definition at line 349 of file CBufferReactor.cpp.
References CReactor::operator==().
The documentation for this class was generated from the following files:
CBufferReactor.h
CBufferReactor.cpp