XMScrolledList Class Reference
#include <XMList.h>
Public Methods
XMScrolledList (char *n, XMWidget &parent, int rows=10, ArgList args=NULL, Cardinal arg_count=0)
XMScrolledList (char *n, Widget parent, int rows=10, ArgList args=NULL, Cardinal arg_count=0)
Widget GetScrolledWindow ()
void Manage ()
void UnManage ()
Protected Attributes
Widget scrolled_widget
Constructor & Destructor Documentation
XMScrolledList::XMScrolledList (char * n, XMWidget & parent, int rows = 10, ArgList args = NULL, Cardinal arg_count = 0) [inline]
Definition at line 474 of file XMList.h.
References XMWidget::getid(), XMWidget::id, Manage(), scrolled_widget, and XMListBaseClass::SetRows().
XMScrolledList::XMScrolledList (char * n, Widget parent, int rows = 10, ArgList args = NULL, Cardinal arg_count = 0) [inline]
Definition at line 484 of file XMList.h.
References XMWidget::id, Manage(), scrolled_widget, and XMListBaseClass::SetRows().
Member Function Documentation
Widget XMScrolledList::GetScrolledWindow () [inline]
Definition at line 494 of file XMList.h.
References scrolled_widget.
void XMScrolledList::Manage () [inline]
Reimplemented from XMWidget (p.).
Definition at line 498 of file XMList.h.
References XMWidget::id, and scrolled_widget.
Referenced by XMScrolledList().
void XMScrolledList::UnManage () [inline]
Reimplemented from XMWidget (p.).
Definition at line 502 of file XMList.h.
References XMWidget::id, and scrolled_widget.
Member Data Documentation
Widget XMScrolledList::scrolled_widget [protected]
Definition at line 471 of file XMList.h.
Referenced by GetScrolledWindow(), Manage(), UnManage(), and XMScrolledList().
The documentation for this class was generated from the following file:
XMList.h