Shell Class Reference
#include <XMShell.h>
Public Methods
Shell (String shellname, WidgetClass shelltype, XMWidget *parent, ArgList args=NULL, Cardinal num_args=0)
~Shell ()
void AllowResize (Boolean allow)
Boolean IsResizeAllowed ()
void SetGeometry (String newg)
void GetGeometry (String geom)
void SetSaveUnder (Boolean newstate)
Boolean GetSaveUnder ()
void Realize ()
void Manage ()
void UnManage ()
Protected Attributes
XMCallback< Shell > Popdown
XMCallback< Shell > Popup
Private Methods
virtual void PopupCb (XMWidget *shell, XtPointer user_d, XtPointer call_d)
virtual void PopdnCb (XMWidget *shell, XtPointer user_d, XtPointer call_d)
Constructor & Destructor Documentation
Shell::Shell (String shellname, WidgetClass shelltype, XMWidget * parent, ArgList args = NULL, Cardinal num_args = 0)
Definition at line 323 of file XMShell.cpp.
References XMWidget::getid(), XMWidget::id, PopdnCb(), Popdown, Popup, PopupCb(), and XMCallback< Shell >::Register().
Shell::~Shell ()
Definition at line 385 of file XMShell.cpp.
References Popdown, Popup, UnManage(), and XMCallback< Shell >::UnRegister().
Member Function Documentation
void Shell::AllowResize (Boolean allow) [inline]
Definition at line 311 of file XMShell.h.
References XMWidget::SetAttribute().
void Shell::GetGeometry (String geom) [inline]
Definition at line 322 of file XMShell.h.
References XMWidget::GetAttribute().
Boolean Shell::GetSaveUnder () [inline]
Definition at line 327 of file XMShell.h.
References XMWidget::GetAttribute().
Boolean Shell::IsResizeAllowed () [inline]
Definition at line 313 of file XMShell.h.
References XMWidget::GetAttribute().
void Shell::Manage () [inline]
Reimplemented from XMWidget (p.).
Definition at line 339 of file XMShell.h.
References XMWidget::id.
Referenced by Realize().
void Shell::PopdnCb (XMWidget * shell, XtPointer user_d, XtPointer call_d) [private, virtual]
Definition at line 402 of file XMShell.cpp.
Referenced by Shell().
void Shell::PopupCb (XMWidget * shell, XtPointer user_d, XtPointer call_d) [private, virtual]
Definition at line 399 of file XMShell.cpp.
Referenced by Shell().
void Shell::Realize () [inline]
Reimplemented from XMWidget (p.).
Definition at line 334 of file XMShell.h.
References XMWidget::id, and Manage().
void Shell::SetGeometry (String newg) [inline]
Definition at line 320 of file XMShell.h.
References XMWidget::SetAttribute().
void Shell::SetSaveUnder (Boolean newstate) [inline]
Definition at line 325 of file XMShell.h.
References XMWidget::SetAttribute().
void Shell::UnManage () [inline]
Reimplemented from XMWidget (p.).
Definition at line 340 of file XMShell.h.
References XMWidget::id.
Referenced by ~Shell().
Member Data Documentation
XMCallback<Shell> Shell::Popdown [protected]
Definition at line 342 of file XMShell.h.
Referenced by Shell(), and ~Shell().
XMCallback<Shell> Shell::Popup [protected]
Definition at line 343 of file XMShell.h.
Referenced by Shell(), and ~Shell().
The documentation for this class was generated from the following files:
XMShell.h
XMShell.cpp