CDuplicateNameException Class Reference
#include <CDuplicateNameException.h>
Public Methods
CDuplicateNameException (const char *pDoing, const char *pName)
CDuplicateNameException (const char *pDoing, const string &rName)
CDuplicateNameException (const string &rDoing, const char *pName)
CDuplicateNameException (const string &rDoing, const string &rName)
virtual ~CDuplicateNameException ()
CDuplicateNameException (const CDuplicateNameException &aCDuplicateNameException)
CDuplicateNameException operator= (const CDuplicateNameException &aCDuplicateNameException)
int operator== (const CDuplicateNameException &aCDuplicateNameException)
string getName () const
void setName (string am_sName)
virtual const char * ReasonText () const
Protected Methods
void UpdateReasonText ()
Private Attributes
string m_sName
string m_sReasonText
Constructor & Destructor Documentation
CDuplicateNameException::CDuplicateNameException (const char * pDoing, const char * pName) [inline]
Definition at line 300 of file CDuplicateNameException.h.
References m_sName, and UpdateReasonText().
CDuplicateNameException::CDuplicateNameException (const char * pDoing, const string & rName) [inline]
Definition at line 305 of file CDuplicateNameException.h.
References m_sName, and UpdateReasonText().
CDuplicateNameException::CDuplicateNameException (const string & rDoing, const char * pName) [inline]
Definition at line 310 of file CDuplicateNameException.h.
References m_sName, and UpdateReasonText().
CDuplicateNameException::CDuplicateNameException (const string & rDoing, const string & rName) [inline]
Definition at line 315 of file CDuplicateNameException.h.
References m_sName, and UpdateReasonText().
virtual CDuplicateNameException::~CDuplicateNameException () [inline, virtual]
Definition at line 320 of file CDuplicateNameException.h.
CDuplicateNameException::CDuplicateNameException (const CDuplicateNameException & aCDuplicateNameException) [inline]
Definition at line 324 of file CDuplicateNameException.h.
References m_sName, and UpdateReasonText().
Member Function Documentation
string CDuplicateNameException::getName () const [inline]
Definition at line 354 of file CDuplicateNameException.h.
References m_sName.
CDuplicateNameException CDuplicateNameException::operator= (const CDuplicateNameException & aCDuplicateNameException) [inline]
Definition at line 334 of file CDuplicateNameException.h.
References m_sName, CException::operator=(), and UpdateReasonText().
int CDuplicateNameException::operator== (const CDuplicateNameException & aCDuplicateNameException) [inline]
Definition at line 345 of file CDuplicateNameException.h.
References m_sName, and CException::operator==().
const char * CDuplicateNameException::ReasonText () const [virtual]
Returns a const pointer to text which describes the reason the exception was thrown. This is exception type specific. The default action returns a pointer to the constant string: `Unspecified Exception`
Reimplemented from CException (p.).
Definition at line 284 of file CDuplicateNameException.cpp.
References m_sReasonText.
void CDuplicateNameException::setName (string am_sName) [inline]
Definition at line 360 of file CDuplicateNameException.h.
References m_sName.
void CDuplicateNameException::UpdateReasonText () [protected]
Definition at line 290 of file CDuplicateNameException.cpp.
References m_sName, and m_sReasonText.
Referenced by CDuplicateNameException(), and operator=().
Member Data Documentation
string CDuplicateNameException::m_sName [private]
Definition at line 295 of file CDuplicateNameException.h.
Referenced by CDuplicateNameException(), getName(), operator=(), operator==(), setName(), and UpdateReasonText().
string CDuplicateNameException::m_sReasonText [private]
Definition at line 296 of file CDuplicateNameException.h.
Referenced by ReasonText(), and UpdateReasonText().
The documentation for this class was generated from the following files:
CDuplicateNameException.h
CDuplicateNameException.cpp