CTCLTimer Class Reference
#include <TCLTimer.h>
Public Methods
CTCLTimer ()
CTCLTimer (CTCLInterpreter *pInterp, UInt_t nMsec=0)
virtual ~CTCLTimer ()
Tk_TimerToken getToken () const
UInt_t getMsec () const
Bool_t IsSet () const
virtual void operator() ()=0
void Set ()
void Set (UInt_t nms)
void Clear ()
Static Public Methods
void CallbackRelay (ClientData pObject)
Protected Methods
void setToken (Tk_TimerToken am_tToken)
void setMsec (UInt_t am_nMsec)
void setSet (Bool_t am_fSet)
Private Methods
CTCLTimer (const CTCLTimer &aCTCLTimer)
CTCLTimer & operator= (const CTCLTimer &aCTCLTimer)
int operator== (const CTCLTimer &aCTCLTimer)
Private Attributes
Tk_TimerToken m_tToken
UInt_t m_nMsec
Bool_t m_fSet
Constructor & Destructor Documentation
CTCLTimer::CTCLTimer () [inline]
Definition at line 324 of file TCLTimer.h.
References m_fSet, m_nMsec, and m_tToken.
CTCLTimer::CTCLTimer (CTCLInterpreter * pInterp, UInt_t nMsec = 0) [inline]
Definition at line 330 of file TCLTimer.h.
References m_fSet, m_nMsec, m_tToken, and UInt_t.
virtual CTCLTimer::~CTCLTimer () [inline, virtual]
Definition at line 336 of file TCLTimer.h.
References Clear().
CTCLTimer::CTCLTimer (const CTCLTimer & aCTCLTimer) [private]
Member Function Documentation
void CTCLTimer::CallbackRelay (ClientData pObject) [static]
Definition at line 321 of file TCLTimer.cpp.
References m_fSet.
Referenced by Set().
void CTCLTimer::Clear ()
Reimplemented in CTCLIdleProcess (p.).
Definition at line 369 of file TCLTimer.cpp.
References m_fSet, and m_tToken.
Referenced by CTCLIdleProcess::Clear(), and ~CTCLTimer().
UInt_t CTCLTimer::getMsec () const [inline]
Definition at line 360 of file TCLTimer.h.
References m_nMsec, and UInt_t.
Tk_TimerToken CTCLTimer::getToken () const [inline]
Definition at line 356 of file TCLTimer.h.
References m_tToken.
Bool_t CTCLTimer::IsSet () const [inline]
Definition at line 364 of file TCLTimer.h.
References Bool_t, and m_fSet.
virtual void CTCLTimer::operator() () [pure virtual]
Implemented in CTCLIdleProcess (p.).
CTCLTimer& CTCLTimer::operator= (const CTCLTimer & aCTCLTimer) [private]
int CTCLTimer::operator== (const CTCLTimer & aCTCLTimer) [private]
void CTCLTimer::Set (UInt_t nms) [inline]
Definition at line 390 of file TCLTimer.h.
References m_nMsec, Set(), and UInt_t.
void CTCLTimer::Set ()
Reimplemented in CTCLIdleProcess (p.).
Definition at line 344 of file TCLTimer.cpp.
References CallbackRelay(), m_fSet, m_nMsec, and m_tToken.
Referenced by Set(), and CTCLIdleProcess::Set().
void CTCLTimer::setMsec (UInt_t am_nMsec) [inline, protected]
Definition at line 376 of file TCLTimer.h.
References m_nMsec, and UInt_t.
void CTCLTimer::setSet (Bool_t am_fSet) [inline, protected]
Definition at line 380 of file TCLTimer.h.
References Bool_t, and m_fSet.
void CTCLTimer::setToken (Tk_TimerToken am_tToken) [inline, protected]
Definition at line 372 of file TCLTimer.h.
References m_tToken.
Member Data Documentation
Bool_t CTCLTimer::m_fSet [private]
Definition at line 319 of file TCLTimer.h.
Referenced by CallbackRelay(), Clear(), CTCLTimer(), IsSet(), Set(), and setSet().
UInt_t CTCLTimer::m_nMsec [private]
Definition at line 318 of file TCLTimer.h.
Referenced by CTCLTimer(), getMsec(), Set(), and setMsec().
Tk_TimerToken CTCLTimer::m_tToken [private]
Definition at line 317 of file TCLTimer.h.
Referenced by Clear(), CTCLTimer(), getToken(), Set(), and setToken().
The documentation for this class was generated from the following files:
TCLTimer.h
TCLTimer.cpp