CTCLVariable Class Reference
#include <TCLVariable.h>
Public Methods
CTCLVariable (std::string am_sVariable, Bool_t am_fTracing)
CTCLVariable (CTCLInterpreter *pInterp, std::string am_sVariable, Bool_t am_fTracing)
~CTCLVariable ()
CTCLVariable (const CTCLVariable &aCTCLVariable)
CTCLVariable & operator= (const CTCLVariable &aCTCLVariable)
int operator== (const CTCLVariable &aCTCLVariable) const
std::string getVariableName () const
Bool_t IsTracing () const
void setVariableName (const std::string am_sVariable)
virtual char * operator() (char *pName, char *pSubscript, int Flags)
virtual const char * Set (const char *pValue, int flags=TCL_LEAVE_ERR_MSG|TCL_GLOBAL_ONLY)
virtual const char * Set (const char *pSubscript, char *pValue, int flags=TCL_LEAVE_ERR_MSG|TCL_GLOBAL_ONLY)
virtual const char * Get (int flags=TCL_LEAVE_ERR_MSG|TCL_GLOBAL_ONLY, char *pIndex=0)
int Link (void *pVariable, int Type)
void Unlink ()
int Trace (int flags=TCL_TRACE_READS|TCL_TRACE_WRITES|TCL_TRACE_UNSETS, char *pIndex=(char *) kpNULL)
void UnTrace ()
void Update ()
Static Public Methods
char * TraceRelay (ClientData pObject, Tcl_Interp *pInterpreter, char *pName, char *pIndex, int flags)
Protected Methods
void setTracing (Bool_t am_fTracing)
void DoAssign (const CTCLVariable &rRhs)
Private Attributes
std::string m_sVariable
Bool_t m_fTracing
Int_t m_nTraceFlags
std::string m_sTraceIndex
Constructor & Destructor Documentation
CTCLVariable::CTCLVariable (std::string am_sVariable, Bool_t am_fTracing) [inline]
Definition at line 320 of file TCLVariable.h.
References Bool_t, m_fTracing, and m_sVariable.
CTCLVariable::CTCLVariable (CTCLInterpreter * pInterp, std::string am_sVariable, Bool_t am_fTracing) [inline]
Definition at line 325 of file TCLVariable.h.
References Bool_t, m_fTracing, and m_sVariable.
CTCLVariable::~CTCLVariable ()
Definition at line 312 of file TCLVariable.cpp.
References m_sVariable, and UnTrace().
CTCLVariable::CTCLVariable (const CTCLVariable & aCTCLVariable) [inline]
Definition at line 334 of file TCLVariable.h.
References DoAssign(), m_fTracing, and m_sVariable.
Member Function Documentation
void CTCLVariable::DoAssign (const CTCLVariable & rRhs) [protected]
Definition at line 618 of file TCLVariable.cpp.
References m_fTracing, m_nTraceFlags, m_sTraceIndex, m_sVariable, Trace(), and UnTrace().
Referenced by CTCLVariable(), and operator=().
const char * CTCLVariable::Get (int flags = TCL_LEAVE_ERR_MSG|TCL_GLOBAL_ONLY, char * pIndex = 0) [virtual]
Definition at line 468 of file TCLVariable.cpp.
References CTCLInterpreterObject::AssertIfNotBound(), CTCLInterpreter::getInterpreter(), and m_sVariable.
Referenced by CArrayBinding< T >::Commit().
std::string CTCLVariable::getVariableName () const [inline]
Definition at line 367 of file TCLVariable.h.
References m_sVariable.
Bool_t CTCLVariable::IsTracing () const [inline]
Definition at line 371 of file TCLVariable.h.
References Bool_t, and m_fTracing.
Referenced by setVariableName().
int CTCLVariable::Link (void * pVariable, int Type)
Definition at line 495 of file TCLVariable.cpp.
References CTCLInterpreterObject::AssertIfNotBound(), CTCLInterpreter::getInterpreter(), and m_sVariable.
char * CTCLVariable::operator() (char * pName, char * pSubscript, int Flags) [virtual]
Definition at line 326 of file TCLVariable.cpp.
CTCLVariable& CTCLVariable::operator= (const CTCLVariable & aCTCLVariable) [inline]
Definition at line 344 of file TCLVariable.h.
References DoAssign(), and CTCLInterpreterObject::operator=().
int CTCLVariable::operator== (const CTCLVariable & aCTCLVariable) const [inline]
Definition at line 355 of file TCLVariable.h.
References m_fTracing, m_sVariable, and CTCLInterpreterObject::operator==().
const char * CTCLVariable::Set (const char * pSubscript, char * pValue, int flags = TCL_LEAVE_ERR_MSG|TCL_GLOBAL_ONLY) [virtual]
Definition at line 446 of file TCLVariable.cpp.
References CTCLInterpreterObject::AssertIfNotBound(), CTCLInterpreter::getInterpreter(), and m_sVariable.
const char * CTCLVariable::Set (const char * pValue, int flags = TCL_LEAVE_ERR_MSG|TCL_GLOBAL_ONLY) [virtual]
Definition at line 414 of file TCLVariable.cpp.
References CTCLInterpreterObject::AssertIfNotBound(), CTCLInterpreter::getInterpreter(), and m_sVariable.
void CTCLVariable::setTracing (Bool_t am_fTracing) [inline, protected]
Definition at line 385 of file TCLVariable.h.
References Bool_t, and m_fTracing.
void CTCLVariable::setVariableName (const std::string am_sVariable) [inline]
Definition at line 379 of file TCLVariable.h.
References IsTracing(), m_sVariable, and UnTrace().
int CTCLVariable::Trace (int flags = TCL_TRACE_READS|TCL_TRACE_WRITES|TCL_TRACE_UNSETS, char * pIndex = (char *) kpNULL)
Definition at line 549 of file TCLVariable.cpp.
References CTCLInterpreterObject::AssertIfNotBound(), CTCLInterpreter::getInterpreter(), m_fTracing, m_nTraceFlags, m_sTraceIndex, m_sVariable, TraceRelay(), and UnTrace().
Referenced by DoAssign().
char * CTCLVariable::TraceRelay (ClientData pObject, Tcl_Interp * pInterpreter, char * pName, char * pIndex, int flags) [static]
Definition at line 370 of file TCLVariable.cpp.
References CTCLInterpreterObject::AssertIfNotBound(), and CTCLInterpreter::getInterpreter().
Referenced by Trace(), and UnTrace().
void CTCLVariable::Unlink ()
Definition at line 532 of file TCLVariable.cpp.
References CTCLInterpreterObject::AssertIfNotBound(), CTCLInterpreter::getInterpreter(), and m_sVariable.
void CTCLVariable::UnTrace ()
Definition at line 592 of file TCLVariable.cpp.
References CTCLInterpreterObject::AssertIfNotBound(), CTCLInterpreter::getInterpreter(), m_nTraceFlags, m_sTraceIndex, m_sVariable, and TraceRelay().
Referenced by DoAssign(), setVariableName(), Trace(), and ~CTCLVariable().
void CTCLVariable::Update ()
Invokes Tcl_UpdateLinkedVar on this variable. Intended to be used if the variable is linked to a C/C++ variable that may be modified by the C/C++ code but traced by Tcl.
Definition at line 645 of file TCLVariable.cpp.
References CTCLInterpreter::getInterpreter(), CTCLInterpreterObject::getInterpreter(), and m_sVariable.
Member Data Documentation
Bool_t CTCLVariable::m_fTracing [private]
Definition at line 313 of file TCLVariable.h.
Referenced by CTCLVariable(), DoAssign(), IsTracing(), operator==(), setTracing(), and Trace().
Int_t CTCLVariable::m_nTraceFlags [private]
Definition at line 314 of file TCLVariable.h.
Referenced by DoAssign(), Trace(), and UnTrace().
std::string CTCLVariable::m_sTraceIndex [private]
Definition at line 315 of file TCLVariable.h.
Referenced by DoAssign(), Trace(), and UnTrace().
std::string CTCLVariable::m_sVariable [private]
Definition at line 312 of file TCLVariable.h.
Referenced by CTCLVariable(), DoAssign(), Get(), getVariableName(), Link(), operator==(), Set(), setVariableName(), Trace(), Unlink(), UnTrace(), Update(), and ~CTCLVariable().
The documentation for this class was generated from the following files:
TCLVariable.h
TCLVariable.cpp