CTCLApplication Class Reference
#include <TCLApplication.h>
Public Methods
CTCLApplication ()
~CTCLApplication ()
CTCLApplication (const CTCLApplication &aCTCLApplication)
CTCLApplication & operator= (const CTCLApplication &aCTCLApplication)
int operator== (const CTCLApplication &aCTCLApplication)
virtual int operator() ()=0
Private Attributes
void * m_pInit
Constructor & Destructor Documentation
CTCLApplication::CTCLApplication () [inline]
Definition at line 308 of file TCLApplication.h.
References m_pInit, and Tcl_AppInit().
CTCLApplication::~CTCLApplication () [inline]
Definition at line 310 of file TCLApplication.h.
CTCLApplication::CTCLApplication (const CTCLApplication & aCTCLApplication) [inline]
Definition at line 315 of file TCLApplication.h.
Member Function Documentation
virtual int CTCLApplication::operator() () [pure virtual]
CTCLApplication& CTCLApplication::operator= (const CTCLApplication & aCTCLApplication) [inline]
Definition at line 323 of file TCLApplication.h.
References CTCLInterpreterObject::operator=().
int CTCLApplication::operator== (const CTCLApplication & aCTCLApplication) [inline]
Definition at line 333 of file TCLApplication.h.
References CTCLInterpreterObject::operator==().
Member Data Documentation
void* CTCLApplication::m_pInit [private]
Definition at line 304 of file TCLApplication.h.
Referenced by CTCLApplication().
The documentation for this class was generated from the following file:
TCLApplication.h