XMBulletinBoard Class Reference
#include <XMManagers.h>
Public Methods
XMBulletinBoard (char *n)
XMBulletinBoard (Widget w)
XMBulletinBoard (char *n, XMApplication &parent, ArgList l=NULL, Cardinal num_args=0)
XMBulletinBoard (char *n, Widget parent, ArgList l=NULL, Cardinal num_args=0)
XMBulletinBoard (char *n, XMWidget &parent, ArgList l=NULL, Cardinal num_args=0)
void AllowOverlap (Boolean allow)
void Margins (Dimension ymargin, Dimension xmargin=0)
void SetShadowType (unsigned char type)
void SetAbsPosition (XMWidget &w, int x, int y)
Protected Methods
XMBulletinBoard (char *n, WidgetClass cl, Widget parent, ArgList l, Cardinal num_args)
Constructor & Destructor Documentation
XMBulletinBoard::XMBulletinBoard (char * n, WidgetClass cl, Widget parent, ArgList l, Cardinal num_args) [inline, protected]
Definition at line 376 of file XMManagers.h.
XMBulletinBoard::XMBulletinBoard (char * n) [inline]
Definition at line 382 of file XMManagers.h.
XMBulletinBoard::XMBulletinBoard (Widget w) [inline]
Definition at line 383 of file XMManagers.h.
XMBulletinBoard::XMBulletinBoard (char * n, XMApplication & parent, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 384 of file XMManagers.h.
XMBulletinBoard::XMBulletinBoard (char * n, Widget parent, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 388 of file XMManagers.h.
XMBulletinBoard::XMBulletinBoard (char * n, XMWidget & parent, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 392 of file XMManagers.h.
Member Function Documentation
void XMBulletinBoard::AllowOverlap (Boolean allow) [inline]
Definition at line 398 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMBulletinBoard::Margins (Dimension ymargin, Dimension xmargin = 0) [inline]
Definition at line 401 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMBulletinBoard::SetAbsPosition (XMWidget & w, int x, int y) [inline]
Definition at line 410 of file XMManagers.h.
References XMManager::SetConstraint().
void XMBulletinBoard::SetShadowType (unsigned char type) [inline]
Definition at line 405 of file XMManagers.h.
References XMWidget::SetAttribute().
The documentation for this class was generated from the following file:
XMManagers.h