CTCLInterpreterObject Class Reference
#include <TCLInterpreterObject.h>
Public Methods
CTCLInterpreterObject ()
virtual ~CTCLInterpreterObject ()
CTCLInterpreterObject (CTCLInterpreter *pInterp)
CTCLInterpreterObject (const CTCLInterpreterObject &aCTCLInterpreterObject)
CTCLInterpreterObject & operator= (const CTCLInterpreterObject &aCTCLInterpreterObject)
int operator== (const CTCLInterpreterObject &aCTCLInterpreterObject) const
CTCLInterpreter * getInterpreter () const
CTCLInterpreter * Bind (CTCLInterpreter &rBinding)
CTCLInterpreter * Bind (CTCLInterpreter *pBinding)
Protected Methods
virtual void OnBind ()
virtual void OnUnbind ()
CTCLInterpreter * AssertIfNotBound ()
Private Attributes
CTCLInterpreter * m_pInterpreter
Constructor & Destructor Documentation
CTCLInterpreterObject::CTCLInterpreterObject () [inline]
Definition at line 320 of file TCLInterpreterObject.h.
virtual CTCLInterpreterObject::~CTCLInterpreterObject () [inline, virtual]
Definition at line 322 of file TCLInterpreterObject.h.
References OnUnbind().
CTCLInterpreterObject::CTCLInterpreterObject (CTCLInterpreter * pInterp) [inline]
Definition at line 326 of file TCLInterpreterObject.h.
References OnBind().
CTCLInterpreterObject::CTCLInterpreterObject (const CTCLInterpreterObject & aCTCLInterpreterObject) [inline]
Definition at line 332 of file TCLInterpreterObject.h.
References m_pInterpreter, and OnBind().
Member Function Documentation
CTCLInterpreter* CTCLInterpreterObject::AssertIfNotBound () [inline, protected]
Definition at line 377 of file TCLInterpreterObject.h.
References getInterpreter().
Referenced by CTCLProcessor::AddRegisteredOnCurrent(), CTCLResult::AppendElement(), CTCLResult::Clear(), CTCLVariable::Get(), CTCLVariable::Link(), CTCLResult::operator const char *(), CTCLObject::operator double(), CTCLObject::operator int(), CTCLObject::operator()(), CTCLResult::operator+=(), CTCLObject::operator+=(), CTCLResult::operator=(), CTCLProcessor::Register(), CDAQTCLProcessor::Register(), CTCLVariable::Set(), CTCLList::Split(), CTCLVariable::Trace(), CTCLVariable::TraceRelay(), CTCLVariable::Unlink(), CTCLProcessor::Unregister(), and CTCLVariable::UnTrace().
CTCLInterpreter * CTCLInterpreterObject::Bind (CTCLInterpreter * pBinding)
Definition at line 318 of file TCLInterpreterObject.cpp.
References m_pInterpreter, OnBind(), and OnUnbind().
CTCLInterpreter* CTCLInterpreterObject::Bind (CTCLInterpreter & rBinding) [inline]
Definition at line 364 of file TCLInterpreterObject.h.
Referenced by CTCLProcessor::DeleteRelay(), CTCLProcessor::EvalRelay(), CTCLException::setInterpreter(), Tcl_AppInit(), and CTCLProcessor::UnregisterAll().
CTCLInterpreter* CTCLInterpreterObject::getInterpreter () const [inline]
Definition at line 359 of file TCLInterpreterObject.h.
Referenced by CTCLException::AddErrorInfo(), AssertIfNotBound(), CTCLFileHandler::CTCLFileHandler(), CTCLIdleProcess::CTCLIdleProcess(), CTCLProcessor::DeleteRelay(), CTCLProcessor::EvalRelay(), CTCLException::GetResult(), CTCLProcessor::ParseBoolean(), CTCLProcessor::ParseDouble(), CTCLProcessor::ParseInt(), CTCLCommandPackage::Register(), CTCLException::SetErrorCode(), CTCLProcessor::UnregisterAll(), and CTCLVariable::Update().
virtual void CTCLInterpreterObject::OnBind () [inline, protected, virtual]
Definition at line 371 of file TCLInterpreterObject.h.
Referenced by Bind(), CTCLInterpreterObject(), and operator=().
virtual void CTCLInterpreterObject::OnUnbind () [inline, protected, virtual]
Definition at line 372 of file TCLInterpreterObject.h.
Referenced by Bind(), operator=(), and ~CTCLInterpreterObject().
CTCLInterpreterObject& CTCLInterpreterObject::operator= (const CTCLInterpreterObject & aCTCLInterpreterObject) [inline]
Definition at line 341 of file TCLInterpreterObject.h.
References CTCLInterpreter::m_pInterpreter, OnBind(), and OnUnbind().
Referenced by CTCLVariable::operator=(), CTCLResult::operator=(), CTCLObject::operator=(), CTCLFileHandler::operator=(), CTCLException::operator=(), CTCLCommandPackage::operator=(), and CTCLApplication::operator=().
int CTCLInterpreterObject::operator== (const CTCLInterpreterObject & aCTCLInterpreterObject) const [inline]
Definition at line 352 of file TCLInterpreterObject.h.
References m_pInterpreter.
Referenced by CTCLVariable::operator==(), CTCLResult::operator==(), CTCLProcessor::operator==(), CTCLIdleProcess::operator==(), CTCLFileHandler::operator==(), CTCLException::operator==(), CTCLCommandPackage::operator==(), and CTCLApplication::operator==().
Member Data Documentation
CTCLInterpreter* CTCLInterpreterObject::m_pInterpreter [private]
Definition at line 315 of file TCLInterpreterObject.h.
Referenced by Bind(), CTCLInterpreterObject(), and operator==().
The documentation for this class was generated from the following files:
TCLInterpreterObject.h
TCLInterpreterObject.cpp