XMButton Class Reference
#include <XMPushbutton.h>
Public Methods
virtual void Enable ()
virtual void Disable ()
virtual void Label (XmString label)
virtual void Label (String label)
virtual void SetMnemonic (KeySym k)
XMButton (char *n, WidgetClass c, Widget parent)
XMButton (char *n, WidgetClass c, XMWidget &parent)
XMButton (Widget w)
void SetAccelerator (char *translation, char *prompt)
Constructor & Destructor Documentation
XMButton::XMButton (char * n, WidgetClass c, Widget parent) [inline]
Definition at line 349 of file XMPushbutton.h.
XMButton::XMButton (char * n, WidgetClass c, XMWidget & parent) [inline]
Definition at line 352 of file XMPushbutton.h.
XMButton::XMButton (Widget w) [inline]
Definition at line 355 of file XMPushbutton.h.
Member Function Documentation
virtual void XMButton::Disable () [inline, virtual]
Definition at line 320 of file XMPushbutton.h.
References XMWidget::SetAttribute().
virtual void XMButton::Enable () [inline, virtual]
Definition at line 316 of file XMPushbutton.h.
References XMWidget::SetAttribute().
Referenced by XMArrowButton::XMArrowButton(), XMCascadeButton::XMCascadeButton(), XMPushButton::XMPushButton(), and XMToggleButton::XMToggleButton().
virtual void XMButton::Label (String label) [inline, virtual]
Reimplemented in XMArrowButton (p.).
Definition at line 332 of file XMPushbutton.h.
References Label().
virtual void XMButton::Label (XmString label) [inline, virtual]
Reimplemented in XMArrowButton (p.).
Definition at line 328 of file XMPushbutton.h.
References XMWidget::SetAttribute().
Referenced by XMPulldown::BuildMenu(), Label(), and XMPulldown::Label().
void XMButton::SetAccelerator (char * translation, char * prompt) [inline]
Definition at line 358 of file XMPushbutton.h.
References XMWidget::id.
virtual void XMButton::SetMnemonic (KeySym k) [inline, virtual]
Reimplemented in XMArrowButton (p.).
Definition at line 342 of file XMPushbutton.h.
References XMWidget::SetAttribute().
Referenced by XMPulldown::BuildMenu().
The documentation for this class was generated from the following file:
XMPushbutton.h