CApplicationRegistry Class Reference
#include <CApplicationRegistry.h>
Public Methods
CApplicationRegistry ()
CApplicationRegistry (const CApplicationRegistry &rhs)
~CApplicationRegistry ()
CApplicationRegistry & operator= (const CApplicationRegistry &rhs)
int operator== (const CApplicationRegistry &rhs)
Static Public Methods
CClassifiedObjectRegistry * getInstance ()
Static Protected Methods
void setInstance (CClassifiedObjectRegistry *p)
Set a new value for the instance (should not be done).
Static Private Attributes
CClassifiedObjectRegistry * m_pInstance
Detailed Description
Encapsulates a singleton CClassifiedObjectRegistry (p.) which contains the names of all objects registered by the application.
Definition at line 301 of file CApplicationRegistry.h.
Constructor & Destructor Documentation
CApplicationRegistry::CApplicationRegistry ()
Construct the application registry. Normally this does not need to be used, just call CApplicationRegistry::getInstance() (p.).
Definition at line 302 of file CApplicationRegistry.cpp.
References getInstance().
CApplicationRegistry::CApplicationRegistry (const CApplicationRegistry & rhs)
Copy construction:
Definition at line 307 of file CApplicationRegistry.cpp.
References getInstance().
CApplicationRegistry::~CApplicationRegistry () [inline]
Definition at line 311 of file CApplicationRegistry.h.
Member Function Documentation
CClassifiedObjectRegistry * CApplicationRegistry::getInstance () [static]
Get the singleton instance of the application registry:
Definition at line 334 of file CApplicationRegistry.cpp.
References m_pInstance.
Referenced by CApplicationRegistry(), operator=(), and CReactor::~CReactor().
CApplicationRegistry & CApplicationRegistry::operator= (const CApplicationRegistry & rhs)
Assignment:
Definition at line 315 of file CApplicationRegistry.cpp.
References getInstance(), and m_pInstance.
int CApplicationRegistry::operator== (const CApplicationRegistry & rhs)
Equality compare: All application registries are equal.
Definition at line 325 of file CApplicationRegistry.cpp.
void CApplicationRegistry::setInstance (CClassifiedObjectRegistry * p) [inline, static, protected]
Set a new value for the instance (should not be done).
Definition at line 322 of file CApplicationRegistry.h.
Member Data Documentation
CClassifiedObjectRegistry * CApplicationRegistry::m_pInstance [static, private]
Referenced by getInstance(), and operator=().
The documentation for this class was generated from the following files:
CApplicationRegistry.h
CApplicationRegistry.cpp