CTCLFileHandler Class Reference
#include <TCLFileHandler.h>
Public Methods
CTCLFileHandler (CTCLInterpreterObject *pInterp, UInt_t am_nFid=STDIN_FILENO)
CTCLFileHandler (CTCLInterpreterObject *pInterp, FILE *pFile)
CTCLFileHandler (CTCLInterpreterObject *pInterp, fstream &rFile)
CTCLFileHandler (CTCLInterpreter *pInterp, UInt_t am_nFid=STDIN_FILENO)
CTCLFileHandler (CTCLInterpreter *pInterp, FILE *pFile)
CTCLFileHandler (CTCLInterpreter *pInterp, fstream &rFile)
~CTCLFileHandler ()
CTCLFileHandler (const CTCLFileHandler &aCTCLFileHandler)
CTCLFileHandler & operator= (const CTCLFileHandler &aCTCLFileHandler)
int operator== (const CTCLFileHandler &aCTCLFileHandler) const
UInt_t getFid () const
void setFid (UInt_t am_nFid)
virtual void operator() (int mask)=0
void Set (int mask)
void Clear ()
Static Public Methods
void CallbackRelay (ClientData pObject, int mask)
Private Attributes
UInt_t m_nFid
Constructor & Destructor Documentation
CTCLFileHandler::CTCLFileHandler (CTCLInterpreterObject * pInterp, UInt_t am_nFid = STDIN_FILENO) [inline]
Definition at line 327 of file TCLFileHandler.h.
References CTCLInterpreterObject::getInterpreter(), m_nFid, and UInt_t.
CTCLFileHandler::CTCLFileHandler (CTCLInterpreterObject * pInterp, FILE * pFile) [inline]
Definition at line 332 of file TCLFileHandler.h.
References CTCLInterpreterObject::getInterpreter(), and m_nFid.
CTCLFileHandler::CTCLFileHandler (CTCLInterpreterObject * pInterp, fstream & rFile) [inline]
Definition at line 337 of file TCLFileHandler.h.
References m_nFid.
CTCLFileHandler::CTCLFileHandler (CTCLInterpreter * pInterp, UInt_t am_nFid = STDIN_FILENO) [inline]
Definition at line 342 of file TCLFileHandler.h.
References m_nFid, and UInt_t.
CTCLFileHandler::CTCLFileHandler (CTCLInterpreter * pInterp, FILE * pFile) [inline]
Definition at line 347 of file TCLFileHandler.h.
References m_nFid.
CTCLFileHandler::CTCLFileHandler (CTCLInterpreter * pInterp, fstream & rFile) [inline]
Definition at line 352 of file TCLFileHandler.h.
References m_nFid.
CTCLFileHandler::~CTCLFileHandler () [inline]
Definition at line 357 of file TCLFileHandler.h.
References Clear().
CTCLFileHandler::CTCLFileHandler (const CTCLFileHandler & aCTCLFileHandler) [inline]
Definition at line 360 of file TCLFileHandler.h.
References m_nFid.
Member Function Documentation
void CTCLFileHandler::CallbackRelay (ClientData pObject, int mask) [static]
Definition at line 321 of file TCLFileHandler.cpp.
Referenced by Set().
void CTCLFileHandler::Clear ()
Definition at line 372 of file TCLFileHandler.cpp.
References m_nFid.
Referenced by ~CTCLFileHandler().
UInt_t CTCLFileHandler::getFid () const [inline]
Definition at line 388 of file TCLFileHandler.h.
References m_nFid, and UInt_t.
virtual void CTCLFileHandler::operator() (int mask) [pure virtual]
CTCLFileHandler& CTCLFileHandler::operator= (const CTCLFileHandler & aCTCLFileHandler) [inline]
Definition at line 369 of file TCLFileHandler.h.
References m_nFid, and CTCLInterpreterObject::operator=().
int CTCLFileHandler::operator== (const CTCLFileHandler & aCTCLFileHandler) const [inline]
Definition at line 379 of file TCLFileHandler.h.
References m_nFid, and CTCLInterpreterObject::operator==().
void CTCLFileHandler::Set (int mask)
Definition at line 348 of file TCLFileHandler.cpp.
References CallbackRelay(), and m_nFid.
void CTCLFileHandler::setFid (UInt_t am_nFid) [inline]
Definition at line 395 of file TCLFileHandler.h.
References m_nFid, and UInt_t.
Member Data Documentation
UInt_t CTCLFileHandler::m_nFid [private]
Definition at line 322 of file TCLFileHandler.h.
Referenced by Clear(), CTCLFileHandler(), getFid(), operator=(), operator==(), Set(), and setFid().
The documentation for this class was generated from the following files:
TCLFileHandler.h
TCLFileHandler.cpp