CTCLException Class Reference
#include <TCLException.h>
Public Methods
CTCLException (CTCLInterpreter &am_rInterpreter, Int_t am_nReason, const char *pString)
CTCLException (CTCLInterpreter &am_rInterpreter, Int_t am_nReason, const std::string &rString)
virtual ~CTCLException ()
CTCLException (const CTCLException &aCTCLException)
CTCLException operator= (const CTCLException &aCTCLException)
int operator== (const CTCLException &aCTCLException)
Int_t getReason () const
void AddErrorInfo (const char *pMessage)
void AddErrorInfo (const string &rMessage)
void AddErrorInfo (const CTCLString &rMessage)
void SetErrorCode (const char *pMessage, const char *pMnemonic=`???`, const char *pFacility=`TCL`, const char *pSeverity=`FATAL`)
void SetErrorCode (const string rMessage, const string &rMnemonic=string(`???`), const string &rFacility=string(`TCL`), const string &rSeverity=string(`FATAL`))
CTCLResult GetResult () const
virtual const char * ReasonText () const
virtual Int_t ReasonCode () const
Protected Methods
void setInterpreter (CTCLInterpreter &am_rInterpreter)
void setReason (Int_t am_nReason)
Private Attributes
Int_t m_nReason
Constructor & Destructor Documentation
CTCLException::CTCLException (CTCLInterpreter & am_rInterpreter, Int_t am_nReason, const char * pString) [inline]
Definition at line 331 of file TCLException.h.
References Int_t, and m_nReason.
CTCLException::CTCLException (CTCLInterpreter & am_rInterpreter, Int_t am_nReason, const std::string & rString) [inline]
Definition at line 339 of file TCLException.h.
References Int_t, and m_nReason.
virtual CTCLException::~CTCLException () [inline, virtual]
Definition at line 347 of file TCLException.h.
CTCLException::CTCLException (const CTCLException & aCTCLException) [inline]
Definition at line 351 of file TCLException.h.
References m_nReason.
Member Function Documentation
void CTCLException::AddErrorInfo (const CTCLString & rMessage) [inline]
Definition at line 410 of file TCLException.h.
References AddErrorInfo().
void CTCLException::AddErrorInfo (const string & rMessage) [inline]
Definition at line 407 of file TCLException.h.
References AddErrorInfo().
void CTCLException::AddErrorInfo (const char * pMessage)
Definition at line 313 of file TCLException.cpp.
References CTCLInterpreter::getInterpreter(), and CTCLInterpreterObject::getInterpreter().
Referenced by AddErrorInfo().
Int_t CTCLException::getReason () const [inline]
Definition at line 385 of file TCLException.h.
References Int_t, and m_nReason.
Referenced by ReasonCode().
CTCLResult CTCLException::GetResult () const
Definition at line 407 of file TCLException.cpp.
References CTCLInterpreterObject::getInterpreter().
Referenced by ReasonText().
CTCLException CTCLException::operator= (const CTCLException & aCTCLException) [inline]
Definition at line 360 of file TCLException.h.
References m_nReason, CException::operator=(), and CTCLInterpreterObject::operator=().
int CTCLException::operator== (const CTCLException & aCTCLException) [inline]
Definition at line 373 of file TCLException.h.
References m_nReason, CException::operator==(), and CTCLInterpreterObject::operator==().
Int_t CTCLException::ReasonCode () const [virtual]
Returns a code which describes the reason for the exception . This is exception type specific and may be used to do detailed exception analysis and recovery. For example in the CErrnoException (p.) class, the errno at the time of instantiation of the object is returned. The default returns -1
Reimplemented from CException (p.).
Definition at line 390 of file TCLException.cpp.
References getReason().
const char * CTCLException::ReasonText () const [virtual]
Returns a const pointer to text which describes the reason the exception was thrown. This is exception type specific. The default action returns a pointer to the constant string: `Unspecified Exception`
Reimplemented from CException (p.).
Definition at line 374 of file TCLException.cpp.
References GetResult().
void CTCLException::SetErrorCode (const string rMessage, const string & rMnemonic = string(`???`), const string & rFacility = string(`TCL`), const string & rSeverity = string(`FATAL`)) [inline]
Definition at line 418 of file TCLException.h.
References SetErrorCode().
void CTCLException::SetErrorCode (const char * pMessage, const char * pMnemonic = `???`, const char * pFacility = `TCL`, const char * pSeverity = `FATAL`)
Definition at line 339 of file TCLException.cpp.
References CTCLInterpreter::getInterpreter(), and CTCLInterpreterObject::getInterpreter().
Referenced by SetErrorCode().
void CTCLException::setInterpreter (CTCLInterpreter & am_rInterpreter) [inline, protected]
Definition at line 395 of file TCLException.h.
References CTCLInterpreterObject::Bind().
void CTCLException::setReason (Int_t am_nReason) [inline, protected]
Definition at line 399 of file TCLException.h.
References Int_t, and m_nReason.
Member Data Documentation
Int_t CTCLException::m_nReason [private]
Definition at line 321 of file TCLException.h.
Referenced by CTCLException(), getReason(), operator=(), operator==(), and setReason().
The documentation for this class was generated from the following files:
TCLException.h
TCLException.cpp