XMHorizontalSeparator Class Reference
#include <XMSeparators.h>
Public Methods
XMHorizontalSeparator (char *n)
XMHorizontalSeparator (char *n, Widget parent, ArgList l=NULL, Cardinal num_args=0)
XMHorizontalSeparator (char *n, XMWidget &parent, ArgList l=NULL, Cardinal num_args=0)
Constructor & Destructor Documentation
XMHorizontalSeparator::XMHorizontalSeparator (char * n) [inline]
Definition at line 333 of file XMSeparators.h.
References XMWidget::Manage().
XMHorizontalSeparator::XMHorizontalSeparator (char * n, Widget parent, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 334 of file XMSeparators.h.
References XMWidget::Manage(), and XMSeparator::SetOrientation().
XMHorizontalSeparator::XMHorizontalSeparator (char * n, XMWidget & parent, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 339 of file XMSeparators.h.
References XMWidget::Manage(), and XMSeparator::SetOrientation().
The documentation for this class was generated from the following file:
XMSeparators.h