XMArrowButton Class Reference
#include <XMPushbutton.h>
Public Methods
XMArrowButton (char *n, Widget parent, void(*cb)(XMWidget *, XtPointer, XtPointer)=NULL, XtPointer cd=NULL)
XMArrowButton (char *n, XMWidget &parent, void(*cb)(XMWidget *, XtPointer, XtPointer)=NULL, XtPointer cd=NULL)
Callback_data * AddCallback (void(*cb)(XMWidget *, XtPointer, XtPointer)=NULL, XtPointer cd=NULL)
void PointLeft ()
void PointRight ()
void PointUp ()
void PointDown ()
unsigned char Direction ()
virtual void Label (XmString label)
virtual void Label (String label)
virtual void SetMnemonic (KeySym k)
Constructor & Destructor Documentation
XMArrowButton::XMArrowButton (char * n, Widget parent, void(* cb)(XMWidget *, XtPointer, XtPointer) = NULL, XtPointer cd = NULL) [inline]
Definition at line 538 of file XMPushbutton.h.
References XMWidget::AddCallback(), and XMButton::Enable().
XMArrowButton::XMArrowButton (char * n, XMWidget & parent, void(* cb)(XMWidget *, XtPointer, XtPointer) = NULL, XtPointer cd = NULL) [inline]
Definition at line 547 of file XMPushbutton.h.
References XMWidget::AddCallback(), and XMButton::Enable().
Member Function Documentation
Callback_data* XMArrowButton::AddCallback (void(* cb)(XMWidget *, XtPointer, XtPointer) = NULL, XtPointer cd = NULL) [inline]
Definition at line 559 of file XMPushbutton.h.
References XMWidget::AddCallback().
unsigned char XMArrowButton::Direction () [inline]
Definition at line 577 of file XMPushbutton.h.
References XMWidget::GetAttribute().
virtual void XMArrowButton::Label (String label) [inline, virtual]
Reimplemented from XMButton (p.).
Definition at line 588 of file XMPushbutton.h.
virtual void XMArrowButton::Label (XmString label) [inline, virtual]
Reimplemented from XMButton (p.).
Definition at line 587 of file XMPushbutton.h.
void XMArrowButton::PointDown () [inline]
Definition at line 573 of file XMPushbutton.h.
References XMWidget::SetAttribute().
void XMArrowButton::PointLeft () [inline]
Definition at line 564 of file XMPushbutton.h.
References XMWidget::SetAttribute().
void XMArrowButton::PointRight () [inline]
Definition at line 567 of file XMPushbutton.h.
References XMWidget::SetAttribute().
void XMArrowButton::PointUp () [inline]
Definition at line 570 of file XMPushbutton.h.
References XMWidget::SetAttribute().
virtual void XMArrowButton::SetMnemonic (KeySym k) [inline, virtual]
Reimplemented from XMButton (p.).
Definition at line 589 of file XMPushbutton.h.
The documentation for this class was generated from the following file:
XMPushbutton.h