TopLevelShell Class Reference
#include <XMShell.h>
Public Methods
TopLevelShell (String shellname, XMWidget *parent)
~TopLevelShell ()
void RealizeIconic (Boolean val)
Boolean GetIconic ()
void SetIconName (String name)
void GetIconName (String name)
Constructor & Destructor Documentation
TopLevelShell::TopLevelShell (String shellname, XMWidget * parent)
Definition at line 418 of file XMShell.cpp.
TopLevelShell::~TopLevelShell () [inline]
Definition at line 358 of file XMShell.h.
Member Function Documentation
Boolean TopLevelShell::GetIconic () [inline]
Definition at line 362 of file XMShell.h.
References XMWidget::GetAttribute().
void TopLevelShell::GetIconName (String name) [inline]
Definition at line 371 of file XMShell.h.
References XMWidget::GetAttribute(), and XMWidget::name.
void TopLevelShell::RealizeIconic (Boolean val) [inline]
Definition at line 360 of file XMShell.h.
References XMWidget::SetAttribute().
void TopLevelShell::SetIconName (String name) [inline]
Definition at line 369 of file XMShell.h.
References XMWidget::name, and XMWidget::SetAttribute().
The documentation for this class was generated from the following files:
XMShell.h
XMShell.cpp