CTimerEvent Class Reference
#include <CTimerEvent.h>
Public Methods
CTimerEvent (unsigned long nms, bool fRepeat)
CTimerEvent (const char *pName, unsigned long nms, bool fRepeat)
CTimerEvent (const string &rName, unsigned long nms, bool fRepeat)
virtual ~CTimerEvent ()
CTimerMonitor & getMonitor ()
Allow manipulation of the event monitor:.
CTimerGenericReactor & getReactor ()
Allow manipulation of the event reactor:.
void Enable (unsigned long nms, bool fRepeat=true)
void Enable ()
void SetTimeout (unsigned long nms)
void Repeat (bool fRepeat=true)
virtual void OnTimer ()
void InternalOnTimer ()
string DescribeSelf ()
Private Methods
CTimerEvent (const CTimerEvent &rhs)
CTimerEvent & operator= (const CTimerEvent &rhs)
int operator== (const CTimerEvent &rhs)
Private Attributes
CTimerMonitor & m_rMonitor
Refer to the timer monitor maintained.
CTimerGenericReactor & m_rReactor
Refers to the callback reactor.
Detailed Description
CTimerEvent encapsulates a thread which manages a single timer event. The timer event is capable of waiting for a fixed period of time. Timer events are either one-shot or are multi-shot. Each timer event can be dynamically switched between one-shot and multi-shot.
Definition at line 317 of file CTimerEvent.h.
Constructor & Destructor Documentation
CTimerEvent::CTimerEvent (unsigned long nms, bool fRepeat)
Construct an anonymous CTimerEvent.
Parameters:
nms - Number of milliseconds before timer expires.
fRepeat - True if the timer is a recurring timer.
Definition at line 330 of file CTimerEvent.cpp.
References getMonitor(), getReactor(), m_rMonitor, m_rReactor, CEvent::setReactivity(), and CTimerMonitor::setTimeout().
CTimerEvent::CTimerEvent (const char * pName, unsigned long nms, bool fRepeat)
Construct an named CTimerEvent where the name is given as an char* p C String.
Parameters:
pName - Pointer to object name..
nms - Number of milliseconds before timer expires.
fRepeat - True if the timer is a recurring timer.
Definition at line 347 of file CTimerEvent.cpp.
References m_rMonitor, CEvent::setReactivity(), and CTimerMonitor::setTimeout().
CTimerEvent::CTimerEvent (const string & rName, unsigned long nms, bool fRepeat)
Construct an named CTimerEvent where the name is given as an STL String.
Parameters:
rName - Reference to object name..
nms - Number of milliseconds before timer expires.
fRepeat - True if the timer is a recurring timer.
Definition at line 364 of file CTimerEvent.cpp.
References m_rMonitor, CEvent::setReactivity(), and CTimerMonitor::setTimeout().
CTimerEvent::~CTimerEvent () [virtual]
Destroy a timer event. This involves simply deleteing the monitor and the reactor:
Definition at line 380 of file CTimerEvent.cpp.
References m_rMonitor, and m_rReactor.
CTimerEvent::CTimerEvent (const CTimerEvent & rhs) [private]
Member Function Documentation
string CTimerEvent::DescribeSelf () [virtual]
Called to produce a string description of self.
Reimplemented from CEvent (p.).
Definition at line 464 of file CTimerEvent.cpp.
References CEvent::DescribeSelf().
void CTimerEvent::Enable () [inline]
Enable execution of the event. This is intended to be called from outside the Event thread. This allows us to directly schedule the object as a thread, rather than going through the rigmarole required by CEvent::Schedule (p.)
Enabling an active thread is a no-op.
The enable state is a flag, not a counter, so only a single disable is required to kill the thread regardless of the number of Enable calls.
Reimplemented from CEvent (p.).
Definition at line 369 of file CTimerEvent.h.
References CEvent::Enable().
void CTimerEvent::Enable (unsigned long nms, bool fRepeat = true)
Overload for Enable specific to timers... since one shot timers are allowed, this member is supplied to setup the timer and start it in one operation.
Parameters:
nms - Number of milliseconds before timer expires.
fRepeat- true if this is a repetitive timer.
Definition at line 396 of file CTimerEvent.cpp.
References CEvent::Enable(), m_rMonitor, CTimerMonitor::Repeat(), CEvent::setReactivity(), and CTimerMonitor::setTimeout().
CTimerMonitor& CTimerEvent::getMonitor () [inline]
Allow manipulation of the event monitor:.
Reimplemented from CEvent (p.).
Definition at line 359 of file CTimerEvent.h.
Referenced by CTimerEvent().
CTimerGenericReactor& CTimerEvent::getReactor () [inline]
Allow manipulation of the event reactor:.
Reimplemented from CEvent (p.).
Definition at line 362 of file CTimerEvent.h.
Referenced by CTimerEvent().
void CTimerEvent::InternalOnTimer ()
Called directly from the reactor.
Calls the user overridable member.
If the timer is a single shot timer, the thread is disabled from continuing.
Definition at line 441 of file CTimerEvent.cpp.
References CTimerMonitor::getOneShot(), m_rMonitor, OnTimer(), and CEvent::setEnable().
Referenced by CTimerEvent::CTimerGenericReactor::OnEvent().
void CTimerEvent::OnTimer () [virtual]
Called internally - user overridable event code. No-OP for now:
Definition at line 456 of file CTimerEvent.cpp.
Referenced by InternalOnTimer().
CTimerEvent& CTimerEvent::operator= (const CTimerEvent & rhs) [private]
int CTimerEvent::operator== (const CTimerEvent & rhs) [private]
void CTimerEvent::Repeat (bool fRepeat = true)
Set the flag indicating if the timer is a repeating or single shot:
Parameters:
fRepeat - True if this is a repetetitve timer.
Definition at line 421 of file CTimerEvent.cpp.
References m_rMonitor, and CTimerMonitor::Repeat().
void CTimerEvent::SetTimeout (unsigned long nms)
Re-export the members of the monitor which allow control over the timer. This member sets the timeout.
Parameters:
nms - Number of milliseconds before timeout fires.
Definition at line 410 of file CTimerEvent.cpp.
References m_rMonitor, CEvent::setReactivity(), and CTimerMonitor::setTimeout().
Member Data Documentation
CTimerMonitor& CTimerEvent::m_rMonitor [private]
Refer to the timer monitor maintained.
Reimplemented from CEvent (p.).
Definition at line 335 of file CTimerEvent.h.
Referenced by CTimerEvent(), Enable(), InternalOnTimer(), Repeat(), SetTimeout(), and ~CTimerEvent().
CTimerGenericReactor& CTimerEvent::m_rReactor [private]
Refers to the callback reactor.
Reimplemented from CEvent (p.).
Definition at line 336 of file CTimerEvent.h.
Referenced by CTimerEvent(), and ~CTimerEvent().
The documentation for this class was generated from the following files:
CTimerEvent.h
CTimerEvent.cpp