CTCPNoSuchService Class Reference
#include <CTCPNoSuchService.h>
Public Methods
CTCPNoSuchService (const string &service, const string &Doing)
CTCPNoSuchService (const CTCPNoSuchService &rhs)
Copy Constructor.
virtual ~CTCPNoSuchService ()
Destructor.
CTCPNoSuchService & operator= (const CTCPNoSuchService &rhs)
int operator== (const CTCPNoSuchService &rhs)
string getService () const
< Return service name.
virtual const char * ReasonText () const
Protected Methods
void setService (const string &newVal)
Private Attributes
string m_Service
cached value of service.
string m_Reason
Where the reason text is built up.
Detailed Description
Encapsulates an excpetion which indicates a failure to translate a service specification string into a service port number. Service strings can be either a service name which is looked up in e.g. /etc/services or a stringified service port number.
Definition at line 309 of file CTCPNoSuchService.h.
Constructor & Destructor Documentation
CTCPNoSuchService::CTCPNoSuchService (const string & service, const string & Doing)
Standard constructor. Initialize the member variables to values determined by the application and environmental parameters.
Parameters:
service Textualized service which could not be found. This could either be a service name (mis-spelled e.g.) or a textualized service number.
Doing Context information provided by the application to describe what it was trying to do when the failure was detected.
External inputs:
errno (Thread specific) global variable containing the reason getserv database functions failed.
Definition at line 309 of file CTCPNoSuchService.cpp.
CTCPNoSuchService::CTCPNoSuchService (const CTCPNoSuchService & rhs)
Copy Constructor.
Copy constructor: Creates an object given a reference object. Used by the language to produce temporaries for .e.g. call by value and return by value function interactions.
Parameters:
rhs The reference object being copied into *this.
Definition at line 322 of file CTCPNoSuchService.cpp.
virtual CTCPNoSuchService::~CTCPNoSuchService () [inline, virtual]
Destructor.
Definition at line 320 of file CTCPNoSuchService.h.
Member Function Documentation
string CTCPNoSuchService::getService () const [inline]
< Return service name.
Definition at line 328 of file CTCPNoSuchService.h.
References m_Service.
CTCPNoSuchService & CTCPNoSuchService::operator= (const CTCPNoSuchService & rhs)
Assignment. Assign *this to a rhs object. Different from copy construction in that:
We already exist as a validly constructed object.
We return a reference to ourselves so that = chaining is supported.
We prevent self assignment.
Parameters:
rhs The item to which we are being assigned.
Definition at line 338 of file CTCPNoSuchService.cpp.
References m_Service, and CErrnoException::operator=().
int CTCPNoSuchService::operator== (const CTCPNoSuchService & rhs)
Equality compare.. This is a field by field compare of the important elements Note that the m_Reason member is unimportant to the compare.
Parameters:
rhs The object *this is being compared to.
Definition at line 353 of file CTCPNoSuchService.cpp.
References m_Service, and CErrnoException::operator==().
const char * CTCPNoSuchService::ReasonText () const [virtual]
Returns the reason for the exception. This is a string which is built up from CErrno::ReasonText and other information we have it is of the form: `Unable to translate service [m_Service] becuase: [CErrno::ReasonText()]`
Reimplemented from CErrnoException (p.).
Definition at line 367 of file CTCPNoSuchService.cpp.
References m_Reason, m_Service, and CErrnoException::ReasonText().
void CTCPNoSuchService::setService (const string & newVal) [inline, protected]
Definition at line 334 of file CTCPNoSuchService.h.
References m_Service.
Member Data Documentation
string CTCPNoSuchService::m_Reason [private]
Where the reason text is built up.
Definition at line 314 of file CTCPNoSuchService.h.
Referenced by ReasonText().
string CTCPNoSuchService::m_Service [private]
cached value of service.
Definition at line 313 of file CTCPNoSuchService.h.
Referenced by getService(), operator=(), operator==(), ReasonText(), and setService().
The documentation for this class was generated from the following files:
CTCPNoSuchService.h
CTCPNoSuchService.cpp