XMMenuBar Class Reference
#include <XMMenus.h>
Public Methods
XMMenuBar (char *n, Widget parent, Cardinal num_menus, ArgList l=NULL, Cardinal num_args=0)
XMMenuBar (char *n, XMWidget &parent, Cardinal num_menus, ArgList l=NULL, Cardinal num_args=0)
~XMMenuBar ()
XMPulldown * AddPulldown (char *n, int max_items, ArgList l=NULL, Cardinal num_args=0)
XMPulldown * AddHelpPulldown (char *n, int max_items, ArgList l=NULL, Cardinal num_args=0)
int NumMenus ()
XMPulldown * GetPulldown (char *n)
XMPulldown * GetPulldown (Cardinal index)
XMPulldown * GetHelpPulldown ()
XMMenuItem * GetMenuItem (char *n)
XMPulldown * GetNextPulldown ()
XMPulldown * GetFirstPulldown ()
Protected Methods
void mbCreate (Widget parent, Cardinal num_menus, ArgList l, Cardinal num_args)
Protected Attributes
XMPulldown * help_pulldown
XMPulldown ** menu_items
Cardinal menu_cursor
Cardinal menu_count
Cardinal max_menu_items
Constructor & Destructor Documentation
XMMenuBar::XMMenuBar (char * n, Widget parent, Cardinal num_menus, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 423 of file XMMenus.h.
References mbCreate().
XMMenuBar::XMMenuBar (char * n, XMWidget & parent, Cardinal num_menus, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 429 of file XMMenus.h.
References XMWidget::getid(), and mbCreate().
XMMenuBar::~XMMenuBar ()
Definition at line 751 of file XMMenus.cpp.
References max_menu_items, and menu_items.
Member Function Documentation
XMPulldown * XMMenuBar::AddHelpPulldown (char * n, int max_items, ArgList l = NULL, Cardinal num_args = 0)
Method Description: XMMenuBar::AddHelpPulldown (p.) - Adds a pulldown menu which will be registerd as the help menu for the bar. Formal Parameters: char *n: Name/label of the pulldown menu. int max_items: Maximum number of items in the pulldown. ArgList l: Possibly null argument list containing resource overrides. Cardinal num_args: Possibly zero count of arguments in l. Returns: Pointer to the pulldown object created.
Definition at line 835 of file XMMenus.cpp.
References AddPulldown(), exit(), XMPulldown::GetCascadeButton(), XMWidget::getid(), help_pulldown, and XMWidget::SetAttribute().
XMPulldown * XMMenuBar::AddPulldown (char * n, int max_items, ArgList l = NULL, Cardinal num_args = 0)
Definition at line 789 of file XMMenus.cpp.
References exit(), max_menu_items, menu_count, and menu_items.
Referenced by AddHelpPulldown().
XMPulldown* XMMenuBar::GetFirstPulldown () [inline]
Definition at line 460 of file XMMenus.h.
References GetNextPulldown(), and menu_cursor.
XMPulldown* XMMenuBar::GetHelpPulldown () [inline]
Definition at line 453 of file XMMenus.h.
XMMenuItem * XMMenuBar::GetMenuItem (char * n)
Definition at line 885 of file XMMenus.cpp.
References XMPulldown::FindMenuItem(), menu_count, and menu_items.
XMPulldown * XMMenuBar::GetNextPulldown ()
Definition at line 906 of file XMMenus.cpp.
References menu_count, menu_cursor, and menu_items.
Referenced by GetFirstPulldown().
XMPulldown* XMMenuBar::GetPulldown (Cardinal index) [inline]
Definition at line 450 of file XMMenus.h.
References menu_count.
XMPulldown * XMMenuBar::GetPulldown (char * n)
Definition at line 864 of file XMMenus.cpp.
References XMWidget::getname(), menu_count, and menu_items.
void XMMenuBar::mbCreate (Widget parent, Cardinal num_menus, ArgList l, Cardinal num_args) [protected]
Definition at line 718 of file XMMenus.cpp.
References exit(), help_pulldown, XMWidget::id, max_menu_items, menu_count, menu_items, and XMWidget::name.
Referenced by XMMenuBar().
int XMMenuBar::NumMenus () [inline]
Definition at line 448 of file XMMenus.h.
References menu_count.
Member Data Documentation
XMPulldown* XMMenuBar::help_pulldown [protected]
Definition at line 412 of file XMMenus.h.
Referenced by AddHelpPulldown(), and mbCreate().
Cardinal XMMenuBar::max_menu_items [protected]
Definition at line 416 of file XMMenus.h.
Referenced by AddPulldown(), mbCreate(), and ~XMMenuBar().
Cardinal XMMenuBar::menu_count [protected]
Definition at line 415 of file XMMenus.h.
Referenced by AddPulldown(), GetMenuItem(), GetNextPulldown(), GetPulldown(), mbCreate(), and NumMenus().
Cardinal XMMenuBar::menu_cursor [protected]
Definition at line 414 of file XMMenus.h.
Referenced by GetFirstPulldown(), and GetNextPulldown().
XMPulldown** XMMenuBar::menu_items [protected]
Definition at line 413 of file XMMenus.h.
Referenced by AddPulldown(), GetMenuItem(), GetNextPulldown(), GetPulldown(), mbCreate(), and ~XMMenuBar().
The documentation for this class was generated from the following files:
XMMenus.h
XMMenus.cpp