XMRowColumn Class Reference
#include <XMManagers.h>
Public Methods
XMRowColumn (char *name)
XMRowColumn (Widget id)
XMRowColumn (char *name, XMApplication &parent, ArgList l=NULL, Cardinal num_args=0)
XMRowColumn (char *name, XMWidget &parent, ArgList l=NULL, Cardinal num_args=0)
XMRowColumn (char *name, Widget parent, ArgList l=NULL, Cardinal num_args=0)
void SetAlignment (unsigned char alignment)
void SetEntryClass (WidgetClass type)
void Align (Boolean align)
void SetHomogenous (Boolean homog)
void Margins (Dimension vertical, Dimension horizontal)
void SetRowColumns (int numcols)
void SetOrientation (unsigned char orientation)
void SetPacking (unsigned char packmethod)
void RadioMenu ()
void RadioForceOne ()
void NoRadioMenu ()
void RadioNoForceOne ()
void SetSpacing (Dimension spacing)
Callback_data * AddEntryCallback (void(*callback)(XMWidget *, XtPointer, XtPointer), XtPointer client_data)
Constructor & Destructor Documentation
XMRowColumn::XMRowColumn (char * name) [inline]
Definition at line 584 of file XMManagers.h.
References XMWidget::name.
XMRowColumn::XMRowColumn (Widget id) [inline]
Definition at line 585 of file XMManagers.h.
References XMWidget::id.
XMRowColumn::XMRowColumn (char * name, XMApplication & parent, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 586 of file XMManagers.h.
References XMWidget::name.
XMRowColumn::XMRowColumn (char * name, XMWidget & parent, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 589 of file XMManagers.h.
References XMWidget::name.
XMRowColumn::XMRowColumn (char * name, Widget parent, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 592 of file XMManagers.h.
References XMWidget::name.
Member Function Documentation
Callback_data* XMRowColumn::AddEntryCallback (void(* callback)(XMWidget *, XtPointer, XtPointer), XtPointer client_data) [inline]
Definition at line 639 of file XMManagers.h.
References XMWidget::AddCallback().
void XMRowColumn::Align (Boolean align) [inline]
Definition at line 604 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMRowColumn::Margins (Dimension vertical, Dimension horizontal) [inline]
Definition at line 610 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMRowColumn::NoRadioMenu () [inline]
Definition at line 628 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMRowColumn::RadioForceOne () [inline]
Definition at line 626 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMRowColumn::RadioMenu () [inline]
Definition at line 624 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMRowColumn::RadioNoForceOne () [inline]
Definition at line 630 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMRowColumn::SetAlignment (unsigned char alignment) [inline]
Definition at line 598 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMRowColumn::SetEntryClass (WidgetClass type) [inline]
Definition at line 601 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMRowColumn::SetHomogenous (Boolean homog) [inline]
Definition at line 607 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMRowColumn::SetOrientation (unsigned char orientation) [inline]
Definition at line 618 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMRowColumn::SetPacking (unsigned char packmethod) [inline]
Definition at line 621 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMRowColumn::SetRowColumns (int numcols) [inline]
Definition at line 615 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMRowColumn::SetSpacing (Dimension spacing) [inline]
Definition at line 632 of file XMManagers.h.
References XMWidget::SetAttribute().
The documentation for this class was generated from the following file:
XMManagers.h