CTCLList Class Reference
#include <TCLList.h>
Public Methods
CTCLList (CTCLInterpreter *pInterp)
~CTCLList ()
CTCLList (CTCLInterpreter *pInterp, const char *am_pList)
CTCLList (CTCLInterpreter *pInterp, const std::string &rList)
CTCLList (const CTCLList &aCTCLList)
CTCLList & operator= (const CTCLList &aCTCLList)
int operator== (const CTCLList &aCTCLList)
int operator!= (const CTCLList &aCTCLList)
const char * getList () const
int Split (StringArray &rElements)
int Split (int &argc, char ***argv)
const char * Merge (const StringArray &rElements)
const char * Merge (int argc, char **argv)
Protected Methods
void setList (const char *am_pList)
void DoAssign (const CTCLList &rRhs)
Private Attributes
char * m_pList
Constructor & Destructor Documentation
CTCLList::CTCLList (CTCLInterpreter * pInterp) [inline]
Definition at line 320 of file TCLList.h.
References m_pList.
CTCLList::~CTCLList () [inline]
Definition at line 324 of file TCLList.h.
References m_pList.
CTCLList::CTCLList (CTCLInterpreter * pInterp, const char * am_pList)
Definition at line 319 of file TCLList.cpp.
References m_pList.
CTCLList::CTCLList (CTCLInterpreter * pInterp, const std::string & rList)
Definition at line 328 of file TCLList.cpp.
References m_pList.
CTCLList::CTCLList (const CTCLList & aCTCLList) [inline]
Definition at line 333 of file TCLList.h.
References DoAssign().
Member Function Documentation
void CTCLList::DoAssign (const CTCLList & rRhs) [protected]
Definition at line 494 of file TCLList.cpp.
References m_pList, and setList().
Referenced by CTCLList(), and operator=().
const char* CTCLList::getList () const [inline]
Definition at line 362 of file TCLList.h.
References m_pList.
Referenced by Merge(), and CTCLObject::operator=().
const char * CTCLList::Merge (int argc, char ** argv)
Definition at line 478 of file TCLList.cpp.
References getList(), and setList().
const char * CTCLList::Merge (const StringArray & rElements)
Definition at line 442 of file TCLList.cpp.
References getList(), and StringArray.
int CTCLList::operator!= (const CTCLList & aCTCLList) [inline]
Definition at line 355 of file TCLList.h.
References operator==().
CTCLList& CTCLList::operator= (const CTCLList & aCTCLList) [inline]
Definition at line 342 of file TCLList.h.
References DoAssign().
int CTCLList::operator== (const CTCLList & aCTCLList)
Definition at line 344 of file TCLList.cpp.
References m_pList.
Referenced by operator!=().
void CTCLList::setList (const char * am_pList) [protected]
Definition at line 370 of file TCLList.cpp.
References m_pList.
Referenced by DoAssign(), and Merge().
int CTCLList::Split (int & argc, char *** argv)
Definition at line 424 of file TCLList.cpp.
References CTCLInterpreterObject::AssertIfNotBound(), CTCLInterpreter::getInterpreter(), and m_pList.
int CTCLList::Split (StringArray & rElements)
Definition at line 387 of file TCLList.cpp.
References StringArray.
Referenced by CAssocArrayBinding< T >::Commit().
Member Data Documentation
char* CTCLList::m_pList [private]
Definition at line 315 of file TCLList.h.
Referenced by CTCLList(), DoAssign(), getList(), operator==(), setList(), Split(), and ~CTCLList().
The documentation for this class was generated from the following files:
TCLList.h
TCLList.cpp