CNoSuchObjectException Class Reference
#include <CNoSuchObjectException.h>
Public Methods
CNoSuchObjectException (const char *pDoing, const char *pName)
CNoSuchObjectException (const char *pDoing, const string &rName)
CNoSuchObjectException (const string &rDoing, const char *pName)
CNoSuchObjectException (const string &rDoing, const string &rName)
virtual ~CNoSuchObjectException ()
CNoSuchObjectException (const CNoSuchObjectException &aCNoSuchObjectException)
CNoSuchObjectException operator= (const CNoSuchObjectException &aCNoSuchObjectException)
int operator== (const CNoSuchObjectException &aCNoSuchObjectException)
string getName () const
void setName (string am_sName)
virtual const char * ReasonText () const
Protected Methods
void UpdateReasonText ()
Private Attributes
string m_sName
string m_sReasonText
Constructor & Destructor Documentation
CNoSuchObjectException::CNoSuchObjectException (const char * pDoing, const char * pName) [inline]
Definition at line 299 of file CNoSuchObjectException.h.
References m_sName, and UpdateReasonText().
CNoSuchObjectException::CNoSuchObjectException (const char * pDoing, const string & rName) [inline]
Definition at line 304 of file CNoSuchObjectException.h.
References m_sName, and UpdateReasonText().
CNoSuchObjectException::CNoSuchObjectException (const string & rDoing, const char * pName) [inline]
Definition at line 309 of file CNoSuchObjectException.h.
References m_sName, and UpdateReasonText().
CNoSuchObjectException::CNoSuchObjectException (const string & rDoing, const string & rName) [inline]
Definition at line 314 of file CNoSuchObjectException.h.
References m_sName, and UpdateReasonText().
virtual CNoSuchObjectException::~CNoSuchObjectException () [inline, virtual]
Definition at line 319 of file CNoSuchObjectException.h.
CNoSuchObjectException::CNoSuchObjectException (const CNoSuchObjectException & aCNoSuchObjectException) [inline]
Definition at line 323 of file CNoSuchObjectException.h.
References m_sName, and UpdateReasonText().
Member Function Documentation
string CNoSuchObjectException::getName () const [inline]
Definition at line 353 of file CNoSuchObjectException.h.
References m_sName.
CNoSuchObjectException CNoSuchObjectException::operator= (const CNoSuchObjectException & aCNoSuchObjectException) [inline]
Definition at line 333 of file CNoSuchObjectException.h.
References m_sName, CException::operator=(), and UpdateReasonText().
int CNoSuchObjectException::operator== (const CNoSuchObjectException & aCNoSuchObjectException) [inline]
Definition at line 344 of file CNoSuchObjectException.h.
References m_sName, and CException::operator==().
const char * CNoSuchObjectException::ReasonText () const [virtual]
Returns a const pointer to text which describes the reason the exception was thrown. This is exception type specific. The default action returns a pointer to the constant string: `Unspecified Exception`
Reimplemented from CException (p.).
Definition at line 284 of file CNoSuchObjectException.cpp.
References m_sReasonText.
void CNoSuchObjectException::setName (string am_sName) [inline]
Definition at line 359 of file CNoSuchObjectException.h.
References m_sName.
void CNoSuchObjectException::UpdateReasonText () [protected]
Definition at line 290 of file CNoSuchObjectException.cpp.
References m_sName, and m_sReasonText.
Referenced by CNoSuchObjectException(), and operator=().
Member Data Documentation
string CNoSuchObjectException::m_sName [private]
Definition at line 295 of file CNoSuchObjectException.h.
Referenced by CNoSuchObjectException(), getName(), operator=(), operator==(), setName(), and UpdateReasonText().
string CNoSuchObjectException::m_sReasonText [private]
Definition at line 296 of file CNoSuchObjectException.h.
Referenced by ReasonText(), and UpdateReasonText().
The documentation for this class was generated from the following files:
CNoSuchObjectException.h
CNoSuchObjectException.cpp