CServerInstance Class Reference
#include <CServerInstance.h>
Public Methods
CServerInstance (CSocket *pSocket, bool fDeleteSocket=true)
CServerInstance (const char *pName, CSocket *pSocket, bool fDeleteSocket=true)
CServerInstance (const string &rName, CSocket *pSocket, bool fDeleteSocket=true)
~CServerInstance ()
CSocket * getSocket ()
bool getDeleteFlag () const
string getPeername () const
unsigned short getPeerPort () const
virtual void OnReadable (istream &rStream)
virtual void OnRequest (CSocket *pConnection)
void Shutdown ()
virtual string DescribeSelf ()
Protected Methods
void setSocket (CSocket *sock)
void setDelFlag (bool flag)
Private Methods
CServerInstance (const CServerInstance &rhs)
CServerInstance & operator= (const CServerInstance &rhs)
int operator== (const CServerInstance &rhs)
Private Attributes
CSocket * m_pPeer
Pointer to peer socket.
bool m_fDeleteSocket
True if destructor deletes socket.
Detailed Description
Encapsulates the funtionality of a `simple' Tcp/Ip server instance. Simpler tcp/ip server instances are connections with a client over a socket which operate in the simple::
Accept a request from the client.
Respond to those requests mode.
This class is a subclass of the CFileEvent (p.) class... OnReadable is overridden by this class, the user, should in turn override this class and override OnRequest() (p.). OnRequest() (p.) entered with the application serialization mutex held, and therefore can perform any function which requires global syncrhonization.
Definition at line 321 of file CServerInstance.h.
Constructor & Destructor Documentation
CServerInstance::CServerInstance (CSocket * pSocket, bool fDeleteSocket = true)
Construct an anonymous server instance:
Parameters:
pSocket - Pointer to the socket open to the client.
fDeleteSocket - true if the destructor should delete the socket.
Definition at line 300 of file CServerInstance.cpp.
CServerInstance::CServerInstance (const char * pName, CSocket * pSocket, bool fDeleteSocket = true)
Construct a server instance whose name comes from a char* string.
Parameters:
pName - Name to give to the instance (const char*) [in]
pSocket - Socket open on peer. (CSocket (p.)*) [in]
fDeleteSocket - true to delete sock on destruct (bool) [in = true]
Definition at line 314 of file CServerInstance.cpp.
CServerInstance::CServerInstance (const string & rName, CSocket * pSocket, bool fDeleteSocket = true)
Construct a server instance whose name comes from a string& string.
Parameters:
rName - Name to give to the instance (const string& [in]).
pSocket- Socket already open on peer (CSocket (p.)* [in]).
fDeleteSocket - true to delete sock on destruction. (bool [in] = true).
Definition at line 328 of file CServerInstance.cpp.
CServerInstance::~CServerInstance ()
The destructor just deletes m_pPeer if m_fDeleteSocket is true.
Definition at line 338 of file CServerInstance.cpp.
References CSocket::Connected, CSocket::getState(), m_pPeer, and CSocket::Shutdown().
CServerInstance::CServerInstance (const CServerInstance & rhs) [private]
Member Function Documentation
string CServerInstance::DescribeSelf () [virtual]
Describe this textually.
Reimplemented from CFileEvent (p.).
Definition at line 447 of file CServerInstance.cpp.
References CEvent::DescribeSelf(), CSocket::getSocketFd(), CSocket::getState(), m_fDeleteSocket, m_pPeer, and CSocket::StateName().
bool CServerInstance::getDeleteFlag () const [inline]
Definition at line 349 of file CServerInstance.h.
References m_fDeleteSocket.
string CServerInstance::getPeername () const
Determines the node to which this socket is connected.
Return values:
string& The name of the peer to which this socket is connected. if the peer has a dns entry the name of the peer is returned, otherwise the IP address is converted to dotted string form and returned. See CSocket::getPeer() (p.)
Note:
Can throw any exception thrown by CSocket::getPeer() (p.)
Definition at line 361 of file CServerInstance.cpp.
References CSocket::getPeer(), and m_pPeer.
unsigned short CServerInstance::getPeerPort () const
Determines the port to which the socket is connected on the peer.
Return values:
int The port number assigned to this socket.
Note:
Can throw any exception thrown by CSocket::getPeer() (p.)
Definition at line 380 of file CServerInstance.cpp.
References CSocket::getPeer(), and m_pPeer.
CSocket* CServerInstance::getSocket () [inline]
Definition at line 346 of file CServerInstance.h.
void CServerInstance::OnReadable (istream & rInput) [virtual]
Called when the socket becomes readable. We get the socket and pass that to OnRequest which is what the user is supposed to override and embed application functionality in.
Parameters:
rInput - Stream open on the socket (istream& [in-out])
Note:
DO NOT OVERRIDE THIS
Reimplemented from CFileEvent (p.).
Definition at line 402 of file CServerInstance.cpp.
References m_pPeer, OnRequest(), and Shutdown().
void CServerInstance::OnRequest (CSocket * pConnection) [virtual]
Called when the client has a request of the server. The application has overridden this member in its derived class.
Parameters:
pConnection - Socket open to the peer (CSocket (p.)* [in-out]).
Definition at line 418 of file CServerInstance.cpp.
Referenced by OnReadable().
CServerInstance& CServerInstance::operator= (const CServerInstance & rhs) [private]
int CServerInstance::operator== (const CServerInstance & rhs) [private]
void CServerInstance::setDelFlag (bool flag) [inline, protected]
Definition at line 361 of file CServerInstance.h.
References m_fDeleteSocket.
void CServerInstance::setSocket (CSocket * sock) [inline, protected]
Definition at line 358 of file CServerInstance.h.
void CServerInstance::Shutdown ()
Called when we want to shutdown the server we must:
Remove all fd monitoring.
Clear the enable flag.
Shutdown the socket.
It's someone else's responsibility to reap these threads and delete the objects.
Definition at line 434 of file CServerInstance.cpp.
References CSocket::Connected, CSocket::getState(), m_pPeer, CFileEvent::MonitorReadable(), CEvent::setEnable(), and CSocket::Shutdown().
Referenced by OnReadable().
Member Data Documentation
bool CServerInstance::m_fDeleteSocket [private]
True if destructor deletes socket.
Definition at line 325 of file CServerInstance.h.
Referenced by DescribeSelf(), getDeleteFlag(), and setDelFlag().
CSocket* CServerInstance::m_pPeer [private]
Pointer to peer socket.
Definition at line 324 of file CServerInstance.h.
Referenced by DescribeSelf(), getPeername(), getPeerPort(), OnReadable(), Shutdown(), and ~CServerInstance().
The documentation for this class was generated from the following files:
CServerInstance.h
CServerInstance.cpp