CRegisteredObject Class Reference
#include <CRegisteredObject.h>
Public Methods
CRegisteredObject (string am_sName, CClassifiedObjectRegistry *am_Registry, const string &RegistryName)
int operator== (const CRegisteredObject &aCRegisteredObject) const
virtual ~CRegisteredObject ()
const CClassifiedObjectRegistry * getRegistry () const
void RegisterSelf (const string &RegistryName)
Protected Methods
void setRegistry (CClassifiedObjectRegistry *const am_Registry)
Private Methods
CRegisteredObject (const CRegisteredObject &aCRegisteredObject)
Copy construction is forbidden for now.
CRegisteredObject operator= (const CRegisteredObject &aCRegisteredObject)
Assignment is forbidden for now.
Private Attributes
CClassifiedObjectRegistry * m_Registry
Detailed Description
RegisteredObject.h:
This file defines the CRegisteredObject class.
Author: Jason Venema NSCL Michigan State University East Lansing, MI 48824-1321 mailto:venemaja@msu.edu
Definition at line 307 of file CRegisteredObject.h.
Constructor & Destructor Documentation
CRegisteredObject::CRegisteredObject (string am_sName, CClassifiedObjectRegistry * am_Registry, const string & RegistryName) [inline]
The classified object registry into which this object will be registered
Definition at line 315 of file CRegisteredObject.h.
References CNamedObject::AppendClassInfo(), and RegisterSelf().
CRegisteredObject::CRegisteredObject (const CRegisteredObject & aCRegisteredObject) [private]
Copy construction is forbidden for now.
virtual CRegisteredObject::~CRegisteredObject () [inline, virtual]
Definition at line 339 of file CRegisteredObject.h.
Member Function Documentation
const CClassifiedObjectRegistry* CRegisteredObject::getRegistry () const [inline]
Definition at line 344 of file CRegisteredObject.h.
Referenced by CEventMonitor::~CEventMonitor().
CRegisteredObject CRegisteredObject::operator= (const CRegisteredObject & aCRegisteredObject) [private]
Assignment is forbidden for now.
Reimplemented in CEventMonitor (p.), and CFdMonitor (p.).
int CRegisteredObject::operator== (const CRegisteredObject & aCRegisteredObject) const [inline]
Definition at line 332 of file CRegisteredObject.h.
References m_Registry, and CNamedObject::operator==().
Referenced by CReactor::operator==(), CPointerPredicate< T >::operator==(), and CEventMonitor::operator==().
void CRegisteredObject::RegisterSelf (const string & RegistryName)
Registers this object in the appropriate object registry. Note: the object registry will throw a DuplicateNameException if there is already an object in our registry with that name. If necessary, the registry is created. Implicit parameters: m_Registry - a static member which is the collection of object registries into which the object will be registered. m_sName - the name under which the object will be registered.
Parameters:
RegistryName The name of the registry in which to register the object
Definition at line 307 of file CRegisteredObject.cpp.
References CClassifiedObjectRegistry::Add(), CClassifiedObjectRegistry::CreateRegistry(), and m_Registry.
Referenced by CRegisteredObject().
void CRegisteredObject::setRegistry (CClassifiedObjectRegistry *const am_Registry) [inline, protected]
Definition at line 352 of file CRegisteredObject.h.
Member Data Documentation
CClassifiedObjectRegistry* CRegisteredObject::m_Registry [private]
Definition at line 309 of file CRegisteredObject.h.
Referenced by operator==(), and RegisterSelf().
The documentation for this class was generated from the following files:
CRegisteredObject.h
CRegisteredObject.cpp