CTCLCommandPackage Class Reference
#include <TCLCommandPackage.h>
Public Methods
CTCLCommandPackage (CTCLInterpreter *pInterp, const std::string &rSignon=std::string(`Unnamed pkg`))
CTCLCommandPackage (CTCLInterpreter *pInterp, const char *pSignon=`Unnamed pkg`)
virtual ~CTCLCommandPackage ()
CTCLCommandPackage (const CTCLCommandPackage &aCTCLCommandPackage)
CTCLCommandPackage & operator= (const CTCLCommandPackage &aCTCLCommandPackage)
int operator== (const CTCLCommandPackage &aCTCLCommandPackage)
std::string getSignon () const
CommandList getCommandList () const
void Register ()
void Unregister ()
void AddProcessor (CTCLProcessor *pProcessor)
void AddProcessors (CommandList &rList)
CommandListIterator begin ()
CommandListIterator end ()
Protected Methods
void setSignon (std::string am_sSignon)
void setCommandList (CommandList &rList)
Private Attributes
std::string m_sSignon
CommandList m_lCommands
Constructor & Destructor Documentation
CTCLCommandPackage::CTCLCommandPackage (CTCLInterpreter * pInterp, const std::string & rSignon = std::string(`Unnamed pkg`)) [inline]
Definition at line 337 of file TCLCommandPackage.h.
References m_sSignon.
CTCLCommandPackage::CTCLCommandPackage (CTCLInterpreter * pInterp, const char * pSignon = `Unnamed pkg`) [inline]
Definition at line 342 of file TCLCommandPackage.h.
References m_sSignon.
virtual CTCLCommandPackage::~CTCLCommandPackage () [inline, virtual]
Definition at line 347 of file TCLCommandPackage.h.
CTCLCommandPackage::CTCLCommandPackage (const CTCLCommandPackage & aCTCLCommandPackage) [inline]
Definition at line 351 of file TCLCommandPackage.h.
References m_lCommands, and m_sSignon.
Member Function Documentation
void CTCLCommandPackage::AddProcessor (CTCLProcessor * pProcessor) [inline]
Definition at line 408 of file TCLCommandPackage.h.
References m_lCommands.
void CTCLCommandPackage::AddProcessors (CommandList & rList) [inline]
Definition at line 411 of file TCLCommandPackage.h.
References CommandList, end(), and m_lCommands.
CommandListIterator CTCLCommandPackage::begin () [inline]
Definition at line 415 of file TCLCommandPackage.h.
References CommandListIterator, and m_lCommands.
Referenced by Register(), and Unregister().
CommandListIterator CTCLCommandPackage::end () [inline]
Definition at line 418 of file TCLCommandPackage.h.
References CommandListIterator, and m_lCommands.
Referenced by AddProcessors(), Register(), and Unregister().
CommandList CTCLCommandPackage::getCommandList () const [inline]
Definition at line 385 of file TCLCommandPackage.h.
References CommandList, and m_lCommands.
std::string CTCLCommandPackage::getSignon () const [inline]
Definition at line 381 of file TCLCommandPackage.h.
References m_sSignon.
CTCLCommandPackage& CTCLCommandPackage::operator= (const CTCLCommandPackage & aCTCLCommandPackage) [inline]
Definition at line 359 of file TCLCommandPackage.h.
References m_lCommands, m_sSignon, and CTCLInterpreterObject::operator=().
int CTCLCommandPackage::operator== (const CTCLCommandPackage & aCTCLCommandPackage) [inline]
Definition at line 371 of file TCLCommandPackage.h.
References m_lCommands, m_sSignon, and CTCLInterpreterObject::operator==().
void CTCLCommandPackage::Register ()
Definition at line 324 of file TCLCommandPackage.cpp.
References begin(), CommandListIterator, end(), and CTCLInterpreterObject::getInterpreter().
void CTCLCommandPackage::setCommandList (CommandList & rList) [inline, protected]
Definition at line 396 of file TCLCommandPackage.h.
References CommandList, and m_lCommands.
void CTCLCommandPackage::setSignon (std::string am_sSignon) [inline, protected]
Definition at line 392 of file TCLCommandPackage.h.
References m_sSignon.
void CTCLCommandPackage::Unregister ()
Definition at line 348 of file TCLCommandPackage.cpp.
References begin(), CommandListIterator, and end().
Member Data Documentation
CommandList CTCLCommandPackage::m_lCommands [private]
Definition at line 331 of file TCLCommandPackage.h.
Referenced by AddProcessor(), AddProcessors(), begin(), CTCLCommandPackage(), end(), getCommandList(), operator=(), operator==(), and setCommandList().
std::string CTCLCommandPackage::m_sSignon [private]
Definition at line 330 of file TCLCommandPackage.h.
Referenced by CTCLCommandPackage(), getSignon(), operator=(), operator==(), and setSignon().
The documentation for this class was generated from the following files:
TCLCommandPackage.h
TCLCommandPackage.cpp