XMPanedWindow Class Reference
#include <XMManagers.h>
Public Methods
XMPanedWindow (char *name)
XMPanedWindow (Widget id)
XMPanedWindow (char *n, XMWidget &parent, ArgList l=NULL, Cardinal num_args=0)
XMPanedWindow (char *n, Widget parent, ArgList l=NULL, Cardinal num_args=0)
void Margins (Dimension vert, Dimension hor)
void SetSashHeight (Dimension height)
void SetSashIndent (Position indent)
void SetSeparator (Boolean enabled)
void SetPaneSpacing (Dimension spacing)
void AllowResize (XMWidget &wid, Boolean allow)
void MaxPaneSize (XMWidget &wid, Dimension max)
void MinPaneSize (XMWidget &wid, Dimension min)
void SkipAdjust (XMWidget &wid, Boolean skip)
Constructor & Destructor Documentation
XMPanedWindow::XMPanedWindow (char * name) [inline]
Definition at line 649 of file XMManagers.h.
References XMWidget::name.
XMPanedWindow::XMPanedWindow (Widget id) [inline]
Definition at line 650 of file XMManagers.h.
References XMWidget::id.
XMPanedWindow::XMPanedWindow (char * n, XMWidget & parent, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 651 of file XMManagers.h.
XMPanedWindow::XMPanedWindow (char * n, Widget parent, ArgList l = NULL, Cardinal num_args = 0) [inline]
Definition at line 655 of file XMManagers.h.
Member Function Documentation
void XMPanedWindow::AllowResize (XMWidget & wid, Boolean allow) [inline]
Definition at line 681 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMPanedWindow::Margins (Dimension vert, Dimension hor) [inline]
Definition at line 662 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMPanedWindow::MaxPaneSize (XMWidget & wid, Dimension max) [inline]
Definition at line 684 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMPanedWindow::MinPaneSize (XMWidget & wid, Dimension min) [inline]
Definition at line 687 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMPanedWindow::SetPaneSpacing (Dimension spacing) [inline]
Definition at line 675 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMPanedWindow::SetSashHeight (Dimension height) [inline]
Definition at line 666 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMPanedWindow::SetSashIndent (Position indent) [inline]
Definition at line 669 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMPanedWindow::SetSeparator (Boolean enabled) [inline]
Definition at line 672 of file XMManagers.h.
References XMWidget::SetAttribute().
void XMPanedWindow::SkipAdjust (XMWidget & wid, Boolean skip) [inline]
Definition at line 690 of file XMManagers.h.
References XMWidget::SetAttribute().
The documentation for this class was generated from the following file:
XMManagers.h