CSocket Class Reference
#include <CSocket.h>
Public Types
enum State { Disconnected,
Bound,
Listening,
Connected
 }
Captures the state of the socket. See general remarks for more info.
Public Methods
CSocket ()
CSocket (int am_Fd, CSocket::State am_State)
virtual ~CSocket ()
int getSocketFd () const
Get accessor function socket file descriptor.
CSocket::State getState () const
Get accessor function for socket state.
void Connect (const string &host, const string &service)
void Connect (unsigned long int IpAddress, unsigned short service)
void Bind (const string &service)
void Listen (unsigned int nBacklog=5)
CSocket * Accept (string &client)
void Shutdown ()
int Read (void *pBuffer, size_t nBytes)
int Write (void *pBuffer, size_t nBytes)
void getPeer (unsigned short &port, string &peer)
void OOBInline (bool State=TRUE)
bool isOOBInline ()
void setRcvLowWaterMark (size_t nBytes)
size_t getRcvLowWaterMark ()
void setSndLowWaterMark (size_t nBytes)
size_t getSndLowWaterMark ()
void setRcvTimeout (unsigned int nMs)
unsigned int getRcvTimeout ()
void setSndTimeout (unsigned int nMs)
unsigned int getSndTimeout ()
void Debug (bool fState=TRUE)
bool isDebug ()
void SetNotRoutable (bool fRoutable=TRUE)
bool isNotRoutable ()
void setSndBufSize (size_t nBufferSize)
size_t getSndBufSize ()
void setRcvBufSize (size_t nBytes)
size_t getRcvBufSize ()
void setLinger (bool lOn, int nLingerSeconds)
void getLinger (bool &isLingering, int &nLingerSeconds)
Static Public Methods
string StateName (CSocket::State state)
Protected Methods
void setSocketFd (const int am_Fd)
Set accessor function for Socket file descriptor.
void setState (const CSocket::State am_State)
Set accessor function for current socket state.
unsigned short Service (const string &rService)
string AddressToHostString (in_addr peer)
void OpenSocket ()
Static Protected Methods
void StockStateMap ()
Private Methods
CSocket (const CSocket &aCSocket)
Copy Constructor forbidden.
CSocket & operator= (const CSocket &aCSocket)
Assignment Operator Forbidden.
int operator== (const CSocket &aCSocket) const
Equality Operator Forbidden.
Private Attributes
int m_Fd
Socket.
CSocket::State m_State
State of socket.
Static Private Attributes
map< CSocket::State, string > m_StateNames
State name lookup tbl.
Detailed Description
Encapsulates a generalized TCP/IP SOCK_STREAM socket. Note that TCP/IP Sockets can come in two flavors: Clients and Servers. Clients must perform a connect, while servers perform a bind, listen and then serveral accepts to create 'server instances'. The state of a socket is maintained in the m_State variable and is from the enumerator: CSocket::State (p.)
Disconnected: The socket is not connected to anything.
Bound: The socket is a server socket which is not connected, but has been bound to a service port.
Listening: The socket is a server port which is listening and can therefore accept connections
Connected The socket is either a client or a server instance and is connected to it's counterpart.
Definition at line 338 of file CSocket.h.
Member Enumeration Documentation
enum CSocket::State
Captures the state of the socket. See general remarks for more info.
Enumeration values:
Disconnected
Bound
Listening
Connected
Definition at line 343 of file CSocket.h.
Referenced by CSocket(), CTCPBadSocketState::CTCPBadSocketState(), CTCPBadSocketState::getBadState(), getState(), OOBInline(), CTCPBadSocketState::setBadState(), setState(), and StateName().
Constructor & Destructor Documentation
CSocket::CSocket ()
The default constructor initializes the fd to an illegal value and sets the state to Disconnected. The body of the constructor attempts to set the m_Fd member via a call to socket(2) to create an INET domain SOCK_STREAM, protocl tcp.
It is up to the user to call Connect or alternatively set up the socket as a server by binding and listening.
Exceptions:
CErrnoException (p.) if getprotoent for tcp fails or if the socket call itself fails.
Definition at line 365 of file CSocket.cpp.
References OpenSocket().
Referenced by Accept().
CSocket::CSocket (int am_Fd, CSocket::State am_State)
This parameterized constructor is intended to allow a program which already has created a socket in some arbitrary state to wrap it inside a CSocket object. It must be used with care.. in the sense that the am_State parameter must match the actual socket state.
Parameters:
am_Fd The file descriptor already open on a socket.
am_State The current state of the socket am_Fd
Definition at line 398 of file CSocket.cpp.
References State, and StockStateMap().
CSocket::~CSocket () [virtual]
Destructor action depends on the state: sockets which are Connected are shutdown and then closed. Sockets which are in other states are just closed if the fd > 0.
Definition at line 378 of file CSocket.cpp.
CSocket::CSocket (const CSocket & aCSocket) [private]
Copy Constructor forbidden.
Member Function Documentation
CSocket * CSocket::Accept (string & client)
This member function can be called on a server socket. The calling thread is blocked until a connection request is received. At that time, the connection is accepted (granted), and a new CSocket is created in the Connected state. The new CSocket represents a Server Instance socket, communication along that socket can take place immediately and will represent communication with the client.
Exceptions which can be thrown:
CTCPBadSocketState (p.) m_State != Listening
CErrnoException (p.) accept(2) call failed.
Side effects:
The client parameter is written with a string representing the hostname of the client or the IP address if the hostname can not be determined.
The socket created is created via new, therefore it is the responsibility of the caller to delete it.
Parameters:
client Recieves the IP information of the connecting host. Where possible, this is the hostname. Where not, a dotted IP address.
Definition at line 659 of file CSocket.cpp.
References AddressToHostString(), Connected, CSocket(), Listening, m_Fd, and m_State.
Referenced by CServerConnectionEvent::OnReadable().
string CSocket::AddressToHostString (in_addr peer) [protected]
Purpose: Given an IP address in in_addr format, returns a string describing the address. First gethostbyaddr(3) is used to attempt to get the primary DNS name of the address. If this fails, then inet_ntoa(3) is called to get a dotted string. Note that this entire function must run syncrhonized to the global application mutex since the (3) network database calls are assumed to be nonthreadsafe.
Parameters:
peer - The network address of a host in in_addr, network byte order form.
Definition at line 1503 of file CSocket.cpp.
References CApplicationSerializer::getInstance(), CThreadRecursiveMutex::Lock(), and CThreadRecursiveMutex::UnLock().
Referenced by Accept(), and getPeer().
void CSocket::Bind (const string & service)
Indicates that the socket will be used as a server listener socket, and binds it to a service port. The service can be provided either as a numerical string or as a string translated via getservbyname().
The following exceptions can be thrown:
CTCPBadSocketState (p.) m_State != Disconnected
CTCPNoSuchService (p.) Service could not be determined.
CErrnoException (p.) bind(2) failed.
On success, m_State = Bound
Definition at line 562 of file CSocket.cpp.
References Bound, Disconnected, m_Fd, m_State, and Service().
Referenced by CServerConnectionEvent::ConfigureSocket().
void CSocket::Connect (unsigned long int IpAddress, unsigned short service)
Connects a socket as a client given numerical host, and port numbers in host byte order. For the host that means that an ip address of form:
aa.bb.cc.dd is stored Hi->Low as aabbccdd in a longword.
See Connect(const string&host, const string& service) (p.) for more information.
Parameters:
IpAddress The numerical ip address of the server in host byte order.
service The port number of the service.
Definition at line 495 of file CSocket.cpp.
References Connected, Disconnected, CApplicationSerializer::getInstance(), CThreadRecursiveMutex::Lock(), m_Fd, m_State, and CThreadRecursiveMutex::UnLock().
void CSocket::Connect (const string & host, const string & service)
Operation Type: Connection Control
Indicates that the socket will be used as a client socket and attempts to connect it to a server. The address of the server can be passed in either in IP address or IP name textual format. Similarly, the port can be passed in as a textual port name (in /etc/services) or a port number.
The action of this function is to convert (if possible) the Host and service into numeric equivalents and call the overloaded Connect(int IpAddress, int service)
Exceptions which can be thrown:
CTCPBadSocketState (p.) -- m_State was not Disconnected
CTCPNoSuchHost (p.) - Host not in DNS or nonexistent.
CTCPNoSuchService (p.) - Named service does not translate.
CTCPConnectionFailed (p.)- Connection refused by remote host (from Connect(int IpAddress, int service).
Parameters:
host Specifies the system to connect to. This can be either a DNS textual name or a string in dotted IP address format.
service Specifies a service offered by the host. This can be either a service name or the textual equivalent of a service number.
On Success the socket state is set to Connected.
Definition at line 443 of file CSocket.cpp.
References Disconnected, CApplicationSerializer::getInstance(), CThreadRecursiveMutex::Lock(), m_State, Service(), and CThreadRecursiveMutex::UnLock().
Referenced by CLogger::Log(), and CAlarmLogger::Log().
void CSocket::Debug (bool fState = TRUE)
Purpose:
Attempts to turn on Socket debugging. To support this. The user must have effective UID = 0. .
Throws:
CErrnoException (p.) if an error was returned from setsockopt(2) At present we don't know of systems which don't implement this so all errors will throw.
Parameters:
fState [TRUE] Desired state of debugging. TRUE will cause debugging to be turned on. FALSE turned off.
Definition at line 1193 of file CSocket.cpp.
References m_Fd, and TRUE.
void CSocket::getLinger (bool & isLingering, int & nLingerSeconds)
Purpose:
Retrieve the linger parameters.
Throws:
CErrnoException (p.) if the setsockopt(2) call failed.
Parameters:
isLingering [out] Receives the value of the linger state:
TRUE linger is enabled.
FALSE linger is not enabled.
Parameters:
nLingerSeconds [out] Receives the value of the linger timeout. This only has meaning in the event that isLingering == TRUE.
Definition at line 1441 of file CSocket.cpp.
References m_Fd.
void CSocket::getPeer (unsigned short & port, string & peer)
Purpose:
Returns information about who a socket is connected to. If the socket is not connected, CTCPBadSocketState (p.) is thrown. If possible, the peername parameter is returned as a string containing the DNS name of the peer. If the DNS lookup fails, the IP address is converted into dotted form.
Parameters:
port The number of the port to which the socket is connected.
peer The peer as either a DNS hostname or a dotted IP address.
Throws:
CTCPBadSocketState (p.) if m_State != Connected
CErrnoException (p.) if getpeeername(2) failed.
Definition at line 870 of file CSocket.cpp.
References AddressToHostString(), Connected, m_Fd, and m_State.
Referenced by CServerInstance::getPeername(), and CServerInstance::getPeerPort().
size_t CSocket::getRcvBufSize ()
Purpose:
Returns the maximum number of bytes which can be recieved in a single read(2) call.
Throws:
CErrnoException (p.) if getsockopt(2) fails.
Definition at line 1375 of file CSocket.cpp.
References m_Fd.
size_t CSocket::getRcvLowWaterMark ()
Returns the size of the current receive low water mark. See setRcvLowWaterMark for information about what this parameter does. Note that the value returned is inquired from the socket rather than stored in internal state.
Throws:
CErrnoException (p.) if an error from getsockopt is detected.
Definition at line 997 of file CSocket.cpp.
References m_Fd.
unsigned int CSocket::getRcvTimeout ()
Purpose:
Retrieve the protocol receive timeout. The time out is returned as an integer number of milliseconds.
Throws:
CErrnoException (p.) if getsockopt(3) returns an error.
Definition at line 1098 of file CSocket.cpp.
References m_Fd.
size_t CSocket::getSndBufSize ()
Purpose:
Returns the number of bytes that can be written in a single write(2) call.
Throws:
CErrnoException (p.) if getsockopt(2) fails.
Definition at line 1326 of file CSocket.cpp.
References m_Fd.
size_t CSocket::getSndLowWaterMark ()
Return the value of the current Send Low Water Mark Set setSndLowWaterMarrk for more information.
Throws:
CErrnoException (p.) if an error from getsockopt is detected.
Definition at line 1044 of file CSocket.cpp.
References m_Fd.
unsigned int CSocket::getSndTimeout ()
Purpose:
Returns the current send timeout in ms.
Throws:
CErrnoException (p.) if there was an error in getsockopt(2).
Definition at line 1159 of file CSocket.cpp.
References m_Fd.
int CSocket::getSocketFd () const [inline]
Get accessor function socket file descriptor.
Definition at line 383 of file CSocket.h.
References m_Fd.
Referenced by CServerInstance::DescribeSelf(), CServerConnectionEvent::DescribeSelf(), CTCPConnectionLost::Host(), and CTCPConnectionLost::Port().
CSocket::State CSocket::getState () const [inline]
Get accessor function for socket state.
Definition at line 388 of file CSocket.h.
References m_State, and State.
Referenced by CServerInstance::DescribeSelf(), CServerConnectionEvent::DescribeSelf(), CServerInstance::Shutdown(), and CServerInstance::~CServerInstance().
bool CSocket::isDebug ()
Purpose:
Returns TRUE if socket debugging is turned on and False otherwise.
Exceptions:
CErrnoException (p.) if an error is returned from the getsockopt(2) call.
Definition at line 1214 of file CSocket.cpp.
References FALSE, m_Fd, and TRUE.
bool CSocket::isNotRoutable ()
Purpose:
Returns the state of the routability flag.
Throws:
CErrnoException (p.) If getsockopt(2) failed.
Return values:
TRUE Routing is turned off.
FALSE Routing is tured on.
Definition at line 1272 of file CSocket.cpp.
References FALSE, m_Fd, and TRUE.
bool CSocket::isOOBInline ()
Purpose:
Returns TRUE if OOBinline is set FALSE otherwise. Note that the underlying socket state is inquired, not some saved internal state.
This function is valid in any socket state.
Throws:
CErrnoException (p.) if getsockopt(2) fails
Definition at line 941 of file CSocket.cpp.
References FALSE, m_Fd, and TRUE.
void CSocket::Listen (unsigned int nBacklog = 5)
Indicates that the specified server listener socket is ready to listen for connections.
The Following exceptions can be thrown:
CTCPBadSocketState (p.) - m_State != Bound
CErrnoException (p.) - listen(2) failed.
On success, m_State = Listening
Parameters:
nBacklog The limit on the queue size for incomming connections. This value of this parameter defaults to 5. If a a connection is requested when the listen queue is full, it is refused or allowed to retry depending on the protocol (according to linux man connect(2)). On some systems this parameter may be ignored or have other meaning.
Definition at line 610 of file CSocket.cpp.
References Bound, Listening, m_Fd, and m_State.
Referenced by CServerConnectionEvent::ConfigureSocket().
void CSocket::OOBInline (bool State = TRUE)
Purpose:
Allows Out Of Band (OOB) data to be inserted in line with buffered data. OOB data is data with a higher delivery priority than 'normal data'. If this flag is not set, then by default OOB data must be read through normal socket interface functions by specifying it in the recv flags parameter. If this flag is set, oob data is queue at the front of the data to be read with the Read member.
This is allowed in any socket state. Exceptions:
CErrnoException (p.) if the setsockopt(2) function failed.
Parameters:
State This can be (Defaults to TRUE):
TRUE Enables out of band inline data.
FALSE disables out of band inline data.
Definition at line 916 of file CSocket.cpp.
References m_Fd, and State.
void CSocket::OpenSocket () [protected]
Opens the socket on a TCP/IP endpoint.
Definition at line 1557 of file CSocket.cpp.
References CApplicationSerializer::getInstance(), CThreadRecursiveMutex::Lock(), m_Fd, StockStateMap(), and CThreadRecursiveMutex::UnLock().
Referenced by CSocket(), and Shutdown().
CSocket& CSocket::operator= (const CSocket & aCSocket) [private]
Assignment Operator Forbidden.
int CSocket::operator== (const CSocket & aCSocket) const [private]
Equality Operator Forbidden.
int CSocket::Read (void * pBuffer, size_t nBytes)
Purpose:
Performs a read on the socket. The read will transfer all of the bytes currently waiting in the socket buffers or block until data is avaialble. The return valiue will be the number of bytes transferred. If the connection is lost, CTCPConnectionLost (p.) will be thrown. Multiple reads will not be performed so that any known messaging structure can be maintained.
Throws:
CErrnoException (p.) - the read(2) system service returned an error.
CTCPConnectionLost (p.) - the read(2) system service returned 0 indicating an end of file condition.
CTCPBadSocketState (p.) - m_State != Connected.
Definition at line 749 of file CSocket.cpp.
References Connected, Disconnected, m_Fd, and m_State.
Referenced by CLogger::Log().
unsigned short CSocket::Service (const string & rService) [protected]
Purpose: Determines the service which corresponds to a service string. Service strings can either be a numerical equivalent of a service port number or a service name which can be looked up in the service database.
Parameters:
rService The service name.
Returns: The port number or throws: -CTCPNoSuchService (p.) The service cannot be translated.
Definition at line 1466 of file CSocket.cpp.
References CApplicationSerializer::getInstance(), CThreadRecursiveMutex::Lock(), and CThreadRecursiveMutex::UnLock().
Referenced by Bind(), and Connect().
void CSocket::setLinger (bool lOn, int nLingerSeconds)
Purpose:
Sets the socket linger parameters. Linger properties govern the way a shutdown, operates. Note that object destruction which requires a shutdown implicitly turns off linger. If linger is enabled, then the close will block until all pending data has been successfully sent or until the linger timeout is exceeded.
Throws:
CErrnoException (p.) if the setsockopt(2) call failed.
Parameters:
lOn Determines if linger is on or off:
TRUE Linger is on.
FALSE Linger is off.
Parameters:
nLingerSeconds (only used if lOn is TRUE). Indicates how many seconds to linger on the close until a timeout is declared and the close unblocks.
Definition at line 1407 of file CSocket.cpp.
References m_Fd.
void CSocket::SetNotRoutable (bool fRoutable = TRUE)
Purpose:
Allows the caller to control the routability of messages sent on the socket. If set, messages will not be sent through a gateway. Note: The socket need not be connected. Presumably, if this flag is set prior to Connect on a client socket the client will be unable to connect outside the local subnet, and if set prior to Bind for a server, the server will be unable to accept connections from outside the subnet.
Exceptions: -CErrnoException (p.) if the setsockopt(2) call failed.
Parameters:
fRoutable [TRUE] :
TRUE to turn OFF Routing
FALSE to turn ON Routing.
Definition at line 1247 of file CSocket.cpp.
References m_Fd.
void CSocket::setRcvBufSize (size_t nBytes)
Purpose:
Sets the maximum number of bytes which can be received in a single read(2) operation. Note that CTCPSocket::Read does >NOT< automatically segment or else you may block when you'd like to believe that a message has been received.
Throws:
CErrnoException (p.) if setsockopt(2) fails.
Parameters:
nBufferSize Number of bytes which can be sent in one write(2) call
Definition at line 1353 of file CSocket.cpp.
References m_Fd.
void CSocket::setRcvLowWaterMark (size_t nBytes)
Purpose:
Sets the Receive low water mark for the socket. This is the number of bytes received by the protocol before any is made available to the user. Note that some systems do not allow this to be changed. It is not an error at this level to attempt to do so, however you will need to call getRcvlowWaterMark to be sure the change was actually made.
Throws:
CErrnoException (p.) if an error from setsockopt is detected other than that the system doesn't support resetting the low water mark.
Definition at line 973 of file CSocket.cpp.
References m_Fd.
void CSocket::setRcvTimeout (unsigned int nMs)
Set the protocol receive timeouts. Note that in some systems, these are not settable. However it is not an error to attempt to do so.
Parameters:
nMs number of milliseconds of timeout to set.
Throws:
CErrnoException (p.) if a setsockopt(3) returns an error other than that this is unsupported.
Definition at line 1067 of file CSocket.cpp.
References m_Fd.
void CSocket::setSndBufSize (size_t nBufferSize)
Operation Type: Configuration
Purpose:
Sets the socket send buffer size. This has to do with how many bytes can be sent in a single write(2) service call. Messages larger than that must be segmented into multiple write(2) calls. Note howerver that CTCPSocket::Write automatically handles any necessary segmentation.
Throws:
CErrnoException (p.) if setsockopt(2) fails.
Parameters:
nBufferSize Number of bytes which can be sent in one write(2) call
Definition at line 1305 of file CSocket.cpp.
References m_Fd.
void CSocket::setSndLowWaterMark (size_t nBytes)
Sets the new value of the Send Low water mark. This controls the number of bytes which must be written before transferring data to the protocol layers for transmission. Note that some systems don't allow this value to be changed. It is not an error to attempt to change this value on those systems, however you should use getSndLowWaterMark to determine the actual value negotiated by the system.
Parameters:
nBytes Number of bytes in the low water mark.
Throws:
CErrnoException (p.) if an error from setsockopt is detected other than that the system doesn't support resetting the low water mark.
Definition at line 1026 of file CSocket.cpp.
References m_Fd.
void CSocket::setSndTimeout (unsigned int nMs)
Purpose:
Set the number of milliseconds in the send timeout. Some systems may not allow this to be set, however it is not an error to try.
Throws:
CErrnoException (p.) if setsockop(2) returned an error other than this option is not supported.
Parameters:
nMs Number of milliseconds in the desired timeout.
Definition at line 1131 of file CSocket.cpp.
References m_Fd.
void CSocket::setSocketFd (const int am_Fd) [inline, protected]
Set accessor function for Socket file descriptor.
Definition at line 397 of file CSocket.h.
References m_Fd.
void CSocket::setState (const CSocket::State am_State) [inline, protected]
Set accessor function for current socket state.
Definition at line 401 of file CSocket.h.
References m_State, and State.
void CSocket::Shutdown ()
Purpose:
Shuts down a connection to a remote system. Unlike shutdown(2) this function does not support selectively shutting down reads or writes. Both are unconditionally shutdown. Note that the destructor will automatically call Shutdown if necessary.
Exceptions:
CTCPBadSocketState (p.) m_State != Connected.
CErrnoException (p.) shutdown(2) failed.
Definition at line 708 of file CSocket.cpp.
References Connected, Disconnected, m_Fd, m_State, and OpenSocket().
Referenced by CLogger::Log(), CAlarmLogger::Log(), CServerConnectionEvent::OnConnection(), CServerInstance::Shutdown(), CServerConnectionEvent::~CServerConnectionEvent(), and CServerInstance::~CServerInstance().
string CSocket::StateName (CSocket::State state) [static]
Purpose: Given a state, returns a text string which describes the state.
Parameters:
state - State to describe.
NOTE: Since this is a static member which can be called before any instances of CSocket have been created, we call StockStateMap() (p.).
Definition at line 1532 of file CSocket.cpp.
References m_StateNames, State, and StockStateMap().
Referenced by CServerInstance::DescribeSelf(), CServerConnectionEvent::DescribeSelf(), and CTCPBadSocketState::ReasonText().
void CSocket::StockStateMap () [static, protected]
Purpose: Stocks the static member: m_StateNames with the states and their names. This is only done if the map is empty. This function must be updated if the set of states is modified.
Definition at line 1544 of file CSocket.cpp.
References Bound, Connected, Disconnected, Listening, and m_StateNames.
Referenced by CSocket(), OpenSocket(), and StateName().
int CSocket::Write (void * pBuffer, size_t nBytes)
Purpose:
Writes data to the socket. Note that this member will block as needed until all data has been queued to the socket buffers. This may require multiple write(2) function calls if the amount of data to be written is larger than the socket's blocking factor. Note that if the connection is lost during the write, CTCPConnectionLost (p.) will be thrown.
Exceptions:
CTCPBadSocketState (p.) m_State != Connected
CErrnoException (p.) write(2) returned an error condition.
CTCPConnectionLost (p.) write(2) indicated an EPIPE condition which says the peer closed the socket.
Bug:
There's not a good way to handle failures on the second or later call to write(2). Since we'd like to indicate that part of the write completed before an error occured. The current assumption is that a followup write will produce the same error. Perhaps the best long term thing to do is to define a CTCPSocketIOError which will include as data the number of bytes written along with a CErrnoException (p.) which describes why the write actually failed??
Definition at line 810 of file CSocket.cpp.
References Disconnected, m_Fd, and m_State.
Referenced by CLogger::Log(), and CAlarmLogger::Log().
Member Data Documentation
int CSocket::m_Fd [private]
Socket.
Definition at line 353 of file CSocket.h.
Referenced by Accept(), Bind(), Connect(), Debug(), getLinger(), getPeer(), getRcvBufSize(), getRcvLowWaterMark(), getRcvTimeout(), getSndBufSize(), getSndLowWaterMark(), getSndTimeout(), getSocketFd(), isDebug(), isNotRoutable(), isOOBInline(), Listen(), OOBInline(), OpenSocket(), Read(), setLinger(), SetNotRoutable(), setRcvBufSize(), setRcvLowWaterMark(), setRcvTimeout(), setSndBufSize(), setSndLowWaterMark(), setSndTimeout(), setSocketFd(), Shutdown(), and Write().
CSocket::State CSocket::m_State [private]
State of socket.
Definition at line 354 of file CSocket.h.
Referenced by Accept(), Bind(), Connect(), getPeer(), getState(), Listen(), Read(), setState(), Shutdown(), and Write().
map< CSocket::State, string > CSocket::m_StateNames [static, private]
State name lookup tbl.
Definition at line 348 of file CSocket.cpp.
Referenced by StateName(), and StockStateMap().
The documentation for this class was generated from the following files:
CSocket.h
CSocket.cpp