FdMonitorTest.cpp File Reference
#include <iostream.h>
#include `CNamedObject.h`
#include `CObjectRegistry.h`
#include `CClassifiedObjectRegistry.h`
#include `CRegisteredObject.h`
#include `CFdMonitor.h`
#include `CDuplicateNameException.h`
#include `CNoSuchObjectException.h`
#include <assert.h>
Functions
int main ()
Variables
const char * Copyright = `(C) Copyright Michigan State University 2002, All rights reserved`
Function Documentation
int main ()
Definition at line 290 of file FdMonitorTest.cpp.
References CFdMonitor::DescribeSelf(), CEventMonitor::Error, CFdMonitor::getConditionMask(), CFdMonitor::MonitorExceptions(), CFdMonitor::MonitorReadable(), CFdMonitor::MonitorWritable(), CEventMonitor::Occurred, CEventMonitor::setTimeout(), and CEventMonitor::TimedOut.
Variable Documentation
const char* Copyright = `(C) Copyright Michigan State University 2002, All rights reserved` [static]
Definition at line 278 of file FdMonitorTest.cpp.