TCLApplication.cpp File Reference
#include `TCLApplication.h`
#include `TCLInterpreter.h`
#include <histotypes.h>
#include <assert.h>
#include <tcl.h>
#include <tk.h>
Functions
int main (int argc, char **argv)
int Tcl_AppInit (Tcl_Interp *interp)
Variables
const char * Copyright = `(C) Copyright Michigan State University 2002, All rights reserved`
char * pCopyright
CTCLApplication * gpTCLApplication
CTCLInterpreter * gpTCLInterpreter
Function Documentation
int main (int argc, char ** argv)
Definition at line 350 of file TCLApplication.cpp.
References Tcl_AppInit().
int Tcl_AppInit (Tcl_Interp * interp)
Definition at line 358 of file TCLApplication.cpp.
References CTCLInterpreterObject::Bind().
Referenced by CTCLApplication::CTCLApplication(), and main().
Variable Documentation
const char* Copyright = `(C) Copyright Michigan State University 2002, All rights reserved` [static]
Definition at line 278 of file TCLApplication.cpp.
CTCLApplication* gpTCLApplication
Definition at line 318 of file TCLApplication.cpp.
CTCLInterpreter* gpTCLInterpreter
Definition at line 320 of file TCLApplication.cpp.
char* pCopyright [static]
Initial value:
"TCLApplication.cpp - (c) Copyright NSCL 1999, all rights reserved\n"
Definition at line 312 of file TCLApplication.cpp.