XMCallback.cpp File Reference
#include <errno.h>
#include <stdio.h>
#include `XMWidget.h`
Functions
void exit (int)
void XMDispatchCallback (Widget w, XtPointer cbd, XtPointer reason)
Callback_data * XMAddCallback (XMWidget *object, String reason, void(*proc)(XMWidget *, XtPointer, XtPointer), XtPointer data)
void XMRemoveCallback (Callback_data *cbd)
void XMUnmanageChild (XMWidget *wid, XtPointer client_data, XtPointer callback_data)
void XMDestroyWidget (XMWidget *w, XtPointer cd, XtPointer cb)
Variables
const char * Copyright = `(C) Copyright Michigan State University 2002, All rights reserved`
char * sccsversion = `@(#)XMCallback.cc 8.2 1/26/98 `
Function Documentation
void exit (int)
Callback_data* XMAddCallback (XMWidget * object, String reason, void(* proc)(XMWidget *, XtPointer, XtPointer), XtPointer data)
Definition at line 359 of file XMCallback.cpp.
References Callback_data::client_data, exit(), Callback_data::function, XMWidget::getid(), Callback_data::object, Callback_data::reason, and XMDispatchCallback().
Referenced by XMWidget::AddCallback().
void XMDestroyWidget (XMWidget * w, XtPointer cd, XtPointer cb)
Definition at line 438 of file XMCallback.cpp.
void XMDispatchCallback (Widget w, XtPointer cbd, XtPointer reason) [static]
Definition at line 335 of file XMCallback.cpp.
References Callback_data::client_data, Callback_data::function, and Callback_data::object.
Referenced by XMAddCallback(), and XMRemoveCallback().
void XMRemoveCallback (Callback_data * cbd)
Definition at line 396 of file XMCallback.cpp.
References XMWidget::getid(), Callback_data::object, Callback_data::reason, and XMDispatchCallback().
void XMUnmanageChild (XMWidget * wid, XtPointer client_data, XtPointer callback_data)
Functional Description: XMUnmanageChild - A callback that can be specified to unmanage a child widget. Formal Parameters: XMWidget (p.) *wid: Widget of callback. XtPointer client_data, callback_data: Ignored data pointers.
Definition at line 422 of file XMCallback.cpp.
References XMWidget::UnManage().
Variable Documentation
const char* Copyright = `(C) Copyright Michigan State University 2002, All rights reserved` [static]
Definition at line 278 of file XMCallback.cpp.
char* sccsversion = `@(#)XMCallback.cc 8.2 1/26/98 ` [static]
Definition at line 303 of file XMCallback.cpp.