XMHelp.cpp File Reference
#include <stdio.h>
#include <Xm/Xm.h>
#include `XMDialogs.h`
Functions
XMInformationDialog * XM_help (char *name, XMWidget *parent, char **help_text)
void XM_display_help (XMWidget *caller, XtPointer client_data, XtPointer reason)
Variables
const char * Copyright = `(C) Copyright Michigan State University 2002, All rights reserved`
char * sccsinfo = `@(#)helpmenu.cc 8.9 10/19/98 \n`
char * About []
char * aboutname = `About`
XM_help_client_data XM_About = { aboutname, NULL, About }
char * Help []
char * overname = `Help_Overview`
XM_help_client_data XM_Help_Overview = {overname, NULL, Help }
Function Documentation
void XM_display_help (XMWidget * caller, XtPointer client_data, XtPointer reason)
Definition at line 464 of file XMHelp.cpp.
References XM_help().
XMInformationDialog* XM_help (char * name, XMWidget * parent, char ** help_text)
Functional Description: XM_help - This function builds a help dialog object and returns it to the caller. The help dialog is built up from a list of string pointers. The Help dialog will be managed at the time we exit. The caller can do whatever it wants with the dialog including recycling it for later use or allowing it to be destroyed. A Help dialog will be an information dialog with a single button labelled `Dismiss`. The `Dismiss` button, when pressed, by default will just pop down the dialog. To alter this behavior, the caller must invoke the AddOkCallback method on the returned dialog to string a callback onto the Dismiss button. Formal Parameters: char *name: Name of the dialog. XMWidget (p.) *parent: Parent widget for the help dialog. char **help_text: A NULL terminated list of character string pointers which will be used to construct the help message string. Returns: XMInformationDialog * - Pointer to the created information dialog. NULL - If failed.
Definition at line 397 of file XMHelp.cpp.
References XMWidget::getid().
Referenced by XM_display_help().
Variable Documentation
char* About[] [static]
Initial value:
 { "Xamine -- The NSCL X/Motif histogram display program\n",
      "               Author: Ron Fox\n",
      "                       NSCL\n",
      "                       Michigan State University\n",
      "                       East Lansing, MI 48824-1321\n",
      "                       fox@foxsun.nscl.msu.edu\n",
      "               Copyright (c) NSCL, 1995,1996,1997,1998 All rights reserved\n",
      "\n",
      "               Version: Xamine - X2.0-003\n",
      "               O/S support for:   VAX/VMS\n",
      "                                  AXP/VMS\n",
      "                                  Ultrix 4.x\n",
      "                                  SunOS 4.1.x\n",
      "                                  OSF/1 AXP\n",
      "                                  Linux with Lesstif\n",
      "               Recent enhancements:\n",
      "                    June 24, 1997:\n"
      "                      Added support for client supplied peak markers\n",
      "                    July 13, 1998:\n",
      "                      Fixed problems doing graphics to deleted pixmaps\n",
      "                      Fixed problems producing corrupt default files\n",
      "                    July 23, 1998:\n",
      "                      Completed port to Linux with Lesstif\n",
      "                    October 19, 1998\n",
      "                      Fixed error in points prompter on client buttons\n",
        NULL
        }
Definition at line 319 of file XMHelp.cpp.
char* aboutname = `About` [static]
Definition at line 346 of file XMHelp.cpp.
const char* Copyright = `(C) Copyright Michigan State University 2002, All rights reserved` [static]
Definition at line 278 of file XMHelp.cpp.
char* Help[] [static]
Initial value:
 { "Xamine is the NSCL X/Motif histogram display program\n\n",
      "   The highlighted pane is the \"selected\" pane. All operations\n",
      " that require a pane are performed on that pane. To get a feel\n",
      " for the functionality of the program, explore the menu bar at the \n",
      " top of the set of panes. Where appropriate, dialogs that result\n",
      " from selecting menu buttons, or buttons on the quick select button\n",
      " bar below the pane region include context sensitive documentation.\n",
      " By exploring these options and reading the associated help where\n",
      " the consequences of your actions are not clear, you can get a hands\n",
      " on introduction to Xamine.\n",
    "\n   For more information about the program, refer to the Xamine paper\n",
      " documentation\n",
      NULL
      }
Definition at line 351 of file XMHelp.cpp.
char* overname = `Help_Overview` [static]
Definition at line 366 of file XMHelp.cpp.
char* sccsinfo = `@(#)helpmenu.cc 8.9 10/19/98 \n` [static]
Definition at line 298 of file XMHelp.cpp.
XM_help_client_data XM_About = { aboutname, NULL, About }
Definition at line 348 of file XMHelp.cpp.
XM_help_client_data XM_Help_Overview = {overname, NULL, Help }
Definition at line 367 of file XMHelp.cpp.