XMWidget.h File Reference
#include <X11/Intrinsic.h>
#include <X11/StringDefs.h>
#include <Xm/Xm.h>
Compounds
struct Callback_data
class XMApplication
class XMManagedWidget
class XMWidget
Typedefs
typedef char XMWidgetName [32]
Functions
void XMRemoveCallback (Callback_data *cb)
void XMUnmanageChild (XMWidget *, XtPointer, XtPointer)
void XMDestroyWidget (XMWidget *, XtPointer, XtPointer)
Typedef Documentation
typedef char XMWidgetName[32]
Definition at line 309 of file XMWidget.h.
Function Documentation
void XMDestroyWidget (XMWidget *, XtPointer, XtPointer)
Definition at line 438 of file XMCallback.cpp.
void XMRemoveCallback (Callback_data * cb)
Definition at line 396 of file XMCallback.cpp.
References XMWidget::getid(), Callback_data::object, Callback_data::reason, and XMDispatchCallback().
void XMUnmanageChild (XMWidget * wid, XtPointer client_data, XtPointer callback_data)
Functional Description: XMUnmanageChild - A callback that can be specified to unmanage a child widget. Formal Parameters: XMWidget (p.) *wid: Widget of callback. XtPointer client_data, callback_data: Ignored data pointers.
Definition at line 422 of file XMCallback.cpp.
References XMWidget::UnManage().