XMWlist.h File Reference
#include <stdio.h>
#include <errno.h>
#include `XMWidget.h`
#include `XMPushbutton.h`
Compounds
class Generic_List
class XMButtonList
class XMWidgetList
Defines
#define LIST_DEFAULT_SIZE 100
Functions
void exit (int code)
Define Documentation
#define LIST_DEFAULT_SIZE 100
Definition at line 308 of file XMWlist.h.
Referenced by Generic_List< XMWidget >::Generic_List(), and XMWidgetList::XMWidgetList().
Function Documentation
void exit (int code)
Referenced by XMMenuBar::AddHelpPulldown(), XMPulldown::AddMenuButton(), XMPulldown::AddMenuToggleButton(), XMMenuBar::AddPulldown(), XMPulldown::AddSeparator(), XMPulldown::AddSubmenu(), XMPulldown::BuildMenu(), XMPulldown::FindMenuItem(), Generic_List< XMWidget >::Generic_List(), XMMenuBar::mbCreate(), and XMAddCallback().