#!/bin/sh
find . -name .deps -exec rm -rf {} \;
set -x
aclocal -I config
libtoolize --force --copy
autoheader
automake --foreign --add-missing --copy
autoconf

(cd btdriver;./bootstrap)
(cd btdriver2.6; ./bootstrap)