/* cmdline.h */

/* File autogenerated by gengetopt version 2.6  */

#ifndef _cmdline_h
#define _cmdline_h

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* Don't define PACKAGE and VERSION if we use automake.  */
#if defined PACKAGE
#  undef PACKAGE
#endif
#define PACKAGE "controlpush"
#if defined VERSION
#  undef VERSION
#endif
#define VERSION "1.0"

struct gengetopt_args_info {
  int port_arg;	/* Port to use when connecting to tcl server..  */
  int interval_arg;	/* Control parameter update interval.  */
  char * node_arg;	/* Host on which tcl server is running.  */
  int authorize_flag;	/* Server needs authorization (default=off).  */

  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int port_given ;	/* Whether port was given.  */
  int interval_given ;	/* Whether interval was given.  */
  int node_given ;	/* Whether node was given.  */
  int authorize_given ;	/* Whether authorize was given.  */

  char **inputs ; /* unamed options */
  unsigned inputs_num ; /* unamed options number */
} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* _cmdline_h */
