#!/bin/bash -xe


rm -rf ${WORKSPACE}/libtcl++

version=`grep AC_INIT configure.ac | cut -f2 -d" " | sed s/,//`

rm -rf libtclplus-${version}

tar xzf libtclplus-${version}.tar.gz
cd libtclplus-${version}

./configure --prefix=${WORKSPACE}/libtcl++
make clean all
make install
make check

rm -rf libtclplus-${version}
rm -rf ${WORKSPACE}/libtcl++
