#!/bin/bash -xe


rm -rf ${WORKSPACE}/libtcl++-${GIT_BRANCH}-${BUILD_NUMBER}-fromdist

version=`grep AC_INIT configure.ac | cut -f2 -d" " | sed s/,//`

rm -rf libtclplus-${version}

tar xzf libtclplus-${version}.tar.gz
cd libtclplus-${version}

./configure --prefix=${WORKSPACE}/libtcl++-${GIT_BRANCH}-${BUILD_NUMBER}-fromdist
make clean all
make install
make check

