#!/bin/bash -xe


rm -rf /tmp/nextgen

version=`grep AC_INIT configure.ac | cut -f2 -d" " | sed s/,//`

rm -rf nscldaq-${version}

tar xzf nscldaq-${version}.tar.gz
cd nscldaq-${version}

./configure --prefix=/tmp/nextgen
make clean all
make install
make check

rm -rf nscldaq-${version}
rm -rf /tmp/nextgen
