/*
  File autogenerated by gengetopt version 2.6  
  generated with the following command:
  gengetopt --unamed-opts 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif
/* Check for configure's getopt check result.  */
#ifndef HAVE_GETOPT_LONG
#include "getopt.h"
#else
#include <getopt.h>
#endif

#ifndef HAVE_STRDUP
#define strdup gengetopt_strdup
#endif /* HAVE_STRDUP */

#include "cmdline.h"


void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", PACKAGE, VERSION);
}

void
cmdline_parser_print_help (void)
{
  cmdline_parser_print_version ();
  printf("\n"
"Purpose:\n"
"  Transfer control system data to Readout/tcl servers\n"
"\n"
"Usage: %s [OPTIONS]... [FILES]...\n", PACKAGE);
  printf("   -h         --help          Print help and exit\n");
  printf("   -V         --version       Print version and exit\n");
  printf("   -pINT      --port=INT      Port to use when connecting to tcl server.\n");
  printf("   -iINT      --interval=INT  Control parameter update interval\n");
  printf("   -nSTRING   --node=STRING   Host on which tcl server is running\n");
  printf("   -a         --authorize     Server needs authorization (default=off)\n");
}


/* gengetopt_strdup(): automatically generated from strdup.c. */
/* strdup.c replacement of strdup, which is not standard */
static char *
gengetopt_strdup (const char *s)
{
  char *result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  int c;	/* Character of the parsed option.  */
  int missing_required_options = 0;	

  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->port_given = 0 ;
  args_info->interval_given = 0 ;
  args_info->node_given = 0 ;
  args_info->authorize_given = 0 ;
#define clear_args() { \
  args_info->node_arg = NULL; \
  args_info->authorize_flag = 0;\
}

  clear_args();

  args_info->inputs = NULL;
  args_info->inputs_num = 0;

  optarg = 0;
  optind = 1;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int option_index = 0;
      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "port",	1, NULL, 'p' },
        { "interval",	1, NULL, 'i' },
        { "node",	1, NULL, 'n' },
        { "authorize",	0, NULL, 'a' },
        { NULL,	0, NULL, 0 }
      };

      c = getopt_long (argc, argv, "hVp:i:n:a", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          clear_args ();
          cmdline_parser_print_help ();
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          clear_args ();
          cmdline_parser_print_version ();
          exit (EXIT_SUCCESS);

        case 'p':	/* Port to use when connecting to tcl server..  */
          if (args_info->port_given)
            {
              fprintf (stderr, "%s: `--port' (`-p') option given more than once\n", PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->port_given = 1;
          args_info->port_arg = atoi (optarg);
          break;

        case 'i':	/* Control parameter update interval.  */
          if (args_info->interval_given)
            {
              fprintf (stderr, "%s: `--interval' (`-i') option given more than once\n", PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->interval_given = 1;
          args_info->interval_arg = atoi (optarg);
          break;

        case 'n':	/* Host on which tcl server is running.  */
          if (args_info->node_given)
            {
              fprintf (stderr, "%s: `--node' (`-n') option given more than once\n", PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->node_given = 1;
          args_info->node_arg = strdup (optarg);
          break;

        case 'a':	/* Server needs authorization.  */
          if (args_info->authorize_given)
            {
              fprintf (stderr, "%s: `--authorize' (`-a') option given more than once\n", PACKAGE);
              clear_args ();
              exit (EXIT_FAILURE);
            }
          args_info->authorize_given = 1;
          args_info->authorize_flag = !(args_info->authorize_flag);
          break;

        case 0:	/* Long option with no short option */

        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          exit (EXIT_FAILURE);

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c\n", PACKAGE, c);
          abort ();
        } /* switch */
    } /* while */

  if ( missing_required_options )
    exit (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;

      args_info->inputs_num = argc - optind ;
      args_info->inputs = 
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        args_info->inputs[ i++ ] = strdup (argv[optind++]) ; 
    }

  return 0;
}
