#!/bin/sh

PATH=./:/bin:/usr/bin:/usr/sbin/:/usr/local/bin
export PATH

let MINBSIZ=1024
let MAXBSIZ=65536

if [ ! -d "./Out" ]; then
  mkdir ./Out
fi

# Busy one processor
./busy&

# -------------------------------------------------------------------
# stdfp
(
  let BSIZ=$MINBSIZ
  echo "# stdfp with 1 ./filter 1 CPU"
  while [ $BSIZ -le $MAXBSIZ ]; do
    ./source $BSIZ | ./filter 1 $BSIZ | ./sink $BSIZ
    let BSIZ=$BSIZ+1024
  done
) 1> Out/fset32k_c1_f1.data 2>&1

(
  let BSIZ=$MINBSIZ
  echo "# stdfp with 2 ./filters 1 CPU"
  while [ $BSIZ -le $MAXBSIZ ]; do
    ./source $BSIZ | ./filter 1 $BSIZ | ./filter 2 $BSIZ | ./sink $BSIZ
    let BSIZ=$BSIZ+1024
  done
) 1> Out/fset32k_c1_f2.data 2>&1

(
  let BSIZ=$MINBSIZ
  echo "# stdfp with 3 ./filters 1 CPU"
  while [ $BSIZ -le $MAXBSIZ ]; do
    ./source $BSIZ | ./filter 1 $BSIZ | ./filter 2 $BSIZ | ./filter 3 $BSIZ | ./sink $BSIZ
    let BSIZ=$BSIZ+1024
  done
) 1> Out/fset32k_c1_f3.data 2>&1

(
  let BSIZ=$MINBSIZ
  echo "# stdfp with 4 ./filters 1 CPU"
  while [ $BSIZ -le $MAXBSIZ ]; do
    ./source $BSIZ | ./filter 1 $BSIZ | ./filter 2 $BSIZ | ./filter 3 $BSIZ | ./filter 4 $BSIZ | ./sink $BSIZ
    let BSIZ=$BSIZ+1024
  done
) 1> Out/fset32k_c1_f4.data 2>&1

(
  let BSIZ=$MINBSIZ
  echo "# stdfp with 5 ./filters 1 CPU"
  while [ $BSIZ -le $MAXBSIZ ]; do
    ./source $BSIZ | ./filter 1 $BSIZ | ./filter 2 $BSIZ | ./filter 3 $BSIZ | ./filter 4 $BSIZ | ./filter 5 $BSIZ | ./sink $BSIZ
    let BSIZ=$BSIZ+1024
  done
) 1> Out/fset32k_c1_f5.data 2>&1

(
  let BSIZ=$MINBSIZ
  echo "# stdfp with 6 ./filters 1 CPU"
  while [ $BSIZ -le $MAXBSIZ ]; do
    ./source $BSIZ | ./filter 1 $BSIZ | ./filter 2 $BSIZ | ./filter 3 $BSIZ | ./filter 4 $BSIZ | ./filter 5 $BSIZ | ./filter 6 $BSIZ | ./sink $BSIZ
    let BSIZ=$BSIZ+1024
  done
) 1> Out/fset32k_c1_f6.data 2>&1

(
  let BSIZ=$MINBSIZ
  echo "# stdfp with 7 ./filters 1 CPU"
  while [ $BSIZ -le $MAXBSIZ ]; do
    ./source $BSIZ | ./filter 1 $BSIZ | ./filter 2 $BSIZ | ./filter 3 $BSIZ | ./filter 4 $BSIZ | ./filter 5 $BSIZ | ./filter 6 $BSIZ | ./filter 7 $BSIZ | ./sink $BSIZ
    let BSIZ=$BSIZ+1024
  done
) 1> Out/fset32k_c1_f7.data 2>&1

(
  let BSIZ=$MINBSIZ
  echo "# stdfp with 8 ./filters 1 CPU"
  while [ $BSIZ -le $MAXBSIZ ]; do
    ./source $BSIZ | ./filter 1 $BSIZ | ./filter 2 $BSIZ | ./filter 3 $BSIZ | ./filter 4 $BSIZ | ./filter 5 $BSIZ | ./filter 6 $BSIZ | ./filter 7 $BSIZ | ./filter 8 $BSIZ | ./sink $BSIZ
    let BSIZ=$BSIZ+1024
  done
) 1> Out/fset32k_c1_f8.data 2>&1

killall busy
