# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded ApplyCancelWidget 11.0 [list source [file join $dir ApplyCanceltDialogue.tcl]]
package ifneeded ConfigurationUI 11.0 [list source [file join $dir ConfigurationUI.tcl]]
package ifneeded FileListWidget 1.0 [list source [file join $dir FileListWidget.tcl]]
package ifneeded OfflineEVBEVBPipelineUI 11.0 [list source [file join $dir EVBPipelineUI.tcl]]
package ifneeded OfflineEVBHoistPipeline 11.0 [list source [file join $dir HoistPipeline.tcl]]
package ifneeded OfflineEVBHoistPipelineUI 11.0 [list source [file join $dir HoistPipelineUI.tcl]]
package ifneeded OfflineEVBInputPipeline 11.0 [list source [file join $dir InputPipeline.tcl]]
package ifneeded OfflineEVBInputPipelineUI 11.0 [list source [file join $dir InputPipelineUI.tcl]]
package ifneeded OfflineEVBJobProcessor 11.0 [list source [file join $dir JobProcessor.tcl]]
package ifneeded OfflineEVBOutputPipeline 11.0 [list source [file join $dir OutputPipeline.tcl]]
package ifneeded OfflineEVBOutputPipelineUI 11.0 [list source [file join $dir OutputPipelineUI.tcl]]
package ifneeded OfflineEVBRunProcessor 11.0 [list source [file join $dir RunProcessor.tcl]]
package ifneeded OfflineOrderer 11.0 [list source [file join $dir OfflineOrderer.tcl]]
package ifneeded OfflineOrdererUI 11.0 [list source [file join $dir OfflineOrdererUI.tcl]]
